### ISSUE TITLE
[Feature Request] Keyboard shortcuts

### ISSUE THREAD

**Issue by Nova38** [polywock/globalSpeed#1]
Hi @polywock, I like what you are doing here. The non-intrusive speed control is a nice implementation of this concept. If i might make a suggestion on an improvement to your add on, it would be to add some configurable keyboard shortcuts.

I currently use [videospeed by igigorik](https://github.com/igrigorik/videospeed) but I am strongly considering switching to yours going forward!

#### Keyboard Shortcuts
- [ ]  Add keyboard shortcut to increase playback speed 
- [ ]  Add keyboard shortcut to decrease playback speed 
- [ ]  Add keyboard shortcut to return to default playback speed 

#### Configuration 
- [ ] Add a way to customize the keyboard shortcuts
- [ ] Add a way to customize the default speed that the shortcut returns to

**Comment by polywock** [comment]
Thanks for considering this extension.  I implemented said features. I don't have any test users and there might be bugs/problems.

**Comment by polywock** [comment]
An update. The extension was updated on Firefox and the Edge extension store. But, the Chrome web store rejected it. The reason they gave was "spam". I've had a different extension be rejected for the same reason. It was reinstated upon review. I'm assuming the same will apply here. It might take about a week to resolve.
