### ISSUE TITLE
Setting to have indicator appear only on certain inputs

### ISSUE THREAD

**Issue by Eisys** [polywock/globalSpeed#101]
I couldn't find a setting for such a thing and couldn't find anything related here among any issues either. So, sorry if I simply missed something.

I would like it if I could choose what inputs produce the indicator and which ones do not.

In my case, I'd like to disable the indicator from showing for Seek, or enable it only for speed control, for example.
Perhaps it could be an extra toggle next to each shortcut, similar to where the lock icon is.

**Comment by polywock** [comment]
Thanks for the suggestion. I've included this in the latest update (2.8.9). The update has been approved for the Chrome and Firefox store, but will take a week for the Edge add on store. Once updated, you should be able to right click the shortcut name (seek in your case) and enable "hide indicator". Let me know if you experience any issues. I haven't tested it much.

**Comment by Eisys** [comment]
Oh wow. Thank you so much. Best dev ever.

I'm on Chrome so I got the update already. Seems to work perfectly.

Thanks again!
