### ISSUE TITLE
Doesn't work when Edge browser open local file

### ISSUE THREAD

**Issue by enginelee** [polywock/globalSpeed#102]
If I use Edge browser open the video file that the file is in my computer, the addon can't work.

**Comment by polywock** [comment]
Need to enable "Allow access to file URLs" in the Edge extension page. Link below if you installed Global Speed from the Edge addon store. 

edge://extensions/?id=mjhlabbcmjflkpjknnicihkfnmbdfced

**Comment by Giglap** [comment]
Polywock,
                I'm very impressed with your work and love that you've used TypeScript.  I'd love to chat with you about globalspeed and it's evolution.  If you're interested, there may be some startup work (paid) that you are uniquely qualified for.
Thanks,
                -Jim Crawford
***@***.******@***.***>

**Comment by polywock** [comment]
I'm open to hearing about the startup work. I would contact you, but Github blurred your email address. I can be reached at polywockhelp@gmail.com. If the offer involves monetizing Global Speed, I don't think I'll be interested as I won't add anything I feel is invasive towards the user's privacy, and most monetization options unfortunately fit that description.

**Comment by Giglap** [comment]
Hi Polywock,

First off let me tell you that I've used Global Speed for so long that I'm now dependent.  Secondly I have no interest in monetizing or leveraging it.
I'm interested in the skillset that you have demonstrated with this extension.   I'd like to chat with you on the phone or zoom at your leisure and I can explain further.

Let me know when you might talk.  I'm looking forward to getting to know  you.
                -Jim



                Jim Crawford
***@***.******@***.***>
425 577 4000

**Comment by enginelee** [comment]
It works!
Thanks for helping me.

> 
> Need to enable "Allow access to file URLs" in the Edge extension management page. Link below if you installed Global Speed from the Edge addon store. Make sure to refresh your local file page after enabling. Let me know it still doesn't work.
> 
> edge://extensions/?id=mjhlabbcmjflkpjknnicihkfnmbdfced

**Comment by polywock** [comment]
@enginelee, No problem, glad I could helpful.
