### ISSUE TITLE
能不能同一个浏览器里设置不同页面不同的速度。

### ISSUE THREAD

**Issue by a156168128** [polywock/globalSpeed#107]
能不能同一个浏览器里设置不同页面不同的速度。

**Comment by polywock** [comment]
Yeah, just pin that page. 📌 

![img1](https://user-images.githubusercontent.com/31208859/127429006-25e4b8d6-5442-4dbe-a642-c0b3d9933f52.png)

**Comment by billysAnna** [comment]
可以根据不同网址设置不同的速度。

这这里配置：

![Snipaste_2021-08-02_20-59-07](https://user-images.githubusercontent.com/12570910/127865896-d7540201-3a60-4506-ab2d-c1dc91839274.png)

配置域名的方法如下图：

（我配置的是看cctv时不快速播放。）
![aaa](https://user-images.githubusercontent.com/12570910/127865963-30a05120-a119-4326-93f0-d895ac415b82.png)

希望能帮助到你。

**Comment by wenmin92** [comment]
有没有更直观的方法？这种方法需要提前配置，步骤较多，且较为死板，不怎么灵活，适合较为固定的网站固定的速度。假如我临时打开的一些网站或者突然想要改变速度，如何快捷操作。或者说，如何让该扩展每次只针对单个视频调节？

**Comment by wenmin92** [comment]
> 有没有更直观的方法？这种方法需要提前配置，步骤较多，且较为死板，不怎么灵活，适合较为固定的网站固定的速度。假如我临时打开的一些网站或者突然想要改变速度，如何快捷操作。或者说，如何让该扩展每次只针对单个视频调节？

The [README.md](https://github.com/polywock/globalSpeed#speed-control) has replied it:
> If pinned, tabs can have their own playback rate.

**Comment by a156168128** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月4日(星期六) 上午6:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] 能不能同一个浏览器里设置不同页面不同的速度。 (#107)





  
有没有更直观的方法？这种方法需要提前配置，步骤较多，且较为死板，不怎么灵活，适合较为固定的网站固定的速度。假如我临时打开的一些网站或者突然想要改变速度，如何快捷操作。或者说，如何让该扩展每次只针对单个视频调节？
  
The README.md has replied it:
  
If pinned, tabs can have their own playback rate.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wenmin92** [comment]
Thanks @a156168128 , got it.
