### ISSUE TITLE
How to delay?

### ISSUE THREAD

**Issue by CoreyVidal** [polywock/globalSpeed#108]
How do I delay? I can't figure it out!

**Comment by polywock** [comment]
Open the audio panel and adjust the delay value. Not compatible with the Firefox version of Global Speed. 

![b1](https://user-images.githubusercontent.com/31208859/128653375-b14cf89d-ff50-4c40-abdc-1ff02d08eba7.png)

![b2](https://user-images.githubusercontent.com/31208859/128653377-def0387b-d22b-401f-9705-8bd83d4985cf.png)

**Comment by CoreyVidal** [comment]
Oh man. I looked for so long and thought I was nuts. I didn't click that speaker because I just thought it meant "Mute" or something. Thanks for putting up with my stupidity.
