### ISSUE TITLE
Volume off and on

### ISSUE THREAD

**Issue by Sucgz** [polywock/globalSpeed#111]
It would be great if a shortcut key for turning off the volume and turning on the volume under this webpage can be launched, suggesting ‘m’

**Comment by polywock** [comment]
You can create a "mute" hotkey in the options page. Is that what you mean? 
![abc](https://user-images.githubusercontent.com/31208859/129298903-eb2cee60-594f-42cd-b1d2-fec330c313ae.png)

**Comment by Sucgz** [comment]
Yes, thanks for your reply, I found this in the settings, thanks, sorry for my carelessness

**Comment by polywock** [comment]
No problem, the best issue is an easy issue.
