### ISSUE TITLE
Global Speed causes tab actions switching/creation/closing to get slower the more tabs are open

### ISSUE THREAD

**Issue by s-i-m-s** [polywock/globalSpeed#112]
Induced delay seems dependent on number of tabs open, tabs do not need to be loaded, discarded tabs still apply.

I probably wouldn't have even noticed it but I have over 700 tabs open and its causing a very noticeable delay.
With 700 tabs on an i7 machine I am seeing a ~2 second delay on switching/creation/closing.

If I disable global speed the delay instantly disappears, if I re-enable global speed it reappears after opening a new tab.

Discovered on window 7 chrome stable with a bunch of other extensions active.
Verified on windows 10 chrome beta with only global speed enabled.

Reproduction instructions.
1. Open about 700 tabs in chrome content doesn't matter I just used the new tab page.
2. Restart chrome so you don't actually have to wait for the new tab page to load 700 times using chrome://restart or however you prefer to do that.
3. Install global speed and open a couple more new tabs notice how they now take much longer to open and switching between tabs and closing tabs is now laggy.
4. Disable global speed and notice that the delay instantly disappears.

Number of tabs you need to notice this likely varies on the speed of your machine. Probably don't even need anywhere near 700 it's just on my machines it's really noticeable at that point.

**Comment by polywock** [comment]
Can't replicate with Mac OS Monterey Chrome 92 (M1 version, not Intel). Tried with 1400 tabs as well, but don't see a noticeable delay. I'll try on my Windows 10 PC.

**Comment by polywock** [comment]
Okay, tested on my i5 Windows 10 PC as well, but couldn't reproduce again. I suspect the issue has something to do with the Badge Manager, which is responsible for showing the correct badge icon and text depending on Global Speed's speed/state. Here's Global Speed, but with the Badge Manager removed. Do you experience the same issue with this version? 

## To Install

[unpacked.zip](https://github.com/polywock/globalSpeed/files/6987952/unpacked.zip)

1. Download and extract unpacked.zip
2. Open Chrome's extensions page -> `chrome://extensions`
3. Enable "Developer mode" on the top-right of the page. 
4. Click on Load unpacked on the top-left of the page, and load the extracted folder.

**Comment by s-i-m-s** [comment]
No issue with the unpacked version provided.

**Comment by polywock** [comment]
Thanks, that narrows down to the Badge Manager. Using the standard Global Speed, does the delay also occur when you switch tabs using keyboard shortcuts (Ctrl-PgDown and Ctrl-PgUp)? 

https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Ctab-and-window-shortcuts

**Comment by s-i-m-s** [comment]
Yes the delay occurs even when using the keyboard shortcuts.

**Comment by polywock** [comment]
Thanks, could you try this as well. This is one where the chrome.browserAction commands are removed. They're used to set the badge's text and icon. 

[unpacked2.zip](https://github.com/polywock/globalSpeed/files/6989173/unpacked2.zip)

**Comment by s-i-m-s** [comment]
No issue with that version either.

**Comment by polywock** [comment]
Interesting, thanks. That narrows it down the culprit to browserAction.setBadgeText, browserAction.setBadgeBackgroundColor, and browserAction.setIcon. Could you try this as well? This just disables the setIcon one. Last one, I promise. 

[unpacked3.zip](https://github.com/polywock/globalSpeed/files/6989380/unpacked3.zip)

**Comment by s-i-m-s** [comment]
unpacked3 still has the issue, unpacked4 does not.

**Comment by polywock** [comment]
Since unpacked4 seems to work, I'll include the optimizations on the next update. Thanks for the help.

**Comment by polywock** [comment]
An update. Had to revert the optimizations. The browserAction API didn't work the way I expected it to and I noticed a few bugs. I'll think about another way of optimizing the badges.
