### ISSUE TITLE
seek is not available in hevc mode

### ISSUE THREAD

**Issue by JeffCheung85** [polywock/globalSpeed#116]
https://www.bilibili.com/video/av720221324
After forcing the use of HEVC，seek is not available
![Snipaste_2021-08-30_22-41-03](https://user-images.githubusercontent.com/49676276/131357434-8fd69af0-2db6-4848-a6ce-37da0b4d40b4.png)
![Snipaste_2021-08-30_22-41-26](https://user-images.githubusercontent.com/49676276/131357446-f26a89c7-37a7-43b4-9777-be2eea5d2780.png)

**Comment by polywock** [comment]
Hey, Jeff. Global Speed doesn't support HEVC mode. Most browsers don't support HEVC videos yet so Bilibili is using a custom video engine to play HEVC videos.
