### ISSUE TITLE
bilibili bug

### ISSUE THREAD

**Issue by zqmever** [polywock/globalSpeed#117]
After clearing the cache everything plays fine. But when logged in, all the bilibili videos are not adjustable and do not appear in the media list. The strange thing is that everything is fine for the videos on the event page (e.g., https://www.bilibili.com/blackboard/techhunters2.html).

**Comment by polywock** [comment]
Hello. Sorry to hear about the issue. Try disabling HEVC mode. Most browsers don't support HEVC videos yet so Bilibili is using a custom video engine to play HEVC videos. 

![a](https://user-images.githubusercontent.com/31208859/131550565-66563874-e419-410b-adf8-5ec8bb8c701f.png)

![b](https://user-images.githubusercontent.com/31208859/131550164-d8564623-d663-45cd-8848-fa5e0092fbbc.png)

**Comment by zqmever** [comment]
> Hello. Sorry to hear about the issue. Try disabling HEVC mode. Most browsers don't support HEVC videos yet so Bilibili is using a custom video engine to play HEVC videos.
> 
> ![a](https://user-images.githubusercontent.com/31208859/131550565-66563874-e419-410b-adf8-5ec8bb8c701f.png)
> 
> ![b](https://user-images.githubusercontent.com/31208859/131550164-d8564623-d663-45cd-8848-fa5e0092fbbc.png)

oh right, I see! Many thanks!
