### ISSUE TITLE
[Feature Request] Ability to scale seek duration when speed is less than 1x

### ISSUE THREAD

**Issue by ShrirajHegde** [polywock/globalSpeed#118]
While watching something slower (usually done to observe something quickly changing), the default time step for seeking might become too long, it would be great if it could be scaled to the speed (like for a speed 0.3, 0.3*5 sec).

**Comment by polywock** [comment]
Already possible, but kind of hidden. The seek hotkey has a little "x" button that could be used to enable it. 

![c](https://user-images.githubusercontent.com/31208859/131682420-76e188ac-867c-4ba6-8b79-5fe943958966.png)

**Comment by ShrirajHegde** [comment]
oh nice, I didn't hover over it.

**Comment by polywock** [comment]
Yeah, the UI could use some work.
