### ISSUE TITLE
Video speed resets constantly

### ISSUE THREAD

**Issue by ElmorenohWTF** [polywock/globalSpeed#119]
I tried using the chrome and the edge extension (I'm using edge chromium browser)
When I put the mouse above the video, or I stop putting it on top of the video(this also occurs when the video player controls are minimized), the video speed is reset to 1, and after about a second it goes back to the indicated speed, is very annoying.

**Comment by polywock** [comment]
Which website are you experiencing this issue?

**Comment by polywock** [comment]
The website is probably resetting the speed back to 1.0. Like a thug of war between Global Speed and the website. Try enabling  "Ghost mode" in the options page, that should block the website from resetting the speed.

**Comment by ElmorenohWTF** [comment]
On twitch, it seems that activating ghost mode fixed it, I tried that option before and it didn't seem to fix it (maybe I didn't reload the web, but I'm not sure). I think that on websites where there are these types of problems, the ghost mode could be activated automatically and on websites where there are no problems, it could be deactivated or something like that. Like a list of includes where the ghost mode is activated, but in the rest of the webs, the ghost mode is deactivated.

**Comment by polywock** [comment]
Good idea. There's currently an internal list of websites that need ghost mode to be enabled like web.whatsapp.com, onedrive.live.com, etc. I'll try to make this list user configurable in the next major update, for now, I'll add twitch.tv to the internal list.
