### ISSUE TITLE
Seek to point with number keys

### ISSUE THREAD

**Issue by non-bin** [polywock/globalSpeed#123]
I wonder, would it be possible to have a feature like youtube, where pressing a number key seeks to num/10 of the way through the video?

ie. 0 goes to beginning, 5 goes to half way etc.

**Comment by polywock** [comment]
Good idea. I Implemented this in the latest release (`2.9.92`). Already approved for the Chrome/Firefox stores, but may take a week for the Edge store. Once updated, there should be a "%" button on the Seek hotkeys.
