### ISSUE TITLE
When watching an animation, you have to manually skip the beginning and end of the film every time

### ISSUE THREAD

**Issue by qqwsvnba123** [polywock/globalSpeed#124]
Can you manually set the time to skip the title film

**Comment by polywock** [comment]
If you want to skip the first 30 seconds of a video on a particular website. In the options page, you can configure a URL rule to run some javascript code that does that. I've added a video attachment to show how to set that up, if you're viewing this through email, the video might not be visible. 

```
window.addEventListener("loadedmetadata", e => {
    const v = e.target
    if (!(v instanceof HTMLMediaElement)) return 
    v.currentTime = 30
}, true)
```

https://user-images.githubusercontent.com/31208859/132780355-0b5a49a0-fb84-406c-a6ad-e2d14b97459a.mov
