### ISSUE TITLE
Add fast forward feature to MS Teams and Sharepoint applications

### ISSUE THREAD

**Issue by Snickers19** [polywock/globalSpeed#125]
I've just found out the app on Chrome extensions, the app is great and working in Youtube and another HTML5 videos around the internet, but during classes today I was expecting to watch an entire class fast forwarding it, but didn't work. So, my request to the developer is to add some feature if possible, to fast forward Microsoft Sharepoint recordings, that are uploaded in Microsoft OneDrive, I knew that MS team are working on it, but with no release date of the feature. Thanks in advance!

**Comment by polywock** [comment]
If they are web videos, try enabling Ghost mode in the Global Speed options page and refresh your video tabs. Let me know if that works.

**Comment by Snickers19** [comment]
It worked perfectly, many thanks for your support!!
