### ISSUE TITLE
打开捕获音频按钮之后，bilibili无法全屏显示

### ISSUE THREAD

**Issue by a156168128** [polywock/globalSpeed#126]

**Comment by polywock** [comment]
Not just for Bilibili, but for all websites. Chrome/Edge doesn't allow entering fullscreen while audio is captured. To bypass this restriction, first enter fullscreen mode and then capture the audio using the optional hotkey.  

1. Create a "capture" hotkey in options page. 

![aa](https://user-images.githubusercontent.com/31208859/133163994-464d470d-07d0-4943-9011-52f27ef6f1f9.png)

2. The "capture" hotkey is special and needs to be configured using browser's shortcut key editor. You can click the link icon to go to it. 

![ab](https://user-images.githubusercontent.com/31208859/133165044-691a943c-67f9-4fe2-9f68-53bfb69c46c1.png)


3. Click the pencil icon to choose your preferred shortcut key. 
 
![ac](https://user-images.githubusercontent.com/31208859/133165050-4ea7465f-a7ed-43e1-a2c9-e4c4abc5277c.png)
