### ISSUE TITLE
Option to show indicator when hiding by default

### ISSUE THREAD

**Issue by non-bin** [polywock/globalSpeed#127]
Hey, I love this extension and will probably have a go at implementing it this week.
I have lots of shortcuts, but the only ones I need an indicator for are speed changes. My idea is to have the option on each shortcut be 'do the opposite of the default' and then have it visible when indicators are hidden

**Comment by polywock** [comment]
Implemented for issue #101. If you click the shortcut's `⋮` icon near the X, you can enable "hide indicator" to hide the indicator for a specific shortcut. You may have not seen it because the option doesn't show up if the global hide indicator option is enabled.

**Comment by non-bin** [comment]
I know, I'm just thinking it would be good to be able to turn it on for individual shortcuts when it's globally off
I have 20ish shortcuts and just don't want to have to go through all of them but 2 turning it off

**Comment by polywock** [comment]
Makes sense. It would also improve the UX design. 

Global hide indicator disabled -> Shortcuts have a "hide indicator" override. 
Global hide indicator enabled -> Shortcuts have a "show indicator" override. 

Warning: This project isn't very contribution friendly. If I stop working on this, I don't think anyone will pick up the baton. The code is disorganized and mostly undocumented. The Manifest V3 API isn't yet mature enough to migrate, but once it is, I'll rewrite the entire codebase to more maintainable and clean. If you still want to implement this feature, here's some tips. 

1. The extension has translations for 10 languages. The strings are stored in locals/XX.json, but no need to provide them. Just hardcode english and I'll include the translations after merging. 
2. The relevant files may be `src/types.ts`, `src/background/processKeybinds.ts`, and `src/options/KeyBindControl.tsx`.

**Comment by polywock** [comment]
Hello. Apologies for the delayed reply. I'm currently going through the open issues one by one. As of today, the feature is implemented.
