### ISSUE TITLE
Shortcut groups

### ISSUE THREAD

**Issue by non-bin** [polywock/globalSpeed#128]
It would be nice to be able to group shortcuts and apply a URL rule to a bunch of them simultaneously
I'll have a go at this one too but it's probably a pretty big undertaking, I don't think I'd use it but I thought it might be a fun project for me to try

**Comment by polywock** [comment]
Thought about implementing this, but the copy/paste feature made copying over URL conditions convenient enough that the effort wasn't worth it anymore.

**Comment by non-bin** [comment]
Oh I didn't see that, cool
