### ISSUE TITLE
Support mouse keys in shortcuts

### ISSUE THREAD

**Issue by Luwx** [polywock/globalSpeed#131]
For example mouse button 6 or 7

**Comment by seefood** [comment]
I agree. I have been using Enhancer for YouTube for years now, and I am used to scrolling with my mouse when on the speed icon to change the speed. Since GlobalSpeed doesn't add a popup menu in the page, is it possible to capture scroll up/down when it happens when hovering over the toolbar icon?

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. I did try implementing this, but turned out more complex than I wanted. Ultimately, I decided against supporting mouse shortcuts.
