### ISSUE TITLE
Enhancement: Allowing for toggling the setting between each tab or applying the setting to all tabs

### ISSUE THREAD

**Issue by justtry123TL** [polywock/globalSpeed#133]
The current setup only allows for applying the setting to all tabs, which makes it annoying when each video requires a different speed setting on a different tab. So my suggestion is to allow for speed changes being made per tab instead of across of all tabs. 
I know that you can switch between tabs so that one can be in a faster speed than another. But there is not a way that I can find where the set speed only affects one of the tabs themselves.

**Comment by polywock** [comment]
If you want a tab to have it's own speed, you can pin it. 📌 

![img1](https://user-images.githubusercontent.com/31208859/127429006-25e4b8d6-5442-4dbe-a642-c0b3d9933f52.png)
