### ISSUE TITLE
Enhancement:  Please add a guide for Firefox user, How to build and install Thank you.

### ISSUE THREAD

**Issue by mobilelifeful** [polywock/globalSpeed#135]
Thank you for sharing. I am new to programming, but fond this plugin useful. trying to build from source for Firefox. Any guide is appreciated. Thank you.

**Comment by polywock** [comment]
Glad to see Global Speed useful. I'll look into making a detailed guide later. 
1. Install Node (+NPM). 
2. Download this repository and extract Global Speed's root folder. 
2. Open terminal or powershell (Windows).
3. Type in `cd`, add a space, and drag in Global Speed's root folder. 
4. Run `npm install`
5. Run `npm run build:dev` to build the unpacked folder. 
6. Open `about:debugging#/runtime/this-firefox` and load `unpacked/manifest.json`
