### ISSUE TITLE
Firefox mobile support

### ISSUE THREAD

**Issue by 17721** [polywock/globalSpeed#136]
First of all, great plugin! Perhaps, the best out there for controlling speed of any audio/video. 
Can you improve the way to use it from a mobile device with a touchscreen? I'm not asking specifically for 'Firefox mobile' version, because right now it works (I mean the plugin itself) in 'Firefox nightly' for android, as it supports desktop plugins. The problem is that you have to make several taps in order to control the speed and it's very tiresome.
Thanks!

**Comment by polywock** [comment]
Hey, glad to see Global Speed useful. I've thought about optimizing for Firefox Android, but it's not worth the effort in my opinion. Firefox Android only allows installing a few Recommende addons at the moment.  The only way to install other addons is through the collections trick, which very few people will do.
