### ISSUE TITLE
add the function of jump frame？

### ISSUE THREAD

**Issue by 459989945** [polywock/globalSpeed#139]
It only has  jumping timeline.Can I jump previous/next frame?

**Comment by polywock** [comment]
Global Speed has a default hotkey for previous/next frame. (shift Z and shift X)

![frame](https://user-images.githubusercontent.com/31208859/138576943-137402d6-783d-4fb1-874e-463d4750f3d2.png)

| Frames per second | Duration      |
|-------------------|---------------|
| 24                | 0.041 seconds |
| 30                | 0.033 seconds |
| 60                | 0.016 seconds |

24fps (or 0.041) is a good approximation to jump to the next frame. If most of the videos you watch are 60fps, you can change it to 0.016.  

The Firefox version supports precise frame seeking if you jump exactly 0.041 seconds forwards, but Chrome/Edge doesn't support the "seekToNextFrame()" yet.
