### ISSUE TITLE
一些论坛的登录和回复按钮点击无反应

### ISSUE THREAD

**Issue by YuI2333** [polywock/globalSpeed#14]
具体表现为：输入账号密码后点击登录按钮没有任何反应，刷新页面后已经登录了，以及回帖时点击回复无反应。
例如：bbs.pcbeta.com   bbs.kafan.cn

另外有一个建议，希望支持关闭页面后重置播放速度为1.0。

最后感谢您的付出！

**Comment by polywock** [comment]
Thank you for kind words. I would first like to say I don't speak Chinese. So, all communication I would translate using Baidu or Google. There might be misunderstandings. I think I know what's causing the issue, and I'll include a fix in the next update. But, my guess might be wrong. If convenient for you, could you email me an invitation code for `bbs.pcbeta.com`. My email address is `polywockhelp@gmail.com`. 

Google Translate
谢谢你的客气话。我首先要说我不会说中文。因此，我将使用百度或Google翻译所有交流方式。可能会有误会。我想我知道导致问题的原因，并且我将在下次更新中包含一个修复程序。但是，我的猜测可能是错误的。如果方便的话，您可以通过电子邮件将bbs.pcbeta.com的邀请代码发送给我。我的电子邮件地址是“ polywockhelp@gmail.com”。

**Comment by kindect** [comment]
I should hope to be helpful after using this web extension for my calculus studying
Great Work! I should say.
When you came into any trouble, or need translations, please let me know immediately.
I should offer my kindest hope I can do(maybe little with the code)

**Comment by kindect** [comment]
The mail address is kindect@163.com, response might be late since I am a high school student who only comes home once a week, but I should hope whenever you encounter a trouble, please let me know

**Comment by kindect** [comment]
Also the text2gender project is great!(by all means!)

**Comment by kindect** [comment]
I think the problem is with the website, not the extension.
see pictures at https://www.matiankai.top/usr/uploads/2020/05/665277769.png
Thank you

**Comment by polywock** [comment]
Thanks, @kindect . I might email you later about translating a few things.  I looked at the picture you linked, and I don't see any issues with the website. What makes you think the problem is with the website and not the extension? Thanks again.

**Comment by kindect** [comment]
Sorry about the delay and here's what I suggest:
The JavaScript in the website use jQuery which might cause the problem
However, problems are not seen on other websites, I'll try to find the problem in about a day's time
Disable the extension do works somehow
The website is made using Discuz! , but it wasn't mentioned on the website so it remains to be discussed

BTW, I didn't receive any emails from @polywock, thank you

**Comment by kindect** [comment]
Okay
here's further research:
the website is made, i think in Discuz!, which, of course breaking the license
<img width="637" alt="截屏2020-07-2721 08 05" src="https://user-images.githubusercontent.com/46749032/88545659-def6d900-d04d-11ea-8d5a-24ec2494c99e.png">
<img width="1088" alt="截屏2020-07-2721 08 17" src="https://user-images.githubusercontent.com/46749032/88545664-e1f1c980-d04d-11ea-9c25-c7cb72925f7c.png">
right here
BTW you don't need a code to sign up on the website

**Comment by polywock** [comment]
Thanks! I could finally reproduce @YuI2333's problem. If I try to sign in with nonsense username/password, it doesn't any response if the extension is enabled. It does when it's disabled. So Global Speed is definitely interfering somehow.  I'll have to look into why. It's a bit hard to do, since `bbs.pcbeta.com` IP blocks for 30 minutes after 5 sign-in attempts. If I continue doing this, they might permanently block my IP. 

As for the invitation thing. If I try to create an account, it does require me to provide an invitation code [[img]](https://i.imgur.com/BWhjO9l.png).

**Comment by polywock** [comment]
Thank you @kindect. I managed to fix the problem. The cause of the problem was discuz expected a specific element to be the first element in the document. But, my extension injected a script first. The solution was one line. 

```
script.remove()
```

**Comment by kindect** [comment]
ha, great
I wasn't able to see the script really(I don't really know why)
And One more thing, I once experienced a error on bilibil.com, there's a error message created by that website's script
I refreshed the browser and the problem just went away. I'll try to reproduce this error and bring a Issue by then
@polywock

**Comment by polywock** [comment]
Your browser didn't show the code, weird? 

script.remove()  // remove <script> element from DOM after inserting it. 

Is the text below visible?

```
Is this visible?
```

How about `this`?
