### ISSUE TITLE
Shortcut keys not working in Tor-enabled incognito mode in Brave.

### ISSUE THREAD

**Issue by sharadmathur1** [polywock/globalSpeed#141]
![image](https://user-images.githubusercontent.com/17840830/140566725-80d8be4e-df41-4f32-bb49-8a07a6b71875.png)
Whenever I try to control media on a website (for example TikTok) using the shortcut keys I've set, they don't seem to work. Other features not controlled through the keyboard like changing speed to a fixed preset seem to work perfectly well. 
![image](https://user-images.githubusercontent.com/17840830/140566965-985a5cc5-e849-4d82-acd7-565748d65347.png)
I've obv allowed the extension to work in Incognito mode but the shortcut keys don't seem to be working.

**Comment by polywock** [comment]
Hello. I managed to reproduced this bug. The root issue is that message passing through the `chrome.tabs.sendMessage` API isn't working for Brave's Tor tabs. No way to fix this on my end without rewriting the extension to not require message passing.
