### ISSUE TITLE
How to set the global speed?

### ISSUE THREAD

**Issue by olliebean** [polywock/globalSpeed#142]
I have "pin by default" and "inherit global" checked in the settings, but the global speed seems to keep changing. I just want to set it so new tabs always open with a speed of 1, no matter what the speed is in any other tabs, including the parent tab. At the moment the only way I've been able to achieve this is by setting a LAX URL rule to set the speed to 1 on all URLs. But surely there must be a way to set the global speed and ensure it will not keep changing to a different speed that I have used on an individual pinned tab?

**Comment by polywock** [comment]
![diagram](https://user-images.githubusercontent.com/31208859/140872045-0ab25dd3-ef1f-48d9-85ba-0fde7975d3d2.png)

Hello. All unpinned tabs share the global context. So to set the global context's speed to 1.0x, unpin your current tab and then change the speed to 1.0x. Now that the global context's speed is 1.0x and "inherit global" is checked, all new tabs will start at 1.0x speed. As for why the global context's speed keeps changing. It shouldn't, unless you're changing the speed while using an unpinned tab. There's a hotkey (key Q by default) that toggles between pinned and unpinned mode. You might have accidentally unpinned one of your tabs and then changed the global speed that way.

**Comment by olliebean** [comment]
Thanks, I think that's probably what's been happening. I've deleted the hotkey as I've never knowingly used it. Also followed your guidance to set the global speed back to 1, where hopefully it will now stay.
