### ISSUE TITLE
Idea : A Hotkey to disable/enable the others hotkeys

### ISSUE THREAD

**Issue by HUGHNew** [polywock/globalSpeed#143]
Idea : a new function hotkey which can disable or enable the others hotkeys
It can improve user experience if the plugin's hotkeys collide with this page default's or others

**Comment by polywock** [comment]
Hello. It's not exactly what you're looking for, but you can use the ⏻ state hotkey to disable/enable the rest of the hotkeys. On the other hand, if you use the ⏻ button in the extension menu, that disables all hotkeys including the ⏻ state hotkey.

**Comment by HUGHNew** [comment]
What I want to do is disable this plugin's hotkeys with a its hotkey while this plugin is active.
It seems that I want to shutdown the plugin with a hotkey (which is like a global hotkey of the browser). But I'd like to keep it working backgroud.

**Comment by HUGHNew** [comment]
> Hello. It's not exactly what you're looking for, but you can use the ⏻ state hotkey to disable/enable the rest of the hotkeys. On the other hand, if you use the ⏻ button in the extension menu, that disables all hotkeys including the ⏻ state hotkey.

Did you mean the **Power** button?

**Comment by HUGHNew** [comment]
That's what I want, thx!
