### ISSUE TITLE
I have a lot of audio issues

### ISSUE THREAD

**Issue by anirudh-pixel** [polywock/globalSpeed#147]
1. Audio feature not always on with respect to previous setting as is the case with video settings like saturation when opening a new page.
2. Audio sync given only non-negative. Please add negative audio sync also.
3. Audio becomes heavily distorted when changing any audio setting.
4. Double sound when setting an audio delay.

I think u should re-program the audio scripts, the amount of issues are tremendous.

**Comment by polywock** [comment]
1. The extension can't auto-capture because of technical limitations with the TabCapture API. The API requires the user invoke the extension before the extension can capture the audio. To invoke an extension, user must either click on the extension icon or use a browser level hotkey. To make capturing more convenient, you can create a "capture" hotkey in the options page and set it to "commandX". You can configure "CommandX" in the shortcuts editor `chrome://extensions/shortcuts`. 
2. There's a cool [extension](https://chrome.google.com/webstore/detail/youtube-audiovideo-sync/mknmhikmjljhpccebpnplhicmcfjkgbk?hl=en) that does negative audio delay for Youtube. That extension's approach cannot be extended to other websites. 
3. Interesting. I'm not sure why. You might have changed other audio settings like the equalizer or pitch. Try to reinstall the extension to see if the issue remains. 
4. Near the delay slider, there's a little "+" icon. Click on that to unmerge the real and delayed audio. 

I'll look into improving the audio functionality for the Manifest V3 update. As for issue 3, let me know if reinstalling fixed the issue.

**Comment by anirudh-pixel** [comment]
As per your recommendations I have done what u told and i also have kinda temporary kinda permanent solutions to the problems not solved.  1,4 got solved for what u told the other 2,3 solutions are beneath

I am gonna include some preface and explanations also so for tl;dr go to bottom.

**For 2. I don't think there is any practical benefit of positive audio delay** because sync is required as wireless headphones tend to delay audio signals in the range of 300-500 ms if I talk about some cheap $60 headphones. So instead of delaying audio signals we need to pre-process them or have a negative audio delay. Positive sync is required only if subtitles or audio files are muxed incorrectly which is quite rare. 
Can you bother explaining why the heck u said "That extension's approach cannot be extended to other websites." I am not so technical but I at least understand that yt video audio/video streams are separate so it's very easy to delay/hasten , and reason why global speed is able to delay audio is bcoz it captures the stream at the point its played and play it after a certain time which certainly isnt possible with hastening or -ve sync but... video players like POTPLAYER which imo is the greatest player ever made can not just delay/hasten network url files but can apply each and every possible functionality that u can have with a local files. This essentially means that even if the audio/video stream is combined and isn't downloaded fully it can still be separately into 2 different parts using the right programming knowledge.

For 3. I tested in I think at least 10 different environments on 4 different machines with different hardware so as to why the audio is distorted using 1 wireless and 1 wired headphone. I am not going to include the results of each and every one but I will still tell the solutions.

Windows 10 official/unofficial debloated version both have higher compatibility with your extension than Windows 11. With higher compatibility I mean that distortions are far less than using same hardware in windows 11. Reinstalling the extension doesn't help at all. Changing from chrome to edge or vice-versa isn't helpful at all. Changing from wired to wireless headphones or vice versa is a hit or a miss some hardware have higher compatibility with wireless some with wired. All the above results were valid also for some other audio modification extensions so that means this isn't an extension problem (or maybe it is who knows?😂).

NOW THE SOLUTIONS FOR 2,3.

For people having problems syncing wireless headphones from what I have researched negative sync extensions or software aren't there. But my latency problems got fixed doing these things . ONLY FOR WINDOWS OS.
Go to change system sounds in control panel.
Go to playback.
Select your playback devices.
TURN OFF BOTH THE OPTIONS FOR EXCLUSIVE MODE UNDER ADVANCED. most people problems would be sorted here.
If this doesn't help tinker with your sample rate, exclusive mode, windows spatial, and enhancements until the time it is synced. This doesn't necessarily means you have to turn all of them off . Try turning on/off some at some time in this manner it should help. For testing the sync I rewatched 12 angry men as it has a lot dialogues without much gap between the dialogues along with subtitles in an online video player.

If you are having distorted audio then i have written above which os and type of thing is most compatible. Turning off both options for exclusive mode under advanced as demonstrated above helps tremendously and is the only option without using 3rd party software. Most users don't need to proceed further, but since i am an audiophile I can detect even the slightest of distortions and some distortions are always there no matter which os/extension/setting you do.
If u still are having distortions use an windows audio program called Boom 3D. I have been using this since last 2 years and when I tested boom 3d with global speed audio capture on not even the slightest of audio distortions were present without even me having to configure any windows settings and that too using Windows 11 which is less compatible. This program essentially converts all incoming windows audio streams to 3d/spatial/etc. depending on users setting in real time. As you might have guessed it is paid but it costs just $15 one time fees and even still genuine cracks are freely available online.

**Comment by polywock** [comment]
The audio delay feature seems to mostly be [used to sync live sports with a separate live commentary](https://www.reddit.com/r/ColoradoAvalanche/comments/npxkxo/dont_like_nbc_announcers_want_to_listen_to_conner/).  

The YouTube Audio/Video Sync extension mutes the Youtube video and loads a separate audio only stream with the time position shifted for either a negative or positive audio delay. To extend that approach to other websites, the website would have to deliver the audio stream separately which is rarely the case and the way to load the audio stream has to be understood. For Youtube that's the case, but other websites are mostly undocumented and would require thorough investigation (reverse engineering). 

Potplayer/VLC negative delay seems to work by delaying the video's visuals.  To delay audio, I just feed the audio stream through a Audio Delay Node using the Web Audio API. There isn't a visual equivalent of that. To delay video, I believe I would have to intercept the video stream, decode the video, modify the video to add delay, and then re-encode the video back. PotPlayer/VLC use [libavcodec](https://en.wikipedia.org/wiki/Libavcodec) to decode/encode videos. I don't think libavcodec is available on the web. There might be a WebAssembly version of that somewhere, but it would still be a lot of work.  Theoretically possible with the right programming knowledge, but too much work for lazy me. 

I don't have any distortion or delay (wired headset) when using the audio effects (on Mac), but I would keep your solutions in mind if someone else has a similar issue.

**Comment by anirudh-pixel** [comment]
Thanks for explaining the delay issue in such technical terms .
Kudos to you for making such a great extension and that too keeping it free and kinda updated.
There are a real dearth of such extensions that help in customizing the video and stuff for browsers; no major video player has developed a video player for the web that has all the options in as that of their windows software.
I am closing the issue now.

**_### Read below only if you are free._**
I have to pirate content just because of this reason as most webseries on netflix/etc. are so so very dark these days that I feel that I am literally watching a black screen with audio. They give no option to customize audio/video sync contrast/brightness aspect ratio/video cropping or changing the audio/video decoder and since I, a veteran of the torrent era has been so accustomed to these things that I cannot watch a video without customizing all the above stuff along with tons of other things.
