### ISSUE TITLE
请问退出再重新打开浏览器，可以恢复默认速度为×1.0吗？

### ISSUE THREAD

**Issue by YiwuZhang** [polywock/globalSpeed#148]
每次重新开机都发现倍速没有关。

**Comment by polywock** [comment]
Hello. If your speed is 1.0x and you want to change it to 2.0x. First pin that tab using the pin button 📌 . Once pinned, the speed change to 2.0x will only effect that tab. So if you go to a different tab or restart your computer, the speed will still be 1.0x. 

![demo2](https://user-images.githubusercontent.com/31208859/143529001-ed548f4f-4863-4e36-88df-14be14452e55.png)

To make this more convenient, you can enable the "pin by default" feature in the options page. Once enabled, all new tabs will automatically be pinned so they have their own context. As long as the global context's speed is 1.0x, all new tabs will start at 1.0x (including when you restart your computer). 

![demo1](https://user-images.githubusercontent.com/31208859/143528694-e970e5ce-6ae3-4ec0-ab39-2c7ad5b9a2b6.png)

**Comment by teadrinker2015** [comment]
> Hello. If your speed is 1.0x and you want to change it to 2.0x. First pin that tab using the pin button 📌 and then change the speed to 2.0x. Once pinned, the speed change to 2.0x will only effect that tab. So if you go to a different tab or restart your computer, the speed will still be 1.0x.
> 
> ![demo2](https://user-images.githubusercontent.com/31208859/143529001-ed548f4f-4863-4e36-88df-14be14452e55.png)
> 
> To make this more convenient, you can enable the "pin by default" feature in the options page. Once enabled, all new tabs will automatically be pinned so they have their own context. If you change the speed, it will only change the speed for that tab. As long as the global context's speed is 1.0x, all new tabs will start at 1.0x (including when you restart your computer).
> 
> ![demo1](https://user-images.githubusercontent.com/31208859/143528694-e970e5ce-6ae3-4ec0-ab39-2c7ad5b9a2b6.png)

I think he is referring to this:
[#174](https://github.com/polywock/globalSpeed/issues/174#issuecomment-1082260282)

具体操作也可以参考这里：
https://github.com/polywock/globalSpeed/issues/152#issuecomment-1098066296

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of today, the issue should be resolved. Additionally, pin by default now supports a "new context" option so all new tabs start at 1x.
