### ISSUE TITLE
The problem of live broadcast acceleration

### ISSUE THREAD

**Issue by surizo** [polywock/globalSpeed#15]
I wonder if you can set it to a specific page and choose to accelerate or not, because the live page effect is not good.

**Comment by polywock** [comment]
Why not just set the speed to 1.0?

**Comment by surizo** [comment]
yeah，but After close the page, it resets.

**Comment by polywock** [comment]
In the next version, I'll add URL rules to automatically set a speed depending on the website. For example, if `https://twitch.com`, set the speed to `1.0`. For now, maybe use the shortcut keys to quickly change your speed, they're configurable in the options page.

**Comment by surizo** [comment]
Thank you for your reply！

**Comment by polywock** [comment]
An update. The next update should be published in a few days. Once it's published, it you need help configuring the URL rules. Let me know.

**Comment by surizo** [comment]
Thanks！It's working pretty well now

**Comment by surizo** [comment]
I have updated.
