### ISSUE TITLE
Support mouse wheel control when the mouse is over the extension icon.

### ISSUE THREAD

**Issue by Hzbeta** [polywock/globalSpeed#150]
I hope when the mouse is over the icon like this, I can use the mouse wheel to control the video speed. 
<img width="205" alt="Snipaste_2021-12-03_16-32-29" src="https://user-images.githubusercontent.com/6748577/144570953-f53b6a2e-0ebd-47d7-a693-9388566adced.png">
Like wheel up to speed up, wheel down to speed down. 
Thank you so much.

**Comment by polywock** [comment]
Hello. Would be nice, but sadly not supported. The [Browser Action API ](https://developer.chrome.com/docs/extensions/reference/browserAction/) only lets you control the image, badge color and badge text.
