### ISSUE TITLE
在b站打开颜色反转，图片的颜色不对，不是想要的黑暗模式

### ISSUE THREAD

**Issue by meihus** [polywock/globalSpeed#151]

**Comment by polywock** [comment]
Hello. I've included some images that might be helpful. If you're viewing this through email the images might not show up. 

1. Go to backdrop section. 
![a1](https://user-images.githubusercontent.com/31208859/144758280-7b818e2f-b38b-4fc8-8b3f-ac7dd8a8ee84.png)

2. Inversion would apply to entire page. 
![a2](https://user-images.githubusercontent.com/31208859/144758288-3cdb540b-b939-4d80-a5a1-d34e77847a09.png)

3. Open the element section. 
![a3](https://user-images.githubusercontent.com/31208859/144758291-1d3c8d05-09e8-4c63-80af-9f5cfa92fcd2.png)

4. Inversion would only apply to the video. Bringing the video's color back to normal. 
![a4](https://user-images.githubusercontent.com/31208859/144758294-2046ce16-8367-4603-afe5-770243641882.png)

5. To fix image color you can change the element selector to "video, img". 
![a6](https://user-images.githubusercontent.com/31208859/144758301-eba36c59-ada7-4bd0-97a1-c090b1ead41f.png)

To make inverting more convenient. You can open the option page and enable this hotkey. 

![a7](https://user-images.githubusercontent.com/31208859/144758578-818a13a2-f28b-4566-8e5b-8205cae61296.png)

Using the hotkey shortcut is much more convenient. 

https://user-images.githubusercontent.com/31208859/144758735-11be87d4-a06c-4467-b5db-28a754df7a92.mov

**Comment by meihus** [comment]
Thank you, this answer is very detailed.

**Comment by polywock** [comment]
No problem. Glad to be helpful
