### ISSUE TITLE
希望可以独立操控各个网站的倍速

### ISSUE THREAD

**Issue by PuKarziu** [polywock/globalSpeed#152]

**Comment by JOZIG** [comment]
你可以看一下同面板上的这个问题的解答，应该可以回答你的问题。https://github.com/polywock/globalSpeed/issues/148
他里面说了，可以单独设定不同页面的速度。

**Comment by teadrinker2015** [comment]
[#174](https://github.com/polywock/globalSpeed/issues/174#issuecomment-1082260282)
在 URL rules 中添加：ILO→==→reg→.*→speed→1
应该可以一劳永逸的解决重启浏览器后标签被unpin的问题（在新的API推出以前）

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of today, I'm not sure what the status of this issue is. For now, I'll close the issue. Please re-open if needed.
