### ISSUE TITLE
视频全屏播放会卡顿

### ISSUE THREAD

**Issue by jil1023** [polywock/globalSpeed#155]
播放速度有卡顿,语速正常

**Comment by polywock** [comment]
Hello. First time hearing about this type of issue. A few questions. 

1. Did you enter fullscreen mode using the standard way? Or did you use this plugin's shortcut (Shift-F by default)? 
1. Does this happen on all websites or just a specific website? If it's a specific website, which website? 
2. Does it also happen with Global Speed plugin disabled?

**Comment by sanbei011** [comment]
你好。第一次听说这种类型的问题。几个问题。

您是否使用标准方式进入全屏模式？还是您使用此插件的快捷方式（默认情况下为Shift-F）？
这是发生在所有网站上还是只发生在特定网站上？如果是特定网站，哪个网站？
当速度设置为 1.0x 时，是否也会发生这种情况？
禁用全球速度插件时也会发生这种情况吗？
