### ISSUE TITLE
Non-linear speed control

### ISSUE THREAD

**Issue by 14Si** [polywock/globalSpeed#158]
A way to set two keybinds (rather than just one) to walk up and down a list of values set for speed control rather than just up. 

I have a bunch of values along the 2^(n/12) curve and I have to cycle all the way around to set it to a lower speed. 

Alternatively implementing a × and ÷ mode to multiply and divide (or just multiply)  would allow me to achieve the functionality I want.

**Comment by polywock** [comment]
Hello. The use case seems too niche to be worth the effort, but if there's more demand I'll look into implementing it. I think the best solution would be to bind the speed values to the 0-9 keys. If the 0-9 keys aren't enough, you could also include modifiers like shift 0-9. You could also memorize the list of values and use speed +/- hotkeys to switch to them. In addition to the default A (-0.1) and D (+0.1) hotkey, you set Shift-A to -0.01 and Shift-D to +0.01 for fine tuning. Or round the list of values to the nearest 0.1 for quicker adjustment, but that will probably defeat the purpose.

**Comment by polywock** [comment]
Hello, an update. Since I received more demand for your suggested feature, I'll probably implement a way to walk down the list of values in the next update, but that might take a while.

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of today, this feature is supported. You can add a shortcut to walk both directions of a list. To do so, click on the 3 dots for the shortcut and enable "reversible".
