### ISSUE TITLE
Speed reset

### ISSUE THREAD

**Issue by k2lz** [polywock/globalSpeed#160]
Hi, awesome extension, I use it all the time!
Just an idea... Maybe it would make sense to create an event, when the extension icon is middle clicked (with mouse scroll), it would reset speed to 1.0 (or any other, that is set as a default)

Again, thank you for this great extension!

**Comment by polywock** [comment]
Thanks! Glad to see the extension useful. I like the suggestion, but it's not possible. The browserAction API doesn't let extensions listen to middle click events.
