### ISSUE TITLE
how to reset speed to 1.0x on new tab

### ISSUE THREAD

**Issue by chefengbo** [polywock/globalSpeed#163]
I change speed 1.3x on Tab A，then open a new Tab B from Tab A，but the Tab B is 1.3x too whether I pin the button。How to reset speed to 1.0x when I open new Tab？

**Comment by polywock** [comment]
Hello. Here's a diagram on how pinning works. All unpinned tabs share the same global context. If a tab is pinned, it will have it's own separate context. 

![diagram](https://user-images.githubusercontent.com/31208859/149994031-64f491e2-6127-45da-ba49-00c1b23966ae.png)

If you want all new tabs to start at 1.0x. 
1. Set the global context's speed to 1.0x. You can change the global context's speed from any tab that's not pinned. 
2. Enable "pin by default" in the options page. Once enabled, all new tabs will be pinned automatically and inherit the global context. As long as the global context's speed is 1.0x, all new tabs should start at 1.0x. 

![img11](https://user-images.githubusercontent.com/31208859/149996028-7149ac1a-918d-47a6-b3bc-98921b4b59bc.png)

**Comment by Mingw0717** [comment]
很棒的插件, 感谢.
That's a so good plugin, thanks.

**Comment by teadrinker2015** [comment]
https://github.com/polywock/globalSpeed/issues/174#issuecomment-1082260282
will resolve this problem temporarily ( before new API release )

In case you not familiar with regex:
in URL rules create: ILO→==→reg→.*→speed→1

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of today, this feature is supported. Set the pin by default mode to "new context" so all tabs start at 1x speed.
