### ISSUE TITLE
画中画的默认位置和大小可以更改么

### ISSUE THREAD

**Issue by CheshireVcat** [polywock/globalSpeed#165]
RT

**Comment by polywock** [comment]
Hello. This plugin enters PiP mode using the video's [requestPictureInPicture()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/requestPictureInPicture) function. The Picture-in-Picture API is very limited and only provides two functions. One to exit PiP mode and one to enter PiP mode. 

Firefox has much better PiP functionality. You can scale your PiP window any size and it remembers your PIP position and size.
