### ISSUE TITLE
在线视频建议增加多个书签

### ISSUE THREAD

**Issue by fqh1995** [polywock/globalSpeed#166]
目前视频（内容太多）仅支持一个标记，希望可以增加多个书签标记，比如热键h可以增加多个视频章节标记，按w依次跳转至下一个书签

**Comment by polywock** [comment]
Hello. In the options page, you can bind 1-9 keys to a different marks (mark1, mark2, mark3, etc). 
![mark2](https://user-images.githubusercontent.com/31208859/152100798-9a36da76-051d-4d94-88b9-6b9c90d1dadc.png).

As for the method you requested, it's also possible, but it's a hidden feature. If you create a "set mark" shortcut, you can change the name from "mark1" to the following list of special keywords.

`::nameless`: This will place a nameless mark, as many as you want. 
`::nameless-prev`: This will go to previous nameless mark. 
`::nameless-next`: This will go to next nameless mark. 

Video example attached below. 

https://user-images.githubusercontent.com/31208859/120088779-201ea600-c0c2-11eb-9aa1-9b73c9928a7f.mov

**Comment by fqh1995** [comment]
感谢回复，本插件非常优秀，希望可以更加进步
