### ISSUE TITLE
希望能加入白名单，黑名单功能

### ISSUE THREAD

**Issue by y9287** [polywock/globalSpeed#167]
希望能加入白名单，黑名单功能

**Comment by polywock** [comment]
Next update I will look into adding a true blacklist function. 

For now, to disable shortcuts in some websites, you can add URL conditions. For example, to blacklist hotkeys for websites, you can do this. (image attached below) 

![demo3](https://user-images.githubusercontent.com/31208859/153326520-b2d1bbd1-a50e-4e0a-a7c5-45639d5b01c3.png)
