### ISSUE TITLE
如果能加入下一个，上一个视频播放的热键定制就更完美了！

### ISSUE THREAD

**Issue by y9287** [polywock/globalSpeed#168]
如果能加入下一个，上一个视频的热键定制就更完美了！

**Comment by polywock** [comment]
Hello. This feature was suggested in #130. There is no good way to implement this feature. Each website has different ways to go to the next/previous video. To be able to support all the most popular websites will require a lot of maintenance work on my part. Not sustainable in my opinion. There are extensions that tried to do this like [Stream Keys](https://github.com/berrberr/streamkeys), but as you can see through their Github, it required a lot of effort and the developer seemed to have got tired and quit. I'm too lazy to even try.
