### ISSUE TITLE
URL Rules not working

### ISSUE THREAD

**Issue by JellyV** [polywock/globalSpeed#170]
I tried adding a URL Rule to disable the extension on wordlegame.org

![image](https://user-images.githubusercontent.com/17710991/153316796-a1b51014-ade4-4dca-90ee-202970397a14.png)
![image](https://user-images.githubusercontent.com/17710991/153316878-085e4a9c-46fc-457b-a5d5-316f601939c4.png)

I also tried "==" instead of "!=", checking/unchecking ILO and LAX options, refreshed the page, restarted the browser, but the shortcuts still work on wordlegame.org. Am I doing something wrong or is this a bug?

**Comment by polywock** [comment]
Hello. A URL rule set to "state = off" should work (it's set to speed = 1 in your screenshot), but to disable shortcuts, it's better to add URL conditions to the shortcut section. It's not an obvious feature so I apologize for that. 

![demo3](https://user-images.githubusercontent.com/31208859/153324374-4fb01419-9737-4e35-b63d-b89b306ba0d8.png)
