### ISSUE TITLE
UI Menu Selevtion

### ISSUE THREAD

**Issue by ahermon** [polywock/globalSpeed#171]
Hello, off the bat, great extension! I use regularly 4-5 different browsers and this extension works great in the major 3 and few of the less major. The video lag when applying video filters is a pain but I saw that someone already brought that issue to your attention. This is really not an issue but an enhancement suggestion. 

I do use the Hotkeys often but I just as often just click the extension icon on the browser and use the UI to Seek +/-. This is especially the case when it is late at night or I am comfortable and just put the keyboard away. Pretty much getting around videos at that point is mouse-dominated. However, the only seek UI selections are for the first set of Seek Hotkey options set. In my case, I have2 sets of Seek HotKey options. One for +/- 5 and the other +/-10. 10 for bigger jumps and 5 for granularity.

Again, works great as long as using Hotkeys but only the first default set comes up in UI in the same section as Audio and Select. 

![image](https://user-images.githubusercontent.com/40039827/153723222-3e614e35-fffa-4f2d-becd-a38c8641357d.png)

I guess it would be great to have the option of having any assigned HotKey also be optionally available in UI, so they can also be used by mouse or touchpad. As of yet, I have not seen anything that allows me to do this.

I have no idea how this could work in UI or make it an option if you have multiple selections. I was thinking that since you have an Enable/ Disable button for each Hotkey, you can add another button of whether to have that Hotkey come up under the UI when someone once to control it from a mouse. Just a thought.

Of course, I am primarily interested in the Seek since I have multiple Hotkeys assigned but I assume other users probably have other selections that might benefit from this enhancement suggestion. Again, great product, and please keep it up!

Thanks!

Also, I totally believe in supporting those products that solve my issues or I really like and use a lot. Often that means the developer(s) are individual entrepreneurs who invested their personal time and efforts in labors of love, to make such good/ great products and solutions! For any product that I really like I like to give little donations to both show appreciation but also to keep these kinds of efforts going. However, I did not see anything to allow us to give a little something on the GlobalSpeed extensions websites or on your GitHub.

Did I just miss it or don't you take support donations?

Again thanks!

Alberto!

**Comment by polywock** [comment]
You're welcome! I don't currently have any donation setup, but the offer to contribute is much appreciated :). 

As for UI, I'm thinking of something like this. If you click the 3 dots, it will show an option to "add to menu". If clicked, it will ask the user to provide the menu button's name. For example, for hotkey to seek -10 seconds, you can call the menu button "-10". 

![example2](https://user-images.githubusercontent.com/31208859/153733573-97cea523-1211-42ed-8147-f75f00714855.png)

In the menu, it would show -10 button under each media item. Is this fine? I'll look into implementing this in the next update. But, that might take a while. Right now, I'm waiting for Manifest V3 to stabilize before I implement any new features. Manifest V3 has a lot of changes and the entire extension will need to be rewritten and I would prefer not to implement stuff just to have to rewrite it later.  

![example1](https://user-images.githubusercontent.com/31208859/153733581-8bf1fb01-8d23-4875-93c4-eac6f651ba3d.png)







> The video lag when applying video filters is a pain but I saw that someone already brought that issue to your attention.

I don't recall any Github Issue about video filters being laggy. Could you elaborate on this?

**Comment by ahermon** [comment]
Hello @polywock! Thanks for the quick reply! Was not prepared for it which is why I am just now responding. Your proposed solution for adding optional Hotkeys settings to UI is great!!  

![image](https://user-images.githubusercontent.com/40039827/153773842-4a020f20-7cd8-4507-853c-9ddbaf62b2c7.png)

Again I spend half time on Keyboard but after a certain hour, I kick back and it is all mouse especially when series binging! Your product gets better and better! Glad I ran across it!

On the delay I experience when using the video filters like brightness and contrast, I will put that in a separate comment. I thought I saw another user post something about negative delays. When you posted back that you did not remember any laggy issues being posted I went back and rechecked. That other issue I think was with Audio and not video. Either way, I want to do a little bit more experimentation and post my finding under a separate issues chain. 

I see it with Opera streaming Youtube TV but I have not tested it with Edge, Chrome, Firefox, or Vivaldi yet. I use Opera for Youtube TV b/c it seems best at not having that buffering streaming issues I see with the other browsers. In fact, Opera does not seem to have it at all. I use Edge for Amazon Prime and a mixture of others for regular Youtube videos, Udemy and PluralSight. You Global Speed works great on all though I have not tested it on Vivaldi yet.

Anyway, it has been a while and a few browser versions since I did streaming tests so I will just test your product's Brightness and Contrast settings on all of them for YouTube TV and post my results about if it gets choppy. Your solution on having optional Hotkeys on UI is the most important to me so I don't want to hold that up if you are planning it for the next release. Also, I am posting another suggestion on UI on a separate chain as well.

Thanks again!

**Comment by polywock** [comment]
@ahermon Hello. Apologies for the late update. I was going through the open issues when I came across this issue again. 

Shortcuts can know be accessible as a context menu, but that wouldn't be convenient for something like seeking. However, there's a new "circle widget" option that might be helpful to you. While videos are visible, it shows a little circle that can be dragged left and right to seek the video. It can also be dragged up/down to change speed.
