### ISSUE TITLE
Does not work on Vidyard player

### ISSUE THREAD

**Issue by cliffordp** [polywock/globalSpeed#173]
True for multiple but here's one example: https://share.vidyard.com/watch/kxxVtb5YCdf26dVH9j2ZUS

**Comment by polywock** [comment]
Hello, Clifford. That example seems to work for me. I also tried a few other Vidyard videos without issue. Maybe try enabling "Ghost mode" in the options page or reinstalling the extension. I'm not sure why it's not working for you.

**Comment by cliffordp** [comment]
Hm, not sure what could have been the issue but I agree it's working now. tyvm for this extension!
