### ISSUE TITLE
Tabs are unpinned when the browser is restarted

### ISSUE THREAD

**Issue by olliebean** [polywock/globalSpeed#174]
I have the settings set to pin by default, as I never want to change the global speed. Also, I have Firefox set up to restore previous tabs when I restart it. But after restarting, all the restored tabs are unpinned in the addon. Because of this, unless I remember to go through all the tabs re-pinning them, I find myself sometimes accidentally changing the global speed instead of the speed for just the current tab.

Is it possible to have the addon maintain the pinned state of the restored tabs when the browser is restarted?

**Comment by polywock** [comment]
Definitely possible. I'll implement this in the next update. But, that might take a while because I'm waiting for the Manifest V3 API to stabilize before I implement any new features.

**Comment by olliebean** [comment]
FWIW, I found a workaround for this (as long as I want all my tabs pinned, which I do) - I found that if I create a URL rule, to match all URLs, and set it to set the speed to 1 during the initial page load, it does this when all the restored tabs load after a restart, and also automatically pins them.

**Comment by teadrinker2015** [comment]
Found another (additional) solution:
Double every shortcut keys which manipulate speed, and make them to "pin tab on" (Make sure those appear on top, otherwise they will still change the global speed)
![图片](https://user-images.githubusercontent.com/22217676/169038386-8e5d3eac-1775-4ca5-92ea-b59b80f2b73e.png)

**Comment by olliebean** [comment]
> Found another (additional) solution: Double every shortcut keys which manipulate speed, and make them to "pin tab on" (Make sure those appear on top, otherwise they will still change the global speed)

That's a good one. Makes sure the global speed never changes - which is exactly how I want it - regardless of whether the tabs start out pinned or not.

**Comment by polywock** [comment]
Finally got around fixing this issue. Long overdue, but better late than never. 

It should be available within a week (at least on Chrome and Firefox).
