### ISSUE TITLE
为什么本地视频文件不能加速

### ISSUE THREAD

**Issue by Xiaomo250** [polywock/globalSpeed#175]
用浏览器打开本地视频文件时，它显示在正常工作，但实际上视频还是原来的速度

**Comment by polywock** [comment]
Hello. Chome/Edge doesn't let plugins access local files by default. The user needs to enable "Allow access to file URLs". 


![test](https://user-images.githubusercontent.com/31208859/154507909-8ef4247a-6ceb-4a2c-bb9a-474794cf8fa2.png)

**Comment by Xiaomo250** [comment]
OK,thanks.
