### ISSUE TITLE
Feature: Calculate the video duration after adjusting play speed

### ISSUE THREAD

**Issue by LinGaNinJa** [polywock/globalSpeed#179]
Is it possible to show the new video duration after adjusting play speed? 
The ultimate goal is to know how much time is left to finish this video. However, speed up play speed makes it quite hard to understand. 

If I can get to the new duration, I can have a rough idea about how much time I need for it. Or even display the time when the video ends after speeding up, like "02:30 PM".

**Comment by polywock** [comment]
Hello. I'm planning to add something like this in the next update, but that might take a while. 

![test](https://user-images.githubusercontent.com/31208859/154722525-972ecd2a-80ed-4949-8aa0-5fe3e4da4513.png)

For now, you can create a Javascript hotkey in the Options page set to the following code. Once triggered, it should show something like this. 

![test1](https://user-images.githubusercontent.com/31208859/155659970-dce248ea-71ef-4332-b600-6ef2b985bca1.png)


```javascript
function main() {
    function formatDuration(secs) {
        if (secs === Infinity) return "∞"; 
        const mins = secs / 60;
        const hours = mins / 60;
        if (hours >= 100) {
            return "";
        }
        else if (hours > 1) {
            return `${Math.floor(hours)}:${Math.floor((mins % 60)).toString().padStart(2, "0")}:${Math.floor((secs % 60)).toString().padStart(2, "0")}`;
        }
        else {
            return `${Math.floor(mins).toString().padStart(1, "0")}:${Math.floor((secs % 60)).toString().padStart(2, "0")}`;
        };
    }
    const video = document.querySelector("video");
    if (!video) return alert("No video found");
    const currentTime = video.currentTime / video.playbackRate;
    const duration = video.duration / video.playbackRate;
    alert(`${formatDuration(currentTime)} / ${formatDuration(duration)} (${formatDuration(duration - currentTime)} remaining)`);
}

main();
```

**Comment by LinGaNinJa** [comment]
I am grateful for your prompt reply. The script already fits my needs perfectly. I believe the future update will definitely be amazing. Global Speed is my favorite tool. I actually changed my default browser from Safari to Edge because of your extension. Thanks for your hard work!

**Comment by toprak** [comment]
Any updates? Script does not work sadly
