### ISSUE TITLE
Reset to 1.00x when opening a new page

### ISSUE THREAD

**Issue by liangjiancang** [polywock/globalSpeed#18]
Please add a setting to do this.

**Comment by polywock** [comment]
This will be possible in next update using URL rules (see issue #7).

**Comment by polywock** [comment]
Okay, the URL rules have been implemented. It should be published in a few days to a week. A URL rule will have a few options to configure. You'll probably want to configure it like so. Also, again, thanks for the translations. 

![Screen Shot 2020-07-28 at 9 45 51 PM](https://user-images.githubusercontent.com/31208859/88746977-d1a82000-d11b-11ea-9e28-e31c40312692.png)
