### ISSUE TITLE
百度网盘倍速不了

### ISSUE THREAD

**Issue by Jacob999-yu** [polywock/globalSpeed#190]
百度网盘怎么突然不行了？

**Comment by cx330cxcx** [comment]
我的也用不了

**Comment by cx330cxcx** [comment]
今天晚上百度网盘的加速用不了，求解决

**Comment by polywock** [comment]
Hi. Could you share me an example link and code? I tried finding some Baidu videos with format pan.baidu.com/XXXXXXXXX and it still works for me.

**Comment by cx330cxcx** [comment]
> 你好。你能给我分享一个示例链接和代码吗？我尝试找到一些格式 pan.baidu.com/XXXXXXXXX 的百度视频，它仍然适用于我。

https://pan.baidu.com/disk/main?from=homeFlow#/index?category=all

**Comment by zhou-123cpo** [comment]
我的也不行了我重新下载之后还是不行

**Comment by ningmoer** [comment]
我也不行

**Comment by cx330cxcx** [comment]
> 你好。你能给我分享一个示例链接和代码吗？我尝试找到一些格式 pan.baidu.com/XXXXXXXXX 的百度视频，它仍然适用于我。
https://pan.baidu.com/disk/main?from=oldversion#/brand

**Comment by zhou-123cpo** [comment]
> Hi. Could you share me an example link and code? I tried finding some Baidu videos with format pan.baidu.com/XXXXXXXXX and it still works for me.

https://pan.baidu.com/disk/main?from=homeFlow#/index?category=all&path=%2F336.%20%E5%88%98%E6%99%93%E7%87%95-%E4%B8%8D%E5%B0%B1%E6%98%AF%E8%AF%AD%E6%B3%95%E5%92%8C%E9%95%BF%E9%9A%BE%E5%8F%A5%E5%90%97%2F%E5%B0%8F%E7%BA%A2%E4%B9%A6%E5%B0%8F%E4%BA%AE%2F04.2022%20%E7%94%9F%E7%89%A9%E5%8C%96%E5%AD%A6

**Comment by polywock** [comment]
@zhou-123cpo, @cx330cxcx  Thank you for the links. I tried going there, but it redirects me to the home page. It seems like you need an account to go there. I tried creating an account, but Baidu says they don't allow oversees account creation at the moment.

**Comment by Ying-A1** [comment]
an example link:

Linked: https://pan.baidu.com/s/1NlEIb5GFMQYSroM36mWCzw?pwd=ixky 
key: ixky

**Comment by moongahng** [comment]
开发者加油！！

**Comment by Rich1790** [comment]
蹲解决方法

**Comment by cx330cxcx** [comment]
求解决方法

**Comment by polywock** [comment]
> Linked: https://pan.baidu.com/s/1NlEIb5GFMQYSroM36mWCzw?pwd=ixky key: ixky

@Ying-A1 Thanks, but it says link expired. -> 啊哦，你来晚了，分享的文件已经被删除了，下次要早点哟。

**Comment by polywock** [comment]
Does turning on "Ghost mode" in the options page fix the issue? 

![screenshot1](https://user-images.githubusercontent.com/31208859/162488632-8f5cf8f3-a600-4d5d-b5dc-767cada7e44a.png)

**Comment by cx330cxcx** [comment]
> 在选项页面中打开“幽灵模式”是否可以解决问题？
> 
> ![截图1](https://user-images.githubusercontent.com/31208859/162488632-8f5cf8f3-a600-4d5d-b5dc-767cada7e44a.png)
> 
> 如果Ghost Mode不能解决这个问题，我怀疑问题是百度不再使用VIDEO元素播放视频，而是使用自定义CANVAS播放器播放视频。由于VIDEO元素不支持HEVC解码，一些国内中国网站正在使用这种方法播放HEVC视频。您可以通过使用Ctrl-Shift-C快捷方式检查视频来确认这一点。检查它是否使用视频元素或画布元素。

问题已经解决啦，可以正常使用，非常感谢您

**Comment by polywock** [comment]
@cx330cxcx Turning on Ghost Mode fixed the issue? Great. I'll make it so Ghost Mode is automatically activated if website's URL contains "baidu.com".

**Comment by lkhlfh** [comment]
@polywock  It's ready to use now. Thank you!  I don't turn on Ghost Mode. It seems that Baidu upgraded the webpage yesterday.

**Comment by ylw666666** [comment]
> > 在选项页面中打开“幽灵模式”是否可以解决问题？
> > ![截图1](https://user-images.githubusercontent.com/31208859/162488632-8f5cf8f3-a600-4d5d-b5dc-767cada7e44a.png)
> > 如果Ghost Mode不能解决这个问题，我怀疑问题是百度不再使用VIDEO元素播放视频，而是使用自定义CANVAS播放器播放视频。由于VIDEO元素不支持HEVC解码，一些国内中国网站正在使用这种方法播放HEVC视频。您可以通过使用Ctrl-Shift-C快捷方式检查视频来确认这一点。检查它是否使用视频元素或画布元素。
> 
> 问题已经解决啦，可以正常使用，非常感谢您

这个页面在谷歌浏览器的哪个位置

**Comment by ylw666666** [comment]
> > 在选项页面中打开“幽灵模式”是否可以解决问题？
> > ![截图1](https://user-images.githubusercontent.com/31208859/162488632-8f5cf8f3-a600-4d5d-b5dc-767cada7e44a.png)
> > 如果Ghost Mode不能解决这个问题，我怀疑问题是百度不再使用VIDEO元素播放视频，而是使用自定义CANVAS播放器播放视频。由于VIDEO元素不支持HEVC解码，一些国内中国网站正在使用这种方法播放HEVC视频。您可以通过使用Ctrl-Shift-C快捷方式检查视频来确认这一点。检查它是否使用视频元素或画布元素。
> 
> 问题已经解决啦，可以正常使用，非常感谢您

我也开了还是不行

**Comment by ylw666666** [comment]
I can use it in edge browser, but there is still no acceleration function in google browser.

**Comment by ylw666666** [comment]
I can use it on Edge, but Google Chrome still doesn't.

**Comment by hngtyia** [comment]
我发现在百度网盘中，视频播放一段时间后就会有极短暂的加速，然后再以原速播放一段时间

**Comment by 1diana11** [comment]
> 

怎么修改自定义视频播放成VIDEO

**Comment by polywock** [comment]
@1diana11 Hello. Are you sure it's playing a custom video using Canvas? You can run [ Ctrl-Shift-C ] to enter Inspect Mode and click on the video. For me, it says it's a VIDEO. I'm not having any issues yet. 
![img3](https://user-images.githubusercontent.com/31208859/163712729-e040b377-8afb-412a-951f-4f6c8478f463.png)

**Comment by hzyhd60** [comment]
> @1diana11 Hello. Are you sure it's playing a custom video using CANVAS? You can run [ Ctrl-Shift-C ] to enter Inspect Mode and click on the video. For me, it says it's a VIDEO. I'm not having any issues yet. ![img3](https://user-images.githubusercontent.com/31208859/163712729-e040b377-8afb-412a-951f-4f6c8478f463.png)

I guess so
![1650201810](https://user-images.githubusercontent.com/103876776/163716267-e6215837-2811-4a96-9ab3-ea85dc9baf7a.png)

**Comment by zhou-123cpo** [comment]
> 你好。你能给我分享一个示例链接和代码吗？我尝试找到一些格式 pan.baidu.com/XXXXXXXXX 的百度视频，它仍然适用于我。

现在又不能倍速百度网盘了
