### ISSUE TITLE
可以优化一下这个网页吗？谢谢谢谢谢谢

### ISSUE THREAD

**Issue by cavalierzzy** [polywock/globalSpeed#191]
https://v.kaoshixing.com/exam/pc/course/#/study?courseId=15353&companyId=197440&process=true&popProcessId=10791
以前这个平台可以加速，现在没法使用了，如果可以优化一下就好了
谢谢大佬！

**Comment by polywock** [comment]
Hi. Does turning on Ghost Mode in the options page fix the issue? That link requires logging in so I can't test it. 

![screenshot1](https://user-images.githubusercontent.com/31208859/163053315-94945c4c-022b-41b0-a6f3-8ee88562ccaa.png)
