### ISSUE TITLE
百度网盘还是不能倍速

### ISSUE THREAD

**Issue by 1diana11** [polywock/globalSpeed#192]

**Comment by 514959** [comment]
这次开幽灵模式也没有解决

**Comment by 514959** [comment]
用Edge不能倍速，但是它可以在火狐浏览器上倍速

**Comment by polywock** [comment]
Hello. Can you share the video with the extraction code? I've so far failed to reproduce the issue. Some people say it's working, others say it's not. I've tried a few videos and they seem to work. 

![img2](https://user-images.githubusercontent.com/31208859/163711949-3b63ddee-42a1-4076-8c96-dd1453ec6961.png)

**Comment by 514959** [comment]
链接: https://pan.baidu.com/s/1LFvX34fNe0-87wOPT00xrg?pwd=2ga4 提取码: 2ga4 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by polywock** [comment]
@514959 Double speed still seems to work for me. Both in share mode and saved. I tested on Chrome/Edge/Firefox. The issue seems to only effect some people.  

https://user-images.githubusercontent.com/31208859/163715161-9b17df4a-bbd8-4c4f-a8b7-0d1881edb2ef.mov

**Comment by hzyhd60** [comment]
> @514959 Double speed still seems to work for me. Both in share mode and saved. I tested on Chrome/Edge/Firefox. The issue seems to only effect some people. Maybe Baidu is gradually rolling out a new update. Some users are Beta testers. The rest get the update later.
> 
>  Untitled.mov
Hello,as for me,double speed works on the video @514959 shared both in share mode and saved as well.But I can‘t speed the files I stored former regularly.Is it possible that the issue comes from the time we save?

**Comment by polywock** [comment]
@hzyhd60 Hello. That might be the case. On the older videos, could you try the "Ctrl-Shift-C" shortcut to inspect the video. Let me know if it's actually a `<video>` element. Some Chinese domestic sites started using the `<canvas>` element to play videos. If that shortcut doesn't, you could also right click the page and click "Inspect".

**Comment by hzyhd60** [comment]
> @hzyhd60 Hello. That might be the case. On the older videos, could you try the "Ctrl-Shift-C" shortcut to inspect the video. I'm wondering if it's actually a `<video>` element. Some Chinese domestic sites started using the `<canvas>` element to play videos. If that shortcut doesn't, you could also right click the page and click "Inspect".

It's a <canvas> element

**Comment by hzyhd60** [comment]
> @hzyhd60 Hello. That might be the case. On the older videos, could you try the "Ctrl-Shift-C" shortcut to inspect the video. I'm wondering if it's actually a `<video>` element. Some Chinese domestic sites started using the `<canvas>` element to play videos. If that shortcut doesn't, you could also right click the page and click "Inspect".

It's a canvas element indeed.

**Comment by 1diana11** [comment]
> @hzyhd60 Hello. That might be the case. On the older videos, could you try the "Ctrl-Shift-C" shortcut to inspect the video. I'm wondering if it's actually a `<video>` element. Some Chinese domestic sites started using the `<canvas>` element to play videos. If that shortcut doesn't work, you could also right click the page and click "Inspect".
显示用的是<<canvas>>

**Comment by 1diana11** [comment]
if use the <canvas>,how to solve the problem?

**Comment by polywock** [comment]
@hzyhd60 😅  I noticed you replied in the other thread. Since it's confirmed `<canvas>`, the storm is probably coming soon. I think they are gradually rolling it out. `<Canvas>` videos are completely custom so adjusting playback speed won't be easy and will require investigation. 

@1diana11 Sadly, It would be hard to look for a workaround without experiencing it myself. 

While the `<canvas>` video is visible, could you run this javascript code in the console and copy the results? Shortcut to open console is Control + Shift + J. I might be able to get some information out of the loaded scripts. 

```javascript
console.log([...document.querySelectorAll("script")].map(v => v.src).filter(v => v).join("\n"))
```

**Comment by hzyhd60** [comment]
> @hzyhd60 😅 I noticed you replied in the other thread. Since it's confirmed `<canvas>`, the storm is probably coming soon. I think they are gradually rolling it out. `<Canvas>` videos are completely custom so adjusting playback speed won't be easy and will require investigation.
> 
![2e4f34ffcaf419a215be9eaa6e17016](https://user-images.githubusercontent.com/103876776/163719427-1364a606-1fb1-4378-b428-0eb7c7741b50.png)

> @1diana11 Sadly, It would be hard to look for a workaround without experiencing it myself.
> 
> While the `<canvas>` video is visible, could one of you run this javascript code in the console and copy the results? Shortcut to open console is Control + Shift + J. I might be able to get some information out of the loaded scripts.
> 
> ```js
> console.log([...document.querySelectorAll("script")].map(v => v.src).filter(v => v).join("\n"))
> ```
Here

**Comment by 1diana11** [comment]
> @hzyhd60 😅我注意到您在另一个线程中回复了。既然已经确认，风暴可能很快就会来临。我认为他们正在逐步推出它。 视频是完全自定义的，因此调整播放速度并不容易，需要调查。`<canvas>``<Canvas>`
> 
> @1diana11可悲的是，如果不亲身体验，就很难找到解决方法。
> 
> 当视频可见时，你们中的一个人可以在控制台中运行此javascript代码并复制结果吗？打开控制台的快捷方式是控制 + Shift + J。我也许能够从加载的脚本中获取一些信息。`<canvas>`
> 
> ```js
> console.log([...document.querySelectorAll("script")].map(v => v.src).filter(v => v).join("\n"))
> ```

现在我的百度网盘又可以倍速了，自己好了
