### ISSUE TITLE
倍速

### ISSUE THREAD

**Issue by zhou-123cpo** [polywock/globalSpeed#193]
今天早上我打开百度网盘发现不能倍速了，求解决

**Comment by zhou-123cpo** [comment]
> 

链接: https://pan.baidu.com/s/1527coIVeCHpt7qXSc3VVQw?pwd=t78x 提取码: t78x 复制这段内容后打开百度网盘手机App，操作更方便哦
链接如上

**Comment by 1diana11** [comment]
我昨天也不能加速，但是现在又可以加速了

**Comment by polywock** [comment]
Should be fixed in the latest update (2.9.95).
