### ISSUE TITLE
在更新之后的edge上无法使用 Can't be used in the newest version Edge

### ISSUE THREAD

**Issue by Abbert-Ekko** [polywock/globalSpeed#194]
![image](https://user-images.githubusercontent.com/59302104/164159762-a7b052d1-756e-4145-ac24-af0b3a6d4d58.png)

**Comment by polywock** [comment]
Hello. Do you have the official version of Global Speed? The icon color looks weird. Official version linked below. 

https://microsoftedge.microsoft.com/addons/detail/mjhlabbcmjflkpjknnicihkfnmbdfced
