### ISSUE TITLE
Text color in badge hard to read 

### ISSUE THREAD

**Issue by Nova38** [polywock/globalSpeed#195]
A while back the badge in the toolbars text color change to be a redish white color instead of a pure white on red background (on at least the edge and chrome version) . These colors combination are hard to read as they don't have a good contrast between each other.

Here is the new icon: ![image](https://user-images.githubusercontent.com/17151865/165127893-2361aecb-a1c2-4ae7-8fac-89cb16de0c8e.png). 

Here is the old icon : ![image](https://user-images.githubusercontent.com/17151865/165128168-d058effe-32bc-47dd-9c4f-828a5614455e.png)

**Comment by polywock** [comment]
Hi Thomas. Happy to see you're still using the extension. I think you were here when it had less than 100 users.  

As for the issue. It seems to be a Chromium bug. There is actually no way for Chromium extensions to change the badge text color. The only methods available are `setBadgeText` and `setBadgeBackgroundColor`. Only Firefox has `setBadgeTextColor`. The extension also hasn't been updated for half a year (waiting for Manifest V3 to stabilize), so one of the newer Chromium updates seems to be the culprit. 

It looks like only some users are affected. I tested on Chrome 100.0.4896 and Edge 100.0.1185 and I couldn't replicate it. Another user also had the same issue recently (#194). 

A few questions. 
1. Are you on the latest Chrome (or Edge)? If not, does updating fix the issue? 
2. Does reinstalling the extension fix the issue? 
3. Does installing Global Speed on a different Chrome/Edge profile fix the issue?
