### ISSUE TITLE
Question(s) about addon

### ISSUE THREAD

**Issue by Fireworkstars46** [polywock/globalSpeed#196]
How exactly do I set up a volume up and volume down shortcut key making it go every single percent (1 2 3, etc up to 100)?

**Comment by Fireworkstars46** [comment]
Ok. Also is it possible to set the volume to a default percentage? Like every tab or a specific website I got to, have it be at a specific percentage.

**Comment by polywock** [comment]
Sadly not. By the way, speaking of default volume. Some websites like Youtube only store volume changes if it's made through the video's volume slider.

*Scanario 1*: If you change volume to 80% using Youtube's own volume slider. If you refresh the page, volume should still be 80%. 

*Scanario 2*: If you change volume to 80% using a Global Speed shortcut. If you refresh the page, volume will not be 80%. 

-----------

This is is kind of annoying, you can use this script to fix that. To setup...

1. Create a URL rule in the options page. 
2. Change it from "speed" mode to "javascript" mode. Click "edit" and paste the code from below. 
3. Click on "-- 0 --" to add a URL condition so that if the URL contains "youtube.com", it should run the code. 
4. Enable "ILO" so the code only loads once. 

```
if (!window.ranScriptFlag) {
    window.ranScriptFlag = true

    // add event listener to persist volume on volume change 
    window.addEventListener("volumechange", e => {
        const video = e.target
        if (!(video instanceof HTMLMediaElement)) return 

        const now = new Date().getTime() 
        const data = JSON.stringify({volume: Math.round(video.volume * 100), muted: video.muted})
        const payload = JSON.stringify({data, expiration: now + 2592000000, creation: now})
        localStorage.setItem("yt-player-volume", payload)
        sessionStorage.setItem("yt-player-volume", payload)
    }, true)
}
```

https://user-images.githubusercontent.com/31208859/165215878-b9e3b363-7886-4f4d-a1e8-659478cc3338.mov

**Comment by Fireworkstars46** [comment]
How would I do it with non YouTube sites? Like Disney now etc?

**Comment by polywock** [comment]
This should work on all sites. This script blocks the website from changing volume at all. The limitation is that you can only change volume using Global Speed, and it will remember the volume even if you refresh the page. I recommend only running it on sites that you notice issues like Youtube. To setup, just change the URL condition to "youtube.com" OR "disney.com" to run on both sites, and replace the javascript to this. 

![sc5](https://user-images.githubusercontent.com/31208859/167011461-5ec953df-3b5d-45d5-92b5-04d8df3a304d.png)



```javascript

if (!window.ranScriptFlag) {
    window.ranScriptFlag = true

    // add event listener to store latest volume.
    window.addEventListener("volumechange", e => {
        const video = e.target
        if (!(video instanceof HTMLMediaElement)) return 

        localStorage.setItem("gs-volume", video.volume)
    }, true)

    // everytime youtube tries to set volume, use our stored volume. 
    const getStoredVolume = () => {
        let volumeRaw = localStorage.getItem("gs-volume")
        if (volumeRaw) {
            return parseFloat(volumeRaw)
        }
    }

    const desc = Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype, "volume")
    Object.defineProperty(HTMLVideoElement.prototype, "volume", {configurable: true, enumerable: true, get: desc.get, set: function(value) {
        return desc.set.call(this, getStoredVolume() ?? 0.5)
    }})
}
```

**Comment by Fireworkstars46** [comment]
What about making it so when I set the volume to like 25 on Disney now and have it save there if the page refreshes or something?

**Comment by polywock** [comment]
Hello. Here's an updated version. You can now change your volume through Youtube (or Disney's own controls) as long as it's after 5 seconds of the video loading. It should save when you refresh the page. 

```javascript
if (!window.ranScriptFlag) {
    window.ranScriptFlag = true
    let blockInterval 
    // block website from changing volume for first 5 seconds. 
    let BLOCK_DURATION = 5000 

    // add event listener to store latest volume. 
    window.addEventListener("volumechange", e => {
        const video = e.target
        if (!(video instanceof HTMLMediaElement)) return 

        localStorage.setItem("gs-volume", video.volume)
    }, true)


    // function to get stored volume 
    const getStoredVolume = () => {
        let volumeRaw = localStorage.getItem("gs-volume")
        if (volumeRaw) {
            return parseFloat(volumeRaw)
        }
    }

    // block page from changing volume 
    const desc = Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype, "volume")
    Object.defineProperty(HTMLVideoElement.prototype, "volume", {configurable: true, enumerable: true, get: desc.get, set: function(value) {
     return blockInterval ? undefined : desc.set.call(this, value) 
}})

    // on start of video, set volume to the stored one. 
    window.addEventListener("loadedmetadata", e => {
        const video = e.target
        if (!(video instanceof HTMLMediaElement)) return 
        blockInterval = setInterval(() => { blockInterval = null }, BLOCK_DURATION)
        desc.set.call(video, getStoredVolume() ?? 0.5)
    }, true)
}
```

**Comment by polywock** [comment]
@Fireworkstars46 I just noticed a big issue with a code. It should be setTimeout instead of setInterval. This could result in issues. Here's a fixed version. 


```javascript
if (!window.ranScriptFlag) {
    window.ranScriptFlag = true
    let blockTimeout 
    // block website from changing volume for first 3 seconds. 
    let BLOCK_DURATION = 3000 

    // add event listener to store latest volume. 
    window.addEventListener("volumechange", e => {
        const video = e.target
        if (!(video instanceof HTMLMediaElement)) return 

        localStorage.setItem("gs-volume", video.volume)
    }, true)


    // function to get stored volume 
    const getStoredVolume = () => {
        let volumeRaw = localStorage.getItem("gs-volume")
        if (volumeRaw) {
            return parseFloat(volumeRaw)
        }
    }

    // block page from changing volume 
    const desc = Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype, "volume")
    Object.defineProperty(HTMLMediaElement.prototype, "volume", {configurable: true, enumerable: true, get: desc.get, set: function(value) {
     return blockTimeout ? undefined : desc.set.call(this, value) 
}})

    // on start of video, set volume to the stored one. 
    window.addEventListener("loadstart", e => {
        const video = e.target
        if (!(video instanceof HTMLMediaElement)) return 
        clearTimeout(blockTimeout)
        blockTimeout = setTimeout(() => { blockTimeout = null }, BLOCK_DURATION)
        desc.set.call(video, getStoredVolume() ?? 0.5)
    }, true)
}
```

**Comment by Fireworkstars46** [comment]
Are you plan on adding a discord server for this addon?

**Comment by Fireworkstars46** [comment]
How exactly do I have it save the volume for specific sites like peacock and not reset when it refreshes?

**Comment by polywock** [comment]
@Fireworkstars46 Only way that's consistent is to change volume through Peacock, and hopefully Peacock remembers your previous speed. I looked into a way to implement a volume memory feature, but gave up after trying a bunch of solutions.
