### ISSUE TITLE
可以支持一下这个网站么https://bksycsu.yuketang.cn

### ISSUE THREAD

**Issue by Maginuo** [polywock/globalSpeed#197]
这个网站接管不了视频倍速，我试了一下其他网站是可以的，就只有这个网站接管不了，救救孩子的网课吧，万分感谢

**Comment by polywock** [comment]
Hello. Class is rescued. You just need to enable "Ghost Mode" (幽灵模式)  in the options page. 

![red](https://user-images.githubusercontent.com/31208859/166084509-8c981fc1-8063-46e9-b245-2fd2ba36478c.png)
