### ISSUE TITLE
您好，在腾讯体育无法正常变速

### ISSUE THREAD

**Issue by whyjxz14** [polywock/globalSpeed#198]
https://sports.qq.com/kbsweb/game.htm?mid=100000:55855672
在腾讯体育无法正常变速视频，不过片头广告可以正常变速

https://v.qq.com/x/cover/mzc00200zhvbxxd/v0042z8rfdm.html
同一个视频在腾讯视频可以正常变速。

**Comment by polywock** [comment]
Hello. You need to enable "Ghost Mode" (幽灵模式)  in the options page. 

![red](https://user-images.githubusercontent.com/31208859/166084509-8c981fc1-8063-46e9-b245-2fd2ba36478c.png)
