### ISSUE TITLE
倍速播放，音频和视频不能同步

### ISSUE THREAD

**Issue by udysyhj** [polywock/globalSpeed#199]
倍速播放，音频和视频不能同步。同样的片源，「video speed controller」可以同步，排除片源问题

**Comment by polywock** [comment]
Hello. Could you explain more or provide examples? Does your audio play a few milliseconds ahead of the video, or vice versa?

**Comment by udysyhj** [comment]
![图片](https://user-images.githubusercontent.com/93963642/166609733-67e39d30-ada4-472e-8124-21df2ee8f2dd.png)
可能是在触发移动时间轴的时候，造成的音频和视频的不同步

**Comment by polywock** [comment]
Hello. This might be a Firefox bug. You see that "f" icon. That enables "fast seeking", which only Firefox supports. The problem might be fixed if you disable fast sync. 

![imgg3](https://user-images.githubusercontent.com/31208859/166624443-4c9c9ac2-0640-4aaa-a388-76dba6e0e31d.png)

**Comment by udysyhj** [comment]
非常感谢你的帮助。通过禁用“f”图标，这个问题已经解决。另外，真的如你所说，“f”图标只有火狐浏览器支持，这是个惊喜的发现。祝愿火狐和globalSpeed越来越好。

**Comment by polywock** [comment]
Glad to see the issue resolved. I'll disable fast seek by default on the next update. You're the only one to mention the issue, but if you see one mouse, there is probably ten.
