### ISSUE TITLE
[Feature Request] Change speed only on opened tab (by default) | Set specified speed on specified website

### ISSUE THREAD

**Issue by Pawloland** [polywock/globalSpeed#2]
I am in love with this add-on. 
I am using Firefox 72.0.2 (64bit). 
Right now there is an option to pin the speed to certain tab. The only problem is that user must click add-on icon and then pin, in order to link the speed to certain tab. 
I would rather have this as the default behavior, so user wouldn't have to click the pin on every page to set custom speed. It would be better like that, because right now, when multiple tabs are opened, speed is changed in all of them, rather than on the specific one, we are browsing at the time.

It would be also cool if we could set default speed per specific page or domain.
For example:
- we have website www.youtube.com and we want all of the videos on that page to play at speed 1.5. 
- we also wand the specific video on that page (for example https://www.youtube.com/watch?v=2lAe1cqCOXo ) to be played at speed 0.5. 

Even though we have specified the speed on the domain, the speed set for the url (on that domain) has higher priority than speed set for domain, so the video on that specific url is played at the speed of 0.5, but all of the other videos on that domain will be played at speed of 1.5.

**Comment by polywock** [comment]
Thank you for the kind words. I added an option to pin new tabs by default. And added a hotkey (q by default) for pinning tabs. The Firefox version is up, Chrome/Edge will take up to a week. If there any bugs, let me know. 

As for URL defaults, I have tried implementing it in the past, but the code got to the state where I didn't like it, and reverted back.

**Comment by polywock** [comment]
@Pawloland, hello again. If you're still interesting in URL rules. I did reimplement for the newest update. If you have questions about it, feel free to ask.
