### ISSUE TITLE
New Logo Suggestion...

### ISSUE THREAD

**Issue by zeref-dragneel** [polywock/globalSpeed#201]
- <img src="https://i.imgur.com/EiIVgvx.png" height="50">
- <img src="https://i.imgur.com/BLVTiXh.png" height="50">
- <img src="https://i.imgur.com/1tYTH4S.png" height="50">
- <img src="https://i.imgur.com/mPZ5do8.png" height="50">
- <img src="https://i.imgur.com/67Wtf58.png" height="50">

I prefer this kind of logo. If necessary, I will upload this logo file. 😅

**Comment by polywock** [comment]
These look great. I will admit they're better than the current logo, which is just a triangle 😅 . But, I'm way too attached to the current one and probably wouldn't swap it for anything. Thank you for the logo mockups. What app do you use to make these?

**Comment by zeref-dragneel** [comment]
I use Inkscape 😄

<img src="https://i.imgur.com/sHXkk8n.png" height="350">
