### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by kiencuongpo** [polywock/globalSpeed#204]
How to add site to whitelist not affected by GS. It's very inconvenient to turn it on and off every time

**Comment by polywock** [comment]
Hello, You can create a URL rule to automatically turn off if the URL matches a certain site. 

https://user-images.githubusercontent.com/31208859/168323657-b54b0a78-5684-4455-a68b-2c29e79bdcad.mov

**Comment by kiencuongpo** [comment]
Thank you
