### ISSUE TITLE
安装插件后，即使不打开，动图等的仍有影响（会卡顿）

### ISSUE THREAD

**Issue by shadowman2022** [polywock/globalSpeed#205]

**Comment by shadowman2022** [comment]
![Snipaste_2022-05-14_17-28-55](https://user-images.githubusercontent.com/98646778/168419978-5c2aa649-fb6b-46d7-b325-2221aa645eba.png)

**Comment by polywock** [comment]
Hello. Could you explain a bit more or provide a video? Which websites are effected?

**Comment by shadowman2022** [comment]
几乎是所有的有GIF的网站
Almost all sites that have GIFs
一个例子
An example
http://www.websiteasteroids.com/
影响的似乎是在<canvas>标签内的东西
What seems to be affected is inside the <canvas> tag

**Comment by polywock** [comment]
No issues on that site for me. I also tried a few gif websites and didn't encounter any lag. Have you tried uninstalling the extension to see if gifs are still stuck? It might be a low memory issue. 

https://user-images.githubusercontent.com/31208859/169665391-6e4aaf0c-7137-45ec-936e-e67c2c764cf5.mov

**Comment by shadowman2022** [comment]
Thank you.Now there is no issue for me.
