### ISSUE TITLE
移动时间轴如何不暂停播放

### ISSUE THREAD

**Issue by qqqq-8** [polywock/globalSpeed#206]
尊敬的开发者大人，我们的插件十分强大好用！
请问移动时间轴之后如何设置成 不暂停播放，即移动时间轴后总是会自动暂停视屏需要重新点击继续播放比较繁琐，希望得到指导，非常感谢。

**Comment by polywock** [comment]
Hello. Glad the plugin could be useful. The pausing is an optional feature for that hotkey. I think you reused the frame by frame hotkeys which had pausing enabled. To disable, click the 3 dots and disable pausing. 

![imgTwo](https://user-images.githubusercontent.com/31208859/168543863-86e989eb-f128-4b82-ac66-ad443e7bcf91.png)

**Comment by qqqq-8** [comment]
非常感谢您的指导！
