### ISSUE TITLE
百度网盘

### ISSUE THREAD

**Issue by qiqiiiiii** [polywock/globalSpeed#207]
百度网盘不能倍速了。

**Comment by 1637466200** [comment]
确实  是因为浏览器更新了嘛

**Comment by Redamancy-Yii** [comment]
作者您好，这个扩展对百度网盘没用了，是百度那边调整了吗

**Comment by polywock** [comment]
Could you share me a link with extraction code?

**Comment by Redamancy-Yii** [comment]
就今天下午突然无法倍速了，几个浏览器都无法使用

**Comment by Redamancy-Yii** [comment]
链接: https://pan.baidu.com/s/1MqS-k5PsfAfm1pCUDNcxUg 提取码: fvj1 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by Redamancy-Yii** [comment]
https://pan.baidu.com/s/17G8uk1fxCzDsi5_XtUT21w 提取码: 68e3

**Comment by Redamancy-Yii** [comment]
> 你能分享我一个提取码的链接吗？

 https://pan.baidu.com/s/17G8uk1fxCzDsi5_XtUT21w 提取码: 68e3

**Comment by polywock** [comment]
I just published an update that may fix the issue. It might take up to a week for the update to get approved.

**Comment by Redamancy-Yii** [comment]
This error occurs


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 晚上10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] 百度网盘 (Issue #207)





 
@Redamancy-Yii Tested all three videos and they work fine for me.  There was a similar issue last month with Baidu. Only some users were affected. Baidu was "AB testing" a new video player. Instead of playing videos using VIDEO element, they played videos using a custom WASM CANVAS player.
 
https://user-images.githubusercontent.com/31208859/168840759-57261a23-0ee4-4214-a150-84bb88978937.mov

**Comment by Redamancy-Yii** [comment]
> 我刚刚发布了一个可以解决问题的更新。更新可能需要长达一周的时间才能获得批准。要立即尝试更新...
> 
> 1. 下载下面的文件并解压文件夹。
> 2. 打开扩展页面 (chrome://extensions)
> 3. 启用开发者模式
> 4. 拖入解压的文件夹。
> 
> [打包的.zip](https://github.com/polywock/globalSpeed/files/8711166/packed.zip)
> 
> 让我知道这是否解决了问题。

出现了错误，同时视频也加载不出来

**Comment by polywock** [comment]
What error? I don't see the rest of the message.

**Comment by polywock** [comment]
@Redamancy-Yii 😞  Could you this one as well? It's really inconvenient to diagnose an issue without being able to reproduce it myself. 

[packed.zip](https://github.com/polywock/globalSpeed/files/8712504/packed.zip)

**Comment by zhou-123cpo** [comment]
> @Redamancy-Yii 😞你也可以试试这个吗？在没有自己重现问题的情况下诊断问题真的很不方便。
> 
> [包装.zip](https://github.com/polywock/globalSpeed/files/8712504/packed.zip)

不行我两个压缩包都试过了都是2.9.93，都不行

**Comment by qaz-123-123** [comment]
我刚刚重新安装了一下，还是2.9.91版本啊，但还是不能倍速播放百度网盘视频，有什么解决的办法吗？

**Comment by fateygyyan** [comment]
![A4$KZ H9VF$6LE01N`C MRI](https://user-images.githubusercontent.com/57716316/168982821-ee55aeeb-282c-46c8-8d10-7b9e11599964.png)
用不了，直接网盘视频都打不开，看下是不是哪里错误

**Comment by polywock** [comment]
@fateygyyan That's just a warning. The majority of extensions are still Manifest V2. I have yet to upgrade to Manifest V3 because some features aren't stable yet.  You can ignore that message.

**Comment by zhaozhiyi666** [comment]
Is it fixed now? STILL does not work on my PC.

**Comment by zhaozhiyi666** [comment]
verson:2.9.93
can't even open the Baidu video

**Comment by Redamancy-Yii** [comment]
我找到个方法，这个插件+global speed可以倍速
https://greasyfork.org/zh-CN/scripts/441747-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8

**Comment by zhaozhiyi666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by SHUFU90D** [comment]
> 

感谢，成功解决了

**Comment by adfdgga** [comment]
> 我找到个方法，这个插件+global speed可以倍速 https://greasyfork.org/zh-CN/scripts/441747-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8

666

**Comment by Blush64** [comment]
> 我找到个方法，这个插件+global speed可以倍速 https://greasyfork.org/zh-CN/scripts/441747-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8
您好 请问具体怎么操作呀 我有点看不懂

**Comment by Redamancy-Yii** [comment]
> > 我的几个方法，这个插件+全局速度可以倍速[https://greasyfork.org/zh-CN/scripts/441747-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B %98%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8](https://greasyfork.org/zh-CN/scripts/441747-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8)
> > 您好请具体怎么操作呀 我有点看不懂

如果可以的话，加我qq809378543

**Comment by HeyBrother-D** [comment]
Excuse me,Is there a solution now

**Comment by HeyBrother-D** [comment]
现在这个问题解决了吗

**Comment by polywock** [comment]
@zhou-123cpo, @Redamancy-Yii  Could you this version? I think I figured out a workaround. 

[packed.zip (Chrome/Edge)](https://github.com/polywock/globalSpeed/files/8782736/packed.zip)

**Comment by HeyBrother-D** [comment]
> @zhou-123cpo, @Redamancy-Yii Could you this version? I think I figured out a workaround.
> 
> [packed.zip (Chrome/Edge)](https://github.com/polywock/globalSpeed/files/8782736/packed.zip)

好的谢谢，问题成功解决了

**Comment by polywock** [comment]
@HeyBrother-D Great. I just pushed the update. It should already be approved for Firefox. The Chrome/Edge version might take a week to get approved.

**Comment by Sonyuquan** [comment]
我的问题简单，就是重新授权一下app的权限，然后网页就行了

**Comment by Redamancy-Yii** [comment]
Thanks！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 凌晨3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] 百度网盘 (Issue #207)





 
I just published an update that may fix the issue. It might take up to a week for the update to get approved.
