### ISSUE TITLE
Netflix / Edge issues with sound and playback

### ISSUE THREAD

**Issue by michalpl7** [polywock/globalSpeed#209]
Hello since few days I'm having huge problem with faster playback of video in Edge / Netflix.

Edge version 101.0.4951.67 ( official version ) (64-bit)
Windows 11 Pro 21H2.

Speaker sound is broken and after I pause and resume it does not remember playback speed. There are also freezes and crashes.

This seems to be related only to Netflix with enabled **PlayReady DRM for Windows**. Too bad if I disable that playback quality drops from FullHD 1920x1080 to HD 1280x720 and bitrate from few thousands let's say 3000 kbps to 250 kbps.

This NF is driving me nuts. I guess this is not issue with Global Speed but could You at least verify that You are having the same problem like me?

Greetings.

**Comment by polywock** [comment]
Hello. I don't currently have a windows machine to test this, but a few people already complained of issues related to PlayReady+Netflix so it's likely not just you. 

As for a solution, you could try enabling "Ghost mode" in the options page. It will try to stop Netflix from changing the speed on pause/play. If this doesn't fix all the issues, you could also try disabling PlayReady DRM and installing this extension to force 1080p instead. I have tested and it seems to work. (It's for Chrome, but you can also install on Edge). 

https://chrome.google.com/webstore/detail/netflix-1080p/cankofcoohmbhfpcemhmaaeennfbnmgp

It might be hard to tell if a video is 720p or 1080p, you can run this bookmarklet to see the resolution.

```
javascript:(() => {
    function formatDuration(secs) {
        if (secs === Infinity) return "∞"; 

        const mins = secs / 60;
        const hours = mins / 60;
        if (hours >= 100) {
            return "";
        } else if (hours > 1) {
            return `${Math.floor(hours)}:${Math.floor((mins % 60)).toString().padStart(2, "0")}:${Math.floor((secs % 60)).toString().padStart(2, "0")}`;
        } else {
            return `${Math.floor(mins).toString().padStart(1, "0")}:${Math.floor((secs % 60)).toString().padStart(2, "0")}`;
        };
    }
    const outputs = [];
    const playVideos = [];
    document.querySelectorAll("video").forEach(video => {
        if (!video.paused) {
            video.pause(); 
            playVideos.push(video);
        }
        outputs.push(`${formatDuration(video.currentTime)} / ${formatDuration(video.duration)} ${video.videoWidth}x${video.videoHeight}`);
    });
    alert(outputs.join("\n"));
    playVideos.forEach(v => v.play());
})();

```

**Comment by michalpl7** [comment]
I tried to disable PlayReady DRM and installed that extension NF1080p. Video is playing perfectly smooth, sound is also great but resolution is 1280x720 and bitrate 683 kbps ( drop over 2000 down ).

**Comment by michalpl7** [comment]
Huge thanks! I tested that NF1080 extension with Iron ( chromium clone ) and it works flawless, 1920x1080/smooth/sound ok and what's best bitrate is 1000 kbps higher than in Edge :D - 3600 kbps. Thanks again!

**Comment by michalpl7** [comment]
It has to be Windows 11 related ( or that device ), tested same Edge / Edge Beta ( 102.0.1245.14 ) in W10 and W11.

**Comment by michalpl7** [comment]
I don't know but this plugin does not help every time, now I watch different production and Edge is: 128/1519 kbps (Audio/Video) and Chrome + plugin is 96/600 kbps

**Comment by polywock** [comment]
Hello. Try enabling "Automatically select best bitrate available" in that extension's options.

**Comment by michalpl7** [comment]
Is there any option that playback speed plugin will be fully compatible with that PlayReady DRM? I see that also HBO Max is trying to use this shitty DRM. :/
