### ISSUE TITLE
High CPU usage if there are iframes on the page

### ISSUE THREAD

**Issue by Aleksanderis** [polywock/globalSpeed#21]
I was experiencing high CPU usage in my browser (in browser task manager it shows around 100% CPU usage). After long investigation I narrowed it down to Global Speed extension. It happens on all Chromium browsers (Chrome, Opera, Edge(ium), etc), where this extension is enabled. Disabling this extension - CPU gets back to normal.
![image](https://user-images.githubusercontent.com/2393205/88760788-6f303d80-d176-11ea-81ed-15f5c82e5a0e.png)

For me it's really useful extension, even though there are a lot of similar extensions, but I find this one as the most suitable and with well-though options and user experience. So it would be really appreciated if it could be looked at.
One other possible option is to add filter by page where you could configure where this extension could be disabled.

**Comment by kindect** [comment]
Can you provide the URL of the website that you're saying?
cause I don't really experience problems using the Global speed

**Comment by polywock** [comment]
Interesting. I've refactored the entire extension recently. The update will take a few days to go live. Could you let me know if the problem still exists in the new version? To load it...

1. Download `packed.zip` below and extract it. 
1. Open the extension manager page -> `chrome://extensions`
1. Top right enable developer mode 
1. The `load unpacked` button should now show up. Load the extracted folder `unpacked/` 

[packed.zip](https://github.com/polywock/globalSpeed/files/4992182/packed.zip)

**Comment by Aleksanderis** [comment]
@polywock perfect, I will try it! :)

@kindect sorry, that particular site is not publicly available. I just have got an impression, that it could be for all sites with iframes, because loading URL from iframe directly - doesn't generate any load on CPU. I will try to investigate with some public available sites to see if I can observe similar behavior.

**Comment by Aleksanderis** [comment]
@polywock I tried it now - and seems like at least that issue is gone now. Looks promising! :)
![image](https://user-images.githubusercontent.com/2393205/88772950-23878f00-d18a-11ea-8b12-f1ef6f6cf676.png)

**Comment by polywock** [comment]
Easiest issue I've ever had. Thanks for the quick reply. I've literally forgotten everything about the old codebase. So, I have zero inkling on what the cause was. Let me know if it reappears.

**Comment by kindect** [comment]
Oh this is fast

**Comment by kindect** [comment]
BTW @polywock can I advertise this extension publicly on Chinese social websites? I'll email you the link of the post and the translation

**Comment by polywock** [comment]
Of course.

**Comment by kindect** [comment]
@polywock the post is here:
https://zhuanlan.zhihu.com/p/165199671
(in chinese, you'll probably need google translate for that)
And try to email me(kindect@163.com), So I can send you the English version
I'm considering bringing up a another issue just for promotion
