### ISSUE TITLE
建议增加【剪掉无声部分】功能，节省用户收听时间

### ISSUE THREAD

**Issue by Ushnidaye** [polywock/globalSpeed#212]
Google podcast和pocket cast都有剪掉无声部分的功能。可以根据声波特性自动剪辑。减少视频的总时长，节省用户时间。其中Google podcast剪得比较彻底，基本上中间没有空白部分。pocket cast将剪掉无声部分分为高中低三个不同的程度，方便用户根据自己的需要进行选择。

**Comment by polywock** [comment]
Hi. I've looked into adding this, but it's pretty much impossible without having access to the entire file at once, or at least the immediate next 10 seconds. Each website would need an individual solution for this.
