### ISSUE TITLE
安卓端听书功能

### ISSUE THREAD

**Issue by Ushnidaye** [polywock/globalSpeed#213]
目前安卓端已经可以使用edge插件了。参见：https://sspai.com/post/60343
因此我建议增加安卓端的加速功能。有两个要点：
1.安卓端听音频MP3更加节省流量。因此建议增加YouTube等平台后台、锁屏听音频功能。实现后台听书、锁屏听书
2.设置变速快捷键：在网页端按CTRL+上下箭头加减0.1变速；在安卓手机端按关机键+音量加减变速0.1倍。

**Comment by polywock** [comment]
Hello. 

> 1.安卓端听音频MP3更加节省流量。因此建议增加YouTube等平台后台、锁屏听音频功能。实现后台听书、锁屏听书

I think there are apps like Vanced Youtube for background play I don't know it works, so I I'll leave it for the experts. 

> 2.设置变速快捷键：在网页端按CTRL+上下箭头加减0.1变速；在安卓手机端按关机键+音量加减变速0.1倍。

I don't think plugins can do that. Only apps (APK) with the accessibility permission.
