### ISSUE TITLE
[Feature] 音量调节记忆功能

### ISSUE THREAD

**Issue by draymondgewade** [polywock/globalSpeed#214]
建议对于音量的调节能不能够提供一个记忆功能, 不然每次刷新或者重新进入页面后对于音量都需要重新调节

**Comment by foricons** [comment]
@polywock  i think this demand should do like this: add volume option to URL Rules, if one page match one of the rules, Plugins should automatically capture audio and do something. if not, do not to capture audio.

**Comment by polywock** [comment]
Continuing thread here #219.
