### ISSUE TITLE
请问这几个媒体列表怎么删除？

### ISSUE THREAD

**Issue by gavinpang3** [polywock/globalSpeed#217]
![123](https://user-images.githubusercontent.com/104836842/172862183-9154c638-4956-4b9a-9a94-c13b14bfe8a3.png)

**Comment by polywock** [comment]
Hello. You can hide the media list in the options page. 

![img1](https://user-images.githubusercontent.com/31208859/172978893-5e156d2f-645f-48a7-8988-7e3f451cde69.png)

**Comment by gavinpang3** [comment]
> Hello. You can hide the media list in the options page.
> 
> ![img1](https://user-images.githubusercontent.com/31208859/172978893-5e156d2f-645f-48a7-8988-7e3f451cde69.png)

**Comment by gavinpang3** [comment]
> > Hello. You can hide the media list in the options page.
> > ![img1](https://user-images.githubusercontent.com/31208859/172978893-5e156d2f-645f-48a7-8988-7e3f451cde69.png)

谢谢你的回答，但是我想说的是删除它，而不是隐藏，

这几个媒体列表只在YouTube上存在，别的网站上就没有

**Comment by polywock** [comment]
Hello. Looks like Youtube preloads a few sound files. In the next update I'll hide all audio <1second. That should fix the problem.

**Comment by gavinpang3** [comment]
> Hello. Looks like Youtube preloads a few sound files. In the next update I'll hide all audio <1second. That should fix the problem.

好的，谢谢
