### ISSUE TITLE
【音量调节】快捷键

### ISSUE THREAD

**Issue by Ushnidaye** [polywock/globalSpeed#220]
上下键调节音量有时候无法正常启动，也不适合61键盘。建议增加音量调节快捷键

**Comment by polywock** [comment]
Hello. You can add volume adjustment shortcut keys in the option page. 

https://user-images.githubusercontent.com/31208859/174814249-71fec2cb-69c3-4573-b4fa-112529ec69ac.mov

**Comment by Ushnidaye** [comment]
thank you very much!
