### ISSUE TITLE
【截图】【截GIF】【截视频clip】

### ISSUE THREAD

**Issue by Ushnidaye** [polywock/globalSpeed#221]
1.快捷键截图，按照原视频最高画质截图
2.快捷键开始+快捷键结束截取GIF
3.快捷键开始1+快捷键结束1；快捷键开始2+快捷键结束2.。。。。截取视频

**Comment by polywock** [comment]
Hello. I think I could do the screenshot shortcut, but video/gif is a whole different beast and will require making separate extension.
