### ISSUE TITLE
No working in URL with file:///  【The browser fails to play the local video】

### ISSUE THREAD

**Issue by DMIND-NLL** [polywock/globalSpeed#222]
No working in URL with file:///  【The browser fails to play the local video】

**Comment by polywock** [comment]
Hello. Permissions don't have permission to load on local pages by default. Did you enable `Allow access to file URLs` in Chrome/Edge's extension page? `chrome://extensions. 

![img3](https://user-images.githubusercontent.com/31208859/175407370-43fdae55-3a9a-42b7-bcc9-de742bd22865.png)

**Comment by DMIND-NLL** [comment]
Sorry, I didn't notice this setting. Thank you very much.
