### ISSUE TITLE
URL Rules - URL conditions - URL gets lost when switching match type

### ISSUE THREAD

**Issue by cliffordp** [polywock/globalSpeed#223]
Demo: https://share.getcloudapp.com/llu0N4Pb
Happens on Firefox and Edge (didn't test Chrome)

**Comment by polywock** [comment]
Hi, Clifford. That's intentional on my part. I wanted to let the user know how the URL should look like based on match type. The user interface otherwise doesn't provide enough clues. 

`starts with`: some people might see `google.com` and `www.google.com` as reasonable values, especially with Chrome hiding the full URL these days. 

`regex`: some people might use `/google\.com/` (common format for REGEX), so I wanted to make clear the forward slashes aren't needed. 

I thought about instead providing a tooltip, but I also wanted to make sure the user confronts the match type change. I could see people changing the match type absent-mindedly and then have issues when they forget to the change the URL.

**Comment by cliffordp** [comment]
fair enough, but it'd be best to have sub-text showing examples like you just did above

**Comment by kr99** [comment]
@polywock - Many user-experience researchers have done scientific research on how to do "placeholder" text properly.  The answer is "don't".  The best solution is to provide hints _above or below_ -- see image.

![image](https://github.com/polywock/globalSpeed/assets/6116049/675d7775-733b-450f-81f9-7ba1c79392b8)
https://uxdworld.com/2019/12/27/design-tip-3/

**Comment by kr99** [comment]
> @polywock - Many user-experience researchers have done scientific research on how to do "placeholder" text properly. The answer is "don't". The best solution is to provide hints _above or below_ -- see image.
> 

By the way, I LOVE this extension, it is amazing.  As a fellow programmer with years of experience... I took a class on usability, and it was humbling when another class member tested my creation (WMP skin) and got terrible feedback (this, after I had studied how to do it right for 3-4 months) - what I learned was:
- I am not the user
- I do not think like the user
- Humility - my design ideas must be killed
- Data - there is actually scientific data on what is best
- Listen to your users - but find out WHY they are asking for something.

It is very frustrating to type a URL, realize I need to switch to regex, and then what I typed is gone.  Very, very annoying.  Don't make users redo stuff.  A compact UI is less important than a helpful one.

I would also say your URL rules are VERY hard to work with.  If the website speed isn't working right, and I open a list of 5 URL rules, there is NO way I can tell what is wrong without opening each-and-every-one.  I will start another topic on that.

Go read this [article on top 10 usability heuristics](https://www.nngroup.com/articles/ten-usability-heuristics/).  NNGroup has tons of GREAT articles on how to make UI well.  They are an independent research firm, and have done data-driven scientific usability research all over the world, for decades.  Their design insights are great.  There are other sites too.

**Comment by polywock** [comment]
UX/UI was never my strong suite. 

> I would also say your URL rules are VERY hard to work with. If the website speed isn't working right, and I open a list of 5 URL rules, there is NO way I can tell what is wrong without opening each-and-every-one. I will start another topic on that.

Absolutely agreed. I've made a few improvements for the URL rules in the draft update. Hopefully the new update will be helpful in this regard (should be published this month).

> It is very frustrating to type a URL, realize I need to switch to regex, and then what I typed is gone. Very, very annoying. Don't make users redo stuff. A compact UI is less important than a helpful one.

To address this, I separated the values for each type (regex stored in `valueRegex`, contains stored in `valueContains`). This way I don't have to override the value. It's still a placeholder system, but hopefully not as annoying. I would try to further improve it later on. 

I appreciate the encouraging feedback.
