### ISSUE TITLE
建议增加一键加速功能

### ISSUE THREAD

**Issue by 1637466200** [polywock/globalSpeed#224]
类似各大视频网站的app端 长按屏幕两倍速播放 松开后按原倍速播放。
可以设置一个快捷键做类似的工作吗。

**Comment by polywock** [comment]
Hello. You can create a speed hotkey for that.  If you press F, it will play in 5x speed. If you press F again, it will go back to previous speed. 

![img4](https://user-images.githubusercontent.com/31208859/176366545-e90acf18-4508-4e57-9180-224e99a54c51.png)

**Comment by teadrinker2015** [comment]
@polywock I think his proposal is to make that hotkey behave like "press = enable & release = disable"?
