### ISSUE TITLE
用这个观看youtube 后台会偷偷播播放其他视频  洗我的账号 用我的长帮别人刷赞刷播放量 被劫持

### ISSUE THREAD

**Issue by shiyuanGame** [polywock/globalSpeed#225]
![BLLQT$ZT4R{G CL$1 7KQR0](https://user-images.githubusercontent.com/80084199/177003602-c891a19d-3e49-438c-8e2a-07b2aaccd564.png)
![Uploading BLLQT$ZT4R{G[CL$1]7KQR0.png…]()

**Comment by shiyuanGame** [comment]
这些都不是我观看的 ， 也不是我点赞的  恶心到了

**Comment by polywock** [comment]
Hello. Did you install the official versions of Global Speed? There are some copycats and you may have installed that. Official versions are linked below. 

Edge: https://microsoftedge.microsoft.com/addons/detail/global-speed/mjhlabbcmjflkpjknnicihkfnmbdfced

Chrome: https://chrome.google.com/webstore/detail/global-speed/jpbjcnkcffbooppibceonlgknpkniiff

Firefox: https://addons.mozilla.org/en-US/firefox/addon/global-speed/ 

If it's official, I would investigate your other extensions or userscripts. I've received no complaints about this type of issue. I will leave this issue up to see if anyone else has a similar problem, but I don't think it's related to Global Speed.

**Comment by aoztech** [comment]
抱歉 貌似不是 软件的问题，我删除了软件还是有这个问题，可能是浏览器的问题。我需要再研究一下。谢谢，非常抱歉。

**Comment by shiyuanGame** [comment]
抱歉 貌似不是 软件的问题，我删除了软件还是有这个问题，可能是浏览器的问题。我需要再研究一下。谢谢，非常抱歉。

**Comment by polywock** [comment]
Hi. It's no problem at all. Hopefully the investigation goes well. On this page, you can see all devices that are using your Google account. If you see a device that isn't yours, I recommend changing your password as soon as possible. 

https://myaccount.google.com/security

**Comment by polywock** [comment]
Hello. An update. I found this Reddit post complaining of a similar issue. The person was using "Global Speed +". (not mine). 

https://www.reddit.com/r/youtube/comments/vyxiw0/random_videos_on_my_watch_history_and_liked/
