### ISSUE TITLE
建议增加新标签页默认速度设置

### ISSUE THREAD

**Issue by LIUXU-T** [polywock/globalSpeed#227]
希望在调节过速度的标签页使用该速度就好，新打开的标签页希望是默认速度

**Comment by polywock** [comment]
Hello. If you want the default speed for new tabs to be 2x. 

1. Make sure the tab is not pinned and set speed to 2x. 

![imgg2](https://user-images.githubusercontent.com/31208859/178054171-da1fc5ce-a4e2-464b-bb66-daa7c9bcba1e.png)

2. Enable  "pin by default" (默认固定) in the options page. All new tabs will inherit the global speed.

![imgg1](https://user-images.githubusercontent.com/31208859/178053659-325115c6-e1a5-4502-897c-465df024a8c9.png)

**Comment by LIUXU-T** [comment]
Got it！Thanks！
&nbsp;


Mr.Church
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月9日(星期六) 凌晨3:00
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [polywock/globalSpeed] 建议增加新标签页默认速度设置 (Issue #227)





 
Hello. If you want the default speed for new tabs to be 2x.
  
Make sure the tab is not pinned and set speed to 2x.
  

  
Enable  "pin by default" (默认固定) in the options page. All new tabs will inherit the global speed.
