### ISSUE TITLE
建议增加64倍速

### ISSUE THREAD

**Issue by zhedielj** [polywock/globalSpeed#229]
有固态硬盘做视频缓存服务器，所以16倍速依然有点慢，能否加16速选项。我看类似视频加速器最多都是16倍速，不知道是不是浏览器本身的限制。

**Comment by polywock** [comment]
Hello. Chromium (Chrome/Edge) limit speed range to 0.0625 to 16. Firefox allow even 200x speed, but mute the audio because pitch correction doesn't well with faster speeds. Safari allows even negative speed, which is pretty cool. It will play the video backwards in that case.
