### ISSUE TITLE
Translation, and bug about "adjustGain"

### ISSUE THREAD

**Issue by liangjiancang** [polywock/globalSpeed#23]
### Translation

First of all, this is my mistake. I didn't notice the two terms "adjustVolume" and "adjustGain" in the original text, so I translated both them into Chinese "volume". These two words are completely different for me who majored in electronics-related, this is indeed an unforgivable mistake.

I don't want to rebase, fix, and create a request pull request again, please modify the translation as follows:

```json
{
    "adjustVolume": "音量",
    "adjustGain": "增益",
}
```

### Bug

1. Add two hotkeys.

```text
volume        ^ KeyA        -0.05
gain  +         ^ KeyQ       0.1
```

2. Open a youtube video.

3. Press ^ KeyQ once

4. Press ^ KeyA, until volume to be 0%

5. Press ^ KeyQ, it shows 120%, but no voice.

**Comment by polywock** [comment]
I noticed the mistake before publishing. I renamed `adjustGain = 音量+` to differentiate between  `adjustVolume = 音量`  For the rest of translations, I did it very similar. Finding the "gain" word in other languages was very hard so I just used the word for volume and added a plus sign.

**Comment by liangjiancang** [comment]
No bug? Do you mean this phenomenon is correct? This seems strange to me.

**Comment by polywock** [comment]
Did you install the newest Chrome version? The translations are `adjustGain` = `音量+`, and `adjustVolume` = `音量`. 

`adjustVolume (音量)` adjusts the volume for the actual video/audio.
`adjustGain (音量+)` adjusts the volume for the entire tab (up to 300%).

**Comment by liangjiancang** [comment]
OK, I know what you mean, the explanation is reasonable.

In addition, I switched to Edge a few days ago.

**Comment by polywock** [comment]
The Edge version takes 2-4 days to publish. It used to be the same for the Chrome version, but the latest update got published in an hour. I wonder what changed. 

What makes the most sense in Chinese? 

1. `音量+`      (current) 
1. `增益`        (gain) 
1. `音量增益` (volume gain) 
1. `标签音量` (tab volume?)

**Comment by liangjiancang** [comment]
`增益` (gain) is the best option.

**Comment by liangjiancang** [comment]
And I advice you not to replace "gain" by "tab volume" or other description. From the perspective of EE, there is no 100%+ volume. 
Maybe you can use "tab gain"（标签页增益，notice "标签"!="标签页"）? I don't know whether if this makes sense in English, but it makes sense in Chinese.

**Comment by liangjiancang** [comment]
In fact, I suddenly wanted to translate because I saw that the name of the extension "Global Speed" was translated very funny by the machine, "全球速度", which means "speed of the world".

Although the original Chinese translation made me feel funny, the machine translation in other languages may offend others. After all, it is easy to make these mistakes if you don't understand the other's culture. For example, listing China and **our** Taiwan province together is uncomfortable for most Chinese.

**Comment by polywock** [comment]
Lol. I should probably stay away from this topic.

**Comment by polywock** [comment]
I'm going nuke this thread. Thanks again for the help.
