### ISSUE TITLE
视频拖动不了进度条 Video can't drag progress bar

### ISSUE THREAD

**Issue by xuantou** [polywock/globalSpeed#232]
尊敬的开发者,希望能开创允许鼠标拖动进度条的功能,不能拖动会有些不方便,非常感谢!
Dear developer, I hope to create a function that allows the mouse to drag the progress bar. It will be inconvenient to not drag, thank you very much!

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of today, this feature is supported. If you reset the shortcuts or re-install global speed, there's a new default shortcut (Backquote ` key) where the mouse can be used to drag the progress bar. The left side of page will seek to beginning of video, and the right side of page will seek to the end.
