### ISSUE TITLE
1.71版本按键“音效”丢失

### ISSUE THREAD

**Issue by TangTank** [polywock/globalSpeed#233]
1.71版本中，按键效果音没有了

**Comment by polywock** [comment]
Hello. The sound feature was removed for technical reasons. All Chrome/Edge extensions must migrate to Manifest v3 (it's currently v2 for Global Speed) by 2023. Manifest v3 doesn't support loading sound in memory so to support sound feature I will have to load it each and every time the key is pressed, which probably won't be performant and there might be a significant enough delay making it useless. I have not yet migrated to V3, but it was removed in preparation for migrating to v3.

**Comment by TangTank** [comment]
thank you for your reply

> Hello. The sound feature was removed for technical reasons. All Chrome/Edge extensions must migrate to Manifest v3 by 2023. Manifest v3 doesn't support loading sound in memory so to support sound feature I will have to load it each and every time the key is pressed, which probably won't be performant and there might be a significant enough delay making it useless. I have not yet migrated to V3, but it was removed in preparation for migrating to v3.
