### ISSUE TITLE
bilibili播放视频时，当前视频可以正常加速，但是自动切换到下一视频就不能加速了

### ISSUE THREAD

**Issue by liangyutang** [polywock/globalSpeed#234]
bilibili播放视频时，当前视频可以正常加速，但是自动切换到下一视频就不能加速了

**Comment by polywock** [comment]
Hello. Global Speed is an active speed controller, which means it applies speed to all videos on an interval. For performance, it only runs on the visible tabs. If Bilibili autoplays in a background tab, that video won't be sped up. I will improve this in the next major release. As a workaround, you can try changing your speed using hotkeys. It should apply to background videos as well.
