### ISSUE TITLE
对“ghost mode”（幽灵模式）的黑（白）名单

### ISSUE THREAD

**Issue by MisakaMikoto9982** [polywock/globalSpeed#236]
如何将“ghost mode”（幽灵模式）的设置自动化？也就是说，默认仅在指定的网站开启（或关闭），而不是对所有网站全局生效

**Comment by polywock** [comment]
Good idea. I will look into implementing it in the next major update (might take a while).

**Comment by polywock** [comment]
Hello. Apologies for the late update. Going through the old issues one by one. As of today, this feature is supported.
