### ISSUE TITLE
设置标记点后无法取消

### ISSUE THREAD

**Issue by HAOJIN1** [polywock/globalSpeed#238]
当我在一个视频设置标记点后再次点击w只能在相同位置重复播放，而不能取消该标记点在原视频新建一个标记点，所以我觉得增加标记点取消按键或者允许多标记点可以完善该插件的功能。

**Comment by polywock** [comment]
Hello. "Shift W" can be used to set mark. Only use "W" to go to mark. 


![amg1](https://user-images.githubusercontent.com/31208859/181429233-360a0500-50b8-4a03-9fec-367bad1ec965.png)
