### ISSUE TITLE
“网页全屏”的需求

### ISSUE THREAD

**Issue by xiaxiaonan1** [polywock/globalSpeed#239]
首先，非常感谢您，您的这款拓展工具在我网上学习时帮了很大的忙。考虑到很多时候，我在网上学习时需要离开浏览器，切换到其它软件，再切换回浏览器，比如看视频的中途需要查看视频配套的学习资料，以及通过专业软件实践刚刚学到的知识。目前的全屏功能，屏蔽了屏幕下方任务栏，不便于浏览器和其它软件间的切换使用，故建议增加网页全屏这一功能。再次感谢您！

**Comment by polywock** [comment]
Hello. Glad to see this extension was useful for your studies. If I'm understanding correctly, you want the video to fill the entire page, but not entirely fullscreen? If so, this trick might work. 

Open the audio filters section, and press the "Capture" (捕获) button. This is used for the audio effects like pitch shift, volume boost, but it also happens to block videos from entering fullscreen. 

If fullscreen doesn't work, many websites like Youtube, Baidu, Bilibili are programmed to maximize the video size. 

![img1](https://user-images.githubusercontent.com/31208859/182523409-5387fe12-bed7-4165-b345-e956060bb184.png)

![img2](https://user-images.githubusercontent.com/31208859/182523716-ca9bda66-d519-4655-9c2a-4d31c82fae3c.png)

It doesn't work on some websites, so you could also try this userscript. 

https://greasyfork.org/zh-CN/scripts/4870-maximize-video
