### ISSUE TITLE
Global Speed 

### ISSUE THREAD

**Issue by LuckyInu** [polywock/globalSpeed#24]
Global Speed doesn't work anymore on google chrome for exemple : on twitch or youtube (shortcuts and manuelly)

**Comment by polywock** [comment]
There was an update recently. After an update, it should stop working on all existing tabs. Did you try it on new tabs?  If you did, the problem is something else. You should probably reinstall the extension.

**Comment by LuckyInu** [comment]
Don't know what I did but now it's working, thanks for the advice.
