### ISSUE TITLE
Love the extension, suggestion 

### ISSUE THREAD

**Issue by odorizzioficial** [polywock/globalSpeed#240]
Hi, all right, great extension, congratulations, it just doesn't work in direct instagram to listen to audios, it can't be sped up, that would be a cool idea, because there is no app or extension for this.

That's the tip ;)

Translate in Google (Brazil haha)

**Comment by polywock** [comment]
Hello. Happy to hear the extension is useful. Does turning on "Ghost mode" in the options page fix the issue?

**Comment by odorizzioficial** [comment]
ooooooooooooowwwwwww <3333333333333333333333333333333333 Thank-you Poliwock worked perfectly, you are a god
