### ISSUE TITLE
网页端speed插件无法正常使用【bug反馈】

### ISSUE THREAD

**Issue by Ushnidaye** [polywock/globalSpeed#242]
在网页端播放视频时，仅在改变速度之后的瞬间实现变速功能，之后插件自动返回一倍原速。在YouTube上手动选择变速后，亦自动返回原速

**Comment by polywock** [comment]
Hello. Global Speed is what I call a top-down speed controller. If you set the plugin's speed to 2x. It tries to force 2x speed on all videos it finds. If you change speed through Youtube's speed control feature, Global Speed will revert back to 2x. To change speed, use the Global Speed menu or shortcut keys (A key to lower speed, S to reset to 1x, D to increase speed).
