### ISSUE TITLE
本地文件的播放

### ISSUE THREAD

**Issue by trustedinster** [polywock/globalSpeed#243]
我在Chrome浏览器上播放本地文件时，发现Global Speed不能支持，但是后来不知道什么原因又支持了。但当我重新安装Chrome后，又发现不能支持。

**Comment by trustedinster** [comment]
请问能不能增加本地文件播放的支持？？？
![image](https://user-images.githubusercontent.com/103629945/184161150-ec5c44a6-097c-4023-89ce-6b4e1ebad058.png)

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Local files are supported, but needs to be enabled in the browser's extensions page . 

Chrome: `chrome://extensions`

Edge: `edge://extensions`

![page](https://user-images.githubusercontent.com/31208859/184238372-c9c52a9b-8add-470c-9661-d3820f9207e5.png)
