### ISSUE TITLE
音量突然控制全局了/在设置里找不到全屏了

### ISSUE THREAD

**Issue by GrandGudako** [polywock/globalSpeed#244]
之前设置的全屏的快捷键没用了，就想重新设置但找不到设置全屏的地方了
![5484FDCA-FC59-4306-BEE7-881AEDC0F6EB](https://user-images.githubusercontent.com/110949339/183788478-090cd636-14e1-4c86-9e39-441c16cf5f8f.jpeg)

我之前看bilibili什么的视频（因为每个视频的音量基础不一样，有的视频50音量正好有的视频50音量听不见，有的视频50音量吵耳朵）所以都是设置一个基础的音量例如20，然后用这个globalspeed微调不干扰别的标签栏里的视频音量，而现在这个globalspeed的调音量功能突然可以控制所有标签栏了，我刚在这个视频嫌声音小把音量从基础20调到了100，切到另一个视频声音就炸耳朵了。这有什么办法解决么。

**Comment by GrandGudako** [comment]
还有这个globalspeed的调音量功能对bilibili直播没用

**Comment by polywock** [comment]
Hello. No recent update that should effect tabs. It could be that Bilibili is reacting the volume changes and applying it other videos. Does that happen on all websites or just bilibili? I might have a workaround. 

The video fullscreen shortcut is this one. You could also press the reset button to restore default shortcuts. 

![fullscreen1](https://user-images.githubusercontent.com/31208859/183828520-4c01349a-bfe8-497c-a140-e8946fdf0192.png)

**Comment by GrandGudako** [comment]
就是bilibili别的视频不是这样，以前globalspeed不能控制全局现在突然就可以了
全屏按钮的话我电脑上显示的和你图里不一样了，之前也是有全屏的现在突然AB循环下面没有全屏和画中画就跳到了FX状态，按你说的恢复默认状态也没找到全屏
![Uploading A6D2A99A-4410-429A-978C-B647962EB60F.jpeg…]()

**Comment by GrandGudako** [comment]
![208D285F-4019-4C04-94DE-0E8D7856F557](https://user-images.githubusercontent.com/110949339/183832952-19e272c4-d20b-44ce-bd5a-28cb3cfcc6bf.jpeg)

**Comment by polywock** [comment]
Weird. Which Global Speed version are you on? Also, which browser?

**Comment by GrandGudako** [comment]
@polywock 
在单位用的360有全屏消失这个问题，家里google浏览器版的没问题
![4BE2617D-5E24-45CE-8F63-4622ABF3753E](https://user-images.githubusercontent.com/110949339/183834534-93e5a84b-c1d6-4027-a1ad-9083d4c10276.jpeg)
这个版本的

**Comment by polywock** [comment]
The fullscreen feature was introduced in 2.8.2. Current version is 2.9.97.
