### ISSUE TITLE
部分网页无法倍速播放【bug反馈】

### ISSUE THREAD

**Issue by txc93710** [polywock/globalSpeed#245]
您好！经过使用发现www.ccmtv.cn该网站上的视频均无法加速播放，一旦加速则会卡在第一帧，但是减速播放是正常的。请问应该如何解决？

**Comment by polywock** [comment]
Hello. Does turning on Ghost mode in the options page fix the issue?

**Comment by txc93710** [comment]
> Hello. Does turning on Ghost mode in the options page fix the issue?
> 
> ![options](https://user-images.githubusercontent.com/31208859/184471677-782e264d-f016-4045-ab72-87c302e54b92.png)

finally solved!!! thankyuuuuuuuu!!!!!!

**Comment by 2227777111** [comment]
https://www.fenbi.com/spa/webclass/class
粉笔课堂网页版 视频也无法开启倍速，点了幽灵模式还是不行，继承全局也不行，
