### ISSUE TITLE
自定义快捷键设置中没有亮度调节功能

### ISSUE THREAD

**Issue by Ushnidaye** [polywock/globalSpeed#248]
建议在自定义快捷键中增加两个功能：
1.增加屏幕亮度
2.降低屏幕亮度

**Comment by polywock** [comment]
Hello. Not screen brightness, but page brightness can be adjusted with FX filter shortcut (FX过滤器).


Shift-Y to decrease brightness by 0.01
Y to increase brightness by 0.01

![brightness](https://user-images.githubusercontent.com/31208859/185816039-479cf18f-b82b-4bfc-8972-e95ef9bb7a81.png)
