### ISSUE TITLE
能否下载被加速的流媒体文件？

### ISSUE THREAD

**Issue by Ushnidaye** [polywock/globalSpeed#249]
可以想IDM和gihosoft那样下载被加速的视频和音频文件？

**Comment by polywock** [comment]
Hello. Global Speed does not support downloading video or audio. I've had multiple people suggest this feature, but it's too risky for me because extensions that support downloading end up being taken down.

**Comment by teadrinker2015** [comment]
出门右转 yt-dlp + ffmpeg
