### ISSUE TITLE
Localize indicator to the HTML5 video frame

### ISSUE THREAD

**Issue by tanykeat** [polywock/globalSpeed#25]
Would be great if it were possible for the indicator to show the speed within the frame of the HTML5 video that is controlled by this extension, rather than on the top left of the page itself!

Apart from that, great job with the versatility of the extension! Love the recent updates to it as well with the feedback sound :)

**Comment by polywock** [comment]
Thanks. I initially added the feedback sound for debugging purposes. But, after getting used to it, removing it was no longer an option. 

As for the suggestion. I've experimented with that before, but ultimately soured on the idea. The reason being, there is no cheap way to determine if a video is visible. So, that means to ensure the user sees it. The extension would have to show the indicator over every video that could potentially visible plus the top-left corner to ensure the user sees it (and that's no beauty)
