### ISSUE TITLE
Please add a "naming" feature for the URL rules

### ISSUE THREAD

**Issue by harmonyharmo** [polywock/globalSpeed#252]
I wish there's a way to name the URL rules in the settings

<img width="860" alt="image" src="https://user-images.githubusercontent.com/11383188/187316745-ddb06454-4a44-4c6b-bd5d-420d7fe4017a.png">

**Comment by harmonyharmo** [comment]
Thanks!

I'm not injecting any scripts, just using the URL matching rule like 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/11383188/187993068-3c61b024-ee5c-4104-a592-96559f6459a5.png">

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of today, this feature is supported. A label can added to both URL rules and shortcuts.
