### ISSUE TITLE
有两点建议希望大神添加下功能

### ISSUE THREAD

**Issue by JonKinM** [polywock/globalSpeed#253]
1，跳过片头片尾功能
2，获取播放列表自动播放下一级

**Comment by polywock** [comment]
> 1，跳过片头片尾功能

Hello. There is a plugin called [SponsorBlock](https://chrome.google.com/webstore/detail/sponsorblock-for-youtube/mnjggcdmjocbbbhaepdhchncahnbgone) that automatically skips intros, outros, sponsorship and other annoying parts of Youtube videos. There might be similar plugins for other websites like Bilibili. This type of plugin is only possible with crowdsourcing. It would be very difficult to implement this type of feature that works on all websites.

2，获取播放列表自动播放下一级

I've considered this in the past. But, there is no good universal way of doing it.  Only way is to maintain a list of websites and how to find the next video button for each site.  Here's an example of 20 websites and how to find the next button. This type of system is hard to maintain so I gave up on it. 

```
7digital.com: ".player-next"
amazon.com/gp/dmusic/cloudplayer/player: ".playbackControlsView .nextButton"
http://ampache.org: "a.jp-next"
accuradio.com: "#playerSkipButton"
airsonic.github.io: "img[onclick^=onNext]"
anghami.com: "#player .next"
beta.music.apple.com: "div.web-chrome-playback-controls__main > button:nth-child(3)"
are.na: "#playPause button:nth-child(3)"
audible.com: "#adbl-cloud-player-controls .adblFastForward"
audiotool.com: "a.forward"
bandcamp.com: ".nextbutton"
bbc.co.uk/radio: "#p_audioui_previousButton"
beatport.com: ".omniplayer--action-icon.next"
castbox.fm: ".forward"
http://cloud-caster.com: "#skip30"
coursera.org: "[data-track-component='item_side_nav_next_lession']"
deezer.com: "div.player-controls > ul > li:nth-child(5) > div > button"
demodrop.com: ".control.next"
disco.io: "#next-button"
disi.co.il: ".youtube-player-toolbar li:nth-child(2)"
```
