### ISSUE TITLE
百度网盘倍速不了了

### ISSUE THREAD

**Issue by Jacob999-yu** [polywock/globalSpeed#256]
百度网盘再次倍速不了了

**Comment by audrey998** [comment]
我也是，昨晚十二点还可以的，解决了吗？？

**Comment by KDbasket** [comment]
厚礼蟹，lz线代还没看完呢，

**Comment by RAY-COLA** [comment]
我408还没看完呢

**Comment by galaxy-plut** [comment]
有什么替代方法吗

**Comment by XINGXINGMIANWO** [comment]
我也是

**Comment by XINGXINGMIANWO** [comment]
他会自动更新吗

**Comment by MinoYang** [comment]
不能加速好痛苦

**Comment by polywock** [comment]
Hello. I think I resolved the issue. I published the update on Firefox, but it will take up to a week for approval on the Chrome and Edge stores. You can also load the update manually right now. Download, unzip folder, and load. 


[packed.zip](https://github.com/polywock/globalSpeed/files/9533362/packed.zip)



**Chrome**: open extensions page `chrome://extensions`, enable dev mode on top right, load unpacked.

**Edge**: open extensions page `edge://extensions`, enable dev mode on top left, load unpacked.

**Comment by Daisy812** [comment]
Thanks for your help.It effectively solved my problem.

**Comment by galaxy-plut** [comment]
Thanks. It works.

**Comment by zxyacg** [comment]
Thanks

**Comment by Sawako-Yan** [comment]
I have also loaded the update manually, and  I have tried on google, but it worked wrongly. 
The current version is 2.9.98 ( windows)

**Comment by polywock** [comment]
@Sawako-Yan Hello. Make sure to uninstall the old version of Global Speed. Also try restarting your browser. Let me know if the issue still hasn't resolved.

**Comment by Sawako-Yan** [comment]
> @Sawako-Yan Hello. Make sure to uninstall the old version of Global Speed. Also try restarting your browser. Let me know if the issue still hasn't resolved.

Thanks. It works well.

**Comment by Jenny2020a** [comment]
> Hello. I think I resolved the issue. Let me know if it works. I published the update (2.9.98) on Firefox, but it will take up to a week for approval on the Chrome and Edge stores. You can also load the update manually.
> 
> [packed.zip](https://github.com/polywock/globalSpeed/files/9533362/packed.zip)
> 
>     1. Download and unzip folder.
> 
>     2. Uninstall old version of Global Speed.
> 
>     3. Load new version.
> 
> 
> **Chrome**: open extensions page `chrome://extensions`, enable dev mode on top right, load unpacked.
> 
> **Edge**: open extensions page `edge://extensions`, enable dev mode on top left, load unpacked.

Very helpful tips! It works again! Thank you very much.

**Comment by polywock** [comment]
Hello again. The Chrome Web Store update (2.9.98) has been approved. If you previously installed from there and loaded the fix manually. You should remove the manual version and install from Chrome web store again to automatically receive updates.

**Comment by mukul-p** [comment]
Hello @polywock. Update for the extension has been approved in Edge webstore (version 2.9.98) on 9th September.
Can you confirm. 
Thanks

**Comment by polywock** [comment]
@mukul-p Thanks, I didn't know. Usually it takes around 7 days. It was approved quickly this time.
