### ISSUE TITLE
globalspeed cannot be applied for baidu netdisk

### ISSUE THREAD

**Issue by KDbasket** [polywock/globalSpeed#257]
date: 2022-9-9

**Comment by polywock** [comment]
Hello. Issue maybe fixed. Continue here. 

https://github.com/polywock/globalSpeed/issues/256#issuecomment-1241626116

**Comment by KDbasket** [comment]
> Hello. Issue maybe fixed. Continue here.
> 
> [#256 (comment)](https://github.com/polywock/globalSpeed/issues/256#issuecomment-1241626116)

it works. i represent the all postgranduates here ,thank u so much
