### ISSUE TITLE
work incorrectly when using baidu netdisk

### ISSUE THREAD

**Issue by hkcoding** [polywock/globalSpeed#259]
i have tried on firefox and edge, both work wrongly

current version is 2.9.97

**Comment by hkcoding** [comment]
more specifically, it do not work for now, the speed on the web page do not change because of the add-on as usual

**Comment by polywock** [comment]
Hello. Are you on Windows? If so which version?

**Comment by hkcoding** [comment]
yes, on windows11 22621.382




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月9日(星期五) 下午2:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [polywock/globalSpeed] work incorrectly when using baidu netdisk (Issue #259)





 
Hello. Are you on Windows? If so which version?

**Comment by polywock** [comment]
Hello. Issue maybe fixed. Continue here. 

https://github.com/polywock/globalSpeed/issues/256#issuecomment-1241626116

**Comment by hkcoding** [comment]
it's really working on firefox now, thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月9日(星期五) 下午3:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [polywock/globalSpeed] work incorrectly when using baidu netdisk (Issue #259)





 
Hello. Issue maybe fixed. Continue here.
 
#256 (comment)

**Comment by polywock** [comment]
Glad to hear.
