### ISSUE TITLE
Dark theme blanks out the dropdown window's text

### ISSUE THREAD

**Issue by tanykeat** [polywock/globalSpeed#26]
When the dark theme is activated, the dropdown window's text gets blanked out, and you can only read the text of the option you're hovering over. Included a screenshot of the issue!

Love the implementation of the dark theme though, just a small oversight with the dropdown window's text and background!

![image](https://user-images.githubusercontent.com/46909525/88984943-a97a1600-d301-11ea-97a2-03b6d0daef9c.png)

**Comment by polywock** [comment]
Oof, fixed. It will take a few days to publish. Fortunately, it's an Edge-only issue.
