### ISSUE TITLE
Couple Suggestions

### ISSUE THREAD

**Issue by CompJF** [polywock/globalSpeed#260]
Hi just started using this and it's great! I've got a couple suggestions that I think would improve it.

- Ability/hotkey to toggle speed between last speed and a preferred speed. I usually find a speed that I like but sometimes the speaker doesn't say it clearly so I want to change speed back to 1 but then I want to go back to the speed I was initially at after that small moment.
- Hotkey to toggle the speed indicator visibility. Sometimes I want to know what speed I'm currently at but the indicator has disappeared.
- Not sure if it's just me or not but in the shortcut editor, when hovering a row, the red URL button that appears feels like a delete button to me instead of a URL condition. Maybe change it to blue instead?
- Maybe move the pin FAQ into a ? next to the pin in the settings? I didn't know what pinning did and it didn't occur to me to look into the FAQ until much later when I sort of figured it out.

Great work on this! Pretty much the best playback chrome plugin I've ever used.

**Comment by polywock** [comment]
Thanks! Apologies for late reply. I wrote a reply but forgot to send it. 

1. The first is already possible with the speed hotkey. If you have speed hotkey that changes speed to 1.0. If speed is already 1.0, it reverts to previous speed. For example, if your speed is 2.5. The first time you press it it will go to 1.0. The second time, it will go back to 2.5.  

2. You can take advantage of toggle feature of speed hotkey for this. Just press it twice when you want to see speed. 

3. Good point. Red can be a misleading color. I will change it on the next update. 

4.  Yeah, the user experience isn't the best. I will try adding a good tooltip.
