### ISSUE TITLE
bilibili开启全屏模式后，空格键无法控制播放和暂停，但是小窗口可以，期待大佬优化一下

### ISSUE THREAD

**Issue by 33hzs** [polywock/globalSpeed#261]

**Comment by polywock** [comment]
Hello. You can create a pause hotkey in the options page. 

1. Create a pause hotkey (暂停) in the options page. 

![one](https://user-images.githubusercontent.com/31208859/190063157-190efef6-e17d-48a8-9b57-6bf5c26904df.png)


3. Set shortcut key to space, and click on little red circle to add URL condition.

![two](https://user-images.githubusercontent.com/31208859/190063169-13298cb9-6d7a-44aa-bb14-59364458475c.png)


5. Add URL condition so it only runs on bilibili.com 

![three](https://user-images.githubusercontent.com/31208859/190063178-87fd2fe5-6aa1-4f33-bc78-fba84a9b5047.png)
