### ISSUE TITLE
Extended Rules

### ISSUE THREAD

**Issue by rennerdo30** [polywock/globalSpeed#262]
It would be great if there where more possibilities for the rules. Like adding a selector if specific html tags are present.

In my case, I want to create a rule, which can diffirenciate between youtube videos and youtube streams. Since the url's are the same, it cannot be done with the url rules.
But if it would be possible to check if a specific string is present, like "live since", this could be done.

**Comment by polywock** [comment]
Hello. Funny you mention that. I actually tried to implement that for the same use case (detecting youtube live streams), but ultimately gave up because it was getting too complex and the feature was too niche to be worth the effort.  I might give it another go later.
