### ISSUE TITLE
A couple of suggestions. Preferred video quality and frame rate.

### ISSUE THREAD

**Issue by AndyBaz** [polywock/globalSpeed#264]
Some sites keep dropping video quality even though they can easily play FullHD. Is it possible to force the preferred video quality (720p, FullHD, etc.) and frame rate (24-30, 50-60)? If the selected video quality is not present in this clip, then the maximum possible quality is set, lower than the preferred one.
Great extension, thanks for it!

**Comment by polywock** [comment]
It's possible, but solution is unique to each different service. For Youtube, there are plenty of extensions. For other services, it might not be available. Try looking through the Edge/Chrome/Firefox extension store to find if an extension is available for the websites you use.
