### ISSUE TITLE
无法兼容简悦（simpread) 的双击a进去阅读模式

### ISSUE THREAD

**Issue by fdjkdf** [polywock/globalSpeed#265]
有一个插件叫简悦 simpread，他有个功能叫阅读模式 需要按两下a，但是当我用你的这个插件设置a为控制视频进度回退2秒时，另一个插件的两下a就不起作用了，请问能否兼容另外一个插件的双击

**Comment by polywock** [comment]
Hello. Global Speed shortcuts stop event propagation by default. You can change it by clicking on the 3 vertical dots. You can also change the shortcut to something other than 'A'. 

![ima](https://user-images.githubusercontent.com/31208859/192014499-6e3a2275-66d3-4daa-8d8c-7a460fac1987.png)
