### ISSUE TITLE
能否自定义允许加速的网站？（有些网站不需要不需要全局加速）

### ISSUE THREAD

**Issue by jyp0426** [polywock/globalSpeed#268]
如题

**Comment by polywock** [comment]
Hello. You can create a URL rule to disable Global Speed depending on URL. Here's walkthrough for how to disable for bilibili.com and pan.baidu.com.

![im1](https://user-images.githubusercontent.com/31208859/193152300-55ba65bd-23ae-42ef-91cb-e5f5519ddd3d.png)

**Comment by jyp0426** [comment]
It works.Thank you!
