### ISSUE TITLE
Bug: 在某些视频网站会导致视频错位

### ISSUE THREAD

**Issue by draymondgewade** [polywock/globalSpeed#269]
在某些视频网站弃用Global Speed插件会导致视频错位,即使未启用所有设置的按键, 例如115网盘, 斗鱼视频(https://www.douyu.com/)等, 关闭插件后恢复正常
如图所示:
![image](https://user-images.githubusercontent.com/43830206/192468094-eca82afa-0bf4-4e1e-99fd-69cf28a0d5f7.png)
![image](https://user-images.githubusercontent.com/43830206/192468136-dca5c968-ff2c-4f21-8c8c-6f6206cafab0.png)

**Comment by draymondgewade** [comment]
{"common":{"audioFx":{"delay":0,"eq":{"enabled":false,"factor":1,"values":[0,0,0,0,0,0,0,0,0,0]},"pitch":0,"volume":1},"audioFxAlt":null,"audioPan":null,"backdropFx":{"filters":[{"name":"sepia","value":0},{"name":"hueRotate","value":0},{"name":"grayscale","value":0},{"name":"contrast","value":1},{"name":"brightness","value":1},{"name":"saturate","value":1},{"name":"invert","value":0},{"name":"blur","value":0},{"name":"opacity","value":1}],"transforms":[{"name":"scaleX","value":1},{"name":"scaleY","value":1},{"name":"translateX","value":0},{"name":"translateY","value":0},{"name":"rotateX","value":0},{"name":"rotateY","value":0},{"name":"rotateZ","value":0}]},"elementFx":{"enabled":true,"filters":[{"name":"sepia","value":0},{"name":"hueRotate","value":0},{"name":"grayscale","value":0},{"name":"contrast","value":1},{"name":"brightness","value":1},{"name":"saturate","value":1},{"name":"invert","value":0},{"name":"blur","value":0},{"name":"opacity","value":1}],"transforms":[{"name":"scaleX","value":1},{"name":"scaleY","value":1},{"name":"translateX","value":0},{"name":"translateY","value":0},{"name":"rotateX","value":0},{"name":"rotateY","value":720},{"name":"rotateZ","value":2160}]},"enabled":true,"lastSpeed":1,"monoOutput":null,"speed":1},"feedbackVolume":0,"firstUse":1652409091428,"hideBadge":false,"hideIndicator":false,"hideMediaView":null,"indicatorInit":{"offset":1,"scaling":1},"inheritPreviousContext":true,"keybinds":[],"language":"detect","pinByDefault":false,"rules":[],"showNetSeek":false,"speedBigStep":null,"speedPresetPadding":null,"speedPresetRows":4,"speedPresets":null,"speedSlider":null,"speedSmallStep":null,"version":10,"staticOverlay":true}

**Comment by draymondgewade** [comment]
上面为一份会导致错位的配置文件

**Comment by polywock** [comment]
Hello. The video filters are enabled. Open the FX panel and reset. 

![img0](https://user-images.githubusercontent.com/31208859/192655092-c92e2d36-975a-42e3-89de-62f82749e551.png)



![img1](https://user-images.githubusercontent.com/31208859/192655082-c8ac5e0c-dc85-41ee-8394-b2e185406138.png)
