### ISSUE TITLE
您好我是菜鸟复杂的也不太懂！您的插件非常好！但是能否请您为音频延迟增加负延迟的选项，因为我会用到home pod播放视频！很感谢您！

### ISSUE THREAD

**Issue by xiaobaoziQQAQQ** [polywock/globalSpeed#273]
谢谢您！

**Comment by polywock** [comment]
There's a cool [extension](https://chrome.google.com/webstore/detail/youtube-audiovideo-sync/mknmhikmjljhpccebpnplhicmcfjkgbk?hl=en) that does negative audio delay for Youtube. That extension's approach cannot be extended to other websites. It's pretty much impossible to do negative delay without reverse engineering and building custom solution for each website.
