### ISSUE TITLE
视频标记mark1的错误

### ISSUE THREAD

**Issue by lihuaming07** [polywock/globalSpeed#278]
第一次按下↑+w可以设置标记点，但是第二次按下就不行了，只能跳转到标记点，无法重新设置

**Comment by polywock** [comment]
Hello. Are you pressing shift-W to set mark? It seems like only W is being pressed. W jumps to mark1 (or sets mark1 the first time you press it).

**Comment by lihuaming07** [comment]
Thanks,I get it






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 上午8:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] 视频标记mark1的错误 (Issue #278)





 
Hello. Are you pressing shift-W to set mark? It seems like only W is being pressed. W jumps to mark1 (or sets mark1 the first time you press it).
