### ISSUE TITLE
Local keyboard shortcuts stop working on MS Edge

### ISSUE THREAD

**Issue by aedgsilva** [polywock/globalSpeed#28]
It was working fine and stopped working out of nothing (apparently). Removed and reinstalled and still not working.

**Comment by polywock** [comment]
There was an update recently. After an update, it should stop working on all existing tabs. Have you tried the shortcuts on new tabs? If you did, try to restart Edge. Let me know if that didn't fix it.

**Comment by aedgsilva** [comment]
It's working now on new tabs. Thanks!

**Comment by polywock** [comment]
Turns out this was a genuine bug. The

**Comment by polywock** [comment]
This might have been a genuine bug. I recently noticed a race condition that could cause this issue.
