### ISSUE TITLE
没有速度预设那个框，只有快捷键和速度指示

### ISSUE THREAD

**Issue by greataolu** [polywock/globalSpeed#285]

**Comment by polywock** [comment]
Hi. To change speed presets, you can click the three dots. 

![a](https://user-images.githubusercontent.com/31208859/203673753-ec9d329d-3d78-484e-9d56-e724e36fe0ed.png)
![aa](https://user-images.githubusercontent.com/31208859/203673759-26f40f61-84c2-4550-8466-9ee3444230b7.png)

**Comment by greataolu** [comment]
非常抱歉，我发现是浏览器自动隐藏了拓展选项，点击拓展选项即可呼出

在 polywock ***@***.***>，2022年11月24日 09:26写道：

Hi. To change speed presets, you can click the three dots.

[a]<https://user-images.githubusercontent.com/31208859/203673753-ec9d329d-3d78-484e-9d56-e724e36fe0ed.png>
[aa]<https://user-images.githubusercontent.com/31208859/203673759-26f40f61-84c2-4550-8466-9ee3444230b7.png>
