### ISSUE TITLE
Don't run keyboard shortcut if focused on a textbox

### ISSUE THREAD

**Issue by stephenkoo** [polywock/globalSpeed#291]
I love your extension, thank you for making it.

I am wondering if you could disable keyboard shortcuts from running if user is focused on a textbox using `.activeElement`:

```js
function onMouseUp(e) {
  const activeTextarea = document.activeElement;

  if (activeTextarea.type === "textarea" || activeTextarea.type === "input") {
  	console.log("Do not run globalSpeed");
  }
}

window.addEventListener('mouseup', onMouseUp, false);
```

**Comment by polywock** [comment]
Thank you. Glad the extension could be helpful. 

This is the current implementation.  It seems like the e.target would equal the active element so it should be equivalent. 

```javascript 
    const target = e.target as HTMLElement
    if (["INPUT", "TEXTAREA"].includes(target.tagName) || target.isContentEditable) {
      return // Do not run globalSpeed
    }
```

**Comment by polywock** [comment]
Thank you. Glad the extension could be helpful. 

The shortcut keys should already be disabled when focused on textbook. The current implementation is this... 

```javascript 
    const target = e.target as HTMLElement
    if (["INPUT", "TEXTAREA"].includes(target.tagName) || target.isContentEditable) {
      return // Do not run globalSpeed
    }
```

e.target should be equal to active element when focusing on a textbox. Not sure why it doesn't seem to work for you. Let me know the website and how to reproduce the issue so I could test it out.

**Comment by stephenkoo** [comment]
Ah I see that! My bad - I realise it just _sometimes_ doesn't work with extensions like [Selection Search](https://chrome.google.com/webstore/detail/selection-search/gipnlpdeieaidmmeaichnddnmjmcakoe) on Firefox/Chrome when clicking on the text field, but this is probably an edge-case not worth looking into.
 
![image](https://user-images.githubusercontent.com/18624246/204721172-ee70c4ea-360b-44df-9bfa-067544a96588.png)

I appreciate your work!
