### ISSUE TITLE
YouTube直播的速度控制

### ISSUE THREAD

**Issue by himcc** [polywock/globalSpeed#293]
我通常用2倍速看视频，但是2倍速看直播的时候就会时断时续，我想给YouTube的直播默认设置为1倍速。但是我看判断规则只能应用在URL上，YouTube的视频和直播观看页面的URL没有明显区别，我改如何给YouTube的直播默认设置为1倍速呢？

**Comment by polywock** [comment]
Hi. Apologies for the late reply. It must have slipped my radar. I stopped working on the extension for about 2 years. 

Yeah, I did in the past implement a javascript solution that worked to dect Youtube's Live indicator. The problem with that kind of approach, Youtube's UI changes so frequently that it becomes a maintenance nightmare.   

I also tried listening to "waiting" event and to reset speed to 1x, but that approach also had issues.
