### ISSUE TITLE
技术提议

### ISSUE THREAD

**Issue by Akirusu** [polywock/globalSpeed#294]
你好，我认为你可以写一个下载视频的功能他对某些人应该都会有些帮助

**Comment by polywock** [comment]
Hi.  Video download extensions can be very complicated and require a lot of maintenance. They're best as dedicated extensions and I don't think I'll have the time to maintain one. They're also risky because Google often takes them down from the Chrome Web Store.

**Comment by Akirusu** [comment]
Don't we all need challenges? You can try to write it out. It is normal for maintenance because everything is updating.

**Comment by polywock** [comment]
The problem with video downloading is that many sites require unique solutions. Some sites share patterns but many sites do things their own way (Youtube, Netflix, Bilibili, etc). It would take a lot of researching, reverse engineering, and testing to make a video downloading extension that works on the most popular websites. I like a good challenge, but this will take months and the reward isn't great.

**Comment by Akirusu** [comment]
奖励就是你的开发技术又强了，我期待你的挑战结果。几个月后在这见。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 晚上6:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [polywock/globalSpeed] 技术提议 (Issue #294)






视频下载的问题是，许多网站需要独特的解决方案。有些网站共享模式，但许多网站以自己的方式做事（YouTube，Netflix，哔哩哔哩等）。这将需要大量的研究，逆向工程和测试，使视频下载扩展，工程上最流行的网站。我喜欢一个好的挑战，但这将需要几个月，奖励不是很大。

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.
