### ISSUE TITLE
edge插件中无法被删除 I cannot uninstall it in edge

### ISSUE THREAD

**Issue by Noeon1** [polywock/globalSpeed#297]
after i uninstalled it , a few days later it will install autoly

**Comment by polywock** [comment]
Very weird. Did you install the official extension through the Edge addon store? Let me know if this is the version you installed. 

https://microsoftedge.microsoft.com/addons/detail/global-speed/mjhlabbcmjflkpjknnicihkfnmbdfced

**Comment by Noeon1** [comment]
I installed it at the Edge addon store, about 2 months ago. The clear time I forgot.  And I have just uninstalled it. If it reinstalls again, I will take care of the version. （My English is poor, sry)

**Comment by Noeon1** [comment]
> 

![图片1](https://user-images.githubusercontent.com/120188966/206894808-0f5e0947-a507-4516-a878-cd0f091933ec.png)

**Comment by polywock** [comment]
Auto installed again? It seems to be the official one, but very weird for it keep installing back. There is over a million users on the Edge version and it's the first time I've heard about this type of issue. 

My current theory is that it has something to do with your Microsoft account and syncing.  If you go to the link below, you should be able to see if your Edge is linked with a Microsoft account. Let me know if it's linked. 

`edge://settings/profiles`

**Comment by Noeon1** [comment]
thanks  
the problem is about synchronization
