### ISSUE TITLE
Twtich直播卡死

### ISSUE THREAD

**Issue by Phowx** [polywock/globalSpeed#298]
设备：Mac mini（M1）
系统版本：macos 13.1
浏览器：Chrome 108.0.5359.124（正式版本） (arm64)
规则：twitch.tv  1倍速
Chrome打开twitch.tv就卡爆，打开其他网页正常。强制重启Chrome并禁用globalspeed可正常观看Twitch。

**Comment by polywock** [comment]
Hello. I was able to reproduce the bug. Fixed in the latest update (2.9.99). Might take a few days for the update to get approved for the Chrome Web Store and up to a week for the Edge Add-on store.

**Comment by EremesNG** [comment]
I came here to report this, a pleasure to see that the fix is already on the way.
