### ISSUE TITLE
B站倍速失败-干扰网页原功能

### ISSUE THREAD

**Issue by Frozen1084** [polywock/globalSpeed#299]
手动在网页选择2倍速后，大概1秒后恢复到1倍速，没有启用幽灵模式。

firefox冰鼬 108 
win10 64

**Comment by polywock** [comment]
Hi. Global Speed overrides all video's speed to the selected speed.  If Global Speed is set to 1x, and you change speed to 2x through the webpage, it will be reset back to 1x. I recommend using Global Speed's hotkeys to change speed instead of the webpage's own controls.

**Comment by Frozen1084** [comment]
Thank you for your reply.
