### ISSUE TITLE
[Feature Request] Mono Audio

### ISSUE THREAD

**Issue by liangjiancang** [polywock/globalSpeed#30]
Function like this:

https://winaero.com/blog/wp-content/uploads/2017/12/Windows-10-enable-mono-audio.png

**Comment by polywock** [comment]
Great idea, I want this as well. And It was surprisingly easy to implement, only a few lines of code. I'll probably push the update in a few weeks. I pushed too many updates recently, the manual reviewers will start to hate me . Also, if I push an update, the extension stops working on all existing tabs unless the user refreshes the page.

If you want to use it, here's the unpacked version. The "M" button near the gain slider activates mono mode.


[packed.zip](https://github.com/polywock/globalSpeed/files/5041346/packed.zip)
