### ISSUE TITLE
2022.12.17 youtube 失效

### ISSUE THREAD

**Issue by loukafai** [polywock/globalSpeed#300]
今天發現使用 chrome extension 版本 2.9.991 已更新 2022年12月16日 不能加速， b 站上還正常

**Comment by polywock** [comment]
HI. After install or update, did you refresh your Youtube page?

**Comment by polywock** [comment]
I have managed to reproduce the issue. In 2.9.991 I implemented a failsafe for a potential infinity loop scenario. For example, Global Speed changes speed, website reacts to that and changes speed back, Global Speed reacts to that and changes speed back. This scenario shouldn't happen but the failsafe is cheap so I might as well add it.  But, of course, I was in a rush so I didn't bother testing it. Hopefully I did a better job on this update. Should get approved today or within a week.

**Comment by polywock** [comment]
An update. Version 2.9.992 got approved. If you haven't received it yet. Make sure to press the update button in the Chrome extensions page.

Also, if you manually loaded the fixed version. You can uninstall that version and re-enable the official one.

**Comment by loukafai** [comment]
真的可以了，感謝作者！！
