### ISSUE TITLE
Breaks Substack audio player when set faster than 2x

### ISSUE THREAD

**Issue by TracingWoodgrains** [polywock/globalSpeed#301]
When the extension's speed is set outside Substack's available parameters (maximum 2x speed), the audio player locks up: you can still click play and hear the audio, but the play button freezes and the timer freezes at 0:00. Tested on Firefox and Brave. 

[Test site 1](https://www.blockedandreported.org/p/episode-143-how-bidens-rogue-deputy#details)

[Test site 2](https://wethefifth.substack.com/p/386#details)

**Comment by polywock** [comment]
Hello. Ghost mode in the options page seems to fix it. If enabled, Global Speed will try to block the website from changing speed or reacting to speed changes.

**Comment by TracingWoodgrains** [comment]
Thanks! That workaround does the trick. Appreciate all you do on this! It's transformed the way I use the internet.
