### ISSUE TITLE
12.17  2.9.991 Watch douyin and kuaishou on Chrome. After watching a few videos, you can't speed up

### ISSUE THREAD

**Issue by xingqi4** [polywock/globalSpeed#302]
Hello,Watch douyin and kuaishou on Chrome. After watching a few videos, you can't speed up
2022.12.17       2.9.991

**Comment by xingqi4** [comment]
No problem with Microsoft Edge

**Comment by polywock** [comment]
Hi. #300 is probably the cause. The update 2.9.992 should fix it. Here's the fixed version if you want to load it manually for now. 

[packed.zip](https://github.com/polywock/globalSpeed/files/10251706/packed.zip)

1. Download packed.zip and extract the folder. 
2. open extensions page, chrome://extensions 
3. Disable the original Global Speed. 
4. Enable dev mode in top right of page. 
5. Click "load unpacked" in top left of page and load the folder.

**Comment by xingqi4** [comment]
> 

 Thank you very much

**Comment by xingqi4** [comment]
@polywock  Thank you very much.

**Comment by didischr** [comment]
same here, i use chrome and the control speed work at the beginning then stop working

**Comment by polywock** [comment]
An update. Version 2.9.992 got approved. If you haven't received it yet. Make sure to press the update button in the Chrome extensions page.

Also, if you manually loaded the fixed version. You can uninstall that version and re-enable the official one.
