### ISSUE TITLE
suggestion:translucent interface

### ISSUE THREAD

**Issue by vuuuj** [polywock/globalSpeed#306]
![STScI-01G77QNQQK7FN6NJDRTFHYMHVM](https://user-images.githubusercontent.com/121086897/208619193-9edc286a-a4f9-4f1d-a63c-e63cbbc75b27.jpg)---->![2](https://user-images.githubusercontent.com/121086897/208619207-dedf5b35-04d3-4647-bbb7-966ed1f6aecc.jpg)

Works very well 
Thank you

**Comment by polywock** [comment]
HI. Not possible to make it see-through (background won't be visible through the interface). It will just look whiter.
