### ISSUE TITLE
学习通考试使用会被检测到吗

### ISSUE THREAD

**Issue by Waddles716** [polywock/globalSpeed#310]

**Comment by polywock** [comment]
Maybe. If you turn on Ghost mode in the options page. If the website checks the .playbackRate property, it will say 1x speed, even if it's actually 2x. So they might get tricked, but are still multiple ways to detect. if you're watching at fast speed. If video is 10 minutes long and you finish in 5 minutes. Obviously, they can figure out you watch in 2x. Depends on how thoroughly they check.
