### ISSUE TITLE
使用后，关闭时或1.0时  在正常看视频自动会加速。bug

### ISSUE THREAD

**Issue by XSG666** [polywock/globalSpeed#311]
bug
1.扩展在1.0x状态，存在自动加速情况，视频开头0-10秒会被加速，随后恢复正常播放速度。
2.扩展关闭后，存在加速。即便关闭时是1.0x。必须打开状态且为1.0x才能正常播放。

**Comment by polywock** [comment]
Hello. Are you on the latest version (2.9.992)? The version prior to this had a serious bug that might be the cause.

**Comment by XSG666** [comment]
![image](https://user-images.githubusercontent.com/122152724/211159279-74f60233-6ccd-460d-aa0e-71cedb3299a5.png)
没错，我刚刚使用了4天，1月3日在microsoft官网扩展网页下载的。
我看的是bilibili视频，发现是较短的视频容易出现自动加速bug，十分钟以上的不会。今天我删除了扩展，播放新视频的倍速有时候就是16x，我之前曾用过的倍速。

**Comment by polywock** [comment]
> Today I deleted the extension, and the speed of playing new videos is sometimes 16x, the speed I used before.

This makes me think you might have multiple speed control extensions (or userscripts). If not, you can try turning on Ghost mode in the options page. Let me know if that fixes it.

**Comment by XSG666** [comment]
关于这个我有一个猜想，我是常常使用原视频更改倍速的人，是不是我装了扩展后，扩展控制了整个浏览器视频的倍速？关闭扩展时也一样，原视频的倍速无法更改？包括我从扩展中删除GS后，GS扩展仍在我的浏览器里发挥作用？这才导致了我视频倍速bug。

**Comment by polywock** [comment]
> I am a person who often uses the original video to change the speed. After I installed the extension, did the extension control the speed of the entire browser video? 

Yes. After installing Global Speed, the only way to change speed is through Global Speed's own controls. So if Global Speed is 2x, and you change video's speed to 1x using the website's own controls, Global Speed will ignore that and continue setting 2x to all videos every few seconds on your active tab. 

> Even after I removed GS from the extension, the GS extension still works in my browser? This caused my video double speed bug.

If you uninstalled Global Speed, it should have no influence whatsoever.  It should be as if you never uninstalled it. Try disabling all your extensions and then checking to see if the issue still occurs.

**Comment by XSG666** [comment]
问题已查明，此扩展名为：html5视频播放工具   ，其带有简单的加速功能，快捷键C可以加速0.1倍。
![image](https://user-images.githubusercontent.com/122152724/213474228-6bcb48f2-531b-4644-8a22-7bd86a2c443e.png)
![image](https://user-images.githubusercontent.com/122152724/213475185-c61641d7-2a54-41d3-b3e3-878a33185b1a.png)
感谢的热心回复。
