### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by wjsw1781** [polywock/globalSpeed#312]
I want to redevelop your plugin, but I have some problems reading the source code, you only need to answer me one question: What is the key code to make the video speed double?
Because the source code has a lot of interface configuration background related content, I can't find the most critical code: that is, the code that doubles the speed of the video, hard work your reply!  1781591279@qq.com or qq 1781591279

我想二次开发您的插件,但是我在阅读源码过程中遇到一些问题,您只需要回答我一个问题就行:使得视频倍速的关键代码是什么?
因为源码是有很多是界面 配置 后台相关的内容,我无法找到那个最关键的代码:就是让视频倍速的代码,辛苦您的回复,您可以通过邮箱或者qq联系我

**Comment by polywock** [comment]
Hello. For the basics, I recommend instead looking through the source code of Video Speed Controller. Another popular speed control extension with much straightforward code. 

https://github.com/igrigorik/videospeed
