### ISSUE TITLE
能不能新增功能，倍速只对一个标签页起作用，其他标签页无效

### ISSUE THREAD

**Issue by Agoinyff** [polywock/globalSpeed#317]

**Comment by polywock** [comment]
Hello. Keep Global Speed off or set to 1x. On the tab you want 2x speed, press the pin 📌 icon and change speed to 2x. Pin makes it so only that tab's speed changes. You can also use shortcut version of 📌 (key Q) to pin and unpin tab.

**Comment by Agoinyff** [comment]
oh,thank you

**Comment by TangbohuDianPaoZhang** [comment]
> Hello. Keep Global Speed off or set to 1x. On the tab you want 2x speed, press the pin 📌 icon and change speed to 2x. Pin makes it so only that tab's speed changes. You can also use shortcut version of 📌 (key Q) to pin and unpin tab.

I can't find global speed option in the setting. Where is it?

**Comment by MrHarutoandMissPei** [comment]
> Hello. Keep Global Speed off or set to 1x. On the tab you want 2x speed, press the pin 📌 icon and change speed to 2x. Pin makes it so only that tab's speed changes. You can also use shortcut version of 📌 (key Q) to pin and unpin tab.

thanks!  :)
