### ISSUE TITLE
When  I create a new tab, can I set the rate to 1 by default

### ISSUE THREAD

**Issue by TangbohuDianPaoZhang** [polywock/globalSpeed#322]
I found that if the rate of tab I was seeing was 2 for example, the new tab's rate would be 2 not 1. I want to know if I can set it. Thank you.

**Comment by polywock** [comment]
Hello. If you want the default speed for new tabs to be 1x.  

1. Enable  "pin by default"  and  "inherit global" in the options page. This will make it so new tabs are automatically pinned, and inherit the global context's speed. 

![imgg1](https://user-images.githubusercontent.com/31208859/178053659-325115c6-e1a5-4502-897c-465df024a8c9.png)

1. To change global context's speed to 1.0x. Make sure the tab is not pinned first, and then set speed to 1.0x. 

![imgg2](https://user-images.githubusercontent.com/31208859/178054171-da1fc5ce-a4e2-464b-bb66-daa7c9bcba1e.png)

**Comment by TangbohuDianPaoZhang** [comment]
Already solve it, appreciate

**Comment by polywock** [comment]
Hello. Going through the old issues one by one. I noticed this was still open. The pin by default mode now supports a "new context" mode where all new tabs start at 1x.
