### ISSUE TITLE
默认固定功能

### ISSUE THREAD

**Issue by NG955** [polywock/globalSpeed#323]
默认固定功能；时不时失效，需求是每个标签页单独设置速度，不想要全局都统一速度，该如何设置？是勾选启用？还是不勾选启用？
两个方案都尝试过，时不时都会失效，导致全局统一速度

**Comment by polywock** [comment]
Hello. Apologies for the long delay. Going through the old issues one by one. The pin by default option now supports a "new context" mode where all new tabs start at 1x. Not exactly what you want, but hopefully still useful. 

@harmonyharmo Tried, but difficult to have both a tab-based and url-based system. Gave up on implementing that.
