### ISSUE TITLE
can we blacklist or turn the extension off for certain sites?

### ISSUE THREAD

**Issue by aaronius25** [polywock/globalSpeed#325]
Unless Im missing something there's not a way to disable the extension for just one tab/site. Great extension, would love if this were added. thanks!

**Comment by aaronius25** [comment]
hitting the power button seems to just turn it off everywhere

**Comment by polywock** [comment]
Hello. Apologies for the long delay. Going through the old issues one by one. There's no proper blacklist function, but you can create a URL rule to turn off global speed for specific websites.

1. Create a URL rule in options page.
2. Configure the websites that will trigger the URL rule. 
3. Change URL rule's mode to "turn off".
