### ISSUE TITLE
【剪掉无声部分】

### ISSUE THREAD

**Issue by Ushnidaye** [polywock/globalSpeed#326]
增加剪掉无声部分功能。用户在播放流媒体时，自动去除低分贝部分，修正语气词
https://sspai.com/post/76939

**Comment by polywock** [comment]
Very interesting article. The method with autocut is complex so will be very hard to implement for live content. Autocut uses OpenAI's Whisper models. It would be very hard to load such heavy models to the browser so would require paying for servers or using an online API (which will probably cost money). 

|  Size  | Parameters | English-only model | Multilingual model | Required VRAM | Relative speed |
|:------:|:----------:|:------------------:|:------------------:|:-------------:|:--------------:|
|  tiny  |    39 M    |     `tiny.en`      |       `tiny`       |     ~1 GB     |      ~32x      |
|  base  |    74 M    |     `base.en`      |       `base`       |     ~1 GB     |      ~16x      |
| small  |   244 M    |     `small.en`     |      `small`       |     ~2 GB     |      ~6x       |
| medium |   769 M    |    `medium.en`     |      `medium`      |     ~5 GB     |      ~2x       |
| large  |   1550 M   |        N/A         |      `large`       |    ~10 GB     |       1x       |


To make it work, I think I will need to make or find a lightweight AI model that can be loaded on the browser, and find a way to grab video content ahead of the current position. I know it's possible for Youtube, but other sites will be harder and maybe impossible. A lot of work. 

I'm actually working on a separate extension that cuts out silent parts of videos but it will only work for Youtube. It uses a simple audio analysis to detect parts that are low-decibel. Nothing fancy like `修正语气词`.

**Comment by Ushnidaye** [comment]
我用过很多软件，其中vanced youtube的剪掉无声功能是最好用的
https://vanced.me/

**Comment by polywock** [comment]
@Ushnidaye. Hello. Thanks for the suggestion, but I think it will be too hard to implement. :smile:
