### ISSUE TITLE
Feature: Mode to auto disable if there is no video or audio detected

### ISSUE THREAD

**Issue by Nova38** [polywock/globalSpeed#329]
Feature Idea:

Have a strict mode where the extension doesn't register unless there is audio/video on the page. This would be helpful in not having to manually go in and block the extension from working on domains to stop it from interfering with keyboard shortcuts of the website.

**Comment by polywock** [comment]
Hey @Nova38. Nice to hear from you again. Good idea. I would look into making this the default behavior for media hotkeys.

**Comment by chromer030** [comment]
+1 for this vital feature, the extension is great but usually interfere with input.
From resources saving perspective (mostly memory), auto mode is highly useful.

**Comment by polywock** [comment]
Hello. Apologies for the late update. Going through the old issues one by one. I did try implementing it a strict mode but gave up due to technical barriers. The way the extension is structured makes it hard to implement this.
