### ISSUE TITLE
【快捷复读键】

### ISSUE THREAD

**Issue by Ushnidaye** [polywock/globalSpeed#332]
目前插件的复读功能不是很好用，建议增加下列快捷复复读功能：
1.【长按空格快捷单段复读】短按空格暂停，长按空格一段时间松手后，自动无限次重复长按时间内播放的音频片段
2.【长按空格加字母键分段复读】流媒体播放时，长按空格键选取需要复读的片段的同时按字母键，将每一小段视频命名。例如，按住空格的同时按住a，那么按a之后直到按下下一个字母键b的这一段音频为a段，用户需要复读a段时，只需要再按空格加a即可无限次复读a段。注意，字母按下的时间为本段的开始，下一个字母按下为本段的结束。启用字母分段后，不会像1中那样自动复读，而是按键后流媒体自动播放。
3.【长按CTRL键多段自动复读】长按CTRL键选取需要复读的片段，流媒体继续播放，再次长按CTRL键选取下一段，直到流媒体播放完毕，或者按CTRL的同时按回车结束选取复读片段后，自动播放选取的多个片段。
4.【按shift键选取多个片段】按shift键设置被选取片段的开头，再按shift选取这一段结束，第三次按选取第二段开头，以此类推，这一功能适用于截取片段较长的情况。流媒体播放完毕，或者在按shift的同时按回车结束选取复读片段，此时自动播放已经选取的片段，与3相同
1234可以同时使用
5.【启动IDM下载选中片段合成新视频导出】
按CTRL+shift+空格+回车自动下载合并所有选段；
按CTRL+空格+回车自动分别下载所有选段；
按shift+空格+选段字母+回车自动下载合并所有已选片段；
按CTRL＋空格+选段字母+回车自动分别在下载所有已选片段

**Comment by polywock** [comment]
Hello. I'm revisiting the older issues and replying to each one. I've looked into expanding this functionality but a beta tester friend advised me from over complicating the extension.
