### ISSUE TITLE
固定标签页后自动变为全局速度

### ISSUE THREAD

**Issue by caolib** [polywock/globalSpeed#336]
这个功能在一般情况下可以给每个标签页设置不同速度，但是如果你右键标签固定了一个标签，固定的那个标签就会变成全局的速度，下次打开浏览器的话就全变成全局速度了，估计是和浏览器的固定标签页有关系，希望大佬能修一下

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of today, if a tab has been pinned in Global Speed, it should be pinned again when restarting the browser.
