### ISSUE TITLE
hi，请问可以给特定YouTube Channel 调整播放速度吗？

### ISSUE THREAD

**Issue by dong-sim** [polywock/globalSpeed#340]
我想给特定YouTube Channel 调整播放速度的原因是，希望在看放松类的频道时是正常速度，在看时政、知识类的频道时是倍速。

**Comment by polywock** [comment]
Hi @dong-sim! It would be useful, but I try to not to implement website specific features. It also isn't very compatible with Global Speed's technical model. I will have to rewrite a whole bunch of code to make it a work. I'm too lazy for that 😕

**Comment by dong-sim** [comment]
I appreciate your feedback and understand your hesitation to implement website-specific features.&nbsp;Thank you for your time and consideration.
&nbsp;


dong
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月2日(星期四) 下午2:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [polywock/globalSpeed] hi，请问可以给特定YouTube Channel 调整播放速度吗？ (Issue #340)





 
Hi @dong-sim! It would be useful, but I try to not to implement website specific features. It also isn't very compatible with Global Speed's technical model. I will have to rewrite a whole bunch of code to make it a work. I'm too lazy for that 😕
