### ISSUE TITLE
How can I Speed up jquery timer counter using this item?

### ISSUE THREAD

**Issue by queevin** [polywock/globalSpeed#343]
speed up icon using jquery.timer.js

$("#countTime").timer({
  | autoTiming: true,
  | initStr:"00:00:00",
  | onStart:function(v){
  | },
  | });

**Comment by polywock** [comment]
Global Speed is designed for speeding up videos and audio. Not sure how to go about speeding up jquery's timer. I assume jQuery  just use setTimeout in the background, so you can load a script before jQuery loads that hijacks the setTimeout function before jQuery uses it.
