### ISSUE TITLE
有没有办法设置下一集的快捷键？

### ISSUE THREAD

**Issue by tudouyaer** [polywock/globalSpeed#345]

**Comment by polywock** [comment]
You can create a javascript hotkey to trigger the next episode icon/button, but each website is different. Which websites you need it for? If it's the website doesn't require an account, I can help out.

**Comment by tudouyaer** [comment]
需要账户，https://www.iqiyi.com/   https://v.qq.com/  这两个网站需要，看您能不能帮帮我。

**Comment by polywock** [comment]
You can create a javascript hotkey in Global Speed's option page. Set the javascript to the code below. 

```javascript 
(() => {
    if (document.location.host === 'www.iqiyi.com') {
        document.querySelector("iqpdiv.iqp-btn.iqp-btn-next")?.click()
    } else if (document.location.host === 'v.qq.com') {
        document.querySelector("div.txp_btn.txp_btn_next_u")?.click()
        
    }
})()
```

**Comment by tudouyaer** [comment]
举一反三，我成功获取其他网站的下一集代码了，https://www.youku.com/这个网站我找不到代码，大哥能帮帮我吗？
