### ISSUE TITLE
keyboard shortcuts to open this extension ?

### ISSUE THREAD

**Issue by eret9616** [polywock/globalSpeed#347]
How to assign a keyboard shortcut to open this extension?

I want to open this control panel by keyboardshortcut

<img width="314" alt="image" src="https://user-images.githubusercontent.com/12445095/228121394-57a5f10f-1540-4969-be56-6be7d7d43c72.png">

**Comment by polywock** [comment]
1. Go to `chrome://extensions/shortcuts` 

2. Set shortcut for **Activate the extension**
