### ISSUE TITLE
Domains Isolation

### ISSUE THREAD

**Issue by Cabus1982** [polywock/globalSpeed#351]
Is there any way to isolate domains? Because I need to slow down the Google Podcast site, but it also affects videos on YouTube 😢

**Comment by polywock** [comment]
On Chrome/edge? 

![screenshot](https://user-images.githubusercontent.com/31208859/229709591-3ef690f1-1145-48e4-b26c-b22176249fa8.png)

**Comment by Cabus1982** [comment]
I tried that, but it does not work, maybe I'm doing something wrong:

![image](https://user-images.githubusercontent.com/28199465/229758420-c36dc78a-7a7c-4b16-a445-5cba91bd6f98.png)

**Comment by polywock** [comment]
I thought you wanted Global Speed to run only on podcasts.google.com. If you want google podcast tab to be 0.25x speed while the rest of the tabs are 2x. You can pin the Google podcast tab and set speed to 0.25x.  Once a tab is pinned, any changes will be isolated for that tab. You can also enable "pin by default" in the options page. That would make it so each new tab will be pinned automatically. So if you change speed on one tab, it won't affect the other tabs.

**Comment by Cabus1982** [comment]
I can’t make it work, even if the YouTube and Google Podcast tabs are pinned, the speed change in one applies to the other 🤔

![image](https://user-images.githubusercontent.com/28199465/229807767-5936ff6a-33d9-4d4d-8e70-9bc3b488cdc4.png)

**Comment by polywock** [comment]
Hi. Current tabs won't be effected. Only new tabs will be pinned automatically.

**Comment by Cabus1982** [comment]
You are right, now it works like you mention before, thanks polywock 👍
