### ISSUE TITLE
Can you make another button for Default Speed? One for x1 (R) and another for x[custom] (G)

### ISSUE THREAD

**Issue by Jacagu** [polywock/globalSpeed#355]

**Comment by polywock** [comment]
You can create a "speed" shortcut in the options page. The speed shortcut has three modes 

+ To increase or lower speed. 

= To set to specific speed. If the speed is already that, it will revert to previous speed. 

:= Cycle between a list of speed values. 

Second one is what you want.

**Comment by Jacagu** [comment]
THANKS!

Enviado desde Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: polywock ***@***.***>
Enviado: Sunday, April 9, 2023 7:09:38 PM
Para: polywock/globalSpeed ***@***.***>
Cc: Jacagu ***@***.***>; Author ***@***.***>
Asunto: Re: [polywock/globalSpeed] Can you make another button for Default Speed? One for x1 (R) and another for x[custom] (G) (Issue #355)


You can create a "speed" shortcut in the options page. The speed shortcut has three modes

  *   To increase or lower speed.

= To set to specific speed. If the speed is already that, it will revert to previous speed.

:= Cycle between a list of speed values.

Second one is what you want.
