### ISSUE TITLE
This site is invalid

### ISSUE THREAD

**Issue by qdxiixbp** [polywock/globalSpeed#356]
The site has just updated its page style and appears to recognize only pre-load animations, not videos in video preview page.
https://pan.baidu.com/
Thanks for your work.

**Comment by polywock** [comment]
Hello. Still works for me. What's your OS, OS version, browser, and browser version? Also, can you share me a link to the video.

**Comment by qdxiixbp** [comment]
Windows 11-22H2 -22621.1413
edge112.0.1722.39
https://pan.baidu.com/s/1hCHtLsgB0u0Qa6HKPpIYaQ?pwd=j4qt Extract code: j4qt 
Thinks a lot!

**Comment by polywock** [comment]
Already have an account. Works for me on sharing page and if saved. I suspect it's an update that's being rolled out to some users. Big websites don't take risks with updates, they try it out on some people first. 

By the way, what's your OS version and browser version. Another user with same issue has Mac/Chrome, maybe we can spot patterns.

**Comment by qdxiixbp** [comment]
Windows 11-22H2-22621.1413
edge112.0.1722.39

**Comment by polywock** [comment]
It was a gradual rollout so some users had the problem first. I implemented a workaround in the latest update (2.9.993). It might take up to a week for update to be approved on the Chrome, Edge, Firefox store. For now, you can try manually loading it.  If you try this, let me know if it works. 

[packed.zip](https://github.com/polywock/globalSpeed/files/11271265/packed.zip) (Chrome, Edge version)

1. Download packed.zip and extract the folder. 
2. open extensions page, chrome://extensions 
3. Disable the original Global Speed. 
4. Enable dev mode in top right of page. 
5. Click "load unpacked" in top left of page and load the folder.
