### ISSUE TITLE
2023年4月11日，刷新才发现百度云的视频播放界面发生了改变，现在已经没法加速了，希望能修改

### ISSUE THREAD

**Issue by APTX4869-maker** [polywock/globalSpeed#357]

**Comment by APTX4869-maker** [comment]
我的系统是mac os 13.3.1
浏览器是 Chrome 版本 112.0.5615.49（正式版本） (arm64)
global speed在我的浏览器版本是2.9.992
链接: https://pan.baidu.com/s/1Ma4lFOaYESZfs1LMvGA2VA 提取码: xbem 复制这段内容后打开百度网盘手机App，操作更方便哦 这是我的视频播放链接 请试一下

**Comment by wan8li** [comment]
遇到了一样的问题，其他网站正常，百度云不可用。希望早日解决。

**Comment by polywock** [comment]
Still works for me. Maybe it's a gradual rollout. Will look into it.

**Comment by yan1103542853** [comment]
对呀，现在这个插件不能使用了

**Comment by sillyducCk** [comment]
2023.4.19  浏览器：Microsoft Edge 版本 112.0.1722.48 (正式版本) (64 位)   百度网盘网页版打开视频在左边，加速了也还是原速   请问还有什么方法可以倍速播放

**Comment by sillyducCk** [comment]
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2023/‎3/‎23
操作系统版本	22621.1555

**Comment by polywock** [comment]
It was a gradual rollout so some users had the problem first. It should be fixed in the latest update (2.9.993). It might take up to a week for update to be approved on the Chrome, Edge, Firefox store. For now, you can try manually loading it.  

[packed.zip](https://github.com/polywock/globalSpeed/files/11271265/packed.zip) (Chrome, Edge version)

1. Download packed.zip and extract the folder. 
2. open extensions page, chrome://extensions 
3. Disable the original Global Speed. 
4. Enable dev mode in top right of page. 
5. Click "load unpacked" in top left of page and load the folder.  

If you try this, let me know if it works.

**Comment by wan8li** [comment]
非常感谢。
我分别在Edge、Chrome中手动加载这个新版本。但仅在Chrome中百度网盘可以正常使用倍数，Edge中仍然不可使用。
我的Edge版本为版本 112.0.1722.48 (正式版本) (64 位)
我的Chrome版本为版本 112.0.5615.121（正式版本） （64 位）












At 2023-04-19 17:15:41, "polywock" ***@***.***> wrote:

It was a gradual rollout so some users had the problem first. It should be fixed in the latest update (2.9.993). It might take up to a week for update to be approved on the Chrome, Edge, Firefox store. For now, you can try manually loading it.

packed.zip (Chrome, Edge version)

Download packed.zip and extract the folder.
open extensions page, chrome://extensions
Disable the original Global Speed.
Enable dev mode in top right of page.
Click "load unpacked" in top left of page and load the folder.

If you try this, let me know if it works.

**Comment by bobo-fish** [comment]
> It was a gradual rollout so some users had the problem first. I implemented a workaround in the latest update (2.9.994). It might take up to a week for update to be approved on the Chrome, Edge, Firefox store. For now, you can try manually loading it. If you try this, let me know if it works.
> 
> [packed.zip](https://github.com/polywock/globalSpeed/files/11271527/packed.zip) (Chrome, Edge version)
> 
> 1. Download packed.zip and extract the folder.
> 2. open extensions page, chrome://extensions
> 3. Disable the original Global Speed.
> 4. Enable dev mode in top right of page.
> 5. Click "load unpacked" in top left of page and load the folder.

chrome：版本 112.0.5615.138（正式版本） （64 位）可以使用。非常感谢。

**Comment by polywock** [comment]
@wan8li Does this version work on Edge?  


[packed.zip](https://github.com/polywock/globalSpeed/files/11271527/packed.zip)  (Chrome, Edge version)

**Comment by Ccy2858380551** [comment]
刚进去的主页面百度网盘有一个回到旧版按钮，可以倍速，新版的网页似乎不能倍速播放，edge和goog
le浏览器新版都不能倍速播放

**Comment by wan8li** [comment]
这个版本可以在Edge上正常使用。非常感谢，辛苦你了。













At 2023-04-20 01:40:42, "polywock" ***@***.***> wrote:

@wan8li Does this version work on Edge?

packed.zip (Chrome, Edge version)

**Comment by hxiaope** [comment]
> 

thanks， it's work my computer edge ver. 112.0.1722.48

**Comment by hxiaope** [comment]
> 这是一个逐步推出的过程，因此一些用户首先遇到了问题。我在最新更新 （2.9.994） 中实施了解决方法。Chrome、Edge、Firefox 商店的更新可能需要长达一周的时间才能获得批准。现在，您可以尝试手动加载它。如果您尝试此操作，请告诉我它是否有效。
> 
> [打包.zip](https://github.com/polywock/globalSpeed/files/11271527/packed.zip)（Chrome，边缘版本）
> 
> 1. 下载打包.zip并解压缩文件夹。
> 2. 打开扩展页面，chrome://extensions
> 3. 禁用原始全局速度。
> 4. 在页面右上角启用开发模式。
> 5. 单击页面左上角的“加载解包”并加载

> It was a gradual rollout so some users had the problem first. I implemented a workaround in the latest update (2.9.994). It might take up to a week for update to be approved on the Chrome, Edge, Firefox store. For now, you can try manually loading it. If you try this, let me know if it works.
> 
> [packed.zip](https://github.com/polywock/globalSpeed/files/11271527/packed.zip) (Chrome, Edge version)
> 
> 1. Download packed.zip and extract the folder.
> 2. open extensions page, chrome://extensions
> 3. Disable the original Global Speed.
> 4. Enable dev mode in top right of page.
> 5. Click "load unpacked" in top left of page and load the folder.

thanks, it's work my Edge ver. 112.0.1722.48

**Comment by croissantwithcheese** [comment]
hello, I download this package but it doesn't work and warns me there is an error: "Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details."
my chrome version is 版本 113.0.5672.93（正式版本） （64 位）. thanks for ur help.

> 非常感谢。 我分别在Edge、Chrome中手动加载这个新版本。但仅在Chrome中百度网盘可以正常使用倍数，Edge中仍然不可使用。 我的Edge版本为版本 112.0.1722.48 (正式版本) (64 位) 我的Chrome版本为版本 112.0.5615.121（正式版本） （64 位） At 2023-04-19 17:15:41, "polywock" ***@***.***> wrote: It was a gradual rollout so some users had the problem first. It should be fixed in the latest update (2.9.993). It might take up to a week for update to be approved on the Chrome, Edge, Firefox store. For now, you can try manually loading it. packed.zip (Chrome, Edge version) Download packed.zip and extract the folder. open extensions page, chrome://extensions Disable the original Global Speed. Enable dev mode in top right of page. Click "load unpacked" in top left of page and load the folder. If you try this, let me know if it works. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by hxiaope** [comment]
来信已收到，谢谢！

**Comment by croissantwithcheese** [comment]
hello, I download this package but it doesn't work and warns me there is an error: "Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details."
my chrome version is 版本 113.0.5672.93（正式版本） （64 位）. thanks for ur help.



> It was a gradual rollout so some users had the problem first. I implemented a workaround in the latest update (2.9.994). It might take up to a week for update to be approved on the Chrome, Edge, Firefox store. For now, you can try manually loading it. If you try this, let me know if it works.
> 
> [packed.zip](https://github.com/polywock/globalSpeed/files/11271527/packed.zip) (Chrome, Edge version)
> 
> 1. Download packed.zip and extract the folder.
> 2. open extensions page, chrome://extensions
> 3. Disable the original Global Speed.
> 4. Enable dev mode in top right of page.
> 5. Click "load unpacked" in top left of page and load the folder.

**Comment by polywock** [comment]
@ croissantwithcheese Hello. That's just a warning and can be ignored. By the way, you no longer need to manually load the package. Already approved on the Edge web store and Chrome. It should also already be on third party extension websites (make sure to choose 2.9.995, the latest version).

**Comment by hxiaope** [comment]
来信已收到，谢谢！
