### ISSUE TITLE
第一次用，请问“捕获”是什么功能？另外，有没有视频截图功能？

### ISSUE THREAD

**Issue by pipashu** [polywock/globalSpeed#358]
试了一下捕获，但是没看出作用。开始以为是视频截图。

**Comment by polywock** [comment]
1. Capture is to apply audio effects (pitch shift, volume boost, etc) to the tab. Useful for listening to music in different pitch. 
2. No, screenshot feature.

**Comment by pipashu** [comment]
> Hi. Capture is to apply audio effects (pitch shift, volume boost, etc) to the tab. Useful for listening to music in different pitch. There is no screenshot feature.

thanks🙂
