### ISSUE TITLE
Can I set the state off when I am browsing specific website?

### ISSUE THREAD

**Issue by TangbohuDianPaoZhang** [polywock/globalSpeed#359]
Hi, I want to know whether I can create a rule so that when I am on some website, the state of extension can be set off, thank you.

**Comment by polywock** [comment]
Hello. Let me know if you have trouble setting it up. 

1. Open options page and scroll down to URL rules section. 
2. Create new URL rule. 
3. Change the mode to "state" and set power icon (⏻) to off.  
4. Click -- 0 --, to add a new URL condition. (add the domain of specific website here)

**Comment by TangbohuDianPaoZhang** [comment]
Thanks!
