### ISSUE TITLE
Option to import,export the options.html

### ISSUE THREAD

**Issue by sournail** [polywock/globalSpeed#36]
That would help with using it on multiple browsers.

**Comment by polywock** [comment]
Similar request from #11. Since there is a demand for this. I'll look into adding it again.

**Comment by profcaju** [comment]
I came here to write exactly the same suggestion. I am testing various chromium flavours in Windows and MacOS, and each time I install a new browser, I have to copy all my customised options manually. And an option to export/import these options will be a very good improvement.
Kind regards,

**Comment by polywock** [comment]
Implemented in the latest update (export/import and copy/paste). There may be some bugs. Let me know if you experience any issues.

![](https://user-images.githubusercontent.com/31208859/99410168-297fb800-28c0-11eb-8b35-a58e4a8a889a.png)
