### ISSUE TITLE
方便添加 暂停/播放 键吗？

### ISSUE THREAD

**Issue by Bqrerr** [polywock/globalSpeed#360]
插件很好用，感谢。但我观看的视频不能用空格暂停/播放视频，如果插件能加一个 暂停/播放 的快捷方式就好了，再次感谢原作者

**Comment by polywock** [comment]
Hello. Glad you find the extension helpful. You can create a "pause" shortcut in the options page. By default, news shortcuts will be set to "NoKey", click on it and press space to change it.
