### ISSUE TITLE
Discovered on April 21, 2023 that it cannot accelerate the speed of Baidu Netdisk web version videos（pan.baidu.com）. Wish your update!

### ISSUE THREAD

**Issue by sunshineflymeat** [polywock/globalSpeed#362]
![image](https://user-images.githubusercontent.com/92577771/233579035-3574f686-25d1-45f4-a34a-ea7cebcfc7ad.png)

**Comment by polywock** [comment]
Hello. Issue fixed on latest update (2.9.995). Chrome Web Store approved the update already, but for Edge, Firefox store it might take up to a week. 

[packed.zip](https://github.com/polywock/globalSpeed/files/11299249/packed.zip)

1. Download packed.zip and extract the folder. 
2. open extensions page, chrome://extensions 
3. Disable the original Global Speed. 
4. Enable dev mode in top right of page. 
5. Click "load unpacked" in top left of page and load the folder.
