### ISSUE TITLE
能不能出一个白名单屏蔽掉不需要的网页

### ISSUE THREAD

**Issue by ghost** [polywock/globalSpeed#365]
排除某网站，在某网站不生效而不是关闭插件，能不能做一个白名单屏蔽某些网站

**Comment by 88la** [comment]
我在FAQ里找到了一个方法，如下:)
如何阻止某些网站上的热键？
在此示例中，我将屏蔽游戏流媒体网站 stadia.com 的热键。
1. 单击-- 0 --“快捷方式编辑器”部分右下角的按钮。在这里，我们可以添加使热键保持启用状态所需满足的条件。
3. 因为我们希望热键仅在网站不是“stadia.com”时保持启用状态。如果 URL 包含“stadia.com”关键字，请添加不等于条件[!=] 。
注意：如果添加多个条件，则需要指定是满足所有条件还是只满足一个条件。如果我们希望仅在网站不是[ != ] stadia.com 并且不是[ != ] miniclip.com 时才启用热键，我们将选择“全部 (AND)”选项。
另一方面，如果我们希望仅当网站的 URL 匹配[ == ]特定网站（如 youtube.com 或 twitch.tv）时才启用热键，我们只需要满足一个条件，因此选择“any （或）”选项。
注意：您还可以将 URL 条件添加到特定的热键，方法是将鼠标悬停在热键项上并单击右上角的红色按钮。

**Comment by leiman147** [comment]
> 我在FAQ里找到了一个方法，如下:) 如何阻止某些网站上的热键？ 在此示例中，我将屏蔽游戏流媒体网站 stadia.com 的热键。
> 
> 1. 单击-- 0 --“快捷方式编辑器”部分右下角的按钮。在这里，我们可以添加使热键保持启用状态所需满足的条件。
> 2. 因为我们希望热键仅在网站不是“stadia.com”时保持启用状态。如果 URL 包含“stadia.com”关键字，请添加不等于条件[!=] 。
>    注意：如果添加多个条件，则需要指定是满足所有条件还是只满足一个条件。如果我们希望仅在网站不是[ != ] stadia.com 并且不是[ != ] miniclip.com 时才启用热键，我们将选择“全部 (AND)”选项。
>    另一方面，如果我们希望仅当网站的 URL 匹配[ == ]特定网站（如 youtube.com 或 twitch.tv）时才启用热键，我们只需要满足一个条件，因此选择“any （或）”选项。
>    注意：您还可以将 URL 条件添加到特定的热键，方法是将鼠标悬停在热键项上并单击右上角的红色按钮。

我试了 却不起作用 这是为什么

**Comment by polywock** [comment]
@leiman147 Can you send me your config info? In the options page, you can press the copy button near the export (导出) button and send it to me. 

![img](https://github.com/polywock/globalSpeed/assets/31208859/4b203c39-356f-4d22-8e93-4045e73372b0)

**Comment by leiman147** [comment]
here

**Comment by polywock** [comment]
To turn off Global Speed if URL contains`live.yj1211.work`.

1. Turn URL rule into state = off  (状态 = 关闭) 
![imgg](https://github.com/polywock/globalSpeed/assets/31208859/85458c64-d191-422f-b701-dec2f1555e67)

2. Change URL condition to if URL contains `ive.yj1211.work`.  
![imgg](https://github.com/polywock/globalSpeed/assets/31208859/91faed21-b743-48ec-bd19-ae282dd741e4)



You can import this updated one as well. 

[Global Speed - Sat Jun 03 2023 (2).json.zip](https://github.com/polywock/globalSpeed/files/11644473/Global.Speed.-.Sat.Jun.03.2023.2.json.zip)

**Comment by leiman147** [comment]
> 我真的应该简化这个过程，是很糟糕的用户体验。
> 
> 把关掉全球的速度如果 URL包含`live.yj1211.work`.
> 
> 1. 将 URL 规则变为状态 = 关闭（状态 = 关闭）
>    ![imgg](https://user-images.githubusercontent.com/31208859/243141385-85458c64-d191-422f-b701-dec2f1555e67.png)
> 2. 更改网址状况如果网址包含 `ive.yj1211.work`.
>    ![imgg](https://user-images.githubusercontent.com/31208859/243141521-91faed21-b743-48ec-bd19-ae282dd741e4.jpg)
> 
> 你可以进口这也更新了一个。
> 
> [全球速度 - 2023 年 6 月 3 日星期六 (2).json.](https://github.com/polywock/globalSpeed/files/11644473/Global.Speed.-.Sat.Jun.03.2023.2.json.zip)

it work! thank you!
