### ISSUE TITLE
Responsible Methods for Speed Control

### ISSUE THREAD

**Issue by skarussel** [polywock/globalSpeed#366]
Hey Guys, thank you so much for creating this amazing Extension.

I was wondering, which functions of your sourcecode are responsible for speeding up or delaying a tab? Would help a lot if you could name the function names and the files in which they occur!

I wanna integrate the extension into a private side project and i am not super familiar with JS.

**Comment by polywock** [comment]
Hello. You can check out [Video Speed Controller](https://github.com/igrigorik/videospeed) on Github. Source code is much easier to read and is more helpful for the video speed aspect. As for delaying a tab's audio, I use the TabCapture API to capture the tab's audio, turn it into a MediaStreamSource and pipe it through a Delay Node. 

https://developer.chrome.com/docs/extensions/reference/tabCapture/

https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamSource 

https://developer.mozilla.org/en-US/docs/Web/API/DelayNode
