### ISSUE TITLE
【建议】关于全局速度的问题和想法

### ISSUE THREAD

**Issue by wushu037** [polywock/globalSpeed#367]
# 问题
现在提供的"默认固定"功能有一些问题：
1. 浏览器勾选了"启动时打开上次浏览的网页"，当重启浏览器后，所有的页面上的 globalSpeed 又都回到了全局模式
2. 只有新打开的标签页才会使用"默认固定"，对于已有标签页，用户还是需要手动点击固定
3. 明明没有勾选继承全局，但还是会继承全局的速度

这对于我这种仅使用此插件用作(非全局)速度控制、快捷键操作的用户造成困扰
(真的有那么多人会有"全局速度"的需求吗？)

# 一些想法
(但愿作者读起来不会那么累)

本插件目前的设计是"每个页面的速度默认都是共享(全局)的"，然后提供一个"默认固定"选项。我理解这是本插件叫做`globalSpeed`的原因。

然而本插件的强大不止于此，或许它更适合叫做"video controller"，相信很多用户都感受到了这一点。
但如此一来，就不能以`global`为主了。

一个更符合使用习惯的设计思路应该是："每个页面的速度默认都是独立的"。
比如，通常只有某个视频的速度不合适时，用户才会想着去调节它的速度。而不是为所有的其它网页视频都调整速度。

再此基础上，再去做"全局速度"功能，有一个简单粗暴的UI设计：
![image](https://github.com/polywock/globalSpeed/assets/61787040/33b12996-1105-4c39-9d40-9765e0019ab2)

# 最后
与此类似的问题，在issue中非常常见。即使本插件没有如此优秀的快捷键功能，而只是单纯地提供"全局速度"，也避免不了现在的情况：那就是很多用户都把本插件作为一个简单的速度控制器，而非"全局"速度控制器

在目前的设计下，若用户上一次只是微调了某个视频(如1.25倍速)，而后去沉浸地享受某个经典电影时(另一个页面)，可能不会第一时间察觉到异样，但已经影响了用户的观影感受。

感谢阅读！

**Comment by polywock** [comment]
> 浏览器勾选了"启动时打开上次浏览的网页"，当重启浏览器后，所有的页面上的 globalSpeed 又都回到了全局模式

Issue I've been procrastinating working on. Will get it. 😅

> 只有新打开的标签页才会使用"默认固定"，对于已有标签页，用户还是需要手动点击固定

For this, maybe I could pin all existing tabs when they enable it. Not too sure about this. 

> 明明没有勾选继承全局，但还是会继承全局的速度

Weird. Functionality seems to work for me. For example, Global context is 1x. Current tab is 0.25x. If I open a new tab or open link in new tab, the speed becomes 0.25. 

> 然而本插件的强大不止于此，或许它更适合叫做"video controller"，相信很多用户都感受到了这一点。
但如此一来，就不能以global为主了。

 If I can go back in time, I would've named it local speed or something, but I think it's too late now. Bad for search engine optimization as most people look up "global speed" to find this extension. 


User experience needs a lot of work. Thank you for the suggestions.

**Comment by wushu037** [comment]
> If I can go back in time, I would've named it local speed or something, but I think it's too late now. Bad for search engine optimization as most people look up "global speed" to find this extension.
> 
> User experience needs a lot of work. Thank you for the suggestions.

或许可以调查一下：通过搜索"global speed"来找到这个扩展的占比是？
我是如何搜索到这个插件的呢：video controller 、video speed、speed、视频速度    这样最终才找到本插件
通过issue可以看出来，大量大部分用户并不关心 global ，甚至为此苦恼

我试用了多个 video controller 拓展，目前还没有发现功能和设计比本插件更全面和简洁的。
重新起一个项目，在此基础上修修改改或许并不费时，最难的是决定何时开始，对此我也深有体会。

祝项目越来越好。

**Comment by 2077505931** [comment]
请问现在可以每个标签页默认'local speed'了吗？

**Comment by 4pricity** [comment]
你好，我得到了相同的问题！在此向您反馈！
在我的一台笔记本电脑上（Y7000P），默认固定功能工作良好，当我重启浏览器时，每个标签页仍是固定的。
然而，当我把配置导入到我的另一台设备（surface go 3），我遇到了和 @wushu037 相同的问题，每次重启浏览器时，每个标签页都是全局状态，即使我开启了默认固定功能。
我想我会观察两个设备浏览器的设置，也许这是造成此bug的原因。

**Comment by 4pricity** [comment]
不知道为什么，该现象已经消失了，此插件现在在我的surface go上工作良好
