### ISSUE TITLE
能不能添加只针对特定网站的功能

### ISSUE THREAD

**Issue by leiman147** [polywock/globalSpeed#369]
现在一个速度适应到所有视频和音频，还需要手动再改回来

**Comment by polywock** [comment]
You can turn on "Pin by default" in options page so all new tabs get pinned automatically. If a tab is pinned, the speed change will only effect that tab.

**Comment by leiman147** [comment]
> You can turn on "Pin by default" in options page so all new tabs get pinned automatically. If a tab is pinned, the speed change will only effect that tab.

我试了，那只针对一个标签页，不能针对特定的网站

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of today, the URL rules are much simpler to use so I can recommend them as solutions. You can create a URL rule that sets the speed for a particular tab.
