### ISSUE TITLE
Global keyboard setup not work

### ISSUE THREAD

**Issue by pigpigfour** [polywock/globalSpeed#37]
I want to setup a Global Key by Chrome, but it didnt work, I dont know why

**Comment by pigpigfour** [comment]
![image](https://user-images.githubusercontent.com/71087190/93504687-68d76a00-f94c-11ea-9205-c8f9202dbf22.png)

**Comment by polywock** [comment]
You configured it in the Global Speed options page? 


This might not help, but I made a video on [how to set it up](https://www.youtube.com/watch?v=EZA-TnVAyDo).

**Comment by pigpigfour** [comment]
WOW! Amazing! 

HAHAHAH，From？


U see, I have already setup at that

**Comment by pigpigfour** [comment]
HELLO

I follow your step, it work!!!

Really don’t know why…

Buy worked!

Thank you!

**Comment by polywock** [comment]
Great! Global keys are powerful. But, they're also buggy. Many key combinations don't work. Sometimes while testing. I had to restart Chrome to make it work again. 

Feel free to reopen the issue if you're having issues again.

**Comment by pigpigfour** [comment]
Hello，Sir
I don’t know why my app don’t have this option???

**Comment by polywock** [comment]
![](https://user-images.githubusercontent.com/31208859/97098081-5c32e980-164f-11eb-8321-cead369c4ebe.png)

This thing? Weird, it should show all videos on the open tab. Maybe your Global Speed version is outdated. The current version is 2.6.4. You may also have disabled it in the options page. In english, there's an option called "hide media list" that hides it. You may have enabled that.

**Comment by pigpigfour** [comment]
My GS version is 2.6.4.

follow your step，but it also don’t show~~

**Comment by polywock** [comment]
Could you send me a screenshot (while a video is playing)?
