### ISSUE TITLE
数字快捷键调整倍速失效

### ISSUE THREAD

**Issue by hyusho** [polywock/globalSpeed#373]
速度的快捷键我设置的是数字，以前可以用，现在没作用了

**Comment by polywock** [comment]
Hello. Have you tried uninstalling and reinstalling Global Speed?

**Comment by hyusho** [comment]
我试了，但是任然没有用。我猜测可是是因为我对使用的浏览器arc进行了一些客制化的设定，使得按键被占用吧。谢谢您的回复。
