### ISSUE TITLE
增益bug

### ISSUE THREAD

**Issue by MiracleYyds** [polywock/globalSpeed#374]
1、增益默认没有启动
2、当手动启动增益后，全屏幕播放失效，变成网页内全屏
3、测试链接 https://cokemv.me/vodplay/5537-2-1.html

**Comment by polywock** [comment]
Hello. For audio effects (gain, pitch shift, etc), I use the TabCapture API. This API is very restricted and the user cannot enter fullscreen when the tab's audio is being manipulated. Instead it enters partial fullscreen. 

The other major restriction is that it cannot be auto-activated. It must be user initiated. To conveniently activate it, open Global Speed's option page and create a Capture hotkey (捕获). It's a global hotkey, so you must go to `chrome://extensions/shortcuts` to configure it. 

Let me know if you have problems setting it up.

**Comment by MiracleYyds** [comment]
@polywock  Thanks for your clarification, I have manually activated the gain by setting the hotkey in edge browser

**Comment by polywock** [comment]
@MiracleYyds Forgot to mention. There is a workaround to go fullscreen while using gain, pitch shift, etc. First go fullscreen and then use shortcut key to activate the capture (捕获).

**Comment by MiracleYyds** [comment]
Yeah, that's how I set the hotkeys, haha
