### ISSUE TITLE
能否添加教程？

### ISSUE THREAD

**Issue by fengxuanzs** [polywock/globalSpeed#375]
扩展上只有按键，没有详细的教程，有点功能不会用

**Comment by polywock** [comment]
Hi. There is a tutorial in English.

**Comment by polywock** [comment]
Hi. Sorry, only tutorial right now is in English. Let me know if you cannot access Youtube, I will re-host it somewhere else.  

https://www.youtube.com/watch?v=5x8Kg8ahxjM
