### ISSUE TITLE
希望能够增加一个自动播放下一集的功能

### ISSUE THREAD

**Issue by shary20** [polywock/globalSpeed#378]
希望能够增加一个自动播放下一集的功能

**Comment by polywock** [comment]
Hard feature to implement as most websites handle things differently. A feature like this tends to become a maintenance nightmare.

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of today, this feature isn't supported and probably won't be. This is a common request but very hard to implement. All websites handle next/previous differently so a generalized solution isn't feasible.
