### ISSUE TITLE
Can you add more comments to the EQ adjustment options?

### ISSUE THREAD

**Issue by baiwumiao** [polywock/globalSpeed#379]
like 10 20 30 and their suboption : 1965, etc. These maybe help us understand the meaning of the EQ adjustment option

**Comment by polywock** [comment]
10-20-30 is just how many EQ bands you want. For 10, the range is split into 10 bands. For 30, the range is split into 30 bands. More bands, more control. 

I was too lazy to figure out nice presets so just copied the EQ presets from Adobe Audition (1965, Rattle the Trunk, etc). The presets don't mean anything and is just a preset for ease of use.

**Comment by polywock** [comment]
The POW slider is to control intensity of the EQ effect. Higher the POW, the stronger the EQ adjustment.
