### ISSUE TITLE
Cannot type on a few websites

### ISSUE THREAD

**Issue by NayamAmarshe** [polywock/globalSpeed#38]
https://www.tweetbinder.com/blog/hashtag-counter/

Cannot type in the input boxes on a few boxes, the Global Speed plugin detects a video and doesn't let you type the text.

**Comment by polywock** [comment]
Thanks for letting me know. The extension doesn't actually check if there's a video. The shortcuts are triggered in all cases, except if you're typing in a text field. For that website, the text field was nestled within a ShadowRoot (think hidden layer). I've just implemented a fix for this edge case.  It should go live in the next version (might take a while to publish). 

Usually in these cases. I like to use the `state` shortcut (Shift-Q by default) to temporarily disable the extension. Once disabled, all shortcuts except the `state` shortcut stop working. You can finish typing what you want. Once done, use the `state` shortcut again to reenable the plugin (and the rest of the shortcuts).
