### ISSUE TITLE
edge浏览器开b站画面来回卡

### ISSUE THREAD

**Issue by CharlesLee78** [polywock/globalSpeed#380]
画面会出现来回正倒放问题
Microsoft Edge版本 114.0.1823.43 (正式版本) (64 位)
b站播放策略如下
![image](https://github.com/polywock/globalSpeed/assets/29223944/09751105-4290-494d-bf4e-47f2ba9fe6d0)

**Comment by polywock** [comment]
Hello.  Try to disable Global Speed to confirm if it's the cause. If it is the cause, try to reinstall Global Speed. If that doesn't fix the issue, try disabling all your other extensions to see if there's some conflict going on. 

Let me know if the issue still persists.
