### ISSUE TITLE
浏览器拓展的页面没法进行倍速设置,希望重新捕获下实践

### ISSUE THREAD

**Issue by jdAction** [polywock/globalSpeed#383]
extension://bcneiehcbgahghfmgigmblcgkhihehad/listen1.html
这是 listen1的插件 打开插件后是一个扩展页面 但是没法启用倍速

**Comment by polywock** [comment]
Hi. No extension can run inside another extension's file. Can only run https, http, and local files (if user enables it).

**Comment by jdAction** [comment]
Can we overcome this problem? If it is a limitation of the browser itself, can you contact the official of Edge for functional development?

**Comment by polywock** [comment]
Hi. You can use this bookmarklet on listen1. Create any bookmark and change the URL to the code below. The name can be anything. 

```javascript
javascript:(() => {
    const speed = parseFloat(prompt("Speed? ", 2));
    document.querySelectorAll("video, audio").forEach(v => { v.playbackRate = speed });
})()
```
