### ISSUE TITLE
边缘鼠标滚轮

### ISSUE THREAD

**Issue by Enchantedz** [polywock/globalSpeed#384]
全屏播放时在左边和下边滚动鼠标滚轮时增加倍速有效而减少倍数无效。希望能有鼠标滚轮调整倍速的开关

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of today, this feature isn't supported and probably won't be. Mouse wheel controls are generally considered bad practice.
