### ISSUE TITLE
暗色模式下，固定按钮在点下后，颜色看不出太大变化

### ISSUE THREAD

**Issue by Brucevlw** [polywock/globalSpeed#385]
暗色模式下，固定按钮在点下后，颜色看不出太大变化

**Comment by polywock** [comment]
Hi. Can you explain more about the issue? Pinning should not affect the dark mode, as the dark mode only changes the appearance of Global Speed's interface. Unless, you're talking about the video filters like (invert, brightness, etc)?

**Comment by leewwang** [comment]
Sorry for not describing it accurately enough，let me illustrate it with screenshot.

The "dark theme" is off——when the “pin tab” is pressed, its color changes very significantly；（see figure 1）
The "dark theme" is on——when the “pin tab” is pressed, its color changes not significantly；（see figure 2）


ps，I have color weakness，perhaps it caused me to have a biased judgment.




1521704263
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月5日(星期三) 凌晨2:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] 暗色模式下，固定按钮在点下后，颜色看不出太大变化 (Issue #385)





 
Hi. Can you explain more about the issue? Pinning should not affect the dark mode, as the dark mode only changes the appearance of Global Speed's interface. Unless, you're talking about the video filters like (invert, brightness, etc)?

**Comment by polywock** [comment]
Hi. Have you sent this comment via email? The images (figure 1 and 2) don't show up that way. To upload the images, go directly to Github, and drag it into the comment box.

**Comment by leewwang** [comment]
![图片](https://github.com/polywock/globalSpeed/assets/64349788/217f18df-00ba-4a79-90be-0726de1fac55)
![图片](https://github.com/polywock/globalSpeed/assets/64349788/dbd698c6-1499-4646-93b7-96522ebf47e7)

**Comment by polywock** [comment]
Interesting. For me, the color looks very different. It turns from white/silver to a vibrant green color. Do you have Deuteranopia (green color weakness)? 

I will work on the color-scheme in the next update, but that might take a while (sorry for that).

**Comment by polywock** [comment]
Hello. Apologies for the late update. Going through the old issues one by one. Hopefully the issue is fixed as of today. Let me know if the colors are still non-differentiable.
