### ISSUE TITLE
希望增加镜面翻转

### ISSUE THREAD

**Issue by raevi613** [polywock/globalSpeed#386]

**Comment by leewwang** [comment]
这功能已经有了。把FX过滤器选“背景”和“Y轴旋转”，设置一个快捷键，参数选0和180，以后按快捷键就能快速实现Y轴的镜面翻转了。

**Comment by raevi613** [comment]
> 这功能已经有了。把FX过滤器选“背景”和“Y轴旋转”，设置一个快捷键，参数选0和180，以后按快捷键就能快速实现Y轴的镜面翻转了。

好的，十分感谢🙇‍
