### ISSUE TITLE
能否增加一个设置，当我自己修改当前页面倍速时取消插件的强制修改，而其他界面继续保持设置的倍速

### ISSUE THREAD

**Issue by bingyunhe** [polywock/globalSpeed#387]
部分视频我不需要倍速观看，或者需要其他的倍速。
目前是我自己单独修改视频的倍速后插件会强制把倍速改成我在插件内设置好的倍速。
我希望在我手动修改倍速之后插件关闭强制修改倍速。

**Comment by 13913585904** [comment]
> 

是的，但总觉得不大方便，并且对于一些初学者不大友好，我也建议要有针对标签页的倍速。

**Comment by JinghuaOriental** [comment]
右键扩展->这里可以读取和更改站点数据->选择“单击扩展时”，该页面即被加入黑名单，其他页面仍可正常使用
