### ISSUE TITLE
If you add a live captioning feature, you will be Buddha！

### ISSUE THREAD

**Issue by ShelterWFF** [polywock/globalSpeed#389]
If you add a live captioning feature, you will be Buddha！

**Comment by polywock** [comment]
I have considered it, but I decided being Buddha is too expensive and also too much work. 

1. Chrome and Edge have already added a live captioning feature. It's limited to a few languages right now, but will expand. 
2. To do live captioning, I will have to either use a speech to text service (most cost money), or use a public model. 
3. To use a speech to text model, which most aren't suited for live captioning.  The model will have to either be hosted on a server (cost money), or included in Global Speed's package, which will inflate the size and scare away users. 

You know the saying "all roads lead to Rome"? In this case, all roads lead to money or a lot of work.
