### ISSUE TITLE
Speed multiplier gets reset on Spotify

### ISSUE THREAD

**Issue by ShrirajHegde** [polywock/globalSpeed#39]
### Spotify web player on [open.spotify.com](https://open.spotify.com/) works temporarily, whenever the song shifts, the speed multiplier gets reset.
 **(Still shows right multiplier in the UI)**

#### Requires manual speed setting for each song. (switching back and forth makes it work again for one song)

**Comment by polywock** [comment]
Apologies for the late reply. Busy with work. Fixed in the latest version. Should be published today or tomorrow for Chrome/Firefox, and 2-4 days for Microsoft Edge store.  Thanks for the feedback.
