### ISSUE TITLE
web page full screen playback

### ISSUE THREAD

**Issue by weineo** [polywock/globalSpeed#390]
请问能添加“网页全屏播放”的功能吗，在很多情况下，“网页全屏”的体验会好于常见的“全屏播放”功能。我在下方展现了在中国常用的网站bilibili上实现的效果。其保留了浏览器上方的标签页和功能栏的展现，只占据了网页的部分。
May I ask if it is possible to add the feature of "web page full screen playback"? In many cases, the experience of "web page full screen" will be better than the common feature of "full screen playback". I have shown the results achieved on Bilibili, a commonly used website in China, below. It retains the display of the tabs and function bars above the browser and only occupies a portion of the webpage.
![image](https://github.com/polywock/globalSpeed/assets/60565258/3890608e-d086-42d1-8b29-afee9bb39abf)

**Comment by polywock** [comment]
Hi. Partial full screen is possible right now as a secret feature. Are you on Edge or Chrome? If so, you can go to the audio effects panel and click "capture". Capturing the tab's audio allows for special audio effects like pitch shift, but it also disables full screen mode (instead the video goes partial fullscreen like Bilibili.  

![im1](https://github.com/polywock/globalSpeed/assets/31208859/ffd94d4c-d552-40be-b6ed-2f1e00b21e15)

![im2](https://github.com/polywock/globalSpeed/assets/31208859/4aa2ba99-8b44-4114-b3e6-657c2d1f2d9e)

![im3](https://github.com/polywock/globalSpeed/assets/31208859/9b57bfe8-2d04-4300-8efe-36709d97bd82)

![im4](https://github.com/polywock/globalSpeed/assets/31208859/2eec7126-f1b0-4e50-9602-9a72840112e5)

**Comment by weineo** [comment]
十分感谢你的帮助，不过要是能在之后的版本里加入实现部分全屏的快捷键以使其与全屏模式共存的话那就更完美了。
Thank you very much for your help, but it would be even more perfect if we could add shortcut keys for partial full screen in future versions to coexist with full screen mode.

**Comment by polywock** [comment]
For convenience, shortcut key can be configured to capture tab's audio. But, unlike other shortcut keys. This must be configured through the browser. 

1. Create a Capture shortcut key in the options page. 
![m1](https://github.com/polywock/globalSpeed/assets/31208859/c5cab96d-41ec-4a91-9002-06ebc1f85ea0)

2. Make sure it's set to `CommandA`, which should be the default. Click the chain icon to open `chrome://extensions/shortcuts`, where extension shortcuts can be configured. 
![m2](https://github.com/polywock/globalSpeed/assets/31208859/c2ce5cd6-42a5-4db4-86f3-722b1488a5c1)

3. Set `CommandA` to your preferred shortcut key. 
![m3](https://github.com/polywock/globalSpeed/assets/31208859/defe867c-49c6-4656-9801-3d6a0f62b264)
