### ISSUE TITLE
建议：增加对Safari的支持

### ISSUE THREAD

**Issue by 13913585904** [polywock/globalSpeed#393]
身边有一些使用Safari浏览器的朋友，他们很羡慕这个随意倍速的功能，希望诸位开发大佬们能实现。

**Comment by polywock** [comment]
Hi. I have considered Safari extension development in the past, but it cost $99/year. If it's a one time payment, I would've done it, but a recurring charge is simply unacceptable for me. Some users have offered to pay or donate, but I feel uncomfortable taking donations .

**Comment by polywock** [comment]
Merging with issue #110
