### ISSUE TITLE
Spotify Web Player fluctuating when using 'speed changes pitch'.

### ISSUE THREAD

**Issue by mattjaydunn** [polywock/globalSpeed#399]
The speed and pitch fluctuate once every few seconds when using 'speed changes pitch', only on this website. I've tried youtube and other web audio players and it seems to only affect spotify web. The effect is similar to if you try slowing something down _without_ the 'speed changes pitch' enabled, where every few seconds it will fluctuate to the correct pitch to match the speed--except the inverse.

**Comment by polywock** [comment]
Enabling "Ghost mode" in the options page should solve this issue.

**Comment by mattjaydunn** [comment]
Worked like a charm. Thanks ^^
