### ISSUE TITLE
Feature request: audio delay on Firefox and Edge

### ISSUE THREAD

**Issue by chrissnell-okta** [polywock/globalSpeed#40]
College football season is finally here!  I'm super happy to find your plugin, because I used the old (delisted) Audio Delay extension for Chrome to delay the radio game-call broadcast to match up with the cable TV broadcast.

 Any chance we could get this functionality in Chromium and Edge, too?

**Comment by polywock** [comment]
The audio delay functionality should already be working for Chromium ([Chrome](https://chrome.google.com/webstore/detail/global-speed/jpbjcnkcffbooppibceonlgknpkniiff) and [Edge](https://microsoftedge.microsoft.com/addons/detail/global-speed/mjhlabbcmjflkpjknnicihkfnmbdfced)). Up to 60 seconds of delay. For the next update, I increase the max delay to 180 seconds. 

![a](https://user-images.githubusercontent.com/31208859/94029137-7ea0c100-fd8a-11ea-9916-3c7e42d9e65d.png)

Unfortunately, Firefox doesn't support the TabCapture API (used to manipulate audio).
