### ISSUE TITLE
Speed keeps fluctuating

### ISSUE THREAD

**Issue by acarperscarper** [polywock/globalSpeed#402]
Hi, 

Love the extension but I'm having a problem. If I set a faster speed it will at regular intervals drop back down to normal speed for a second and then it will go back up. This is very annoying especially when speed changes pitch is on because it goes out of key for a second. I'm on firefox 116.0.1 on m1 mac with ventura. Any help would be appreciated

**Comment by polywock** [comment]
Hello. Have you tried enabling "Ghost mode" in the options page. It usually helps with this kind of issue.
