### ISSUE TITLE
能否增加播放速度的快捷键吗？

### ISSUE THREAD

**Issue by Amazer526** [polywock/globalSpeed#403]
比如3倍，4倍，6倍等，自定义一个对应的快捷键。

**Comment by polywock** [comment]
In the options page, you can create a flexible "speed" shortcut key. It has three three modes

+ To increase or lower speed. (enter a negative number to lower speed)

= To set to specific speed. If the speed is already that, it will revert to previous speed.

:= Cycle between a list of speed values. (you can cycle between 1x, 2x, 3x, 4x, etc).
