### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by I-xyu** [polywock/globalSpeed#406]
希望能够增加一个视频画质捕捉选择功能  比如在一个网站上我想看1080画质 或者更高画质可以进行画质的选择播放 可以默认嗅探视频最高画质播放 这样在浏览器所看所有视频都可以用高清画质浏览  尤其是对在线的网盘视频  或者可以增加m3u8视频嗅探下载功能 这样使得该插件更全面功能

**Comment by polywock** [comment]
Hello. Many people have suggested this functionality, but it's very risky thing to implement. Extensions that do that are often taking down by the Chrome Web Store.
