### ISSUE TITLE
请问是否方便添加视频暂停时自动恢复播放？

### ISSUE THREAD

**Issue by sdyxxjj123** [polywock/globalSpeed#409]
部分网课的网站虽然可以使用本插件开到二倍速，但是他们会不定期暂停，是否可以添加一个发现视频暂停时自动恢复播放的选项？万分感谢。

**Comment by polywock** [comment]
Hello. This feature will be very niche so not suitable to be implemented. But, I do suggest creating a "Pause" shortcut in the options page to conveniently play/pause if the online courses website doesn't let you do that easily.
