### ISSUE TITLE
网站过滤

### ISSUE THREAD

**Issue by vnsnclo** [polywock/globalSpeed#410]
怎么让它过滤某些网站，有的网站不需要这个功能，但是还占用着某个键位，导致那个字母打不出来。
或者说已经有这个功能了，只是我没有找到？

**Comment by polywock** [comment]
Hello. You can create a URL rule to disable Global Speed depending on URL. Here's walkthrough for how to disable for bilibili.com and pan.baidu.com (follow the numbers) 

![im1](https://user-images.githubusercontent.com/31208859/193152300-55ba65bd-23ae-42ef-91cb-e5f5519ddd3d.png)

**Comment by vnsnclo** [comment]
thank you, very useful
