### ISSUE TITLE
YouTube subtitle speed issue

### ISSUE THREAD

**Issue by weineo** [polywock/globalSpeed#412]
When using this extended speed to play YouTube videos, if subtitles are turned on, the subtitle playback speed will still be the default speed. For example, if you use the extension to set double-speed playback, the subtitles will still be played at one-time speed. When the time difference between the subtitles and the video reaches a threshold, the subtitles will be forced to switch to the same time point in the video, and then continue to cycle the above process. But the strange thing is that if you manually click the button of the YouTube player to set the playback speed to x times, then use the extension to set the video playback speed to x and 1x, the subtitles will follow the video normally. Others, such as 0.5x and 2x speed, still have the above problems.
当使用该拓展倍速播放油管的视频时，如果打开了字幕，字幕播放速度还会依然是默认的速度。比如使用拓展设置二倍速播放，字幕会依然一倍速播放，当字幕和视频的时间差达到一个阈值时，字幕会强制切换到视频同一时间点，然后继续循环上述过程。但奇怪的是，如果手动点击油管播放器的按钮设置播放速度为x倍速，那么使用拓展设置视频播放倍速为x和1倍速，字幕都能正常跟随视频。而其他例如0.5x、2x倍速则依然存在上述问题.
![image](https://github.com/polywock/globalSpeed/assets/60565258/e02255a8-91da-4915-bf25-bc8f351f1247)

**Comment by polywock** [comment]
Hello. I have uploaded a potential fix. It might take a week for the update to get approval at the Edge/Chrome/Firefox stores. You can also load it manually. If you do, let me know if this fixes the issue. 

[packed.zip](https://github.com/polywock/globalSpeed/files/12698422/packed.zip)

1. Uninstall or disable the original Global Speed. 
1. Download packed.zip and extract the folder. 
2. open extensions page, edge://extensions 
4. Enable developer mode on the left (chrome) or top right side of the page (Chrome). 
5. Once developer mode is enabled, you should see "load unpacked". Click on that and load the extracted folder.

**Comment by weineo** [comment]
Thanks, it seems worked.
