### ISSUE TITLE
为什么固定按钮无法固定

### ISSUE THREAD

**Issue by Mrdudada** [polywock/globalSpeed#413]
面板左上角第二个钉子按钮，不论是否选中都无法始终保持在前端

**Comment by polywock** [comment]
Hello. The function isn't clearly explained. By default all tabs share the same context (speed, status, etc). The pin feature allows the tab to have it's own context. That way, users can change the speed just for that tab. 

Another user suggested a feature to keep the panel in front so it seems to be a desired feature. I will look into implementing it in the next major release.

**Comment by Mrdudada** [comment]
I'm sorry I didn't make my point clear, what i want to suggest is same with another user:"keep the panel in front !"!thanks!

**Comment by polywock** [comment]
@Mrdudada Not possible to keep the panel always loaded, but there's an alternative. 

 1. Open the options page and take note of the URL. It would be like `chrome-extension://jpbjcnkcffbooppibceonlgknpkniiff/options.html`.
 2. Create a `open URL` shortcut and set the URL to the same one but replace `options.html` with `popup.html`. 
 3. Change the mode from `foreground tab` to `popup`. A new window should popup, resize it to your desired size and press Apply. 
 4. Now when you press this shortcut the UI should appear as a moveable popup.

**Comment by Mrdudada** [comment]
thanks!  i will try!
