### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by SONGjiemo** [polywock/globalSpeed#416]
对网页视频进行音量增益之后，就会导致无法视频全屏播放。
音量增益之后
![image](https://github.com/polywock/globalSpeed/assets/46627639/a89a704f-34b2-4503-a2b0-494b3a8abbce)
没有改变之前，网页是可以进行全屏播放的。改变之后如下图界面。
使双击视频区域进行全屏播放。
![image](https://github.com/polywock/globalSpeed/assets/46627639/106e23a0-52cf-42a1-b58f-6e6fc579cd60)
正确的界面，如下图所示。
![image](https://github.com/polywock/globalSpeed/assets/46627639/25a1a243-acc0-4b4b-a6f3-d853492424e9)

**Comment by polywock** [comment]
Hello. Global Speed uses the Tab Capture API to manipulate a tab's audio. This API is very limited and has problems. One of the limitations is that videos cannot enter fullscreen while the tab is being manipulated. To circumvent this, you can first enter fullscreen and then "Capture" the tab's audio using a shortcut. You can create the shortcut in the options page, and configure it here `chrome://extensions/shortcuts`. 

![img1](https://github.com/polywock/globalSpeed/assets/31208859/911a4d09-43f0-4c46-a49c-de40906bc471)

![img2](https://github.com/polywock/globalSpeed/assets/31208859/89bd22be-36a5-4090-a7bc-5d8e7ea14d6c)
