### ISSUE TITLE
Some suggestions for Safari compatibility

### ISSUE THREAD

**Issue by notlccc** [polywock/globalSpeed#417]
First off, I just want to give a big shoutout for creating this awesome plugin. It's been a game-changer for my studies and daily grind. However, lately, my laptop's battery life has been a real downer, so I took the plunge and got an iPad for my online courses. To my disappointment, it feels like I'm dragging my feet without that "global speed" plugin. I get that you might not be into charging for your plugin or taking donations, but here's a thought: Safari lets you install Tampermonkey. So, here's an idea - maybe whipping up a Tampermonkey script could help us bypass these pesky issues. Either way, I want to say thanks once again for your dedication.

**Comment by polywock** [comment]
Hello. Thank you, I'm very glad to see Global Speed was helpful. My problem with Safari development, aside from the $99/yearly cost, is that the developer experience is pretty bad compared to Chromium/Firefox. They also require you to be up-to-date on the latest Mac OS version.  In addition, they're pretty strict about using your real name on the App Store unless you register a corporation/LLC. None of these reasons alone is a dealbreaker for me, but all together makes me hesitant to port it. 

You can mimic some of Global Speed's functionality in a userscript, but I think at that point, there are probably other scripts that also perform most of the same functions. Either way, I will be too busy to do so. I am currently working on two new extensions, and am falling behind on maintenaning of my existing ones.  Sorry I couldn't be more helpful.

**Comment by notlccc** [comment]
Well, it seems like this issue will only be resolved when Apple lifts its restrictions on browser engine access. By the way, I still hold a strong desire to see a donation channel opened by you. The value this plugin has created for me far surpasses any amount I would be willing to donate.

**Comment by polywock** [comment]
Merged with #110
