### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jillv46** [polywock/globalSpeed#418]
Is there a way to have a shortcut so I can pause the extension and un-pause it? I'm on Chrome

**Comment by polywock** [comment]
Yes, you can create a "pause" shortcut in the options page.

**Comment by jillv46** [comment]
> Yes, you can create a "pause" shortcut in the options page.

Does that pause the video or the extension? Because I tried a pause thing and it seemed to pause the video

**Comment by polywock** [comment]
Sorry, I misread. The shortcut is "state" to turn on/off the extension (Shift-Q by default on QWERTY keyboard). You can adjust it in the options page.

By the way, If you use the shortcut to turn off Global Speed, you can also use it to turn it back on. But, if you use the toolbar menu to turn off Global Speed, you cannot turn it back on using shortcut.

**Comment by jillv46** [comment]
> Sorry, I misunderstood. The shortcut is "state" to turn on/off the extension (Shift-Q by default on QWERTY keyboard). You can adjust it in the options page.
> 
> By the way, If you use the shortcut to turn off Global Speed, you can also use it to turn it back on. But, if you use the toolbar menu to turn off Global Speed, you cannot turn it back on using shortcut.

Thanks 😄 The reason why I wanted to turn it off and on is because sometimes I want to put the video on slow motion (to catch a fast part in it etc) and having it on when I click the YouTube's speed to the lowest it does it for a sec but then it goes back to the default. I know it's the Global Speed doing it because I disabled all my "video" related extensions and slowly enabled each one until it stopped working. Is there a way for me to make it so Global Speed doesn't disable me adjusting the YouTube's end for the playback speed or do I have to turn it off each time I want to slow the video down for the one part and then turn Global Speed back on afterwards?

**Comment by polywock** [comment]
If the user changes the speed through the website's controls, Global Speed has no way of knowing if the user did that or if the website did that. Websites often revert or change speed without user's input. The only way for Global Speed to know the user's intent is by changing the speed through Global Speed's shortcuts or toolbar menu. 

I guess you could enable Global Speed using shortcut/menu, change speed to 0.7x and then turn off Global Speed. That way the speed is initially set to 0.7 once.
