### ISSUE TITLE
Is there a manual or something?

### ISSUE THREAD

**Issue by Mjsaxo** [polywock/globalSpeed#42]
I am trying this add on to see if I would be able to switch completely from Chrome to Edge for good productivity. 

I am exploring the features such as pin tab, state, set mark, etc and unclear on certain things like "state" and do not see any guide on this site. Thanks for this add on.

**Comment by Mjsaxo** [comment]
Update: also this extension for most site but does not work for embedded videos in canvas, the main site for my online courses :(

**Comment by polywock** [comment]
Here's a pretty bad [demo video](https://www.youtube.com/watch?v=h0oY1_sPCiE). I'll try making a better one soon. 

**set mark**: sets a mark on the current time of video.

**seek mark**: goes to mark. 

**AB loop**: sets an AB loop between the marked position and the current time. (eg. if you want to loop a specific part of the video). 

**state ⏻**: Used to suspend the plugin. Speed no longer changes. Filters are deactivated. Shortcut keys are deactivated except for the `state` shortcut.  Useful if you're playing a web game and want to disable the Global Speed shortcut keys. 


**pin tab 📌**: All unpinned tabs share the same global context (speed, state, filters, etc). If you want a tab to have custom settings you need to pin it. For example, one tab you can listen at 1x speed. The other tab you can listen at 2x speed. 

Apologies for the terrible explanations. If you need more info, reply back. 

As for Canvas. I tried it out. Seems to work for Youtube videos embedded on Canvas. It might depend on what type of video is embedded. Eg. flash videos aren't supported. 

![a](https://user-images.githubusercontent.com/31208859/94860521-2ca01100-0404-11eb-9cc0-0cf45fbea106.png)
