### ISSUE TITLE
视频无法解除倍速

### ISSUE THREAD

**Issue by zbdq-1** [polywock/globalSpeed#420]
无论是打开扩展还是关闭扩展都无法解除倍速，关闭扩展，视频倍速会变成三倍，无法通过网站本身来调试倍速，求解决办法

**Comment by polywock** [comment]
Hello. Did you try re-installing the extension?  If that doesn't fix the issue. Try disabling all extensions except Global Speed to see if there is a conflict.

**Comment by zbdq-1** [comment]
和其他扩展冲突了

**Comment by polywock** [comment]
Thanks for the update. In that case, I will close the issue. Let me know if you need further assistance.
