### ISSUE TITLE
在Firefox使用遇到的一些问题

### ISSUE THREAD

**Issue by JamisonLeo** [polywock/globalSpeed#421]
使用Firefox观看bilibili的视频时使用该插件倍速播放会出现破音，Chrome上相同的视频不会出现这种情况

**Comment by polywock** [comment]
Does enabling Ghost Mode in the options page make a difference?

**Comment by MisterJunxian** [comment]
> Does enabling Ghost Mode in the options page make a difference?在选项页面中启用幽灵模式会有所不同吗？

Thank you very much, the issue has been resolved.
