### ISSUE TITLE
Add exception to url

### ISSUE THREAD

**Issue by Dannykcw** [polywock/globalSpeed#422]
Is it possible to have a section in the section GUI to allow for checking against a list that the user can modify, to tell the extension to exempt keyboard shortcuts on certain websites? It will help avoid key conflicts or applying the extension on sites that I personally think are unnecessary.

**Comment by polywock** [comment]
The capability is there, but kind of hidden. Bottom right of the Shortcut Editor, there is an unlabeled button that says "--0--". You can click that to add URL conditions. This example blocks all shortcuts on Twitch and Google docs. 

![screenshots1](https://github.com/polywock/globalSpeed/assets/31208859/d248a3e0-4655-46dc-986a-18d38cdd2e96)

**Comment by Dannykcw** [comment]
Would it be possible to give the button a more proper labeling and/or add some text to explain how this functionality would be used for clarity?

**Comment by polywock** [comment]
Yes, currently refactoring the extension. I plan to improve the UI a bit.
