### ISSUE TITLE
Edge browser cannot be controlled using shortcut keys

### ISSUE THREAD

**Issue by kangx1987** [polywock/globalSpeed#423]
I can't control it using shortcut keys in the latest version of Edge, but it works fine in Firefox. I disabled other Edge browser extensions but still can't use the shortcut keys. This problem occurred recently, and it has been working normally before.

**Comment by polywock** [comment]
Seems very similar to this Issue. Apparently that was caused by a windows update, and was eventually fixed by a newer windows update. Have you checked if you have updates available? 

https://github.com/polywock/globalSpeed/issues/415
