### ISSUE TITLE
Is it possible to control the speed for each video window.

### ISSUE THREAD

**Issue by JamesTso0530** [polywock/globalSpeed#424]
Is it possible to control the speed for each video window? or add a feature to choose control the global speed or only the current tab speed.

**Comment by polywock** [comment]
You can't control windows separately. If you pin the tab using the pin icon 📌 or using the pin shortcut (Q by default on qwerty keyboard), you change the speed just for that tab.

**Comment by JamesTso0530** [comment]
I found it can be set to local as default when opening each tab. Thank you for your help. It is a nice extension.
