### ISSUE TITLE
Can you improve the compatibility of this extension on cell phones

### ISSUE THREAD

**Issue by Wei-Winter** [polywock/globalSpeed#425]
I've noticed that there are a lot of users who need to use this extension on Mac or ios, and there are already browsers on Mac and ios that can install chrome extensions, so you can recommend this one to them. it's called Orion. there are some compatibility issues, but I've been using this extension on my iPhone, and the speed shifting function works basically. I just can't quickly adjust the speed, can you add the option to adjust the speed in the upper right or left corner of each embedded video, like this extension.

https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk?hl=zh-CN

This feature allows me to quickly adjust the speed of the video even when I'm on my cell phone.

**Comment by polywock** [comment]
> can you add the option to adjust the speed in the upper right or left corner of each embedded video, like this extension.

I occasionally look at that extension's Github and I notice a large portion of issues revolve around the embedded controls. It seems to be a maintenance nightmare. 😢  Sorry, I am too busy for that.
