### ISSUE TITLE
Player's default caption

### ISSUE THREAD

**Issue by devrenj** [polywock/globalSpeed#427]
Hi! Love your work, I'm usinig the extension for edge (ver. 118.0.2088.61 official version x64)

I wish there's a feature to toggle on/off the current video player's automatic caption, also select by default the user preffered, language if it's available on the video

Thanks anyway!
Keep doing this good job 😄

**Comment by polywock** [comment]
Always happy to see the extension being helpful! 

The problem with toggling captions is all sites handle it differently. Same with next/previous shortcuts, which is a feature suggestion I get often. I could implement it for some popular websites but I generally try to keep the extension website agnostic. Site specific functions tend to balloon in the size and require a lot of maintenance. Sorry I could not be more helpful.

**Comment by devrenj** [comment]
That’s okay, don’t worry… Maybe if you change your mind, implementing a
YouTube function would be great, as “experimental” checked, it would be
used as a development setting, for those who are looking for “hidden
features”. As well, thanks a lot for this solution, it’s great for my
studies purposes!

Em dom., 22 de out. de 2023 às 23:00, polywock ***@***.***>
escreveu:
