### ISSUE TITLE
Websites Whitelist

### ISSUE THREAD

**Issue by Cabus1982** [polywock/globalSpeed#429]
Is there any way to whitelist sites? Because I regularly listen to music (Spotify or YouTube Music) and I have to correct the speed and equalization that I use for videos. 😪

**Comment by polywock** [comment]
Hello. Are you on Chrome/Edge? If so, you can right click Global Speed's icon in the toolbar and click "Manage Extension". While there, change the site access to on specific sites, and add the websites you want to allow.

**Comment by Cabus1982** [comment]
Interesting, but I need the opposite, because I want it to work everywhere except in a couple.

**Comment by polywock** [comment]
In that case, you can create a URL rule that turns the state off. 

1. In options page, create a new URL rule. 
2. Change speed to state (and make sure it's in off position). 
3. Click the -- 0 -- to change the URL conditions. 
4. For example, the second image shows what it looks like to block docs.google.com and twitch.tv, just substitute those with Spotify and Youtube Music. 
5. To verbalize it, this means if the URL matches docs.google.com OR matches twitch.tv, turn off the extension. 

![img1](https://github.com/polywock/globalSpeed/assets/31208859/25a9efa4-d0d5-4583-b29c-9318ce5cbfe0)
![img2](https://github.com/polywock/globalSpeed/assets/31208859/10f70cb0-dfeb-48cd-8253-f5c79721950d)


By the way, I plan to improve the UX in the next major release. Please bear with it for now.

**Comment by Cabus1982** [comment]
> In that case, you can create a URL rule that turns the state off.
> 
> 1. In options page, create a new URL rule.
> 2. Change speed to state (and make sure it's in off position).
> 3. Click the -- 0 -- to change the URL conditions.
> 4. For example, the second image shows what it looks like to block docs.google.com and twitch.tv, just substitute those with Spotify and Youtube Music.
> 5. To verbalize it, this means if the URL matches docs.google.com OR matches twitch.tv, turn off the extension.
> 
> ![img1](https://user-images.githubusercontent.com/31208859/277833243-25a9efa4-d0d5-4583-b29c-9318ce5cbfe0.jpg) ![img2](https://user-images.githubusercontent.com/31208859/277833908-10f70cb0-dfeb-48cd-8253-f5c79721950d.png)
> 
> By the way, I plan to improve the UX in the next major release. Please bear with it for now.

After reviewing that section, I became very confused and thought it was meant for another purpose. Thank you for your help and instructions in setting up the extension. Your development efforts are really appreciated 🙏

**Comment by polywock** [comment]
> After reviewing that section, I became very confused and thought it was meant for another purpose. 

😓 Yeah, the UI needs a lot of work.
