### ISSUE TITLE
Pin by default for all tabs

### ISSUE THREAD

**Issue by SanbikiNoKaeru** [polywock/globalSpeed#430]
As far as I understand pinned by default option makes only new tabs have pinned speed. 
I always use my browser's feature 'Open previous windows and tabs' so when close and reopen my browser (Firefox 119.0), previously pinned sites are unpinned now.
Is there a way to pin all tabs by default no matter new or old?

**Comment by LifeJustDLC** [comment]
I can't understand your situation very well. Reopening the browser doesn't reset every tabs to "pined" state?
However, you can try: adding your most frequently used hotkeys which had already been bind to frequently used functions, e.g., change speed, like this:

![图片](https://github.com/polywock/globalSpeed/assets/112793544/07c29da8-6bc0-4e85-ab54-eb3598c29fc8)

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of today, the issue should be fixed. On startup, existing tabs will be re-pinned.
