### ISSUE TITLE
快捷键功能微软 Edge 上不能正常工作

### ISSUE THREAD

**Issue by BNRK300** [polywock/globalSpeed#431]
快捷键功能在 Chrome 和 Firefox 上可以正常工作，但在微软 Edge 上不能正常工作。

**Comment by polywock** [comment]
Other people complained of similar issues. It might be related to a Windows/Edge update. The problem might be fixed if you update your windows/Edge.

**Comment by kangx1987** [comment]
> 我也是遇到这个问题，后来我从应用程序里找到edge webview2 runtime这个应用，点后面的三个点点，点修复，然后能用了，你可以试试

当我没说，电脑关机后重新开机又不能用了

**Comment by polywock** [comment]
Is this issue still a problem? If so, please re-open.
