### ISSUE TITLE
Wanna keep speed label always on

### ISSUE THREAD

**Issue by daiki-cyber** [polywock/globalSpeed#432]
I want to always check what speed I'm on. When increase/decrease speed, the label flash, but immediately, it's gone. 
If I can toggle the label on/off, it's much better. 

On google, another video speed controller extension have the function. But on edge, this extension is the best. 

Thanks for consideration, in advance!
Nice work, anyway. I really appreciate this extension.

**Comment by polywock** [comment]
Hello. In the bottom of the options there's an import button. You can import this edited JSON, where I changed the duration to 9999 seconds. 

[Global Speed - Sat Oct 28 2023.json](https://github.com/polywock/globalSpeed/files/13195032/Global.Speed.-.Sat.Oct.28.2023.json)

**Comment by daiki-cyber** [comment]
Thanks for the reply. I import the file and I follow your jason file. I copy "indicatorInit" and paste it in the newest version. BOOOOM, it worked. 

I knew you are the GOD in disguise. I appreciate I have spent same generation as you do. 
This is an incredible work. 
You will be one of the biggest reason people flee from Chrome to Edge :)

**Comment by polywock** [comment]
❤️  I appreciate it! _(But, I also publish on Chrome 😆)_

**Comment by daiki-cyber** [comment]
Oh, it's like a treason. I switched to God polywock's extension on google. 
Now, I've got a reason to stay on chrome 😄
