### ISSUE TITLE
在bilibili插件出现bug

### ISSUE THREAD

**Issue by zhangfugui6** [polywock/globalSpeed#433]
edge浏览器里在使用bilibili插件时出现bug,当播放视频时就提示出现错误，按照提示解决步骤做任然无法正常使用。

**Comment by polywock** [comment]
Can you explain the bug a bit? Also let me know your OS version.

**Comment by zhangfugui6** [comment]
An error occurred.
1. Try refreshing this page.
refresh
2. If that didn't work, click this button to reset thesettings.
reset
3. As a final resort, try reinstalling the extension.操作系统win11

**Comment by polywock** [comment]
#400 Had the same issue. 

They fixed it by resetting Edge. 

edge://settings/reset

**Comment by zhangfugui6** [comment]
Thank you for your answer.
