### ISSUE TITLE
Invalid URL! (

### ISSUE THREAD

**Issue by wegie1** [polywock/globalSpeed#44]
I sometimes get this error message in youtube when i press default "S" key for set speed 1. I refresh the tab, then I can use "S" without getting any message.

![yout](https://user-images.githubusercontent.com/73955440/98663568-52e99280-235a-11eb-8dde-438acd604a1b.PNG)

**Comment by polywock** [comment]
I've had this happen before as well, but couldn't reproduce it. I've changed the shortcut key approach in the latest version, which I think will solve it. It should be published today or tomorrow. After you receive the update, let me know if you experience that error again. Thanks for the feedback.

**Comment by egoistinr** [comment]
I also got this sometimes.
After some try, in my case, I think it is cause by conflict with another addon "imagus".

**Comment by bartschliam** [comment]
I have the same issue as @a7168 is there any way to have both extensions enabled and not have this bug?

**Comment by wegie1** [comment]
Probably it fixed with updates. I realized that i did not get it any more. This is my addon list:

Adobe Acrobat efaidnbmnnnibpcajpcglclefindmkaj
Screen Recorder hniebljpgcogalllopnjokppmgbhaden
Global Speed jpbjcnkcffbooppibceonlgknpkniiff
Google Dictionary mgijmajocgfcbeboacabfgobmjgjcoja
Google Translate aapbdbdomjkkjkaonfhkkikfgjllcleb
IDM Integration Module ngpampappnmepgilojfohadhhmbhlaek
Imagus immpkjjlgappgfkkfieppnmlhakdmaab
ImTranslator noaijdpnepcgjemiklgfkcfbkokogabh
Nimbus bpconcjcammlapcogcnnelfmaeghhagj
Picture-in-Picture Extension (by Google) hkgfoiooedgoejojocmhlaklaeopbecg
uBlock Origin cjpalhdlnbpafiamejdnhcphjbkeiagm
Volume Master jghecgabfgfdldnmbfkhmffcabddioke
Watch2Gether cimpffimgeipdhnhjohpbehjkcdpjolg
Wikiwand emffkefkbkpkgpdeeooapgaicgmcbolj

**Comment by polywock** [comment]
@wegie1 Seems like @a7168 was a correct about Imagus conflicting with Global Speed. I'll look into the conflict. I was busy with life lately and didn't have time to do so before.

**Comment by bartschliam** [comment]
Thank you so much @polywock, I really appreciate all the work you put into this!
