### ISSUE TITLE
小窗口使用快捷键

### ISSUE THREAD

**Issue by KenyonLvHust** [polywock/globalSpeed#441]
我觉的小窗口使用快捷键挺不错的，不用再回到网页，目前支持吗?

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. Supported as global shortcut keys. 

Make sure to pin the video, and then you can use global shortcut keys to control the PiP video on Chrome/Edge. (Firefox doesn't support global shortcuts). 

Demo: https://www.youtube.com/watch?v=EZA-TnVAyDo
