### ISSUE TITLE
Allow speed change from other sources

### ISSUE THREAD

**Issue by Wronschien** [polywock/globalSpeed#442]
Is there a way to let original controls or other extensions change speed for a specific tab, while keeping the global speed for the others ?
For example I sometimes let a background tab with music (most likely on youtube) while watching a 'real' video on another tab. Currently I can't (I think) speed up the video while keeping the music tab untouched.

**Comment by polywock** [comment]
Once the tab is pinned, you can turn off Global Speed for that tab. 

Shortcuts (QWERTY keyboard default): Q to pin tab. Shift-Q to turn off.

**Comment by Wronschien** [comment]
Ah thank you for reply. I can't seem to turn it off only for the pinned tab though. If I do that, other unpinned tabs are affected too.
Btw, I'm using Firefox on Windows 10, I forgot to mention it.
Ideally I'd like to keep the addon active on the music tab to be able to use other shortcuts than speed.

**Comment by polywock** [comment]
Tested on Firefox with no issues.  As long as you make the changes after the tab is pinned, it should work. You can also try enabling  "pin by default" in the options page. All new tabs should automatically get pinned.
