### ISSUE TITLE
Preciso que seja desativado em um site.

### ISSUE THREAD

**Issue by glebysonsantos** [polywock/globalSpeed#445]
Olá! Gostaria de saber se há como desativar a extensão para determinados sites.

Por exemplo, adicionar um site X à uma lista de sites que não quero que a extensão seja ativa.

**Comment by polywock** [comment]
You can add a URL rule to turn off Global Speed. The system isn't great right, but I'm hoping to improve in a later update. 

![images](https://github.com/polywock/globalSpeed/assets/31208859/466ad93b-bc53-48b5-bfb6-fcb28e24eb0c)

1. Create a new URL rule. 
2. Add a URL condition for the site you want to turn off. (For example: Youtube.com) 
3. Change the mode to "state".

**Comment by glebysonsantos** [comment]
Muito obrigado! 🙂
________________________________
De: polywock ***@***.***>
Enviado: quarta-feira, 22 de novembro de 2023 01:36
Para: polywock/globalSpeed ***@***.***>
Cc: glebysonsantos ***@***.***>; Author ***@***.***>
Assunto: Re: [polywock/globalSpeed] Preciso que seja desativado em um site. (Issue #445)


You can add a URL rule to turn off Global Speed. The system isn't great right, but I'm hoping to improve in a later update.

[images]<https://user-images.githubusercontent.com/31208859/284791168-466ad93b-bc53-48b5-bfb6-fcb28e24eb0c.png>

  1.  Create a new URL rule.
  2.  Add a URL condition for the site you want to turn off. (For example: Youtube.com)
  3.  Change the mode to "state".
