### ISSUE TITLE
Bug with latest update.

### ISSUE THREAD

**Issue by polywock** [polywock/globalSpeed#45]
The new update published on Chrome/Firefox had a bug that broke the extension for some users. 

## To fix: 
Update to the fixed version >2.6.9 or reinstall. (warning: reinstalling doesn't preserve your settings)

**Comment by polywock** [comment]
[packed.zip](https://github.com/polywock/globalSpeed/files/9175122/packed.zip)

**Comment by valerielmerritt** [comment]
> The new update published on Chrome/Firefox had a bug that broke the extension for some users. 
> 
> ## To fix: 
> Update to the fixed version >2.6.9 or reinstall. (warning: reinstalling doesn't preserve your settings) 
>
