### ISSUE TITLE
能设置加入黑名单吗

### ISSUE THREAD

**Issue by eamon2003** [polywock/globalSpeed#453]
有一些网站不是视频网站 比如打字网站 也会触发效果 导致无法正常打字 所以可以搞黑名单功能手动把这些网站加进去吗

**Comment by JinghuaOriental** [comment]
右键扩展->这里可以读取和更改站点数据->选择“单击扩展时”，该页面即被加入黑名单，其他页面仍可正常使用
Right-click the extension -> here you can read and change site data -> select "When clicking extension", the page will be added to the blacklist, and other pages can still be used normally.

**Comment by eamon2003** [comment]
> 右键扩展->这里可以读取和更改站点数据->选择“单击扩展时”，该页面即被加入黑名单，其他页面仍可正常使用 Right-click the extension -> here you can read and change site data -> select "When clicking extension", the page will be added to the blacklist, and other pages can still be used normally.

感谢

**Comment by eamon2003** [comment]
> 右键扩展->这里可以读取和更改站点数据->选择“单击扩展时”，该页面即被加入黑名单，其他页面仍可正常使用 Right-click the extension -> here you can read and change site data -> select "When clicking extension", the page will be added to the blacklist, and other pages can still be used normally.

好像选了单击拓展后 所有网页都是单击拓展了

**Comment by polywock** [comment]
I'm looking into adding a proper, easy to use blacklist function for the next major release. For now, you can add some URLs to a shortcut blacklist. Here's an example on how to block example.com, example2.com, and example3.com. Make sure to change mode to "所有 (AND)"

![image1](https://github.com/polywock/globalSpeed/assets/31208859/d2fa8cf1-b1ac-485e-95fd-109db0dbad63)

![image2](https://github.com/polywock/globalSpeed/assets/31208859/4a5434bc-af55-474c-b9b7-8b6d9e74bd67)

**Comment by eamon2003** [comment]
> I'm looking into adding a proper, easy to use blacklist function for the next major release. For now, you can add some URLs to a shortcut blacklist. Here's an example on how to block example.com, example2.com, and example3.com. Make sure to change mode to "所有 (AND)"
> 
> ![image1](https://private-user-images.githubusercontent.com/31208859/292064495-d2fa8cf1-b1ac-485e-95fd-109db0dbad63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjQ1MDEsIm5iZiI6MTcwMzEyNDIwMSwicGF0aCI6Ii8zMTIwODg1OS8yOTIwNjQ0OTUtZDJmYThjZjEtYjFhYy00ODVlLTk1ZmQtMTA5ZGIwZGJhZDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyMDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZmRmYmMzNmQzOGQ5NzFjMmU0MWQ0NmM2YmFlOTk1OTg5NjkzMGYxNDY1Yzk2N2M0NDZiMDdhNmU3OTYxZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X_iZnHiJG5cw6F9cg5pWDQz0pDdd4i6AlBKCsjDn_go)
> 
> ![image2](https://private-user-images.githubusercontent.com/31208859/292064491-4a5434bc-af55-474c-b9b7-8b6d9e74bd67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjQ1MDEsIm5iZiI6MTcwMzEyNDIwMSwicGF0aCI6Ii8zMTIwODg1OS8yOTIwNjQ0OTEtNGE1NDM0YmMtYWY1NS00NzRjLWI5YjctOGI2ZDllNzRiZDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyMDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYWRhNjM4YjI3MDZlYjgwM2Q2Nzg4ZGVhNDFkZGUxNTM5ZjgzNDU3MjdjNTBjNjBkZWQyYTJkYWU5ZDY3NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EHu-qSzeqi8G2sdV2p_yr7QQRLrQlnvpvU7r4ZZBXGI)

I tried and it worked, thanks. 
![image](https://github.com/polywock/globalSpeed/assets/51506762/b94ccdb9-9ee3-4ed0-8e7d-aa4a54700190)
I hope there is a button which can easily add the website into blacklist
