### ISSUE TITLE
Extension does not work on Kiwi browser

### ISSUE THREAD

**Issue by zmobbie** [polywock/globalSpeed#46]
The extension does not work on [Kiwi browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser&hl=en&gl=US) (a chromium based android browser with extension support).
When I try to open the popup, its just a blank page.
When I try to manually navigate to the options page, its also a blank page.

**Comment by polywock** [comment]
I suspect it's because of the update bug. What version of Global Speed are you on? 

https://github.com/polywock/globalSpeed/issues/45

**Comment by zmobbie** [comment]
Hello.
I am already using the latest version from the web store and the version is 2.7.0

**Comment by polywock** [comment]
Maybe another issue. Did you try reinstalling the extension?

**Comment by zmobbie** [comment]
Yes. I did a clean install from the web store less than an hour ago

**Comment by polywock** [comment]
Just tried it on Kiwi Browser. Doesn't work for me either. Weird, still works on Yandex browser (another Chromium Android browser with extension support). I'll look into debugging it.

**Comment by zmobbie** [comment]
Basically an error like this is both on the background, popup and options page
![chrome_Nlf8spmdva](https://user-images.githubusercontent.com/74409316/99083938-f0e59300-25ce-11eb-8ae1-8d293dff0717.png)

**Comment by zmobbie** [comment]
More info: Kiwi uses V8 6.8, which was released in June 2018, and the dev doesnt seem to be too interested in updating it to a more recent version. Chrome was approximately on version 68 then. The only possible way to currently support Kiwi would be with polyfills but it would make the extension bigger

**Comment by zmobbie** [comment]
I got it to work on Kiwi.
Basically I made fromEntries-polyfill.js file in the static directory with this content. I adapted someones else work so this may not be acceptable for you to include in this repository:
```
/*! fromentries. MIT License. Feross Aboukhadijeh <https://feross.org/opensource> */
// https://github.com/feross/fromentries/blob/master/index.js
Object.prototype.fromEntries || Object.defineProperty(Object.prototype, "fromEntries", { configurable: !0, value: function (iterable) { return [...iterable].reduce((obj, [key, val]) => { obj[key] = val; return obj; }, {})}, writable: !0});
```

then in manifest.json:
```
"background": {
    "scripts": ["fromEntries-polyfill.js", "background.js"]
},
```
```
"content_scripts": [{
    "matches": ["https://*/*", "http://*/*", "file://*/*"],
    "js": ["fromEntries-polyfill.js", "contentScript.js"],
```
In options.html:
```
<script src="fromEntries-polyfill.js"></script>
<script src="options.js"></script>
```
In popup.html:
```
<script src="fromEntries-polyfill.js"></script>
<script src="popup.js"></script>
```
![image](https://user-images.githubusercontent.com/74409316/99090254-0b236f00-25d7-11eb-8545-36e3a5bf2dc4.png)
![image](https://user-images.githubusercontent.com/74409316/99090288-18405e00-25d7-11eb-8c92-e91bc9103672.png)

**Comment by polywock** [comment]
Nice. This is my favorite issue so far.  I do nothing.

**Comment by zmobbie** [comment]
Will you merge this? It doesnt make the extension significantly larger. Also I checked the MIT license and it seems that it's okay to include that file if the copyright notice remains intact in that file.

**Comment by polywock** [comment]
Yeah. Do you want to do a formal pull request, or should I just manually add it?

**Comment by zmobbie** [comment]
Ill try to add it myself. Never done that before though

**Comment by polywock** [comment]
If you're not familiar with Git. The easiest way will be to fork the project. And edit the files uses Github's online editor.
