### ISSUE TITLE
peoblems when use on Netflix with edge 

### ISSUE THREAD

**Issue by gnafrgb** [polywock/globalSpeed#460]
I am using your globalspeed add-on both on Firefox and edge. The Firefox version works great. But right now Netflix only allow Microsoft edge to play on 1080p. The "Netflix 1080p" [add-on](https://chromewebstore.google.com/detail/netflix-1080p/cankofcoohmbhfpcemhmaaeennfbnmgp?pli=1) is not working anymore(Firefox and Chrome). So I use edge to watch Netflix. I notice 2 issues right now. 
  
1. When I change the speed(speed up or slow down), the video will always freeze or lag for 3-5 sec. This only happen on Netflix with edge. Using Firefox to play Netflix(not 1080p of course) or using edge with other sites will not cause this issue.

2. If I ever pause the video and resume again, the play speed will back to normal even if I enable the ghost mode.
 
I guess both are DRM related. Is there any way to avoid?

**Comment by polywock** [comment]
Hi. Apologies for the late reply. Yeah, DRM issues. There is no good solution. You can disable DRM through edge://flags (I think ti was called PlayReady or something), but that will bring the quality down as well.
