### ISSUE TITLE
关于视频短期加快和放慢的建议

### ISSUE THREAD

**Issue by percharm** [polywock/globalSpeed#461]
我使用的是Edge浏览器，我看长视频比较多，遇到某些片段时，我会有短时加快或减慢的请求，作者能不能做一个功能，长按方向键当前时间段速度翻倍。谢谢。

**Comment by polywock** [comment]
Hello. I will look into that. For now, you could add a shortcut that changes the speed to 4x. The first time you press it, it will go to 4x. The second time, it will revert to your old speed. It's like a super-speed mode.
