### ISSUE TITLE
While watching a LIVE youtube video at greater than 1.00x speed BUG.

### ISSUE THREAD

**Issue by albixhuveli** [polywock/globalSpeed#464]
While watching a LIVE youtube video at greater than 1.00x speed. once the video catches up to the livestream the video should go back to 1.00x speed but instead it stutters, pauses, and keeps going at >1.00 previous set speed.

**Comment by zedd-0** [comment]
detecting and responding to the state in a live video with timeshift on youtube is impossible.
a completely new plugin would need to be written, and it would only work for YouTube, and only in this specific case.
I would certainly want something like that, but I understand the complexity and effort involved.
also, the interest is practically nonexistent, if nobody knows such a thing would be possible.
it would be a nice "quality of life" feature,
but it will likely never be implemented unless you do it yourself.

sorry.

**Comment by albixhuveli** [comment]
No worries. I recently switched browsers from chrome to edge and the old
extension I was using seemed to do this but had terrible UI when switching
to Edge. I might consider trying to fix it myself since I know it's
possible with the other extension, but like you said the complexity and
effort might not be worth it. Thanks anyway for what you're doing and the
state of the work you have done, I use your controller daily.
