### ISSUE TITLE
Hope to add support for touch screen devices

### ISSUE THREAD

**Issue by junexus** [polywock/globalSpeed#468]
For devices that support touch screens, it would be great if you could customize some gestures or areas to control the fast forward, fast backward or speed control of the video screen.

**Comment by polywock** [comment]
Hello. I wanted to implement this, but it's much harder than I thought. Anything beyond very simple gestures requires A.I. models bundled with the extension. It's probably not worth the effort so I'll close the issue. 

Thanks for the suggestion.
