### ISSUE TITLE
Using volume gain for videos

### ISSUE THREAD

**Issue by pravekum84** [polywock/globalSpeed#469]
Hello, 
   I recently starter using this extension and really love it. Have a couple suggestions or if they are already implemented can you please let me know how.
1. In order to use the volume gain for any videos currently I am having to activate it through the volume button in the extension on the top right. Is it possible to change the volume gain for the videos on different websites be default without clicking capture or release in the extension.
![image](https://github.com/polywock/globalSpeed/assets/159583253/8c55c163-3a74-463e-81f4-d4cd6f79e49c)

2. When press Ctrl+A it automatically open the extension on the top right (like shown in the image) I have checked and its not a shortcut that I have created. Is it possible to disable it.
![image](https://github.com/polywock/globalSpeed/assets/159583253/be4349c3-2318-464f-abcc-e62fc393016e)

3. Cannot go full screen on the video after capturing it for changing volume gain.

Thank you very much for the extension.

**Comment by polywock** [comment]
Hi! Sorry for the late reply. I must have missed it. 

The Ctrl-A was probably configured here. 
chrome://extensions/shortcuts

I recommend adding a Tab Capture shortcut in the options page and configuring it at `chrome://extensions/shortcuts`. Using this shortcut, you can more conveniently enable and disable volume gain. 

In addition, you can enter full screen first, and then use the shortcut to enable it. This is the only workaround to have audio effects with fullscreen. The API has limitations for security reasons.
