### ISSUE TITLE
Problems setting tab to 1x speed when navigating in the same tab?

### ISSUE THREAD

**Issue by RuntimeErrorz** [polywock/globalSpeed#477]
I have alreay enabled "pin by default" and "inherit global" in the options page, abd it works well on opening a new tab. But when I navigate into another site in the same tab, it seems to inherit the previous tab context, is there a way to fix this?

**Comment by polywock** [comment]
Hello. It's currently not supported, but I am looking into it. States are currently separated on a tab-by-tab basis.
