### ISSUE TITLE
When extension is active, YouTube front page doesn't refresh video recommendations

### ISSUE THREAD

**Issue by SonixV3T** [polywock/globalSpeed#478]
Hey!

Just a small bug, but when the extension is active (as in actively forcing the playback speed), for some reason the videos in the YouTube front page won't be refreshed if you refresh the page. 

It will show the same videos, sometimes mantaining the same spot as before the refresh, even.

I'm running Global Speed ver. 2.9.9971, downloaded from Chrome Web Store.
Google Chrome version 122.0.6261.95 at the time I tested this.

Thank you!

**Comment by polywock** [comment]
I can't reproduce the issue. I do notice the feed doesn't change that often. But, I notice that with Global Speed both enabled and fully disabled. Are you sure it's related to Global Speed? Youtube might have updated their caching mechanism.
