### ISSUE TITLE
Global Speed extension indicator does not show on screen if Global hotkey is pressed.

### ISSUE THREAD

**Issue by amanarya1r** [polywock/globalSpeed#487]
Global hot keys assigned: 
                                   forward +5 sec = ctrl+shift+0
If I am watching YouTube in Edge browser and running and working on Onenote(current active window){note taking app}. So Global Speed Extension does show up on pressing global hot key. Indicator only shows when Edge browser become current active window(and during both operation I pressed hotkey).

**Comment by w1s3one805** [comment]
#486

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of today, the Issue appears to be solved. Let me know if it's not.
