### ISSUE TITLE
[EDGE] Youtube shorts overlap with each other

### ISSUE THREAD

**Issue by licdar87** [polywock/globalSpeed#489]
Watching Youtube shorts at 1.5x speed makes them overlap with each other. In practice, when a short is close to its end, the next video starts to play for a couple of seconds, and then the original video restarts from the beginning. It has been happening since the last 3-4 days IIRC.

Thank you in advance for your help

**Comment by polywock** [comment]
I can't seem to reproduce the issue. Have you tried fully disabling Global Speed to see if the issue remains?

**Comment by licdar87** [comment]
> I can't seem to reproduce the issue. Have you tried fully disabling Global Speed to see if the issue remains?

Wow, that was quick. 
I forgot to say it doesn't happen right away, you need to scroll across a couple of videos before to make it happen. 

And yes, I disabled global speed, refreshed the page and it stopped doing so.

**Comment by polywock** [comment]
Still no luck. A few questions if you don't mind. 

1. Do you only experience the issue on 1.5x speed? 
2. Have you tried without all extensions, besides Global Speed disabled? (Might be a conflict with another extension). 
3. Have you tried re-installing Global Speed?

**Comment by licdar87** [comment]
Sorry I couldn't answer earlier.

> Still no luck. A few questions if you don't mind.
> 
> 1. Do you only experience the issue on 1.5x speed?
> 2. Have you tried without all extensions, besides Global Speed disabled? (Might be a conflict with another extension).
> 3. Have you tried re-installing Global Speed?

1. I just made some tests, apparently it happens with any speed > 1.0 (it happens even with 1.02)
2. I disabled all extension bar GS, but it still happens. Obviously, if I disable GS the problem is gone
3. Yes I tried, unfortunately it didn't fix the problem

As a side note,  I've been using the same computer and never had a problem with the extension. Apart from the automatic Windows and Edge updates, everything is the same

**Comment by polywock** [comment]
Hi. I've added a label asking if anyone else was experiencing the issue. So far, no response. Although, it's not 100%, the issue is probably related to your environment, conflicts, cache, etc. 

A quick test, if you don't mind. 

1. Go to `edge://settings/profiles` and click on Add Profile on the top right. 
2. Once created a separate profile, install Global Speed and try to reproduce the issue.

**Comment by licdar87** [comment]
> Hi. I've added a label asking if anyone else was experiencing the issue. So far, no response. Although, it's not 100%, the issue is probably related to your environment, conflicts, cache, etc.
> 
> You can test this out by trying Global Speed on a new Edge profile.
> 
> 1. Go to `edge://settings/profiles` and click on Add Profile on the top right.
> 2. Once created a separate profile, install Global Speed and try to reproduce the issue.

Hey there, I did as you asked. I created a new profile and downloaded the GS extension, nothing else. Then I logged in my Youtube account and started watching some shorts. The problem is still there, I'm linking a short video I made depicting the problem (made while using the new profile).
If nobody else has encountered this problem, there's likely something wrong with my environment, however I can't figure out what it could be since I've been using GS on the same machine for years without any problem. Not much has changed since then, aside from the usual windows/drivers/apps updates, and some new games installed.

My specs:
AMD Ryzen 5 3600X 6-Core Processor 3.80 GHz
RAM 16,0 GB
Radeon Rx580 series
Windows 11 Pro 23H2 Build 22631.3447
OS installed on SSD Samsung 860 Evo

And this is the link to the video: https://youtu.be/6574-_ha6FM

**Comment by polywock** [comment]
Definitely a weird issue. I can't do much without being able to personally reproduce it, but I'll be uploading a new update in late May. About 70% of the codebase is different, so hopefully the issue was accidentally fixed. 🤞

**Comment by licdar87** [comment]
Update: It seems this problem has disappeared somehow, and once again I'm clueless as I didn't change anything. But the good thing is this is now fixed, hopefully forever. I'm gonna close the issue, thanks again for the support.

**Comment by polywock** [comment]
@licdar87 Great to hear! Hopefully all my issues resolve this way.
