### ISSUE TITLE
Optional speed shortcut in menu

### ISSUE THREAD

**Issue by hourmor** [polywock/globalSpeed#49]
Can I set my **_preferred speed shortcut_** in menu, such as shortcut like "1.0 2.0 3.0 4.0 ". Furthermore , the step can be set as 0.5. Love this extension, hope your rely.

**Comment by polywock** [comment]
Sounds useful. Just made the speed presets and step amounts configurable.  But, it may take me a while to publish. I don't publish updates too frequently. 

![](https://user-images.githubusercontent.com/31208859/99755745-87c3bb00-2ab9-11eb-910e-ac47813b5624.png)

**Comment by hourmor** [comment]
Thx your reply, it worth waiting
