### ISSUE TITLE
FirefoxExtensionProblemSince2.6.0

### ISSUE THREAD

**Issue by WPFGit-hub** [polywock/globalSpeed#50]
Hi,good tool!
But your extension for Firefox doesn't work since the version 2.6.0 released on 29th Jul 2020. On the option page of the extension, I can't see anything and the menu doesn't show when clicking the entension icon on the extension bar of firefox. And my Firefox are 67.0.4 and 72.0.2,both have the problem.

**Comment by polywock** [comment]
Thanks for the feedback. It should work on the latest update (2.7.1). If it doesn't, let me know.
