### ISSUE TITLE
- hotkey disappeared

### ISSUE THREAD

**Issue by gmelcher3889** [polywock/globalSpeed#502]
Since the last update the "-" key disappeared. I can only set hotkeys to be equal to a value or "+"

**Comment by polywock** [comment]
Hello. You can set a negative value while in + mode to decrease value. That's how it always worked. Unless I'm misunderstanding the issue.

**Comment by gmelcher3889** [comment]
Thanks! For some reason the update had made the - disappear but now it's working again. Thanks!

**Comment by polywock** [comment]
Ah, I got the problem. The shortcuts didn't migrate to the new version correctly. Apologies for the inconvenience. You can add - to fix the issue. 

I can't correct through an update so people will have to manually fix it. Good thing I only rolled the update to 10% of users.
