### ISSUE TITLE
设置速度 "=" 快捷键的问题

### ISSUE THREAD

**Issue by ghcyp** [polywock/globalSpeed#503]
在之前的版本中,快捷键设置速度 "=" 时,可以从当前页面的速度直接转为预设的值,再按一次快捷键就可以重新回到页面当前的速度,比如,我预设的快捷键为 "S"  默认值为 "1.5" ,我当前页面速度为' 3 '时,我按下快捷键后,页面速度变为 ' 1.5 ',当我再按一次 ' S ' 时  页面速度会重新变为 '3',但插件更新后这个功能似乎被负优化了,无论我按下多少次快捷键,页面的速度都是默认值,没有之前的模式好用,希望可以重新上线之前的模式!

**Comment by ghcyp** [comment]
还有就是,如果我想体验最新版本以外的Gobal speed时  我可以去哪里下载安装

**Comment by ghcyp** [comment]
求教Gobal speed的历史版本的仓库是什么

**Comment by polywock** [comment]
Hello. I rewrote the entire extension for the latest update. I must have missed this. Here's the fixed version. It should be published in the Chrome Web Store within a week. Here's downloadable version for now. 

[packed.zip](https://github.com/polywock/globalSpeed/files/15424779/packed.zip)

Let me know if you still need the old version.

**Comment by ghcyp** [comment]
> 您好。我重写了整个扩展程序以进行最新更新。我肯定错过了这个。这是修复版本。它应该会在一周内发布在 Chrome 网上应用店中。这是目前可下载的版本。
> 
> [打包.zip](https://github.com/polywock/globalSpeed/files/15424779/packed.zip)
> 
> 如果您仍然需要旧版本，请告诉我。
![Snipaste_2024-05-24_10-51-11](https://github.com/polywock/globalSpeed/assets/128791486/b5efc818-81f1-47b6-beef-5218c3a25969)
感谢您的帮助,当我使用您提供的压缩包的时候,每次我使用这个功能时都会出现图片上的错误,我不确定是否还存在未知的bug,但您提供的压缩包确实解决了我的问题,,如果可以的话,我希望能知道旧版本的下载途径,以便当我遇到类似的问题时可以回滚到问题之前的版本,再次感谢您的帮助

**Comment by ghcyp** [comment]
> Hello. I rewrote the entire extension for the latest update. I must have missed this. Here's the fixed version. It should be published in the Chrome Web Store within a week. Here's downloadable version for now.
> 
> [packed.zip](https://github.com/polywock/globalSpeed/files/15424779/packed.zip)
> 
> Let me know if you still need the old version.

您好,在我使用的过程中,我发现了新的问题,您向我提供的压缩包存在非常严重的bug,在使用上述的功能时,视频的播放变的很奇怪,默认的倍速和回滚之前的倍速交替出现,可以理解为视频上一秒是 "1.5"倍,下一秒就变成了"3"倍,并且一直重复

**Comment by polywock** [comment]
Here's the old version: [old.zip](https://github.com/polywock/globalSpeed/files/15427471/packed.zip). However, I recommend eventually moving to the new one. The old uses Manifest V2, which Chrome says they will depreciate very soon.  It might last another six or more months. 


That error message with the extension context invalidated is normal and should be ignored. 

> The default speed and the speed before rolling back appear alternately. It can be understood that the video is "1.5" times in the previous second, and becomes "3" times in the next second, and it keeps repeating.

You might have two versions of Global Speed installed and they're fighting for control.

**Comment by ghcyp** [comment]
> 这是旧版本：[old.zip](https://github.com/polywock/globalSpeed/files/15427471/packed.zip)。不过，我建议最终还是换到新版本。旧版本使用 Manifest V2，Chrome 表示很快就会弃用该版本。它可能还能用六个月或更长时间。
> 
> 扩展上下文无效的错误消息是正常的，应该被忽略。
> 
> > 默认速度与回滚前速度交替出现，可以理解为视频上一秒是“1.5”倍，下一秒就变成“3”倍，不断重复。
> 
> 您可能安装了两个版本的 Global Speed，它们正在争夺控制权。请确保只启用了一个版本的 Global Speed，然后刷新您的标签。

感谢您的帮助,我的问题已得到妥善解决
