### ISSUE TITLE
URL Rules not working 

### ISSUE THREAD

**Issue by SupLiCatinG** [polywock/globalSpeed#505]
I have this rule, normally it should force every website to 2x speed as the old version does. But in the newest version when i set 1x speed with hotkey it stays like that 
I said in the title not working but (off) rule works. 

![image](https://github.com/polywock/globalSpeed/assets/94017480/0e41fc49-d343-4d04-a952-294d7fde40eb)

![image](https://github.com/polywock/globalSpeed/assets/94017480/2e0babf8-acba-4942-a602-acb746fa66e6)
![image](https://github.com/polywock/globalSpeed/assets/94017480/ba2a2a0e-4728-4819-a118-2fd7a8b61e23)

**Comment by polywock** [comment]
Hello. You can update to the latest version to fix this issue. I've only rolled the update to 10% of users, so you might not get it automatically. To manually update, go to `chrome://extensions`, enable developer mode, and click on Update. 

You can now click on the 3 dots near the delete button to change the "strictness". There's 4 levels, i've made the new default '2'. For your use case, either level 2 or 3 will be ideal. 

```txt
strictness 1: Apply only the first time the URL matched. 
strictness 2: Re-apply if domain name is different. (new Default) 
strictness 3: Re-apply every page load.
strictness 4: Re-apply every time URL
```

**Comment by SupLiCatinG** [comment]
Thanks for quick solution, i updated and it seems to be working. Strict level 3 works like the old the.
