### ISSUE TITLE
Acceleration Function Not Working After Update (2024/5/25)

### ISSUE THREAD

**Issue by xiaoliou008** [polywock/globalSpeed#506]
**Issue:** Acceleration Function Not Working After Update (2024/5/25)

**Description:**
After the automatic update today (2024/5/25) to version 3.0.7, the acceleration function of the plugin is no longer working. The accelerated playback feature is not functioning in Google Chrome. I tested this on multiple video platforms including YouTube and Bilibili, but the acceleration feature does not work on any of them.

**Steps to Reproduce:**
1. Update the plugin to version 3.0.7.
2. Open Google Chrome.
3. Try to use the accelerated playback feature on YouTube or Bilibili.

**Expected Behavior:**
The videos should play at an accelerated speed as per the user's settings.

**Actual Behavior:**
The videos play at normal speed, and the acceleration feature does not work.

**Environment:**
- Plugin version: 3.0.7
- Browser: Google Chrome
- Platforms tested: YouTube, Bilibili
- Language: Chinese (Simplified)

**Additional Information:**
Many users have also reported in the Google Chrome Web Store that the acceleration function stopped working after today's update.

**Request:**
Please fix this issue. Alternatively, provide instructions on how to revert to the previous version of the plugin.

![image](https://github.com/polywock/globalSpeed/assets/32353310/e363d361-0c20-4df7-8c1f-acdb70fba8c7)

![image](https://github.com/polywock/globalSpeed/assets/32353310/80e98517-e4b7-40b9-a1be-b7233a03100a)

**Comment by polywock** [comment]
Hello. Can you tell me which Chrome version you're on?

**Comment by xiaoliou008** [comment]
> Hello. Can you tell me which Chrome version you're on?

My Chrome version is 109.0.5414.75

**Comment by polywock** [comment]
Hello. The issue seems to be the Chrome version. The new update requires a modern version of Chrome. I'll look into adding  a fix for the old version, but I recommend updating Chrome.

**Comment by polywock** [comment]
@xiaoliou008 Hello. I've updated the extension to support Chrome > 104. The update might take a few days to get approved. You can update Chrome for an immediate solution.

**Comment by xiaoliou008** [comment]
> @xiaoliou008 Hello. I've updated the extension to support Chrome > 104. The update might take a few days to get approved. You can update Chrome for an immediate solution.

Thank you, I've updated the Chrome to version 121 and it solved the issue.
