### ISSUE TITLE
🔴 速度 - 设置为值，出现 BUG

### ISSUE THREAD

**Issue by Thomas-Harrell** [polywock/globalSpeed#507]
速度会在快捷键当前设定值「1」和视频上一个使用过的速度「1.25（举例）」间来回切换

<img width="883" alt="SCR-20240527-djsd" src="https://github.com/polywock/globalSpeed/assets/106761803/ddb0cf9e-c01d-499e-b816-33dad3303fcd">

**Comment by polywock** [comment]
Hello. This was fixed in the latest version. The update is being gradually rolled out, so you might not have received it yet. 

1. Go to `chrome://extensions`
2. Enable Developer mode. 
3. Click Update.

**Comment by polywock** [comment]
@Thomas-Harrell Can you explain more about the bug?

**Comment by polywock** [comment]
> I kinda forgot if this feature was originally designed this way, or if it was a bug

It was originally designed that way, but in the next update, I'll add an option to disable the automatic toggle.

**Comment by polywock** [comment]
Option added in 3.0.986

![Screenshot 2024-05-30 at 3 59 45 PM](https://github.com/polywock/globalSpeed/assets/31208859/9d6139d5-8d34-449f-b43b-f9f7c1879a95)

**Comment by polywock** [comment]
Always happy to help!
