### ISSUE TITLE
可以把速度-设置为值的功能调整回原来的版本吗

### ISSUE THREAD

**Issue by awesomepeppa** [polywock/globalSpeed#508]
即按下对应键后速度可以在设定值和上一次使用过的值之间来回切换的功能。这比只是重置回设定值更实用，因为你使用中不需要多次按下一个键来回到同一个设定值。

**Comment by polywock** [comment]
Hi. That was fixed recently. I've only rolled the update to 10% of users so you probably won't automatically get it. To update, go to `chrome://extensions/`, enable Developer mode and click `Update`. After updating, you can turn off developer mode.

**Comment by awesomepeppa** [comment]
我的意思是想使用原来的功能，有没有什么方法可以恢复到原来的版本？

**Comment by polywock** [comment]
It's still not working for you? If so, can you provide your browser and Global Speed version?

**Comment by polywock** [comment]
Here's the old version if you want to download it. 

https://github.com/polywock/globalSpeed/issues/503#issuecomment-2128499314
