### ISSUE TITLE
White/black square in the middle of chrome tab

### ISSUE THREAD

**Issue by srprizma** [polywock/globalSpeed#510]
![image](https://github.com/polywock/globalSpeed/assets/116825420/be01ccb0-de5a-4baa-b3a7-1e208455d434)
![image](https://github.com/polywock/globalSpeed/assets/116825420/7972faf6-17af-4273-aa23-a53dc6f6f303)
![image](https://github.com/polywock/globalSpeed/assets/116825420/b7966ac1-d863-4920-b3f4-0735fcf80181)

When Global Speed is turned on this square appears. If I turn on dark mode it goes small or just black.

Chrome Version 125.0.6422.77 (Official Build) (64-bit)
Global Speed Version 3.0.8

**Comment by polywock** [comment]
Very interesting. For some reason, it's not showing for me. If it's no bother, can you turn off all extensions other than Global Speed and then refresh the page. There might be a conflict with another extension.

**Comment by srprizma** [comment]
You're right!

It conflicts with Super Dark Mode Version 5.0.5.1
![image](https://github.com/polywock/globalSpeed/assets/116825420/42814ad5-ebc0-472e-8af7-afaba1e5a4c3)
https://chromewebstore.google.com/detail/super-dark-mode/nlgphodeccebbcnkgmokeegopgpnjfkc

**Comment by polywock** [comment]
Hello. I've addressed this issue in the latest version (3.0.986). To update, open chrome://extensions, enable Developer mode, and press Update to forcefully update to latest version.

**Comment by polywock** [comment]
Always happy to help! Thank you for reporting the issue!
