### ISSUE TITLE
关于项目中存在console.log

### ISSUE THREAD

**Issue by HCenggel** [polywock/globalSpeed#511]
希望删除一下项目中存在的console.log
![image](https://github.com/polywock/globalSpeed/assets/24600623/29c70fef-1a12-4c5e-a3f9-71caf5cafab7)
这个对程序员不友好。

**Comment by polywock** [comment]
Hi. Already removed in one of the later versions. To update, you can go to `chrome://extensions`, enable Developer mode and press Update.
