### ISSUE TITLE
希望仍可以像 Youtube 按住 Space 可以暫時2倍快轉功能，放開回原倍速

### ISSUE THREAD

**Issue by amanteae** [polywock/globalSpeed#513]
雖然Global speed設 HotKey 可以作到 2x 倍播放，但是有時候只想要快轉一下，一直按不是很方便。
像Youtube 可以按住 space 就可以暫時 2X 播放，放開就回到原倍速 （可能是1x 或其他 1.25x 等)
希望Global Speed 也有類似功能，長按space (或其他hotkey)就暫時可以快轉到<自設> 倍速，放開要回到原來設定的倍速

**Comment by polywock** [comment]
Hello. I've added support for this in the latest version (3.0.986). To update, open `chrome://extensions`, enable Developer mode, and press Update to forcefully update to latest version. 

Once updated, from the shortcut menu, select "presets", and afterwards select "Temporary speed". This will create 3 shortcuts that work in harmony all set to KeyG. If you change the shortcut, make sure to change it for all of them. 

![screenshot](https://github.com/polywock/globalSpeed/assets/31208859/e788102f-4fb5-4549-97ae-208da7871f0f)

**Comment by amanteae** [comment]
Thank you! You are genius！

**Comment by polywock** [comment]
😊 I wish! Always happy to help!
