### ISSUE TITLE
Speed changes have a noticeably increased delay after a recent update

### ISSUE THREAD

**Issue by tiggerbiggo** [polywock/globalSpeed#515]
Hi,

I think that something to do with a recent update (possibly https://github.com/polywock/globalSpeed/commit/0c31478c446dc39df43d8ae664ed602ce68dc096) has caused speed changes to become much laggier. When toggling or changing speeds rapidly, the speed takes a while to update.

This can be reproduced by setting a key to Set speed (=) with the toggle setting turned on. Increase the speed to a noticeable increase (say 2x), then hold down the toggle key. This will appear in the indicator to change the speed rapidly, but the video does not follow that, and takes much longer to update.

Yes, this is probably a case of https://xkcd.com/1172/ , I do apologise in advance :P

I know there are a variety of uses for this plugin, but its prime use for me is comedic, and rapid pitch / speed changes are something that I have come to use a lot when watching videos alone or with friends simply because it's funny.

I had a quick go at building it from commit 2847620cef0ec0deff1241dbd2ed0fda2b812bf2 before the somewhat recent changes to see if i can find the point where it broke, but I'm not on linux and WSL is throwing some weird errors so i've got to try again when I have time, possibly in a VM.

It seems these changes may have been for synchronisation, if this cannot be done without preserving the old behaviour I will probably persue building from an older version since I suspect that this sync fix will be deemed more important than my use case, which I understand.

Thanks :)

EDIT:

Some more info just in case, realised i missed out the basic stuff:

Windows: 10
Chrome: 123.0.6312.86
Global Speed: 3.0.987

**Comment by polywock** [comment]
Hi. I'm not 100% sure, but I believe those commits were only published in 3.0.988. To give the latest version a try, you can  go to chrome://extensions, enable Developer mode on the top right and press Update.  

> Yes, this is probably a case of https://xkcd.com/1172/ , I do apologise in advance :P

Also, I don't accept your apology. :)  PS: I miss the days when people use to reference xkcd comics all the time.

**Comment by tiggerbiggo** [comment]
Ah, it seems that the commit I referenced was probably a fix for this exact thing, given the timing changes. It's working the same as it did before whatever version change auto updated from the web store.

Regarding xkcd posting, I never see anyone else doing it but I have so many of the good ones memorised that there's always bound to be a situation where it comes up and I take advantage of that :P

Thanks for the plugin, it's awesome.

**Comment by polywock** [comment]
> Ah, it seems that the commit I referenced was probably a fix for this exact thing,

That's probably it. Another user previously reported the speed was changing slowly.  I'll probably lower the delay even further in the next update. 

> I know there are a variety of uses for this plugin, but its prime use for me is comedic, and rapid pitch / speed changes are something that I have come to use a lot when watching videos alone or with friends simply because it's funny.

By the way, there's a new shortcut combination that might be helpful here. From the list of shortcuts you can create, there's an option called "presets...", once selected, you will have an option to create a "temporary speed" combination. It's three shortcuts that are set to the G key. While you hold down G key, it will play on 3x speed, and once you release, it will go back to your previous speed. If you change the shortcut key, make sure to change for all three.
