### ISSUE TITLE
在特定的网页使用快捷键无法打开Global Speed

### ISSUE THREAD

**Issue by ref-y** [polywock/globalSpeed#518]
Chrome在更新到新版本之前，我可以通过自定义快捷键`shift`+`A`在需要的网页上切换GS的状态，
![image](https://github.com/polywock/globalSpeed/assets/30405700/22a3ec60-6107-489c-bf4b-9a6ec2ad8514)
更新之后，不能使用快捷键打开GS，例如在 https://www.facebook.com/watch/?v=220294766913114
若不想在url中，添加facebook.com，因为很少使用fb，应该如何设置呢？

**Comment by polywock** [comment]
Hi. The status shortcut can only be used to turn on the extension if it was last turned off using the same shortcut. For example, if you shut down Global Speed using the UI menu, the shortcut will not work. 

I'll look into adding an option so that the status shortcut always work, no matter what.
