### ISSUE TITLE
请问能否使用非全局快捷键来控制PIP视频浮窗

### ISSUE THREAD

**Issue by XMB-7** [polywock/globalSpeed#519]
当把视频以PIP模式播放时, 即便已点选浮窗使之聚焦了, 仍无法使用插件的快捷键来对视频播放进行控制. 
简单在issue区搜了一下, 从#134看, 似乎只有通过设置全局快捷键才能控制PIP, 不知是否确实如此, 有无变通的实现方式?

p.s. 设置全局快捷键会妨碍我在其它软件里使用相同的按键, 所以并不想设置全局快捷键.

**Comment by polywock** [comment]
Hi. If you mean while outside the browser, then no, it's not possible without global shortcuts.  Local shortcuts are only active while you're focused on a page that has Global Speed loaded. 

Would popout controls be helpful? The controls can have the standard controls like play, seek -10, seek +10 buttons, etc. However, it's not possible to make it always visible, like PiP.

**Comment by XMB-7** [comment]
> Local shortcuts are only active while you're focused on a page that has Global Speed loaded.

所以, 以PIP模式播放视频时, 插件其实并未加载, 我这么理解没错吧? 如果是这样, 那真的没办法了.
感谢回复, 看来还是得用ahk之类的对非浏览器的软件写一个按键重映射的脚本.

**Comment by polywock** [comment]
> 所以, 以PIP模式播放视频时, 插件其实并未加载, 我这么理解没错吧?

That's right. Let me know if there's anything else. Always happy to help.
