### ISSUE TITLE
Would it be possible to add a negative audio delay ? :)

### ISSUE THREAD

**Issue by rattlesnake2028** [polywock/globalSpeed#52]
It's amazing but I can't use it as I want with my airplay device.
Please can you add the option to use a negative audio delay ?

Like this plugin for youtube https://chrome.google.com/webstore/detail/youtube-audiovideo-sync/mknmhikmjljhpccebpnplhicmcfjkgbk?hl=en

I would be pleased to donate !
Seb

**Comment by polywock** [comment]
Unfortunately, I cannot think of a practical and general implementation. That extension's approach will only work for Youtube. 

Thanks for the suggestion.
