### ISSUE TITLE
3.0.992 会导致Home Assistant页面加载不出来

### ISSUE THREAD

**Issue by Antecer** [polywock/globalSpeed#520]
如题，禁用这个插件就正常了。

**Comment by polywock** [comment]
Hello! Can you provide a link?

**Comment by Antecer** [comment]
yeah, you can see here:

https://demo.home-assistant.io/#/lovelace/0

**Comment by polywock** [comment]
Seems to load fine for me. Maybe it's Global Speed + Something else that are conflicting.

**Comment by Antecer** [comment]
But i test it already closed all other plugins:
![image](https://github.com/polywock/globalSpeed/assets/8684916/819c7207-ab1f-40d3-b5d5-bc6afd056664)
![image](https://github.com/polywock/globalSpeed/assets/8684916/f5fb3aa5-4657-449f-965f-f65192e5d68c)

only when i close `Global Speed` or set it `run until click`, the page can open normal.

**Comment by Antecer** [comment]
> What Chrome version are you on?

125.0.6422.142

**Comment by Antecer** [comment]
Chrome update to 126.0.6478.62, then it work normal!

**Comment by polywock** [comment]
So weird. I've managed to reproduce the error once but couldn't reproduce it again. Maybe it depends on some context. Well, glad to see it's no longer any issue. Let me know if the issue resurfaces.
