### ISSUE TITLE
[BUG?] Global shortcut doesn't work in Arc (chromium based browser) split-screen

### ISSUE THREAD

**Issue by msf999** [polywock/globalSpeed#523]
Hi,

Thanks for the awesome extension! Everything works fine on Arc (Mac) including using global shortcuts while focused on another application, but using global shortcuts in split-screen doesn't work, e.g. if you have youtube in one part of the screen and taking notes on the other part then the global shortcut doesn't work unless you are focused on the youtube screen.

I am aware that this is probably a niche use-case, but thought others might have come across the same issue. It could also be an issue with Arc rather than the extension..

Thanks.

**Comment by msf999** [comment]
I tried using the split screen feature of Edge and found the same problem.

I then tried having two windows of Chrome side by side with one playing a Youtube video while I took notes on the other (Notion). The global seek shortcut I set worked fine while I was focused on the youtube window (or while being focused on any other application), but did not work while I was focused on the Notion window.

Is this a technical limitation that can't be circumvented? Thanks.

**Comment by polywock** [comment]
Hello. Can you confirm if both sides don't work, or just the right side? As you mentioned, the issue seems similar to Edge, and Edge only detects the left side during split mode.

**Comment by msf999** [comment]
I just tested and having the video on the left side worked on Edge! However on Arc the left side doesn't work as well.

Thanks for the quick response.

**Comment by PureSouIs** [comment]
有没有人能搭理一下我的问题啊，或者说有没有大佬能分享一下第三方镜像网站下载回以前的版本的方法啊，拜托了，我真的很需要

**Comment by polywock** [comment]
@PureSouIs Replied to the other post. Apologies for the late reply.
