### ISSUE TITLE
Change permissions to `activeTab` rather than all sites.

### ISSUE THREAD

**Issue by MicahZoltu** [polywock/globalSpeed#53]
I don't want to give this plugin access to read/write to every site I visit for security reasons, but I do want to be able to use it.  The easiest way to accomplish this is to use the `activeTab` permission rather than `https://*/*` permission.  This way the plugin will only inject into pages when I click the icon rather than auto-injecting into every page I visit.

**Comment by polywock** [comment]
Are you on Chrome or Edge? You should be able to change the SIte Access to "When you click...".

![a](https://user-images.githubusercontent.com/31208859/104104214-ba499300-5274-11eb-9ae0-1bf1f7a39e25.png)

I've considered the `activeTab` permission in the past, but decided against it for a few reasons. 

1. It's more inconvenient if you prefer a non-1x default speed. 

2. `activeTab` only lets an extension inject a script into the main scope. This would break support for classroom sites, show & movie streaming sites, Youtube embeds, etc. 

3. For another reason (timing issues), it would also break support for Spotify, Soundcloud, Amazon Music, podcast sites, etc.

**Comment by MicahZoltu** [comment]
I'm on Firefox which doesn't have that option, sadly.

I'm aware of (2) that you mention, I created a bug to get that fixed (for totally unrelated reasons) but it is unclear if it will be or when.

(3) is quite unfortunate.  I didn't realize you had to be in first.

As a work around, any chance you could publish a zip version of the build in releases so I can just manually edit the manifest locally?  I tried building it myself (to do just this), but it doesn't build on Windows and I quickly gave up.

**Comment by polywock** [comment]
Yeah, mac/linux commands (`find`, `cp`, `rm`, `zip` are used during the build step).  If all need is speed control. Here's a bookmarklet you can use.  ASD keys to control speed.  

```javascript
javascript:(() => {
  let speed = 1;
  let indicator; 
  let indicatorTimeout;

  function createIndicator() {
    indicator = document.createElement("div");
    indicator.setAttribute(`style`, `
    position: fixed;
    left: 15px;
    top: 15px;
    background-color: black;
    color: white;
    font-size: 20px;  
    padding: 10px;
    display: none;
    z-index: 99999999999999;
    `);
    document.body.appendChild(indicator);
  };

  function show(text) {
    if (!indicator) createIndicator();
    indicator.innerText = text;
    indicator.style.display = "block";
    indicatorTimeout && clearTimeout(indicatorTimeout);
    indicatorTimeout = setTimeout(() => {
      indicator.style.display = "none";
    }, 5000);
  }

  function round(value, precision) {
    const scalar = 10 ** precision;
    return Math.round(value * scalar) / scalar;
  };

  function conformSpeed(value) {
    return Math.min(Math.max(value, 1 / 16), 16);
  };

  function syncSpeed() {
    document.querySelectorAll("video").forEach(video => {
      video.playbackRate = speed;
    });
  };

  function changeSpeed(value) {
    speed = conformSpeed(value);
    show(round(speed, 2).toString());
    syncSpeed();
  }

  setInterval(syncSpeed, 3000);

  window.addEventListener("keydown", e => {
    if (e.code === "KeyA") {
      changeSpeed(speed - 0.1);
    } else if (e.code === "KeyS") {
      changeSpeed(1);
    } else if (e.code === "KeyD") {
      changeSpeed(speed + 0.1);
    } 
  }, {capture: true});
})()
```

Bookmarklet is preferred, but here's the zip just in case. Editing to `activeTab` would be hard as you'll need to edit the code as well to inject the content script. Instead I recommend changing the `https://*/*` permission to `https://youtube.com/*` or whatever. 

[packed.zip](https://github.com/polywock/globalSpeed/files/5791893/packed.zip)

**Comment by MicahZoltu** [comment]
Thanks!  I need something that works with Spotify, so I suspect the bookmarklet won't work for me (for the reason you alluded to above).  None the less, I'll definitely add this bookmarklet to my bookmarks for everything else!
