### ISSUE TITLE
Plugin will make reddit page appear blank

### ISSUE THREAD

**Issue by vnsnclo** [polywock/globalSpeed#530]

**Comment by polywock** [comment]
Hello. I can't replicate this issue. Can you tell me more about your browser and Global Speed version?

**Comment by vnsnclo** [comment]
The browser version is Chrome 126.0.6478.127, and the GlobalSpeed version is 3.0.992. The strange thing is that I can only load Reddit pages normally if I completely disable GlobalSpeed on the manage extensions page. Even if I just turn it off without disabling it, Reddit still loads as a blank page, like shown below.
![1](https://github.com/polywock/globalSpeed/assets/120261584/d798d6c5-2d53-4362-a8af-4b0a414ae39d)
![2](https://github.com/polywock/globalSpeed/assets/120261584/6e084ec3-6315-4e21-b409-fa2b361b6389)

**Comment by kevinhwang91** [comment]
It has confused me for a long time. As a workaround, I only remove the extension, and then install it after rebooting chrome, which will make reddit work again.

**Comment by polywock** [comment]
I've figured out the issue that prevents Reddit from loading, but not the root cause yet. 

There seems to be a situation where the extension's different components cannot communicate with each other. I'm not sure if that's a Global Speed or Chromium issue as I cannot reliably reproduce it. 

Anyway, Reddit shouldn't have any issues loading in next update.

**Comment by kevinhwang91** [comment]
[www.reddit.com-1719551005138.log](https://github.com/user-attachments/files/16024350/www.reddit.com-1719551005138.log)
Here is the console log, I hope it will help.

**Comment by polywock** [comment]
@kevinhwang91 Thanks! I published the fixed version and it'll probably take a few days to get approved. 

A question: On sites other than Reddit, does Global Speed still work?

**Comment by kevinhwang91** [comment]
> A question: On sites other than Reddit, does Global Speed still work?

Yes, only reddit. Blank screen after reloading components.

**Comment by polywock** [comment]
Update got approved (3.0.994). Restarting Chrome should automatically update Global Speed. 

@kevinhwang91  @vnsnclo After updating, let me know if Reddit still shows a blank screen.

**Comment by kevinhwang91** [comment]
> Update got approved (3.0.994). Restarting Chrome should automatically update Global Speed.
> 
> @kevinhwang91 @vnsnclo After updating, let me know if Reddit still shows a blank screen.

It works fine with reddit.

**Comment by vnsnclo** [comment]
> Update got approved (3.0.994). Restarting Chrome should automatically update Global Speed.
> 
> @kevinhwang91 @vnsnclo After updating, let me know if Reddit still shows a blank screen.

perfect
