### ISSUE TITLE
希望添加一个网页视频长按倍速的效果（Would like to add a long press multiplier for web videos）

### ISSUE THREAD

**Issue by KuchenLee** [polywock/globalSpeed#533]
----中文（Chinese）-----
比如长按键盘“←”键实现2x快退效果，长按键盘“→”键实现2x快进效果，并且支持自定义长按“快进”和“快退”的速度，也支持自定义某个页面生效。
希望开发者人员添加此功能，万分感谢！

-----English（英文）-----
For example, long press the keyboard "←" key to achieve 2x fast rewind effect, and long press the keyboard "→" key to achieve 2x fast forward effect. It also supports customizing the speed of long press "fast forward" and "fast backward", and also supports customizing the effect of a certain page.
I hope the developer will add this long press multiplier, thanks a lot!

**Comment by polywock** [comment]
Possible on latest update. Currently only available on Chrome while being tested. I'll upload to Edge in a few weeks and Firefox in two months. 

Are you on Edge? You can try out the latest version by installing from the Chrome store.  

https://chromewebstore.google.com/detail/global-speed/jpbjcnkcffbooppibceonlgknpkniiff


Once updated, you can create a shortcut (Presets -> Temporary speed shortcut). 

![img](https://github.com/polywock/globalSpeed/assets/31208859/6c5d30a7-6b5a-4cd7-905f-5566401e322a)

**Comment by KuchenLee** [comment]
thank u, sir! I am on Edge as you say. I'll try it later.

**Comment by KuchenLee** [comment]
> thank u, sir! I am on Edge as you say. I'll try it later.

now that i have tried the method you taught me, I think it has solved my problem. thk u😀

**Comment by polywock** [comment]
Great to hear! If you run into any issues with the latest update, let me know.

**Comment by KuchenLee** [comment]
okay i will
