### ISSUE TITLE
新功能提出：画中画默认播放尺寸为最小比例。

### ISSUE THREAD

**Issue by MAKER555** [polywock/globalSpeed#534]
新功能提出：画中画默认播放尺寸为最小比例。小窗的比例太大的话，如果上班时候被上司看到了，会有些尴尬。New feature proposed: Picture in Picture default playback size is the minimum ratio. If the proportion of small windows is too large, it may be awkward for the boss to see them at work

**Comment by polywock** [comment]
Hi. The picture-in-picture window is not not controllable in any way. Extensions can only open, close them, and check their size (but not change the size).

**Comment by MAKER555** [comment]
好的，明白了，谢谢
Okay, I understand. Thank you
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月4日(星期四) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] 新功能提出：画中画默认播放尺寸为最小比例。 (Issue #534)





 
Hi. The picture-in-picture window is not not controllable in any way. Extensions can only open it, close it, and check their size (but not change the size).
