### ISSUE TITLE
On keypress showing keybind in console

### ISSUE THREAD

**Issue by JamesBond8088** [polywock/globalSpeed#538]
When ever a key is pressed, a console.log appears in console.
In isolated.js, the following lines occur
```
 handleKeyDown = e=>{
                if ("IFRAME" === document.activeElement?.tagName)
                    return;
                if (!chrome.runtime?.id)
                    return Ae.os.handleOrphan();
                if (!this.client?.view)
                    return;
                if (this.client.view.superDisable)
                    return;
                const i = this.client.view.enabled;
                let s = this.client.view.keybinds;
                if (!i && (s = this.client.view.keybinds.filter((e=>"state" === e.command && e.enabled && (e.trigger || v.LOCAL) === v.LOCAL && (this.client.view.latestViaShortcut || e.alwaysOn))),
                console.log("KEYBINDS: ,", s),
```
I think get rid of console.log works. Please fix it

**Comment by polywock** [comment]
It should be removed in the newest updates. Chrome has updated version already, testing before publishing the update for Edge/Firefox. 

Assuming you're on Edge.  

[packed.zip](https://github.com/user-attachments/files/16122069/packed.zip)

1. Disable original Global Speed. 
2. Download packed.zip and extract folder.
1. Open edge://extensions
3. Enable developer mode on the left side of the page.
4. Click Load Unpacked and select extracted folder.

**Comment by JamesBond8088** [comment]
> It should be removed in the newest updates. Chrome has updated version already, testing before publishing the update for Edge/Firefox.
> 
> Assuming you're on Edge.
> 
> [packed.zip](https://github.com/user-attachments/files/16122069/packed.zip)
> 
> 1. Disable original Global Speed.
> 2. Download packed.zip and extract folder.
> 3. Open edge://extensions
> 4. Enable developer mode on the left side of the page.
> 5. Click Load Unpacked and select extracted folder.

I have updated to the latest version of global speed Version 3.0.994 on Google Chrome, but the issue still persists.

**Comment by polywock** [comment]
@JamesBond8088 I was looking at the wrong project's source code. My mistake. 

I've published the fixed version, but it might take a few days for the update to get approved. 

Here's the packed version if you want to load it manually for now. 

[global-speed-chromium.zip](https://github.com/user-attachments/files/16122405/global-speed-chromium.zip)

**Comment by JamesBond8088** [comment]
Great, it works now. Thanks
