### ISSUE TITLE
Support for negative delay

### ISSUE THREAD

**Issue by 7UR7L3** [polywock/globalSpeed#54]
Would be useful for misaligned video/audio of a mp4 source.

I don't immediately see an alternative to a delayNode that would make this immediately possible, since delay nodes themselves enforce positive delays. But I also don't know much about the web audio api.

Is there any way to delay the video instead of the audio of a video element? Can you seek both directions in the audio stream to mimic the delay node as a more general audio shift? Or is this extension entirely on the tab-level and it only uses the audio output of the tab as a source and can't really do anything about this problem.

Just thought I'd ask! Awesome extension by the way. Thanks!

**Comment by polywock** [comment]
Thanks for the kind words. Unfortunately, I don't think a generic approach is possible. There's an [extension](https://chrome.google.com/webstore/detail/youtube-audiovideo-sync/mknmhikmjljhpccebpnplhicmcfjkgbk) that works for Youtube, but in their approach is Youtube only. They mute the video, and load a separate audio only stream with the time position shifted. Interesting approach, but hard to extend to other sites.
