### ISSUE TITLE
Global Speed is very controlling about the speed. It's very hard to determine if the user intended to change the speed or the website is doing it on it's own. That's why Global Speed requires the user change the speed through Global Speed's controls.

### ISSUE THREAD

**Issue by BARTZHENRON24** [polywock/globalSpeed#544]
Global Speed is very controlling about the speed. It's very hard to determine if the user intended to change the speed or the website is doing it on it's own. That's why Global Speed requires the user change the speed through Global Speed's controls. 

Personally, I use shortcuts to accomplish same thing. You can create a shortcut that sets speed to 4x. The first time you press it, speed will go to 4x. Second time you press it, it will go back to the original speed.

_Originally posted by @polywock in https://github.com/polywock/globalSpeed/issues/540#issuecomment-2226829531_

**Comment by polywock** [comment]
Hello. Are you having an issue? I'm having trouble understanding.
