### ISSUE TITLE
I need hotkey for pause button.

### ISSUE THREAD

**Issue by A3212** [polywock/globalSpeed#546]
I need hotkey for pause button.
Please do it if this is possible.

Мне нужна горячая клавиша для кнопки паузы.
Пожалуйста, сделайте это, если это возможно.

**Comment by A3212** [comment]
P.S.: addon firefox

**Comment by polywock** [comment]
Hello. A pause key is already available as an option. 

![Img](https://github.com/user-attachments/assets/d00b80df-bab2-4720-a944-4b7920dc54f4)

**Comment by A3212** [comment]
oh, sorry, my mistake.

Great thanks!
