### ISSUE TITLE
When I restart the browser, the pinning comes off by itself.

### ISSUE THREAD

**Issue by chiwati** [polywock/globalSpeed#552]
When I restart the browser, the tabs are unpinned even though they are set to pinned by default.

**Comment by polywock** [comment]
Hello. I fixed the issue and the update should be available within a week (at least on Chrome and Firefox).

**Comment by chiwati** [comment]
I was able to confirm that it is pinned.
However, the background of the icon is red instead of the pinned blue.

**Comment by chiwati** [comment]
I'm sorry.
I looked at it again after I wrote it and it was blue.
There seems to be a delay in reflection.
