### ISSUE TITLE
Version 3.0.997 stopped working on Firefox Nightly for Android

### ISSUE THREAD

**Issue by Rodze** [polywock/globalSpeed#553]
Version 3.0.997 stopped working on Firefox Nightly for Android

Video speed doesn't change anymore.

I know it's not officially available for Android, but the addon worked perfectly until this update.

Firefox 131.0a1 (Build #2016038743), hg-35292ed5ccd3+
GV: 131.0a1-20240815213144
AS: 131.20240815050258

**Comment by polywock** [comment]
Hello. Sorry about that. Testing on Firefox for Android is tedious so I typically skip it. Issue has been fixed and submitted for publishing. It's probably going to take a 5-7 days for approval.

**Comment by polywock** [comment]
@Rodze The update got approved. Let me know if the issue remains.

**Comment by polywock** [comment]
Great to hear! Let me know if there's any other issues.

**Comment by PaulAbrams36** [comment]
Great
