### ISSUE TITLE
更新至3.0.9984后，大部份快捷键不可用

### ISSUE THREAD

**Issue by S-T-eve** [polywock/globalSpeed#560]
edge128.0.2739.42 (正式版本) (64 位) ，插件自动更新至3.0.9984后，存在大部份快捷键不可用的情况，如图
![image](https://github.com/user-attachments/assets/b2e46202-5c05-4976-9dda-b1e135db4f51)
已经尝试过修改快捷键，改为全局快捷键，依然不可用

**Comment by S-T-eve** [comment]
已尝试重装插件，并排除网站问题的可能

**Comment by polywock** [comment]
Works for me on Edge 128 (Mac). Maybe a platform-specific issue. Does installing Global Speed on a new Edge profile fix the issue? 

1. Go to `edge://settings/profiles`
2. On the top right of page, click "Add profile". 
3. Install Global Speed on the new profile.

**Comment by S-T-eve** [comment]
已测试使用new profile，存在同样问题
通过第三方镜像回退到2.9.9971后可以正常使用

**Comment by ydfzgyj** [comment]
same question

**Comment by polywock** [comment]
@S-T-eve If you load a third-party image of the current version, do you see any errors when you press "Inspect"?

**Comment by S-T-eve** [comment]
没有任何内容
![image](https://github.com/user-attachments/assets/322bd1db-dcbc-4b96-8e7a-0592d01d043a)

**Comment by S-T-eve** [comment]
再次测试，确认了更多细节
把移动时间轴的Z,X快捷键改成A,D，并没有效果
把移动时间轴的Z,X快捷键改为方向键（arrow L,R），在youtube平台测试表现为会导致youtube原有的左右方向键移动时间轴无效，把全屏快捷键shift+F修改为F也表现为原有的F键全屏无效

**Comment by polywock** [comment]
In the options, there's a setting called "keyboard input" (or 键盘输入) that controls the keyboard input method. It's set to QWERTY by default, but what happens if you change it to virtual and rebind the shortcuts again?

**Comment by S-T-eve** [comment]
键盘输入改为虚拟并重新绑定快捷键后测试，Z,X移动时间轴和Shift+F全屏也是还是不起作用，另外也测试了改变速度的A,S,D依旧是正常的
可能问题不在于快捷键而是功能本身，在2.9.9971->3.0.9985改变了什么而导致了问题（2.9.9971没有出现任何问题，一切正常）

**Comment by S-T-eve** [comment]
![image](https://github.com/user-attachments/assets/304eff77-42fb-4ff6-a649-51726b1a8e51)

没有出现在媒体列表
另外顺便测试了速度滑块，速度改变音高，圆形小部件功能，没有问题

**Comment by polywock** [comment]
Interesting. On the Edge store, another person wrote a review saying the media list no longer works. It seems to be the same issue. 

Please do the following and let me know if there's any output or error. 

1. Open Global Speed options page. 
2. Right click on the page and click "Inspect"
3. Open the console tab. 
4. Enter the follow code

```
await chrome.storage.session.set({"woot": true});
await chrome.storage.session.get();
```

**Comment by S-T-eve** [comment]
![image](https://github.com/user-attachments/assets/b7a55045-c4bc-4c8d-8276-b5c1c2c8fe04)
没有任何东西

**Comment by S-T-eve** [comment]
> ![image](https://private-user-images.githubusercontent.com/53549980/363402771-b7a55045-c4bc-4c8d-8276-b5c1c2c8fe04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTY3OTYsIm5iZiI6MTcyNTA5NjQ5NiwicGF0aCI6Ii81MzU0OTk4MC8zNjM0MDI3NzEtYjdhNTUwNDUtYzRiYy00YzhkLTgyNzYtYjVjMWMyYzhmZTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDA5MjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyODM3M2JjMTNjNDdmMDE5ZGYyYWRkNjM4NGQxNjNmZGRmZWQ3YzA2M2UwNTgxMTJiOWU1YTU5NTM4NDlhYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AehJEdTQP8ZC8IhTkuJYU0R9Lbdrqf60QUiw34bGnQY) 没有任何东西

另外，在2.9.9971是有内容的
![image](https://github.com/user-attachments/assets/1cd1c89a-4eff-4027-a87f-ac141c295b80)

**Comment by polywock** [comment]
Root issue is now identified. It seems like the Session Storage Area is not available for you. Your Edge version is up to date so I'm not sure why that's happening. 

Do you have other extensions installed that also have an options page? If not, you can install uBlock Origin. Try going to the options page for that extension and trying the same code.

**Comment by LifeJustDLC** [comment]
uBO seems not using `chrome.storage.session`, might because they didn't declare the permission.
I only found Dark Reader use this, and it works:
![image](https://github.com/user-attachments/assets/a9e12959-0df0-4ac1-93c5-b9b82c9d27e8)

from 3.0.9985 installed from Edge store, it also works:
![image](https://github.com/user-attachments/assets/7592aeb7-1a45-4222-a101-6605cf02491f)

**Comment by polywock** [comment]
@LifeJustDLC I checked uBlock Origin's  `manifest.json` using Rob Wu's [CRX viewer.](https://robwu.nl/crxviewer/). uBO requests for the `"storage"` permission which gives access to all storage areas including session. Global Speed, and Dark Reader also requests for the same permission. The code I supplied above should work for all extensions.  

@S-T-eve You probably should report the issue to Edge. The `session` storage area (Web Extensions API) doesn't work on your computer for some reason.

**Comment by S-T-eve** [comment]
emmmm，我刚刚想起来可能edge://flags/里面我打开了什么，于是把flags全部重制了
然后全部恢复正常了，Z,X移动时间轴和shift+F全屏全部都能用了，控制面板用上面的指令也有内容了
![image](https://github.com/user-attachments/assets/f2147d08-13b0-4062-9617-6bd2033bac8a)
所以。。。。可能是什么flags开启后会产生冲突？？？

刚刚确定了，我开启了[#enable-experimental-web-platform-features](edge://flags/#enable-experimental-web-platform-features)导致了这个问题

**Comment by polywock** [comment]
@S-T-eve Yup, that's the one. Reproduced the issue after enabling that flag.

**Comment by PureSouIs** [comment]
有没有人能搭理一下我的问题啊，或者说有没有大佬能分享一下第三方镜像网站下载回以前的版本的方法啊，拜托了，我真的很需要

**Comment by PureSouIs** [comment]
有没有人能搭理一下我的问题啊，或者说有没有大佬能分享一下第三方镜像网站下载回以前的版本的方法啊，拜托了，我真的很需要
