### ISSUE TITLE
（功能需求）希望有一个启用/关闭“快捷键”的设置选项

### ISSUE THREAD

**Issue by ykqmain** [polywock/globalSpeed#568]
插件默认快捷键有单按键，经常误触（比如打字没有点到输入框，B站点赞Q、投币W），误触后不知道发生了什么，动了哪些设置，也不方便还原。

我一般使用鼠标点击需要的速度来用该插件，但又不想把每个默认快捷键都删掉，希望添加一个设置选项，可以启用或关闭快捷键。

**Comment by polywock** [comment]
Hello. Apologies for not replying earlier. 

I plan to add the requested feature. Probably in a few months.
