### ISSUE TITLE
Suggestion to Add Independent Speed Control Feature（建议添加独立速度控制功能）

### ISSUE THREAD

**Issue by luiguangguan** [polywock/globalSpeed#570]
I would like to suggest adding an independent speed control feature for each website. Users should be able to adjust the speed for individual websites, and there could also be an option to disable independent speed control. This would significantly improve the user experience.

**Comment by polywock** [comment]
Hello. I agree that it would be useful. I did try implementing this, but gave up. Fitting a website based system into the existing codebase was surprisingly complicated. For that reason, I probably won't be able to implement this.
