### ISSUE TITLE
Permanently Dismiss Notification

### ISSUE THREAD

**Issue by JustArion** [polywock/globalSpeed#573]
In the file [OrlHeader.tsx:13](https://github.com/polywock/globalSpeed/blob/master/src/popup/OrlHeader.tsx#L13) a notification is created but there is no way to permanently disable such notifications. By the looks of it, it is instantiated in [popup.tsx:14](https://github.com/polywock/globalSpeed/blob/master/src/popup/popup.tsx#L44).

Could an update introduce an option to permanently disable such notifications?

**Comment by polywock** [comment]
Hello. I've added a way to hide it, but the update is only available on Chrome right now. Might take a week for Firefox and Edge stores. Once you have the latest update...

1. Go to options page.
2. Scroll to the Help section and click "Help" repeatedly until the prompt box appears. 
3. Type in "toggle url banner" to hide it.
