### ISSUE TITLE
Old speeds?

### ISSUE THREAD

**Issue by babico** [polywock/globalSpeed#58]
Why did you delete 3x and others. I am using them :/

**Comment by polywock** [comment]
15 presets might be overkill now because they're now customizable in the options page. 

![nm](https://user-images.githubusercontent.com/31208859/107317823-6398ca00-6a69-11eb-927f-add3202ba368.png)

**Comment by babico** [comment]
It is nice that it can be customized, I am waiting excitedly.

**Comment by polywock** [comment]
It should already be implemented in the new update, under the hidden section.  My bad 😅.,  I should've mentioned that.

![](https://user-images.githubusercontent.com/31208859/107399945-4eef1d00-6acf-11eb-959a-c2d904f334dc.png)

**Comment by babico** [comment]
LUL :D
