### ISSUE TITLE
插件在使用URL规制设置为关闭状态下的视频播放中显示关闭的情况下启动。

### ISSUE THREAD

**Issue by forget-rain** [polywock/globalSpeed#585]
在有使用URL让插件在部分网页关闭的情况下，将这部分网页打开并播放的情况下，打开其它使用插件的网站播放视频并使用”A“和”D“调整倍速的情况下，插件处在关闭情况下的网页插件会莫名启动，我使用的是edge，具体为观看bilibili直播的情况下打开其它视频网站观看视频，一旦使用”A“和”D“调整视频倍速，正在播放的bilibili的直播页面会启动倍速，但插件显示是关闭状态，只能刷新网页或者视频才能关闭倍速。

**Comment by polywock** [comment]
Hello. Fixed in 22e5e8b. Update should be approved within a week.
