### ISSUE TITLE
Negative audio delay

### ISSUE THREAD

**Issue by will09122000** [polywock/globalSpeed#59]
I've added audio delay shortcuts in the settings but it won't let me bring the audio forward with negative audio delay. Would this be possible? Useful when using bluetooth speakers and there's a delay in the audio.

**Comment by polywock** [comment]
Not possible with Global Speed. But, there's an extension for Youtube that might help you. 

https://chrome.google.com/webstore/detail/youtube-audiovideo-sync/mknmhikmjljhpccebpnplhicmcfjkgbk
