### ISSUE TITLE
How did you make this pitch shifter do you know 

### ISSUE THREAD

**Issue by codeyr67** [polywock/globalSpeed#597]
hey polywock can you tell me how to make a pitch shifter or no is this easy to make because i want to able to make my own pitch shifter chrome extension i do without altering speed and i wanted to make a 12 semitone and 145.00 cents i do so can you tell me the instructions or no if you know how you made the pitch shifter and i am just starting i am i never ever made one before ever i never did

**Comment by codeyr67** [comment]
and i wanted to make it for youtube i do

**Comment by codeyr67** [comment]
and also wanted to make it ultra high quality too i do

**Comment by polywock** [comment]
Hello. If you have no coding experience, then very difficult. Global Speed uses a JS port of Soundtouch

**Comment by codeyr67** [comment]
is it just that or no and what do you mean by no coding experience
