### ISSUE TITLE
hey polywock will the low pitch go silent or no and will the high pitch have that original voice at the end with 7,332 semitones at the end or no because i would never want that i would not 

### ISSUE THREAD

**Issue by codeyr67** [polywock/globalSpeed#599]

**Comment by codeyr67** [comment]
and i only want it to go squeaky i would and with the low pitch that does not go silent just let it revert to -72 semitones or-60 semitones one of them

**Comment by polywock** [comment]
I've done some testing and anything above 100 is very unstable and crashes the entire extension. I'll have to lower the limit to 100.
