### ISSUE TITLE
[Bug] Indicator missing when in full screen

### ISSUE THREAD

**Issue by Nova38** [polywock/globalSpeed#6]
When I go to a website and full screen the video the indicator will occasionally not show up. I do not have problems with this feature on YouTube but seems not to work on other websites. Since all my classes have moved online I have been using your add-on to speed up lectures. These videos are usually just an mp4 file that is hosted online, nothing fancy. The rest of the add-on works: The videos speed changes, keyboard shortcuts are recognized, the indicator in the browser bar updates. When the videos are not full screened  the indicator that is overloaded on the website shows up. It is only when it is full screened that is is not present.

Love the work that you have done with this extension!
@polywock

**Comment by polywock** [comment]
😀 Thank you, @Nova38. As for the issue, I've considered this problem for a while now. But, couldn't come up with a solution I was happy with. 

### Current implementation 
The indicator is placed on the top of the document. CSS has a `z-index` property, roughly analogous to the xy**Z** dimension (depth), which lets you prioritize the element drawing order. I set the CSS `z-index` property to the max value.  In most websites that means it will show in front of the other elements.  

### Problem 
If an element is in real fullscreen (Youtube doesn't use the [`Fullscreen API`](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API)). Nothing outside of the root fullscreen element is shown, even if it has a high z-index value. I can only see two ways of showing an indicator in front of a fullscreen element. 

### Solution #⁠1
Listen to `fullscreenchange` events and move the indicator to the current fullscreen element. I've tested it, and it seems to work in most websites (except AppleTV). But, my problem with this method is that it's a bit invasive. I don't like moving elements deep in the document. Usually it's fine, but it may break a website or two. 

### Solution #⁠2
The [`:fullscreen`](https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen) CSS selector lets you select any fullscreen elements. I could use that with the combination of the[`::after`](https://developer.mozilla.org/en-US/docs/Web/CSS/::after) selector, which allows the creation of a psuedo element. The advantage of this is that I could get away with only placing a <style> tag on the top of the document.

I haven't implemented solution #⁠2 yet, but if it ends up working as expected. I'll go for that route. Either path I'll make optional in the config.

**Comment by Nova38** [comment]
Sounds great! Thanks for the details I appreciate the opportunity to learn more how it works.
