### ISSUE TITLE
[Feature Request] Ability to sync settings via chrome sync.

### ISSUE THREAD

**Issue by ShrirajHegde** [polywock/globalSpeed#60]
It would be nice if the custom settings created could be synced across devices.

**Comment by polywock** [comment]
I've given thought to syncing before, but decided it was too much work. Only 8kb could be synced for a single item. The default config size is around 3kb, but depending on user specific settings could go over 8kb. I'll need to spread the config information over several items to ensure it fits, which would require a pretty serious refactor of an already complicated part of the extension. And I'm too lazy for that. 

Also, you probably know of it. But, if you don't, there's an export/import feature that can help with syncing across devices. Not seamless as true syncing, but better than nothing. 

![](https://user-images.githubusercontent.com/31208859/107994436-a21f0f00-6faa-11eb-9f21-5d14d9dec08a.png)
