### ISSUE TITLE
Can you make it where it does not crash the entire extension or no and just keep 7,332 semitones up and down please 

### ISSUE THREAD

**Issue by codeyr67** [polywock/globalSpeed#600]
hey how about if you just do not let it go silent or do not let the high pitch have that original voice at the end either and just fix things a bit more so it does not crash

**Comment by codeyr67** [comment]
and i would not care about the human hearing i would not

**Comment by polywock** [comment]
Hello. Unfortunately, I cannot. The Soundtouch library is very advanced and I don't think I'll be able to make the necessary changes.
