### ISSUE TITLE
Weird Glitch + lag on brave browser

### ISSUE THREAD

**Issue by HornyPrivateGamer** [polywock/globalSpeed#602]
Using the newest version of brave that some time that even though have 1000mbs internet that the audio doesn't math and there is some time a stutter when change to preferred speed. Like from 1x to 2x 

like is it not always happen like 4/10 time it would happen that would be great to get it fix.

that sorry to say this, that i used video speed controller that has no problem like this please fix thanks. 

have a great day. 

[Version 1.70.126 Chromium: 129.0.6668.100 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by HornyPrivateGamer** [comment]
That this is extremly bad for 4k video in youtube

**Comment by HornyPrivateGamer** [comment]
@polywock 

ok i tested it. it is working on fire fox 

so this is a chromium problem that as it effect both brave and Chrome

Contact me sir if you wanted me send you a full video.

**Comment by HornyPrivateGamer** [comment]
That weird thing is that it doesn't really happen on every video some how

**Comment by HornyPrivateGamer** [comment]
![image](https://github.com/user-attachments/assets/ac73b7af-3bd0-421d-a0af-48a6fe34b832)
That if you change the speed here is working perfecetly fine for some reason. 

So the problem lies in the the Speed setting. 
![image](https://github.com/user-attachments/assets/428ebf24-119b-4cf3-9944-fd4894f1bda1)
That there is some error with the code that the resulting the glitchess and unable to change speed properly.

**Comment by HornyPrivateGamer** [comment]
that i promise that i am not joking here. that these is a really problem for me that i would love to pay the owner 10 USD if he can get this fixed.

**Comment by HornyPrivateGamer** [comment]
ok i really cant fingure out what is casuing the problem. That i have a 4090 + 14900ks + 1000mbps internet so cant be a hardware issue.

Owner would you please help me please thanks. i been using you software for like at least 1 year.

**Comment by HornyPrivateGamer** [comment]
That i think the main reaosn that the Fire fox is running well is beucase of the update pack  from this post 
https://github.com/polywock/globalSpeed/issues/576
maybe i am wrong but firefox is the only browser that is working with out a problem

**Comment by HornyPrivateGamer** [comment]
@polywock 
Sir i would persoanlly donate you 10 USD if you can help me fix this problem for me.

that DM me if you feel free and we can chat in discord if you feel free.

**Comment by HornyPrivateGamer** [comment]
Of course i am not saying you extension is bad that i dont mean any of those.

it is a good exntesion i just want to improve it

that i am sorry to offend you if i did i am really sorry. 

thanks

**Comment by HornyPrivateGamer** [comment]
Update:

That i might find the problem 
that i 64gb of ram 
i currently have 55 tap opening same time 40 of them are vidoe from youtube or other plasform

that if i open a sinlge tap in crome that exntesion work perfectly

that once opened too many tap even video speed controller extension get very laggy and slow. 

it is not hardware problem and my interet so what could be the problem here?

**Comment by HornyPrivateGamer** [comment]
Ok tesed in back in Chrome seem to be workging too. It is just brave than casuing the problems. hmmmmmmmm

**Comment by polywock** [comment]
Hello. Does enabling "Ghost mode" in the options page fix the issue?

**Comment by HornyPrivateGamer** [comment]
> Hello. Does enabling "Ghost mode" in the options page fix the issue?

No i tried every option available sir
