### ISSUE TITLE
Hey Polywock actually change the semitones to 96 semitones instead of 7,332 semitones okay while you fix this because somebody else is asking you to fix the global speed extension they are 

### ISSUE THREAD

**Issue by codeyr67** [polywock/globalSpeed#603]

**Comment by codeyr67** [comment]
and the reason why i want 96 semitones instead of 7,332 semitones is because i realize now you cannot do 7,332 semitones you cannot

**Comment by polywock** [comment]
Hello. Sorry, I can't even imagine working on soundTouch.js. Audio signal processing is very complicated and I just don't have the time for that.

**Comment by polywock** [comment]
96 semitones is fine actually. I thought you still meant 7,332.
