### ISSUE TITLE
Hey can you make the semitones like -84 and -72 and -60 semitones where it matches the voice or no when you update it in a few weeks

### ISSUE THREAD

**Issue by codeyr67** [polywock/globalSpeed#606]
because i want it to match the voice while watching the youtube video i do and right now it's like where it does not match the lips it does not or it does not match the voice it does not

**Comment by codeyr67** [comment]
yeah i need you to fix that i do

**Comment by polywock** [comment]
Sorry, that's outside the scope of the extension.
