### ISSUE TITLE
hey polywock can you give me the global speed extension development file please like you did yesterday just in case you fixed the matches of the lips or voice and i just deleted the file just now i did 

### ISSUE THREAD

**Issue by codeyr67** [polywock/globalSpeed#608]

**Comment by codeyr67** [comment]
and that's because just in case you fixed the matches of the voice or lips just in case that's why

**Comment by polywock** [comment]
Hello. Sorry, cannot fix the sync issue. I know it's important for you, but it takes a lot of effort for a very niche feature that is only useful for a single user. 

Here's the 96 semitone one with no other changes. 

[global-speed-chromium.zip](https://github.com/user-attachments/files/17358842/global-speed-chromium.zip)

Again, please only email me. Github is not meant to be used this way.

**Comment by codeyr67** [comment]
okay sorry about that i'll email you next time i will never use github ever again i promise

**Comment by polywock** [comment]
@codeyr67 😆 Using Github is fine. The only issue was creating new Issues instead of continuing the first one.

**Comment by polywock** [comment]
Here's the version with 100 semitones up/down. [global-speed-chromium.zip](https://github.com/user-attachments/files/17387646/global-speed-chromium.zip)
