### ISSUE TITLE
Firefox - State Toggle not working

### ISSUE THREAD

**Issue by NayamAmarshe** [polywock/globalSpeed#61]
I've set the state toggle hotkey to Shift+Q but when I press it, the text shows only the current state. So, if it's on, pressing Shift+Q won't toggle it to off, it keeps showing on.

I'm using Firefox 86

**Comment by polywock** [comment]
Thanks for the feedback. I'm not sure the cause of this issue. I checked on Firefox and it works fine for me. I recommend reinstalling the extension. But, before you do that, could you send me your configuration file? There's an export/copy button in the Help section of the option page.

**Comment by NayamAmarshe** [comment]
> 
> 
> Thanks for the feedback. I'm not sure the cause of this issue. I checked on Firefox and it works fine for me. I recommend reinstalling the extension. But, before you do that, could you send me your configuration file? There's an export/copy button in the Help section of the option page.
> 
> Edit: Also, does the speed also fail to change, or only the state?

Hi! Thanks for the prompt reply.
I reinstalled everything but it still wasn't working so I tried to set the shortcut to Shift+S and it works fine now.
I suppose setting a different shortcut acts as a workaround to the problem.

Anyway, here's my config in case you need it and the speed was working fine, it was only the state that wasn't working.
`{"version":8,"firstUse":1613216641028,"keybinds":[{"id":"8190127512","command":"adjustSpeed","enabled":true,"greedy":true,"adjustMode":2,"key":"KeyA","valueNumberAlt":-0.5},{"id":"7524782263","command":"adjustSpeed","enabled":true,"greedy":true,"adjustMode":1,"key":"KeyS","valueNumber":1},{"id":"201531611","command":"adjustSpeed","enabled":true,"greedy":true,"adjustMode":2,"key":"KeyD","valueNumberAlt":0.5,"spacing":1},{"id":"3952697350","command":"setPin","enabled":true,"greedy":true,"valueState":"toggle","key":"KeyQ"},{"id":"4725398344","command":"setState","enabled":true,"greedy":true,"valueState":"toggle","key":{"code":"KeyQ","shiftKey":true},"spacing":2},{"id":"9048552485","command":"seek","enabled":true,"greedy":true,"valueNumber":-5,"key":"KeyZ"},{"id":"19171870","command":"seek","enabled":true,"greedy":true,"valueNumber":5,"key":"KeyX","spacing":1},{"id":"1134858019","command":"seek","enabled":true,"greedy":true,"valueNumber":-0.04,"key":{"shiftKey":true,"code":"KeyZ"}},{"id":"6404823372","command":"seek","enabled":true,"greedy":true,"valueNumber":0.04,"key":{"shiftKey":true,"code":"KeyX"},"spacing":1},{"id":"3784574869","command":"setMark","enabled":true,"greedy":true,"valueString":"mark1","key":{"shiftKey":true,"code":"KeyW"}},{"id":"4630960898","command":"seekMark","enabled":true,"greedy":true,"valueString":"mark1","key":"KeyW"},{"id":"5887556968","command":"toggleLoop","enabled":false,"greedy":true,"valueString":"mark1","key":"KeyR","spacing":2},{"id":"5686268621","command":"adjustFilter","filterOption":"invert","enabled":false,"greedy":true,"filterTarget":"both","adjustMode":3,"key":{"code":"KeyE"},"valueCycle":[0,1]},{"id":"2161724201","command":"adjustFilter","filterOption":"grayscale","enabled":false,"greedy":true,"filterTarget":"backdrop","adjustMode":3,"key":{"code":"KeyE","shiftKey":true},"valueCycle":[0,1],"spacing":2},{"id":"4931325031","command":"setState","enabled":true,"greedy":true,"valueState":"toggle","key":{"ctrlKey":false,"altKey":false,"shiftKey":true,"metaKey":false,"code":"KeyQ"}}],"common":{"speed":2,"enabled":true,"backdropFx":{"filters":[{"name":"sepia","value":0},{"name":"hueRotate","value":0},{"name":"grayscale","value":0},{"name":"contrast","value":1},{"name":"brightness","value":1},{"name":"saturate","value":1},{"name":"invert","value":0},{"name":"blur","value":0},{"name":"opacity","value":1}],"transforms":[{"name":"scaleX","value":1},{"name":"scaleY","value":1},{"name":"translateX","value":0},{"name":"translateY","value":0},{"name":"rotateX","value":0},{"name":"rotateY","value":0},{"name":"rotateZ","value":0}]},"elementFx":{"filters":[{"name":"sepia","value":0},{"name":"hueRotate","value":0},{"name":"grayscale","value":0},{"name":"contrast","value":1},{"name":"brightness","value":1},{"name":"saturate","value":1},{"name":"invert","value":0},{"name":"blur","value":0},{"name":"opacity","value":1}],"transforms":[{"name":"scaleX","value":1},{"name":"scaleY","value":1},{"name":"translateX","value":0},{"name":"translateY","value":0},{"name":"rotateX","value":0},{"name":"rotateY","value":0},{"name":"rotateZ","value":0}]},"audioFx":{"pitch":0,"volume":1,"delay":0,"eq":{"enabled":false,"factor":1,"values":[0,0,0,0,0,0,0,0,0,0]},"comp":{"enabled":false,"threshold":-24,"knee":30,"ratio":12,"attack":0.003,"release":0.25,"gain":1}},"lastSpeed":1.5}}`

**Comment by polywock** [comment]
I figured it out the issue. It's kind of funny. By default, Global Speed has a "state toggle" hotkey set to Shift-Q. You added second one. So, Shift-Q first toggles the state, and then it toggles it back again to the original value. Solution, just remove the second "state toggle" hotkey.
