### ISSUE TITLE
how to create separate profiles for PWAs?

### ISSUE THREAD

**Issue by trcrsired** [polywock/globalSpeed#616]
i love this snaeplayer with change pitch feature, but i do not want the settings to interfere with other pwas like youtube.

How to do this?

**Comment by polywock** [comment]
No support for different profiles. However, you can enable "Pin by default", if you want all tabs (and PWA tabs) to be independent. So if you change speed/pitch on one tab,  it won't effect other tabs.

**Comment by trcrsired** [comment]
> No support for different profiles. However, you can enable "Pin by default", if you want all tabs (and PWA tabs) to be independent. So if you change speed/pitch on one tab, it won't effect other tabs.

This is clearly a deal breaker for pwa. I think each PWA should have their own profile tbh because they are logically different apps

**Comment by trcrsired** [comment]
This is my music player. Other music players are either bloatware, ads ware. foobar2000 is also annoying since it does not work for touch screen on linux
https://snaeplayer.com/

**Comment by polywock** [comment]
>  I think each PWA should have their own profile tbh because they are logically different apps.

Agreed, it would be better to separate context for each domain instead of tab, but it's hard to implement that at this stage. I can only implement this type of feature during a full refactor. If that time comes, I'll keep it in mind.
