### ISSUE TITLE
Youtuber No longer Skipping, Fast Forward 5 second when change your play back speed. 

### ISSUE THREAD

**Issue by HornyPrivateGamer** [polywock/globalSpeed#617]
This is only in Fire Fox for some reason.

**Comment by polywock** [comment]
Hello. Apologies for the late reply. 

I'm not sure I understand. All shortcuts are configurable in the options page, including the amount to skip. Can you explain more?

**Comment by HornyPrivateGamer** [comment]
> Hello. Apologies for the late reply.
> 
> I'm not sure I understand. All shortcuts are configurable in the options page, including the amount to skip. Can you explain more?

No worry, it is that when you fast forward in youtube it suppose to be like 5 second. However when using global speed it went from 5 second to 10 second. It is really werid 

![image](https://github.com/user-attachments/assets/484e14ac-7838-40ed-ae6e-6645a58c6918)


It seem to be fire fox 
this is my version Version 132.0

**Comment by polywock** [comment]
It seems like Youtube is now skipping relative to speed (`speed x 5 seconds`). So with speed of 2x, it skips 10 seconds. For me, this behavior is observed in both Chrome and Firefox (with Global Speed uninstalled as well).

**Comment by HornyPrivateGamer** [comment]
> It seems like Youtube is now skipping relative to speed (`speed x 5 seconds`). So at double speed, it skips 10 seconds. For me, this behavior is observed in both Chrome and Firefox (with Global Speed uninstalled as well).

Any way to fix it. or is it a Youtube thing ?

**Comment by HornyPrivateGamer** [comment]
> It seems like Youtube is now skipping relative to speed (`speed x 5 seconds`). So at double speed, it skips 10 seconds. For me, this behavior is observed in both Chrome and Firefox (with Global Speed uninstalled as well).

![image](https://github.com/user-attachments/assets/19cdd952-c7da-490d-a34d-cdb2843487f8)

i kind find a solution for it. that is seek = 5 

However you don't have an option of seek = -5.

**Comment by polywock** [comment]
The field accepts negative numbers so using `-5` will make it go 5 seconds backwards.

**Comment by HornyPrivateGamer** [comment]
> seconds. For me, this behavior is observed in both Chrome and Firefox (with Global Speed uninstalled

Ok, thanks, just i can recommend that it can add a separate called "Rewind"
it is just a bit more clear 

thansk

**Comment by HornyPrivateGamer** [comment]
Plus are there any way to donate to your sir just wondering?
