### ISSUE TITLE
Questions about speed setting

### ISSUE THREAD

**Issue by Nathalie-Annis** [polywock/globalSpeed#619]
Regarding the setting of the speed shortcut key, I aim to implement the logic: upon pressing the shortcut key, if the current playback speed is not the one specified by the shortcut key, then adjust it to the designated playback speed; otherwise, This means that the current playback speed is already the specified playback speed, then restore the initial speed of 1. I would like to inquire whether the current global speed can fulfill this function. I have attempted to set the speed to a value and loop within the list value option, but it is not a perfect solution to the problem.

**Comment by Nathalie-Annis** [comment]
In the current globalSpeed, if the option of setting the speed as a value is chosen and the speed-switching functionality is enabled, the speed can only switch between the previous speed and the set speed, rather than between 1 and the set speed. If the speed is selected to cycle among the list values, problems will arise when using multiple shortcut keys. For instance, I set the s key to cycle between speed 1 and 2 and the w key to cycle between speed 1 and 3. Then, I first press the s key, and the speed becomes 2. Next, I press the w key, and the speed becomes 3. Finally, when I press the s key, I expect the speed to become the next value of the list, which is 1, instead of the 2 I desire. Do you have the corresponding solution? Thank you.

**Comment by polywock** [comment]
Hello. Toggling between 3x and 1x is possible by using three shortcuts set to the same key. 
![b](https://github.com/user-attachments/assets/6ef5adc1-42b1-490d-81d0-e96c0bc94a91)

If current speed is 1x, it will end up becoming 3x.
If current speed is anything else, it will end up becoming 1x.

**Comment by Nathalie-Annis** [comment]
If current speed is anything else, it will end up becoming 3x.
If current speed is 3x, it will end up becoming 1x is what I need

**Comment by Nathalie-Annis** [comment]
> Hello. Toggling between 3x and 1x is possible by using three shortcuts set to the same key. 
> 
> ![b](https://github.com/user-attachments/assets/6ef5adc1-42b1-490d-81d0-e96c0bc94a91)
> 
> 
> 
> If current speed is 1x, it will end up becoming 3x.
> 
> If current speed is anything else, it will end up becoming 1x.

If current speed is anything else, it will end up becoming 3x,
If current speed is 3x, it will end up becoming 1x is what I need

**Comment by Nathalie-Annis** [comment]
I think this feature is an improvement on holding down the key g for 3x fast forward. I don't need to hold down key g all the time to make the video play at 3x speed, and when I want to restore the original speed, I just need to press the key again to restore the original speed

**Comment by polywock** [comment]
> If current speed is anything else, it will end up becoming 3x,
> If current speed is 3x, it will end up becoming 1x is what I need

Flipping the 3 and 1 should match that behavior. 

![Screenshot 2024-11-13 at 3 25 19 AM](https://github.com/user-attachments/assets/82d21cec-3dab-4aa7-8fb4-c3ca557240f1)

**Comment by Nathalie-Annis** [comment]
> > If current speed is anything else, it will end up becoming 3x,
> 
> > If current speed is 3x, it will end up becoming 1x is what I need
> 
> 
> 
> Flipping the 3 and 1 should match that behavior. 
> 
> 
> 
> ![Screenshot 2024-11-13 at 3 25 19 AM](https://github.com/user-attachments/assets/82d21cec-3dab-4aa7-8fb4-c3ca557240f1)
> 
> 

Thank you. This implementation works fine when there is only one such key. The effect is the same as cycling through the values in the list. However, when multiple shortcut keys are set, problems arise. I have set the ‘s’ key to 1 2 1, and the ‘w’ key to 1 3 1. When I first press the ‘s’ key, the speed changes to 2. Then I press the ‘w’ key, and the speed changes to 3. When I press the ‘s’ key again, I want the playback speed to change to 2, but currently, it changes to 1. I need to press the ‘s’ key once more to make the video play at double speed

**Comment by Nathalie-Annis** [comment]
Thanks so much! That works fine. I really appreciate your assistance!

**Comment by Nathalie-Annis** [comment]
I wonder how do these three shortcuts work？

**Comment by polywock** [comment]
![Screenshot 2024-11-13 at 3 25 19 AM](https://github.com/user-attachments/assets/82d21cec-3dab-4aa7-8fb4-c3ca557240f1)

Internally the extension tracks the speed and previous speed. For example, if you start 2.5x and then go to 3x, it would look like this. 

`previous_speed = 2.5`
`current_speed = 3`

By using this series of shortcuts, we're pretty much trying to replace the `previous_speed` with `1` so that it toggles back and fourth. Kind of hacky.
