### ISSUE TITLE
 Support Firefox for mobile

### ISSUE THREAD

**Issue by dvorapa** [polywock/globalSpeed#62]

**Comment by polywock** [comment]
Android Firefox only supports Recommended extensions for the moment. As a workaround, you could install Android Firefox Nightly and follow this guide....

https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by dvorapa** [comment]
I see, will it work well though? Addon has got its own UI, so does Firefox mobile, I wasn't sure if they are even compatible with each other. I'll try it soon

**Comment by polywock** [comment]
The main speed feature works. But, the UI is small.
