### ISSUE TITLE
Please reset the speed when you open a new web. Thank you!

### ISSUE THREAD

**Issue by PyRookie1** [polywock/globalSpeed#63]

**Comment by polywock** [comment]
You can create a URL rule to set the speed to 1.0x if the new webpage matches a certain URL (or any URL if you leave it empty). Is this what you mean? 

https://www.youtube.com/watch?v=sk2VNm3Idpc

**Comment by PyRookie1** [comment]
Of course, the name of your expansion is global speed, but my personal habit is to use shortcut keys to speed up the video when I want to. After all, not all videos need to be played at double speed. Thank you for your reply!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 上午7:55
收件人:&nbsp;"polywock/globalSpeed"<globalSpeed@noreply.github.com&gt;;
抄送:&nbsp;"机械工程学院于佑庆"<1106679542@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] Please reset the speed when you open a new web. Thank you! (#63)





 
You can create a URL rule to set the speed to 1.0x if the new webpage matches a certain URL (or any URL if you leave it empty). Is this what you mean?
 
https://www.youtube.com/watch?v=sk2VNm3Idpc

**Comment by polywock** [comment]
You're welcome. Thank you for the feedback. By the way, in case Youtube is inaccessible in your country, here's the setup demo uploaded to Github.  
 
https://user-images.githubusercontent.com/31208859/110235855-71266000-7f00-11eb-82c1-56546f5ec2d6.mov

**Comment by PyRookie1** [comment]
Don't worry, I have VPN and can visit any website.&nbsp;
Our country's restrictions are only for the protection of traditional culture and Internet industry, not really to regulate the people.After all, only in this way can we have Baidu, Tencent and tiktok, which is a complicated thing.
I already know how to set it. It's nice to talk with you.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 下午5:59
收件人:&nbsp;"polywock/globalSpeed"<globalSpeed@noreply.github.com&gt;;
抄送:&nbsp;"机械工程学院于佑庆"<1106679542@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] Please reset the speed when you open a new web. Thank you! (#63)





 
You're welcome. Thank you for the feedback. By the way, in case Youtube is inaccessible in your country, here's the setup demo uploaded to Github.
 
https://user-images.githubusercontent.com/31208859/110235855-71266000-7f00-11eb-82c1-56546f5ec2d6.mov

**Comment by polywock** [comment]
Glad to hear. I wasn't sure how straightforward Youtube was to access. According to the statistics dashboard, Global Speed's user count is highest in 🇨🇳  China by a wide margin. 🇧🇷  Brazil is second, and the 🇺🇸  United States is third. So just in case, I should avoid Youtube links in the future. 

It was nice talking to you as well.
