### ISSUE TITLE
About Cent Control

### ISSUE THREAD

**Issue by codeyr67** [polywock/globalSpeed#631]
Hey polywock can you please make another cent box like transpose app has from google chrome please and that would be wonderful if you could and yes i would love that better then just using it in the same box and please add this as another feature for enhancement or effects please yeah one should be called pitch and one should be called cents there should be and i'll tell you how many i wanted i wanted 97.00 increments up and down both i do and yes i still love the 100 semitones up and down too but i would have a more better music life i would with another cent box i would and except i do not want to make my own i do not because it's too hard that's why

**Comment by polywock** [comment]
Hello! I'll look into for the next update (maybe a few months). For now, have you tried using shortcut keys to change pitch by 0.01 semitones (one cent)?

**Comment by codeyr67** [comment]
yes i did but i would love another cent box better i would and it would be a lot fun it would

**Comment by codeyr67** [comment]
and i also wanted you to update it for google chrome i do

**Comment by codeyr67** [comment]
and remember i wanted 97.00 increments up and down both remember and also remember with sliders too
