### ISSUE TITLE
你好，和B站长按方向右键的快捷键有冲突

### ISSUE THREAD

**Issue by seqimi** [polywock/globalSpeed#636]
B站长按方向右键可以进入倍速播放，启用插件后这个就失效了，插件的设置如下
![image](https://github.com/user-attachments/assets/140c3700-b013-4700-a028-fa159580085b)
![image](https://github.com/user-attachments/assets/2d2fdff6-da77-4055-8019-4a769b10ad21)

**Comment by polywock** [comment]
Hello. If Global Speed's speed is 1x, double tapping on Bilibili was have no effect because global Speed will revert it back to 1x.  It's recommended to change speed through Global Speed's own controls. 

By default (On a QWERY keyboard): You can use the A-S-D keys to change speed.

**Comment by seqimi** [comment]
原来如此，谢谢大佬
