### ISSUE TITLE
Please Add Another Cent Box in the near future after version 3.0.9998 please

### ISSUE THREAD

**Issue by codeyr67** [polywock/globalSpeed#639]
hey polywock can you add another cent box in the near future please after version 3.0.9998 because i know right now your working hard for this version 3.0.9998 right now you are and i understand and i am talking about for microsoft edge i am talking about and if you do add this as a enhancement logo again please and will you promise me you'll make another cent box in the near future too please

**Comment by codeyr67** [comment]
and also remember i wanted arrow buttons too remember for another cent box

**Comment by codeyr67** [comment]
and hey polywock can you also makesure the -1.00 cents box has to sound like -3.80 semitones with low pitch and then makesure the high pitch with +1.00 cents box sounds like +3.80 semitones please

**Comment by codeyr67** [comment]
and that's because i wanted it to be like the one extension transpose pitch speed loop for videos i do

**Comment by codeyr67** [comment]
except the pitch cents box have to sound a lot lower and a lot higher they do

**Comment by codeyr67** [comment]
and hey polywock and one more suggestion can you makesure to add 97.00 increments up and down too please in the near future after version 3.0.9998 please because i wanted a lot of increments and yes i am still happy with the 100 semitones up and down too but i would have a lot more fun with 97.00 increments up and down instead of 1.00 cents i would

**Comment by codeyr67** [comment]
and i do not care if it has no sound or not that would not bother me it would not but yeah i wanted a lot of increments for another cent box which is 97.00 increments up and down

**Comment by codeyr67** [comment]
and also makesure you promise me to do all that for me too okay because i would have a lot fun with all that i would

**Comment by polywock** [comment]
I cannot. I explained why in my email reply.
