### ISSUE TITLE
Is there a way you can add a hotlink to the media next to the controls?

### ISSUE THREAD

**Issue by nmlen** [polywock/globalSpeed#640]
Currently the functionality is that the link isn't clickable. What if instead it linked to the m3u8 or the video file itself if available? I don't know how the internals of the extension works, but if the extension can already see that information and it's just consciously been decided not to directly provide the link in the UI, it would be really easy to implement. Would be a really great quality of life feature.

![image](https://github.com/user-attachments/assets/eca66070-421f-4025-bc46-93a1d79ccc52)

**Comment by polywock** [comment]
Hello. Would be nice, but extensions that provide that functionality tend to be taken down from the Chrome Web Store.
