### ISSUE TITLE
键盘快捷键监控超范围

### ISSUE THREAD

**Issue by pchenghao** [polywock/globalSpeed#641]
在Android平板上的Edge浏览器中安装此插件，平板连接蓝牙键盘。
当光标在网页内的输入框中时，键盘输入a、s、d键时，屏幕上会出现一个数字的显示，此时当前网页并没有在播放视频中。并且要在网页上输入这3个字母时，无法输入进去。
在菜单中选择扩展，选择此插件，将其关掉，这3个键变得可以输入了。

**Comment by polywock** [comment]
Hello. You can delete all the shortcuts in the options page. I'll also change the default shortcuts to be empty if it detects an android tablet.
