### ISSUE TITLE
Video visual filters don't work in pip mode on firefox and chrome.

### ISSUE THREAD

**Issue by Pawloland** [polywock/globalSpeed#68]
Hi, I like to bump brightness in dark films. The problem is that when I go to PIP mode, all of the filters are gone. I tested it on Chrome and Firefox. Is it possible to fix it, or is it unfixable unless change to the source code of browser? Thanks

**Comment by polywock** [comment]
Unfortunately, it is unfixable, and I can't think of any extension-level workaround.

**Comment by Pawloland** [comment]
Hi @polywock!
After some time of thinking I've got an idea of workaround. The best part is that it works. If you would like, you could link to this issue in readme, so potential newcomers can see it quickly.

At the beginning I need to say, that it is a Windows only workaround, but maybe the idea can be adjusted to mac or linux if those OS-es have a similar software available for them.

The key component is https://github.com/LionelJouin/PiP-Tool being installed.

After that we open website with video, that can be adjusted using Global Speed. 

We run PiP-Tool and then select area with playing video.

We press:

1. `win + ctrl + D`  to open new virtual desktop.
2. `win + tab` to open task view.
3.  We drag browser window to the new virtual desktop (the pip window stays in the main one).
4. Profit

It is necessary to use virtual desktops because we can't minimize browser window. If we tried to do this, our video in pip window would freeze, but audio would still play. The reason of that is how `requestAnimationFrame()` works. We workaround it by moving browser window to virtual desktop. By doing so the browser thinks it is visible so `requestAnimationFrame()` allow video to play and we have our browser window out of sigh, so it doesn't occupy space uselessly.

**Comment by polywock** [comment]
Nice workaround. I've [linked](https://github.com/polywock/globalSpeed/commit/f92083ed6ef2d0e9584cadcec59cf948614c188d) your method in the FAQ section.
