### ISSUE TITLE
When YouTube and Spotify are playing together, I want to change the speed of only one of them.

### ISSUE THREAD

**Issue by sharadmathur1** [polywock/globalSpeed#69]
I frequently watch lectures on YouTube and other platforms with Spotify playing in the background. If I want to change the speed of just the video or just Spotify, what do I do?

**Comment by sharadmathur1** [comment]
Edit: I don't actually have the spotify app, so i use the chrome app, which is basically just another chrome tab with spotify open.

**Comment by polywock** [comment]
By default, all tabs share the same context (speed, filters, etc). You can pin that tab if you want it to have a unique speed.  

You can enable "pin by default" in the settings page, if you prefer all tabs to have separate speeds by default. 

![cat](https://user-images.githubusercontent.com/31208859/112066848-7fe65700-8b3d-11eb-9a5a-c8f5a0b8eb8a.png)
