### ISSUE TITLE
[Feature Request] Disable all hotkeys on specific websites

### ISSUE THREAD

**Issue by Antyos** [polywock/globalSpeed#72]
There are many web-based platforms that use hotkeys for functionality but have nothing to do with video playback. It would be nice to have the ability to disable all hotkeys that block event propagation (or more specifically, hotkeys in general) or those specific websites rather than having to add an exception for each site on each hotkey.

**Comment by polywock** [comment]
You can add URL conditions to all hotkeys. 

1. Click on [ -- 0 -- ] button on the bottom right of the Shortcut Editor section. 

![cc](https://user-images.githubusercontent.com/31208859/113503334-37e11000-94ff-11eb-8005-bd60606313de.png)


2. To blacklist specific sites, you would set it up like this. 

![dd](https://user-images.githubusercontent.com/31208859/113503399-a02ff180-94ff-11eb-92a4-5a32b4f763d2.png)

3. To whitelist specific sites, you would set it up like this. 

![ee](https://user-images.githubusercontent.com/31208859/113503501-509df580-9500-11eb-94f0-fabb7d3d3970.png)

**Comment by Antyos** [comment]
Well thank you to the foresight of your past self! It works great!

I always feel a bit embarrassed when posting an issue that is essentially my ineptitude, though in my defense, I never would have seen that button if you hadn't pointed it out. You might want to consider making the shortcut URL rules button a bit more obvious, both in location and functionality.

**Comment by polywock** [comment]
Thanks, glad the feature could be helpful. Reaching out is always fine, the best issue is an easy issue. Your defense is rock solid, the UX design is ~~terrible~~ lacking in many areas. I'll look into improving the UX design of that button (and more) in the next update. Thanks for the suggestion.

**Comment by Antyos** [comment]
For the UX update, I will also suggest being able to re-order keybindings / URL rules with drag-and-drop rather than the little arrows. 

While it probably deserves a separate issue, if you need beta testers or want feedback on a future update, feel free to @ me. This is one of my favorite browser extensions and I'll always be happy to provide feedback on its development however I can!

**Comment by polywock** [comment]
Speaking of drop-and-drag, I implemented it once a while back. But, I didn't like it for some reason, I don't remember why. I'll take another look. 

The arrows keys aren't too bad if you use the keyboard controls instead. Once you click to focus on them (yellow outline), you can use the Enter key to trigger them. `Tab` / `Shift + Tab` to cycle between the arrow buttons.  

https://user-images.githubusercontent.com/31208859/113637846-91525780-9643-11eb-947b-2bbeb3f79328.mov

Thanks for the offer, I'll keep that in mind. But, I suspect I won't need any beta testers at this stage. The extension is mostly stable right now and I only expect relatively minor changes in the future.
