### ISSUE TITLE
Speed adjustment does not occur with Kaltura videos

### ISSUE THREAD

**Issue by liquidbear99** [polywock/globalSpeed#73]
My school uses kaltura to upload videos. I have an extension that works to change the speed but it seems that this extension does not.

The extension that I have found work is https://github.com/igrigorik/videospeed

**Comment by polywock** [comment]
1. Make sure Global Speed is the only enabled video control extension. 
2. Try enabling Ghost Mode in the Global Speed options page. It's hidden under the [ ... ] button.  Ghost mode blocks the website from changing the speed.

**Comment by liquidbear99** [comment]
Unfortunately that did not fix the issue. I tried enabling ghost mode and also did not have any other video speed control extensions enabled. It still works watching a normal youtube video but not the kaltura ones.

**Comment by polywock** [comment]
I suspect I found the issue. I've published the changes. It may take a few days for approval for Chrome Web Store, and up to a week for the Edge addon store. For now, if you want to load an unpacked version, here's the zip. 

[packed.zip](https://github.com/polywock/globalSpeed/files/6282342/packed.zip)

1. Extract the `packed.zip` file. 
2. Open the extension control page. -> `chrome://extensions`
3. Enable `developer mode` on the top-right of the page (bottom left for Edge). 
4. Load unpacked (load the extracted folder).

**Comment by liquidbear99** [comment]
I just gave it a shot but still no dice. It is still working on youtube but not any kaltura videos.

**Comment by polywock** [comment]
Weird, I just tried on a trial account and it works fine for me (new version, not old). 

Did you refresh the page after loading the unpacked version?

**Comment by liquidbear99** [comment]
Ill give it a shot tonight, maybe uninstalling and reinstalling the add on again will fix it.

**Comment by yovelga** [comment]
Thank you very much

**Comment by polywock** [comment]
@yovelga, no problem, glad I could be helpful.

**Comment by shnchh** [comment]
This is still an issue.
