### ISSUE TITLE
Uncaught (in promise) TypeError: window.overlay.setInit is not a function

### ISSUE THREAD

**Issue by Pawloland** [polywock/globalSpeed#76]
Hi again. 
So I was doing my project and I stumbled upon this error in my console using Chrome. It doesn't show on Firefox, so I was thrown off even more by it. I disabled every extension one by one, to see which one is using it, and it turned out to be Global Speed. Now that I think about it it may even occur in Firefox, but maybe Firefox isn't showing those errors to user console, rather to extension console (hidden away from user last time I checked it). It doesn't throw error on any different site, just this one. I have two hypotheses:
1. There is some test code that runs just when on localhost:3000/admin (I observed it just with this specific url), that you use for developing (sorry for my laziness but I didn't bother to check it) and it made it's way to publicity.
2. Chrome extension behave weirdly with different ports on localhost.

There is an image from console:
![obraz](https://user-images.githubusercontent.com/59684145/114315607-fb657380-9aff-11eb-959a-ee796eb29429.png)

And here is (I think) full trace:
```javascript
contentScript.js:1 Uncaught (in promise) TypeError: window.overlay.setInit is not a function
    at contentScript.js:1
    at u (contentScript.js:1)
    at Generator._invoke (contentScript.js:1)
    at Generator.next (contentScript.js:1)
    at r (contentScript.js:1)
    at s (contentScript.js:1)
(anonymous) @ contentScript.js:1
u @ contentScript.js:1
(anonymous) @ contentScript.js:1
(anonymous) @ contentScript.js:1
r @ contentScript.js:1
s @ contentScript.js:1
Promise.then (async)
r @ contentScript.js:1
s @ contentScript.js:1
Promise.then (async)
r @ contentScript.js:1
s @ contentScript.js:1
(anonymous) @ contentScript.js:1
(anonymous) @ contentScript.js:1
he @ contentScript.js:1
(anonymous) @ contentScript.js:1
(anonymous) @ contentScript.js:1
(anonymous) @ contentScript.js:1
(anonymous) @ contentScript.js:1
```

**Comment by polywock** [comment]
I've seen this overlay.setInit is not a function bug before, but I couldn't reproduce it. I suspect it's a race condition bug. 

Could you load the development version and show me the console and trace again? 

[unpacked.zip](https://github.com/polywock/globalSpeed/files/6292545/unpacked.zip)

1. Unzip the folder. 
2. Open Chrome extension control page.
3. Enable "Dev mode" on the top-right. 
4. Load unpacked, and load the extracted folder.

**Comment by Pawloland** [comment]
No problem, here is a more readable trace:

![obraz](https://user-images.githubusercontent.com/59684145/114424545-85711300-9bb8-11eb-8bec-699c88b63182.png)

```javascript
contentScript.js:7882 Uncaught (in promise) TypeError: window.overlay.setInit is not a function
    at _callee$ (contentScript.js:7882)
    at tryCatch (contentScript.js:7001)
    at Generator.invoke [as _invoke] (contentScript.js:7231)
    at Generator.next (contentScript.js:7056)
    at asyncGeneratorStep (contentScript.js:76)
    at _next (contentScript.js:98)
_callee$ @ contentScript.js:7882
tryCatch @ contentScript.js:7001
invoke @ contentScript.js:7231
(anonymous) @ contentScript.js:7056
asyncGeneratorStep @ contentScript.js:76
_next @ contentScript.js:98
Promise.then (async)
asyncGeneratorStep @ contentScript.js:86
_next @ contentScript.js:98
Promise.then (async)
asyncGeneratorStep @ contentScript.js:86
_next @ contentScript.js:98
(anonymous) @ contentScript.js:105
(anonymous) @ contentScript.js:94
_main @ contentScript.js:7901
main @ contentScript.js:7819
(anonymous) @ contentScript.js:7969
(anonymous) @ contentScript.js:7970
(anonymous) @ contentScript.js:7972

```

**Comment by polywock** [comment]
Thanks. I'm still having a tough time figuring out this bug. Could you try this one as well and let me know if you see the same message. (No trace needed). 

[unpacked.zip](https://github.com/polywock/globalSpeed/files/6299288/unpacked.zip)

**Comment by Pawloland** [comment]
No it didn't help. 
In fact it generates new error:

![obraz](https://user-images.githubusercontent.com/59684145/114700057-55914f00-9d21-11eb-8c91-d8b67f40d50c.png)

```javascript 
contentScript.js:1180 Uncaught (in promise) TypeError: _window$overlay.setInit is not a function
    at contentScript.js:1180
(anonymous) @ contentScript.js:1180
Promise.then (async)
ConfigSync @ contentScript.js:1177
(anonymous) @ contentScript.js:7965
VisibleSync @ contentScript.js:7973
handleDOMLoaded @ contentScript.js:7911
_callee$ @ contentScript.js:7897
tryCatch @ contentScript.js:7001
invoke @ contentScript.js:7231
(anonymous) @ contentScript.js:7056
asyncGeneratorStep @ contentScript.js:76
_next @ contentScript.js:98
Promise.then (async)
asyncGeneratorStep @ contentScript.js:86
_next @ contentScript.js:98
Promise.then (async)
asyncGeneratorStep @ contentScript.js:86
_next @ contentScript.js:98
(anonymous) @ contentScript.js:105
(anonymous) @ contentScript.js:94
_main @ contentScript.js:7907
main @ contentScript.js:7819
(anonymous) @ contentScript.js:7976
(anonymous) @ contentScript.js:7977
(anonymous) @ contentScript.js:7979
contentScript.js:1323 Uncaught (in promise) TypeError: window.overlay.updateBackdrop is not a function
    at FxSync.handleChange (contentScript.js:1323)
    at contentScript.js:1261
    at contentScript.js:913
    at Set.forEach (<anonymous>)
    at handleUpdate (contentScript.js:912)
    at contentScript.js:976
(anonymous) @ contentScript.js:1323
(anonymous) @ contentScript.js:1261
(anonymous) @ contentScript.js:913
handleUpdate @ contentScript.js:912
(anonymous) @ contentScript.js:976
Promise.then (async)
subscribeView @ contentScript.js:975
FxSync @ contentScript.js:1257
(anonymous) @ contentScript.js:1064
(anonymous) @ contentScript.js:1037
(anonymous) @ contentScript.js:913
handleUpdate @ contentScript.js:912
(anonymous) @ contentScript.js:976
Promise.then (async)
subscribeView @ contentScript.js:975
ConfigSync @ contentScript.js:1031
(anonymous) @ contentScript.js:7965
VisibleSync @ contentScript.js:7973
handleDOMLoaded @ contentScript.js:7911
_callee$ @ contentScript.js:7897
tryCatch @ contentScript.js:7001
invoke @ contentScript.js:7231
(anonymous) @ contentScript.js:7056
asyncGeneratorStep @ contentScript.js:76
_next @ contentScript.js:98
Promise.then (async)
asyncGeneratorStep @ contentScript.js:86
_next @ contentScript.js:98
Promise.then (async)
asyncGeneratorStep @ contentScript.js:86
_next @ contentScript.js:98
(anonymous) @ contentScript.js:105
(anonymous) @ contentScript.js:94
_main @ contentScript.js:7907
main @ contentScript.js:7819
(anonymous) @ contentScript.js:7976
(anonymous) @ contentScript.js:7977
(anonymous) @ contentScript.js:7979
contentScript.js:1276 Uncaught TypeError: window.overlay.updateBackdrop is not a function
    at FxSync.release (contentScript.js:1276)
    at ConfigSync.release (contentScript.js:1047)
    at contentScript.js:7960
(anonymous) @ contentScript.js:1276
(anonymous) @ contentScript.js:1047
(anonymous) @ contentScript.js:7960
setTimeout (async)
(anonymous) @ contentScript.js:7950


```

**Comment by polywock** [comment]
For some reason, window.overlay still seems to exist, but the functions within have all been replaced or removed. Or maybe window.overlay was set to something else. This is difficult. Looking through the code, that shouldn't happen. The fact that it only happens under specific cases is very curious. Debugging is very difficult without being able to locally reproduce the issue, so I'm just going to give up (sorry about that).

**Comment by Pawloland** [comment]
I am so embarrassed right now. Just after your last comment everything clicked in my brain. This is the cause of the issue:

![obraz](https://user-images.githubusercontent.com/59684145/114750908-cc940b00-9d54-11eb-93ce-87f3f3514fb8.png)

I accidentally overwrote your function with my variable for overlay div. The only thing to prevent similar problem in future with this extension would be to move this function to a class as a method an maybe with a little more descriptive name, so some noob like me won't unknowingly overwrite it and therefor won't break your extension. 
Again I am so sorry.

**Comment by polywock** [comment]
Lol, that would be funny, but I'm not convinced that's the cause. The extension's code should be in a separate scope from your localhost server code.  So I don't think there's any chance for naming conflict. To test, try renaming your overlay variable to something else, does it end up working?

Also, could you right click on your localhost page and click on  "Inspect" to open the developer console? Here you could select the Global Speed scope and type in "window.overlay" to see the Overlay object is unmolested.  

![imgg](https://user-images.githubusercontent.com/31208859/114785169-44a90380-9d4a-11eb-83e4-85eb2cc85b11.png)

**Comment by Pawloland** [comment]
OK you were correct. The script "overlay" variable was in different scope and wasn't overwriting your function. 
What was causing it was div with id="overlay" set. After I changed it to id="my_super_random_name_for_an_overlay" the error disappeared.
I add a zip file with the express server, to reproduce this issue. You need to have node and npm installed. Once you have it done, just extract zipped files, and run `npm install` && `npm run start`. It will start local http server on port 3000. Go to `localhost:3000/` in chrome browser and see how your extension behaves with div id set. You can modify index.html file to delete problematic id and see, how your function isn't overwritten anymore. 

The only fix I can think of, is to somehow hide your function from window entirely, or obfuscate it's name so it is nearly impossible to randomly overwrite it. 

[test.zip](https://github.com/polywock/globalSpeed/files/6329692/test.zip)

**Comment by polywock** [comment]
Perfect, thank you!. That seems to be it. This problem was stressing me out.
