### ISSUE TITLE
Whatsapp web audio messages no longer being sped up

### ISSUE THREAD

**Issue by fontys3583635** [polywock/globalSpeed#77]
I don't know when this started happening exactly, but recently when listening to whatsapp web audio messages they seem to no longer be affected by the speed changer.

**Comment by polywock** [comment]
They reset speed to 1.0 aggressively now. You'll need to enable Ghost Mode in the options page. It's hidden under the [ ... ] button. That will block them from changing the speed. 

![img](https://user-images.githubusercontent.com/31208859/114441528-821a5f00-9b99-11eb-9fed-1656c275ec67.png)

**Comment by fontys3583635** [comment]
I had tried it and it didn't work, but I did it again and it's fine. Thanks!

**Comment by polywock** [comment]
No problem, glad that Global Speed could be helpful.

**Comment by Arost01** [comment]
厉害了
