### ISSUE TITLE
Imported settings reset after browser restarts

### ISSUE THREAD

**Issue by Antyos** [polywock/globalSpeed#79]
I had to reset my extensions recently and (thankfully) have been able to reimport a backup of my settings. However, every time I restart my browser, the the settings for this extension reset and I have to import them from the json file again. I have had to do this 3 times now so I know I'm not just imagining things.

If I were to guess, the settings are not being saved to the local storage when imported from a json, but they are saved/updated when making any other changes so the issue has gone largely unnoticed.

**Comment by polywock** [comment]
That's pretty much it. The fix would be included in the next update. 

https://github.com/polywock/globalSpeed/commit/4915462c8fa8de00d6830b728bb31486fa919b4a

Thanks for the report (and for the initial export/import suggestion)
