### ISSUE TITLE
Broken on MS Edge browser

### ISSUE THREAD

**Issue by Flookoco** [polywock/globalSpeed#8]
I updated MS Edge browser this morning to Version 80.0.361.111 (Official build) (64-bit), and now Global Speed inverts all screen colours within any browser window. The extension worked perfectly until today, I have proven it is this extension by turning it off and refreshing the window. I've repeated this with all other extensions I'm running but this is the only one with the problem.

I hope this report is useful as I really liked this extension and would like to use it again in the future.

**Comment by polywock** [comment]
If you open the FX menu ⚡. You can disable the invert. Here's a [visual](https://github.com/polywock/globalSpeedTickets/blob/master/tickets/1.md) guide. There is a default shortcut key to invert the page `KeyE`. You probably pressed it. You can also try uninstall and reinstalling the extension, the save files will reset. 

Sorry for that. This is 100% me being a terrible UX designer. I've actually had multiple reports about this. In the next version, I'm planning to disable the page invert shortcut key.

**Comment by kindect** [comment]
It is working on my device and this information might help:

Microsoft Edge | 83.0.478.44 (Official build) (64-bit)
-- | --
Revision | dc53b89c303af22ab5f29be454b45270efbbc6c5
Operating system | Windows 10 OS Version 1909 (Build 18363.836)
JavaScript | V8 8.3.110.9
Flash | 32.0.0.371 C:\Users\kindect\AppData\Local\Microsoft\Edge\User Data\PepperFlash\32.0.0.371\pepflashplayer.dll
User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 Edg/83.0.478.44
