### ISSUE TITLE
How to run this extension locally

### ISSUE THREAD

**Issue by ArunTeltia** [polywock/globalSpeed#81]
Hello , Great Project I am using it for like 1 year now, can you help me with how i can run it on my local and can work on styles and things such that I can create the style of this according to me, I really have no idea how i can work on it, I tried npm run build:dev it is disposing a unpacked folder that is bieng used to locally load the extension in the browser but how can i work on this in real time 

Please help, 
Thank You so much for this 🙌

**Comment by polywock** [comment]
Hot loading is maybe what you want. It quickly shows the changes in styles... but it's [hard](https://medium.com/front-end-weekly/hot-reloading-extensions-using-webpack-cdfa0e4d5a08) to do with Chrome extensions. (his loader is no longer supported). 

I usually just keep calling `npm run build:dev` when I want to preview my changes and press the reload button on the Chrome extension page. `chrome://extensions`. 

1. `npm install` to install dependencies. 
1. Run `npm run build:dev` to create the local folder. 
2. Open browser extensions page  `chrome://extensions`. 
3. Enable dev mode on top-right (Chrome) or bottom-left (edge)
2. Load the unpacked folder. 
3. Make your changes in the various .scss files scattered throughout `src/` folder. Most of the colors are defined in `src/_common.scss`. 
4. `npm run build:dev` to build updated version. Once finished, reload on the `chrome://extensions` page. 
5. Repeat last step until happy with results.

**Comment by ArunTeltia** [comment]
I was doing the same right now, I was not sure about the hot loading part(tbh I dont even know about it) I just assume it must have hot reload which i am not able to use, thats was the reason I asked this question 
Thank you so much for clarifying, I learned a lot from this project and will learn a lot more 
Thank you for linking that article, I am having a look right now 🙌
I am not sure If I should close this issue because this can be the issue for a lot of beginners, You can close this issue if you want

**Comment by polywock** [comment]
No problem. Glad I could be helpful. As for the issue status, I'll close and pin it.
