### ISSUE TITLE
[Feature Request] Fast forward youtube videos frame by frame

### ISSUE THREAD

**Issue by vbHeiko** [polywock/globalSpeed#83]
Hi, globalspeed is one of the best add-ons for me :-)
I'm using Firefox. When I watch youtube videos and pressing [Numpad 3] the video seeks one frame [=0.04s] forward.
[globalspeed setting]![grafik](https://user-images.githubusercontent.com/18700304/116285630-9ad86680-a78e-11eb-9f4c-8cc91e0ba720.png)
-When holding the NUM-3 button down permanently the browser doesn't show one frame after the other but Firefox skips eighty percent of the frames. Is it possible to write e.g. a script so that the browser shows picture by picture even when the [NUM-3] button is pressed permanently ?

**Comment by polywock** [comment]
Maybe a hotkey that sets the speed to `0.07`. That speed is not frame by frame, but still very slow. Pressing that hotkey again should revert the speed back to the original speed.

**Comment by Pawloland** [comment]
> Hi, globalspeed is one of the best add-ons for me :-)
> I'm using Firefox. When I watch youtube videos and pressing [Numpad 3] the video seeks one frame [=0.04s] forward.
> [globalspeed setting]![grafik](https://user-images.githubusercontent.com/18700304/116285630-9ad86680-a78e-11eb-9f4c-8cc91e0ba720.png)
> -When holding the NUM-3 button down permanently the browser doesn't show one frame after the other but Firefox skips eighty percent of the frames. Is it possible to write e.g. a script so that the browser shows picture by picture even when the [NUM-3] button is pressed permanently ?

I don't know, but IIRC YT already has this functionality. The hotkeys for this are , and .  Or  < and > . I am not sure which one of those two pairs.

**Comment by polywock** [comment]
@Pawloland, I tried out Youtube's default frame by frame keys, but it seems like it doesn't solve @vbHeiko's problem.  If you hold down `,` or `.` for a few seconds it skips many frames. 

@vbHeiko, change your seek value from `0.04` seconds to `0.041` seconds. i've made it so the seek value of exactly `0.041` does a `seekToNextFrame` operation if the browser supports it (Firefox does, but not Chromium). This is much smoother and it might be what you want .

**Comment by vbHeiko** [comment]
> @vbHeiko, change your seek value from `0.04` seconds to `0.041` seconds.
Phantastic. Seek forward is now as smooth as I want.

> @vbHeiko since there's no `seekToPreviousFrame` operation, a nega
> tive seek would use the standard method
-Too bad that there is no metod for 'seekToPreviousFrame' ;)
