### ISSUE TITLE
baidu bug

### ISSUE THREAD

**Issue by drc5521** [polywock/globalSpeed#84]
on 2.7.6 version，the extension normal work，but，on 2.7.9 version，it does not work on baidu. so，how to fix the problem. Can you fix it? Thanks.

**Comment by drc5521** [comment]
I suggest that every time a new version is released, it should also be released in GitHub. If there is a problem with the new version, users can reduce the version by themselves.

**Comment by polywock** [comment]
Version 2.7.8 had a bug that causes issues for Baidu Wangpan videos. Version 2.7.6 and 2.7.9 should work. I just tested it myself. 

Are you sure it's not working for 2.7.9?

**Comment by drc5521** [comment]
Yes, I'am sure it's not working for 2.7.9. I also try reinstall the extension，but, it's not working too. On Edge Browser, the version is 2.7.6，it work well.  On Chrome/Firefox (2.7.9) not work. Remove 2.7.9，then install 2.7.6，it working well. the bug specific performance, every second acceleration, and then do not accelerate. But，I found a interesting thing，one account is svip，another one not，the svip not work for 2.7.9，another  one work well，but, both can work for 2.7.6. For 2.7.6, I have to open ghost in settings, otherwise，it not working. For 2.7.9, i also open ghost，but it not working.

**Comment by polywock** [comment]
Okay, I think I figured it out. Try the latest update (2.8.0).

**Comment by drc5521** [comment]
Great! I've updated and the problem has been solved!  Whether or not ghost is turned on, it can work normally. Thank you very much for the repair. Thanks.

**Comment by HITchenguorong** [comment]
目前使用的版本是2.80    这两天突然发现在bilibili一部分视频无法正常调节速度   
The current version is 2.80. Suddenly I found that part of the video in bilibili could not adjust the speed properly

**Comment by polywock** [comment]
You're the fourth person to have issues with Bilibili recently. Very curious. I need to find out why some people are having issues, but not me. Many questions, sorry. 

1. Which browser and browser version?
2. Is this issue found in all bilibili videos?  If not, could you link me the videos that work and those that do not. 
2. What do you mean by part of the video? More details please. For example, does it work initially, but suddenly stops? Or does it alternate back and fourth every few seconds? 
3. Is "Ghost mode" enabled in the Global Speed options page? If disabled, does enabling it make it work, or vice versa? After enabling/disabling, remember to reload your Bilibili page. 
4. Does Bilibili work with other speed control plugins?
5. Does Bilibili work with Global Speed on other browsers like Chrome, Edge, or Firefox?

**Comment by polywock** [comment]
@HITchenguorong, I found the cause of the issue. This is because the new player Bilibili is gradually rolling out. Only some users are affected. I implemented a workaround on the latest update (version 2.8.2). Already approved for the Chrome and Firefox stores, but will take a week for the Edge store.

Let me know if you still have issues.
