### ISSUE TITLE
Weird Issue With Hulu

### ISSUE THREAD

**Issue by ChaoDrake** [polywock/globalSpeed#85]
Let me preface by saying love this extension and works pretty much on every video I watch on Microsoft Edge. So I have a weird issue seemingly only with Hulu. I use this extension on Microsoft Edge and at home I have a PC that is connected to both a monitor and a 4K HDTV. On the monitor the extension works on Hulu, however when switched over to the TV it does not. The extension works on all other streaming websites like Netflix, HBO Max, Disney Plus and Youtube (on both monitor and TV). What could be the problem here?

**Comment by polywock** [comment]
Weird problem. I can't think of any causes. Maybe Hulu detects the screen size change and alters its behavior.

For all tests, keep computer plugged into HDTV. 
1. Try to reinstall and test again.  Still not working? 
1. Try on a new Edge profile. Still not working? 

. ![a](https://user-images.githubusercontent.com/31208859/118207999-dbdda580-b433-11eb-86df-08b2ebd87515.png)

1. Try on different browser like [Chrome](https://chrome.google.com/webstore/detail/global-speed/jpbjcnkcffbooppibceonlgknpkniiff) or [Firefox](https://addons.mozilla.org/en-US/firefox/addon/global-speed/). Still not working?

**Comment by ChaoDrake** [comment]
I have tried all three steps. Seems like the only that it works on is on Chrome, but I would like for it to work on Edge since I believe Edge is the only one that can stream Hulu, Netflix, etc. and higher than 720p.

**Comment by polywock** [comment]
Very interesting issue. Could you disable Global Speed, and test other video control extensions like Video Speed Controller? Need to find out if it's a Global Speed specific issue or if this happens on other extensions as well. 

https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk?hl=en

**Comment by ChaoDrake** [comment]
Just tried it with the Video Speed Controller extension with Global Speed disabled and it doesn't work. Such a strange issue. Seems like it's Edge-specific.

**Comment by polywock** [comment]
It's a long shot, but if you haven't already tried it, try enabling "Ghost mode" in the Global Speed options page. After doing so, reload your Hulu tab. Ghost mode tries to block the website from changing the speed.

**Comment by ChaoDrake** [comment]
Unfortunately I did try ghost mode and still the same. Appreciate the help.

Regards,
Ricky Kwong
