### ISSUE TITLE
哔哩哔哩bilibili___bug

### ISSUE THREAD

**Issue by yijrqz777** [polywock/globalSpeed#88]
哔哩哔哩bilibili最近无法使用

**Comment by polywock** [comment]
Weird, seems to still work for me. Could you try reinstalling the latest version of Global Speed (2.8.0)? If it still doesn't work, could you describe the issue in more detail and link the video. Thank you.

**Comment by yijrqz777** [comment]
对不起，现在才回复你的邮件，具体情况在这个链接里https://wormhole.app/VPKBZ#rF2s_jce2dVesWc3AREagg




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月16日(星期天) 晚上11:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [polywock/globalSpeed] 哔哩哔哩bilibili___bug (#88)





 
Weird, seems to still work for me. Could you try reinstalling the latest version of Global Speed (2.8.0)? If it still doesn't work, could you describe the issue in more detail and link the video. Thank you.

**Comment by polywock** [comment]
That python video fine for me. You could try these two experiments. 

1. Try enabling "Ghost Mode" in the Global Speed options page. Refresh your bilibili page and try again the 16x speed. 

2. The problem might have something to do with your particular environment. Try testing Global Speed on a new Chrome profile.


Google Translation / 谷歌翻译

那个python视频对我来说很好。 您可以尝试这两个实验。

1.尝试在“全局速度”选项页面中启用“虚拟模式”。 刷新您的bilibili页面，然后重试16倍速度。

2.该问题可能与您的特定环境有关。 尝试在新的Chrome配置文件上测试Global Speed。

### 添加新的个人资料
在计算机上打开 Chrome。
点击右上角的“个人资料”图标 个人资料。
点击添加。
选择名称、照片和配色方案。


### 切换到另一份个人资料
在计算机上打开 Chrome。
点击右上角的“个人资料”图标 个人资料。
选择您想切换到的个人资料。

**Comment by yijrqz777** [comment]
我非常的抱歉，它依然没在哔哩哔哩（https://www.bilibili.com/）起作用，但是它能工作在其他网站上，依然感谢你的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月17日(星期一) 晚上10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [polywock/globalSpeed] 哔哩哔哩bilibili___bug (#88)





 
That python video fine for me. You could try these two experiments.
  
 
Try enabling "Ghost Mode" in the Global Speed options page. Refresh your bilibili page and try again the 16x speed.
 
 
 
The problem might have something to do with your particular environment. Try testing Global Speed on a new Chrome profile.
 
  
Google Translation / 谷歌翻译
 
那个python视频对我来说很好。 您可以尝试这两个实验。
 
1.尝试在“全局速度”选项页面中启用“虚拟模式”。 刷新您的bilibili页面，然后重试16倍速度。
 
2.该问题可能与您的特定环境有关。 尝试在新的Chrome配置文件上测试Global Speed。
 
添加新的个人资料
 
在计算机上打开 Chrome。
 点击右上角的“个人资料”图标 个人资料。
 点击添加。
 选择名称、照片和配色方案。
 
切换到另一份个人资料
 
在计算机上打开 Chrome。
 点击右上角的“个人资料”图标 个人资料。
 选择您想切换到的个人资料。

**Comment by yijrqz777** [comment]
我重新安装了edge 并且它开始工作了，非常感谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月17日(星期一) 晚上10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [polywock/globalSpeed] 哔哩哔哩bilibili___bug (#88)





 
That python video fine for me. You could try these two experiments.
  
 
Try enabling "Ghost Mode" in the Global Speed options page. Refresh your bilibili page and try again the 16x speed.
 
 
 
The problem might have something to do with your particular environment. Try testing Global Speed on a new Chrome profile.
 
  
Google Translation / 谷歌翻译
 
那个python视频对我来说很好。 您可以尝试这两个实验。
 
1.尝试在“全局速度”选项页面中启用“虚拟模式”。 刷新您的bilibili页面，然后重试16倍速度。
 
2.该问题可能与您的特定环境有关。 尝试在新的Chrome配置文件上测试Global Speed。
 
添加新的个人资料
 
在计算机上打开 Chrome。
 点击右上角的“个人资料”图标 个人资料。
 点击添加。
 选择名称、照片和配色方案。
 
切换到另一份个人资料
 
在计算机上打开 Chrome。
 点击右上角的“个人资料”图标 个人资料。
 选择您想切换到的个人资料。

**Comment by polywock** [comment]
@yijrqz777, I figured out the cause of the issue. This is because the new player Bilibili is gradually rolling out. Only some users were affected. By reinstalling Edge, you probably opted yourself out by clearing the cache. At least temporarily.  I implemented a workaround on the latest update (version 2.8.2). Already approved for the Chrome and Firefox stores, but will take a week for the Edge store.

Let me know if you still have issues.

**Comment by yijrqz777** [comment]
ok&nbsp; &nbsp;thank you&nbsp; very much



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月25日(星期二) 晚上7:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [polywock/globalSpeed] 哔哩哔哩bilibili___bug (#88)





 
@yijrqz777, I figured out the cause of the issue. This is because the new player Bilibili is gradually rolling out. Only some users were affected. By reinstalling Edge, you probably opted yourself out by clearing the cache. At least temporarily.  I implemented a workaround on the latest update (version 2.8.2). Already approved for the Chrome and Firefox stores, but will take a week for the Edge store.
 
Let me know if you still have issues.
