### ISSUE TITLE
volume control not working in facebook.

### ISSUE THREAD

**Issue by paulscholes0258** [polywock/globalSpeed#89]
in facebook video player. speed is good but cannot control volume. plesae fix. thanks

**Comment by polywock** [comment]
Looks like there is a lot of videos loaded on Facebook. In these cases, Global Speed isn't good at selecting the right video to control. I'll have to look into improving the algorithm for cases like this. 

![ax](https://user-images.githubusercontent.com/31208859/118841007-e5349b00-b895-11eb-80eb-2d8487ae1aec.png)


## Workaround 
For now if you're on a Chromium based browser, the best workaround is switching to the "gain" hotkey. Unlike "volume" hotkey, it doesn't apply to individual videos, but on the entire tab using the Audio Capture API. You'll also need an extra "tab capture" hotkey to activate audio effects for the current tab. 


### Setup 
1. Delete your volume hotkeys and replace them with gain hotkeys with the same keys. 
2. Create a global "tab capture" hotkey. It has to be global. Setup video below. 

https://user-images.githubusercontent.com/31208859/118849464-c6d29d80-b89d-11eb-87a0-9c2ba2030549.mov

### Usage 

1. Activate audio effects for the current tab using the "tab capture" hotkey. On the tab menu, you should see an indicator letting you know the audio is being manipulated. 
2. Now you can adjust the "gain" just like the "volume" hotkeys. You can even boost the volume over 600% for quiet videos. 


Note:  You cannot go fullscreen while the tab's audio is being manipulated.  To go fullscreen, press the "tab capture" hotkey again to toggle it off. Go fullscreen, and reactivate it again.

**Comment by paulscholes0258** [comment]
I'm using firefox and does not have "gain" like chrome.
looking forware you'll update "gain"  for firefox. thank

**Comment by polywock** [comment]
Unfortunately, the Audio Capture API isn't supported by Firefox yet. I'll update you when I improve the video selection algorithm.

**Comment by polywock** [comment]
@paulscholes0258, an update. I've improved the video prioritization algorithm in the latest update. (Global Speed version 2.8.7). Once updated, let me know if you still have issues with Facebook videos.

**Comment by paulscholes0258** [comment]
sr for repling late. 
the lasted version 2.9 is working very good , include fb. thanks for listening.

**Comment by polywock** [comment]
No problem, glad I could be useful.
