### ISSUE TITLE
B站的速度控制失效

### ISSUE THREAD

**Issue by gx1617097814** [polywock/globalSpeed#90]
插件在B站调不了速，但B站自带的调速可以使用。

**Comment by polywock** [comment]
Bilibili for fine for me, but some users seem to have issues. I'm having a tough time debugging this. Many questions, sorry. 

1. Which browser and browser version? 
2. Which Global Speed version? 
3. Is "Ghost mode" enabled in the Global Option options page? If disabled, does enabling it make it work, or vice versa? 
4. Does Bilibili work with other speed control plugins? 
5. Does Bilibili with Global Speed on other browsers like Chrome, Edge, or Firefox?

**Comment by gx1617097814** [comment]
你好：
1. my browser version:&nbsp; Google Chrome (64bit) 90.0.4430.212 for windows
2. Global Speed version:&nbsp; 2.8.0
3. I have not used Ghost mode before, however, even if Ghost mode is enabled, it has no effect on the video playback speed.
4. I just tried three other speed control plugins, and the results are as follows:
	1) Playback Rate Controller1.3.1:&nbsp;
		No audio/video content found on this page.
		But the plug-in can be used normally on other video sites(https://www.ixigua.com)
	2)Video speed controls2.1.3:
		The plugin does not work at all.
		But the plug-in can be used normally on other video sites(https://www.ixigua.com)
	3)Audio/Video Playback Speed Controller1.1:
		No audio or video found on this page.
		Like the other two plugins, it can be used normally on other websites
		The above three plug-ins do not affect the normal use of the built-in speed regulator at Bilibili
5. In the Edge browser, Global Speed can be used normally





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月20日(星期四) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] B站的速度控制失效 (#90)





 
Bilibili for fine for me, but some users seem to have issues. I'm having a tough time debugging this. Many questions, sorry.
  
Which browser and browser version?
 
Which Global Speed version?
 
Is "Ghost mode" enabled in the Global Option options page? If disabled, does enabling it make it work, or vice versa?
 
Does Bilibili work with other speed control plugins?
 
Does Bilibili with Global Speed on other browsers like Chrome, Edge, or Firefox?

**Comment by polywock** [comment]
Interesting that it works on Edge. Both Chrome and Edge rely on Chromium and the internals are very similar. The culprit might be your particular environment, but I'm not very confident because at you're the third person to report having issues with Bilibili. Try these two things... 

1. Reinstall Global Speed for Edge. Does it work now? If not try the next experiment. 
2. Try Global Speed on a new Chrome profile. Does it work now?

**Comment by gx1617097814** [comment]
What you said makes sense. I just cleaned up the recent cache and cookies in the chrome settings, and then re-logged in to the bilibili account. Now the plug-in can be used normally. thank you for your help


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月20日(星期四) 下午4:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] B站的速度控制失效 (#90)





 
Interesting that it works on Edge. Both Chrome and Edge rely on Chromium and the internals are very similar. The culprit might be your particular environment, but I'm not very confident because you're the third person to report having issues with Bilibili. Try these two things...
  
Reinstall Global Speed for Edge. Does it work now? If not try the next experiment.
 
Try Global Speed on a new Chrome profile. Does it work now?

**Comment by polywock** [comment]
Great, glad I could be helpful.

**Comment by polywock** [comment]
@gx1617097814. I figured out the cause of the issue. Bilibili is gradually rolling out a new video player. Only some users were affected because it's still in beta. By clearing the cache, you probably opted yourself out temporarily. I implemented a workaround on the latest update (version 2.8.2). Already approved for the Chrome and Firefox stores, but will take a week for the Edge store.

Let me know if you still have issues.

**Comment by gx1617097814** [comment]
I did solve the problem successfully after clearing the cache and logging in again. I have just upgraded version 2.8.2, and I will let you know if I encounter other problems.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 晚上7:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] B站的速度控制失效 (#90)





 
@gx1617097814. I figured out the cause of the issue. Bilibili is gradually rolling out a new video player. Only some users were affected because it's still in beta. By clearing the cache, you probably opted yourself out temporarily. I implemented a workaround on the latest update (version 2.8.2). Already approved for the Chrome and Firefox stores, but will take a week for the Edge store.
 
Let me know if you still have issues.
