### ISSUE TITLE
The Plugin doesn't work in bilibili(a video website in china)

### ISSUE THREAD

**Issue by TuRan-sino** [polywock/globalSpeed#91]
I just discover this problem this few day. I found that i can't accelerate video in bilibili now.
But this plugin still can be working on bilibili a week ago,

**Comment by ztreble** [comment]
Me too.

**Comment by polywock** [comment]
This is because the new player Bilibili is gradually rolling out. Only some users are affected. I implemented a workaround on the latest update (version 2.8.2). Already approved for the Chrome and Firefox stores, but will take a week for the Edge store. 

Let me know if you still have issues.

**Comment by TuRan-sino** [comment]
Thanks for a lot
