### ISSUE TITLE
视频右上角的快捷键怎么关闭，影响体验

### ISSUE THREAD

**Issue by a156168128** [polywock/globalSpeed#93]
和关闭视频按钮在一起，也影响b站点开up主页面

**Comment by polywock** [comment]
I don't think I understand the issue because the translation software isn't doing a good job. If you can, provide screenshots/or screen recording of the issue, or explain in more detail. 

Are you talking about this thing?  

![test](https://user-images.githubusercontent.com/31208859/119467166-4683c080-bd13-11eb-8b65-d0ccb80394f9.png)

**Comment by a156168128** [comment]
我就是说的这个快捷键不会关。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 下午4:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] 视频右上角的快捷键怎么关闭，影响体验 (#93)





 
I don't think I understand the issue because the translation software isn't doing a good job. If you can, provide screenshots/or screen recording of the issue, or explain in more detail. Thank you.
 
Are you talking about this thing?

**Comment by a156168128** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 下午4:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] 视频右上角的快捷键怎么关闭，影响体验 (#93)





 
I don't think I understand the issue because the translation software isn't doing a good job. If you can, provide screenshots/or screen recording of the issue, or explain in more detail. Thank you.
 
Are you talking about this thing?

**Comment by polywock** [comment]
Which shortcut key? This message came out wrong. 

https://github.com/polywock/globalSpeed/issues/93#issuecomment-847687156

**Comment by a156168128** [comment]
你收不到图片吗？每次打开视频，视频的右上角就会有一个倍速控制键，但是我不需要这个控制键，不会关闭。如果点击×只能暂时关闭，打开新的视频控制键又会出来。









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] 视频右上角的快捷键怎么关闭，影响体验 (#93)





 
Which shortcut key? This message came out wrong.
 
#93 (comment)

**Comment by polywock** [comment]
Nope, no images coming through. To send images, instead of replying by email, reply directly from the Github website. You could just drag and drop the image.

**Comment by a156168128** [comment]
![Uploading a.jpg…]()

**Comment by a156168128** [comment]
![a](https://user-images.githubusercontent.com/39835264/119472084-7e731e00-bd7c-11eb-832e-c2011ee1f9dd.jpg)

**Comment by polywock** [comment]
Happens on every video, even outside Bilibili? I don't think it's Global Speed, it might be a different plugin or userscript.

**Comment by a156168128** [comment]
尴尬，可能因为我装了不同的插件。问题解决了，谢谢您

**Comment by polywock** [comment]
No problem. I'll delete this issue for you.
