### ISSUE TITLE
可以添加多个标记跳转功能吗？

### ISSUE THREAD

**Issue by xiao-peng-yu** [polywock/globalSpeed#94]
标记可以不具体指明 名字，然后提供一个 跳转到上一个标记，下一个标记 。创建标记一个快捷键，上下标记两个快捷键。
不知道作者用过pr 没，类似Pr 中的功能。

**Comment by polywock** [comment]
Interesting suggestions. It may not be suitable for most users, but I'll implement it as a hidden feature. It might take a while to publish the update to the Chrome/Edge stores, so if you want to try it, here's unpacked version for Chromium browsers (Chrome, Edge). If you're on Firefox, let me know. 

[unpacked.zip](https://github.com/polywock/globalSpeed/files/6565140/unpacked.zip)

## To install 
1. Download and extract the zip. 
2. On Chrome/Edge, open extension management page -> `chrome://extensions`
3. Enable Developer mode. (top right for Chrome, bottom left for Edge). 
4. Click on "load unpacked" and load the extracted folder. 
5. Import your Global Speed configuration in the options page. 

## To setup. 
1. Create 3 "set mark" hotkeys. 
2. For the first, replace "mark1" with "::nameless", this special keyword will create a nameless marker (or delete an existing marker if near one). 
3. For the second, replace "mark1" with "::nameless-prev", this special keyword will jump to previous marker. 
4. For the third, replace "mark1" with "::nameless-next", this special keyword will jump to the next marker. 

![nameless](https://user-images.githubusercontent.com/31208859/120080396-b7fe9e80-c086-11eb-89e1-2d4ab40bfbf4.png)

**Comment by xiao-peng-yu** [comment]
I am very happy to receive your reply so quickly.
I'm using Firefox.
Thank you for your help.

**Comment by polywock** [comment]
Glad I could be helpful. It looks like the Firefox update has been approved (2.8.3). Let me know if you have issues.

**Comment by xiao-peng-yu** [comment]
Sorry, we have the following problem.
(1) : it seems that it should be set as follows（ You can't jump according to your settings. All of them are set marks.)
![bug反馈](https://user-images.githubusercontent.com/68453850/120092066-eb9efe80-c142-11eb-86ca-639ac3585276.png)

(2) : according to the above settings, you can only jump on one mark, and multiple marks are not supported（ You can try it yourself)
(3) : there is sometimes a problem with the previous tag. If the time of the previous tag is after the current tag, you should not jump.
This video demonstrates the mark jump function in PR

![问题](https://user-images.githubusercontent.com/68453850/120092057-dde97900-c142-11eb-8130-2ea0fbd53727.gif)

If you can, you can make the mark into the form of a button and click the mark to jump（ Do you have a better solution）

**Comment by polywock** [comment]
Are you sure you're on the right version (2.8.3)? If entered correctly, it should look like this. All should be "set mark" hotkeys. 


https://user-images.githubusercontent.com/31208859/120092632-61bf4900-c0e2-11eb-8763-383c74e2942a.mov

**Comment by xiao-peng-yu** [comment]
It's my problem
The effect can be achieved after the update
excellent!
It would be even better if you could display the tag as a button and describe it!

**Comment by polywock** [comment]
Like with Premiere? Too complicated I think. Every site has a different video player and to integrate the marker visually on that video player would require custom code for each website.

**Comment by xiao-peng-yu** [comment]
Maybe we can change our mind
This effect is achieved by adding buttons on the right side of the browser, rather than embedding them into the player.
like this!
![button](https://user-images.githubusercontent.com/68453850/120095120-b13f5c80-c156-11eb-8aca-288954f250e9.png)

**Comment by polywock** [comment]
Thanks for the suggestion. It seems doable, but anything involving a user interface could require many lines of code. Sadly, Global Speed is getting a bit too bloated. The Chrome Web Store also a rule against including too many things on a single extension. So I'll probably not implement it. I was thinking of creating a separate extension where you can place notes anywhere on a video using markers, but seems like extensions like that exist already.
