### ISSUE TITLE
Buttons/symbols in shortcut section requires clarification

### ISSUE THREAD

**Issue by nicktohzyu** [polywock/globalSpeed#98]
![image](https://user-images.githubusercontent.com/34980083/122349415-d289b080-cf7e-11eb-824c-13afdf0b1b01.png)
There is no hover text explaining what these symbols beside the X mean. I could not find an explanation in the FAQ or readme either.

**Comment by polywock** [comment]
Thanks for letting me know. I'll include hover text in the next version. That controls spacing to help the user organize. 

![screenshot](https://user-images.githubusercontent.com/31208859/122414945-81b19200-cf55-11eb-8d56-c43de0fb69aa.png)
